window.YEAR_3_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        id: 'y3-maths-1',
        name: 'Place Value to 1000',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does the 5 represent in 456?', opts: ['5 ones', '5 tens', '5 hundreds', '5 thousands'], ans: '5 tens' },
          { id: 'q2', type: 'multiple', q: 'How many tens are in 380?', opts: ['3', '8', '38', '308'], ans: '38' },
          { id: 'q3', type: 'fillBlank', q: 'The number 729 has ___ hundreds.', answer: '7', accept: ['7', 'seven'] },
          { id: 'q4', type: 'multiple', q: 'Which number is the largest?', opts: ['234', '243', '324', '214'], ans: '324' },
          { id: 'q5', type: 'trueFalse', q: 'In the number 506, the 5 represents 500.', ans: true },
          { id: 'q6', type: 'multiple', q: 'What is 10 more than 567?', opts: ['568', '577', '576', '667'], ans: '577' },
          { id: 'q7', type: 'fillBlank', q: 'The number 840 can be written as 8 hundreds and ___ tens.', answer: '4', accept: ['4', 'four'] },
          { id: 'q8', type: 'trueFalse', q: '253 is greater than 352.', ans: false },
          { id: 'q9', type: 'multiple', q: 'Which number is the smallest?', opts: ['789', '879', '798', '897'], ans: '789' },
          { id: 'q10', type: 'order', q: 'Put these numbers in order from smallest to largest.', items: ['645', '456', '564', '465'], answer: ['456', '465', '564', '645'] },
          { id: 'q11', type: 'multiple', q: 'What comes next? 100, 200, 300, ___', opts: ['310', '350', '400', '500'], ans: '400' },
          { id: 'q12', type: 'fillBlank', q: '1 hundred + 5 tens + 3 ones = ___', answer: '153', accept: ['153', 'one hundred and fifty-three'] },
          { id: 'q13', type: 'trueFalse', q: 'The number 999 has nine tens.', ans: true },
          { id: 'q14', type: 'multiple', q: 'What is 10 less than 234?', opts: ['224', '233', '244', '134'], ans: '224' },
          { id: 'q15', type: 'multiple', q: 'In 872, the 7 is in the ___ place.', opts: ['hundreds', 'tens', 'ones', 'thousands'], ans: 'tens' },
          { id: 'q16', type: 'fillBlank', q: 'The number 305 has 3 hundreds, 0 tens, and ___ ones.', answer: '5', accept: ['5', 'five'] },
          { id: 'q17', type: 'trueFalse', q: '500 + 40 + 6 equals 546.', ans: true },
          { id: 'q18', type: 'multiple', q: 'Which is closest to 500?', opts: ['480', '420', '550', '350'], ans: '480' },
          { id: 'q19', type: 'order', q: 'Arrange from largest to smallest.', items: ['312', '321', '213', '231'], answer: ['321', '312', '231', '213'] },
          { id: 'q20', type: 'multiple', q: 'What is 100 more than 456?', opts: ['457', '556', '466', '555'], ans: '556' },
          { id: 'q21', type: 'trueFalse', q: 'The number 601 has 6 tens.', ans: false },
          { id: 'q22', type: 'fillBlank', q: '2 hundreds and 8 ones = ___', answer: '208', accept: ['208', 'two hundred and eight'] }
        ]
      },
      {
        id: 'y3-maths-2',
        name: 'Addition & Subtraction',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is 45 + 23?', opts: ['68', '69', '70', '67'], ans: '68' },
          { id: 'q2', type: 'fillBlank', q: '56 + 34 = ___', answer: '90', accept: ['90', 'ninety'] },
          { id: 'q3', type: 'multiple', q: 'What is 87 - 32?', opts: ['55', '65', '45', '56'], ans: '55' },
          { id: 'q4', type: 'trueFalse', q: '123 + 45 = 168', ans: true },
          { id: 'q5', type: 'multiple', q: 'Which strategy helps solve 99 + 15?', opts: ['count on by ones', 'add 100 then subtract 1', 'use the column method', 'any of the above'], ans: 'any of the above' },
          { id: 'q6', type: 'fillBlank', q: '234 + 156 = ___', answer: '390', accept: ['390', 'three hundred and ninety'] },
          { id: 'q7', type: 'multiple', q: 'What is 200 - 75?', opts: ['125', '135', '145', '115'], ans: '125' },
          { id: 'q8', type: 'trueFalse', q: '567 - 234 = 333', ans: true },
          { id: 'q9', type: 'multiple', q: 'If I add 10 to a number and get 67, what was my number?', opts: ['57', '77', '67', '47'], ans: '57' },
          { id: 'q10', type: 'fillBlank', q: '100 - 42 = ___', answer: '58', accept: ['58', 'fifty-eight'] },
          { id: 'q11', type: 'multiple', q: 'What is 134 + 123?', opts: ['257', '247', '267', '237'], ans: '257' },
          { id: 'q12', type: 'trueFalse', q: 'When adding numbers, the order doesn\'t matter: 25 + 30 = 30 + 25', ans: true },
          { id: 'q13', type: 'fillBlank', q: '789 - 456 = ___', answer: '333', accept: ['333', 'three hundred and thirty-three'] },
          { id: 'q14', type: 'multiple', q: 'What is 250 + 150?', opts: ['300', '350', '400', '450'], ans: '400' },
          { id: 'q15', type: 'trueFalse', q: '356 + 200 = 556', ans: true },
          { id: 'q16', type: 'fillBlank', q: '500 - 200 = ___', answer: '300', accept: ['300', 'three hundred'] },
          { id: 'q17', type: 'multiple', q: 'What is 99 + 1?', opts: ['98', '100', '101', '99'], ans: '100' },
          { id: 'q18', type: 'trueFalse', q: '678 - 678 = 0', ans: true },
          { id: 'q19', type: 'fillBlank', q: '145 + 155 = ___', answer: '300', accept: ['300', 'three hundred'] },
          { id: 'q20', type: 'multiple', q: 'What is 432 - 100?', opts: ['332', '342', '132', '532'], ans: '332' },
          { id: 'q21', type: 'trueFalse', q: 'You can use inverse operations: if 5 + 3 = 8, then 8 - 3 = 5', ans: true },
          { id: 'q22', type: 'fillBlank', q: '600 + 145 = ___', answer: '745', accept: ['745', 'seven hundred and forty-five'] }
        ]
      },
      {
        id: 'y3-maths-3',
        name: 'Multiplication & Division',
        questions: [
          { id: 'q1', type: 'fillBlank', q: '3 × 4 = ___', answer: '12', accept: ['12', 'twelve'] },
          { id: 'q2', type: 'multiple', q: 'What is in the 4 times table?', opts: ['3, 6, 9, 12', '4, 8, 12, 16', '2, 4, 6, 8', '5, 10, 15, 20'], ans: '4, 8, 12, 16' },
          { id: 'q3', type: 'trueFalse', q: '8 × 3 = 24', ans: true },
          { id: 'q4', type: 'fillBlank', q: '24 ÷ 8 = ___', answer: '3', accept: ['3', 'three'] },
          { id: 'q5', type: 'multiple', q: 'What is 3 × 7?', opts: ['20', '21', '24', '18'], ans: '21' },
          { id: 'q6', type: 'trueFalse', q: 'The 8 times table goes: 8, 16, 24, 32, 40', ans: true },
          { id: 'q7', type: 'fillBlank', q: '32 ÷ 4 = ___', answer: '8', accept: ['8', 'eight'] },
          { id: 'q8', type: 'multiple', q: 'What is 4 × 9?', opts: ['32', '36', '40', '28'], ans: '36' },
          { id: 'q9', type: 'trueFalse', q: 'Multiplication and division are inverse operations.', ans: true },
          { id: 'q10', type: 'fillBlank', q: '3 × ___ = 15', answer: '5', accept: ['5', 'five'] },
          { id: 'q11', type: 'multiple', q: 'What is in the 3 times table?', opts: ['3, 6, 9, 12, 15', '4, 8, 12, 16', '2, 4, 6, 8', '5, 10, 15, 20'], ans: '3, 6, 9, 12, 15' },
          { id: 'q12', type: 'fillBlank', q: '7 × 4 = ___', answer: '28', accept: ['28', 'twenty-eight'] },
          { id: 'q13', type: 'trueFalse', q: '6 × 8 = 48', ans: true },
          { id: 'q14', type: 'multiple', q: 'What is 16 ÷ 4?', opts: ['3', '4', '5', '6'], ans: '4' },
          { id: 'q15', type: 'fillBlank', q: '40 ÷ 8 = ___', answer: '5', accept: ['5', 'five'] },
          { id: 'q16', type: 'trueFalse', q: 'The order of factors doesn\'t change the product: 3 × 4 = 4 × 3', ans: true },
          { id: 'q17', type: 'multiple', q: 'What is 8 × 6?', opts: ['42', '48', '54', '56'], ans: '48' },
          { id: 'q18', type: 'fillBlank', q: '3 × 9 = ___', answer: '27', accept: ['27', 'twenty-seven'] },
          { id: 'q19', type: 'trueFalse', q: '30 ÷ 3 = 10', ans: true },
          { id: 'q20', type: 'multiple', q: 'What is 4 × 5?', opts: ['15', '20', '25', '30'], ans: '20' },
          { id: 'q21', type: 'fillBlank', q: '24 ÷ 3 = ___', answer: '8', accept: ['8', 'eight'] },
          { id: 'q22', type: 'trueFalse', q: '9 × 4 = 32', ans: false }
        ]
      },
      {
        id: 'y3-maths-4',
        name: 'Fractions',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What fraction is shaded? [1 out of 4 parts]', opts: ['1/2', '1/3', '1/4', '1/5'], ans: '1/4' },
          { id: 'q2', type: 'trueFalse', q: 'A quarter is the same as 1/4.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'One half of 12 is ___', answer: '6', accept: ['6', 'six'] },
          { id: 'q4', type: 'multiple', q: 'What is 1/3 of 9?', opts: ['2', '3', '4', '6'], ans: '3' },
          { id: 'q5', type: 'trueFalse', q: '2/4 is equal to 1/2.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'One quarter of 20 is ___', answer: '5', accept: ['5', 'five'] },
          { id: 'q7', type: 'multiple', q: 'Which fraction shows 3 out of 5 parts?', opts: ['1/3', '3/5', '5/3', '2/5'], ans: '3/5' },
          { id: 'q8', type: 'trueFalse', q: '3/4 is greater than 1/2.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'One third of 18 is ___', answer: '6', accept: ['6', 'six'] },
          { id: 'q10', type: 'multiple', q: 'What is 1/4 of 8?', opts: ['1', '2', '3', '4'], ans: '2' },
          { id: 'q11', type: 'trueFalse', q: '1/2 is equal to 2/4.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'One half of 14 is ___', answer: '7', accept: ['7', 'seven'] },
          { id: 'q13', type: 'multiple', q: 'How many thirds make one whole?', opts: ['2', '3', '4', '5'], ans: '3' },
          { id: 'q14', type: 'trueFalse', q: '2/3 is less than 1/3.', ans: false },
          { id: 'q15', type: 'fillBlank', q: 'One quarter of 16 is ___', answer: '4', accept: ['4', 'four'] },
          { id: 'q16', type: 'multiple', q: 'What is 1/3 of 15?', opts: ['3', '5', '10', '15'], ans: '5' },
          { id: 'q17', type: 'trueFalse', q: '1/4 of 12 = 3', ans: true },
          { id: 'q18', type: 'fillBlank', q: '2/4 of 8 is ___', answer: '4', accept: ['4', 'four'] },
          { id: 'q19', type: 'multiple', q: 'How many quarters make one whole?', opts: ['2', '3', '4', '5'], ans: '4' },
          { id: 'q20', type: 'trueFalse', q: '3/4 of 12 = 9', ans: true },
          { id: 'q21', type: 'fillBlank', q: 'One third of 12 is ___', answer: '4', accept: ['4', 'four'] },
          { id: 'q22', type: 'multiple', q: 'What is 1/2 of 20?', opts: ['5', '8', '10', '15'], ans: '10' }
        ]
      },
      {
        id: 'y3-maths-5',
        name: 'Measurement',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How many grams are in 1 kilogram?', opts: ['100', '500', '1000', '2000'], ans: '1000' },
          { id: 'q2', type: 'trueFalse', q: 'Centimetres are smaller than millimetres.', ans: false },
          { id: 'q3', type: 'fillBlank', q: 'There are ___ millimetres in 1 centimetre.', answer: '10', accept: ['10', 'ten'] },
          { id: 'q4', type: 'multiple', q: 'Which unit would measure the height of a door?', opts: ['millimetres', 'centimetres', 'metres', 'kilometres'], ans: 'metres' },
          { id: 'q5', type: 'trueFalse', q: '1 litre = 1000 millilitres', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'How many centimetres are in 1 metre? ___', answer: '100', accept: ['100', 'one hundred'] },
          { id: 'q7', type: 'multiple', q: 'Which is the heaviest?', opts: ['200g', '500g', '1kg', '1500g'], ans: '1kg' },
          { id: 'q8', type: 'trueFalse', q: 'A teaspoon holds about 5 millilitres.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'There are ___ grams in half a kilogram.', answer: '500', accept: ['500', 'five hundred'] },
          { id: 'q10', type: 'multiple', q: 'Which container holds the most?', opts: ['250ml', '500ml', '750ml', '1 litre'], ans: '1 litre' },
          { id: 'q11', type: 'trueFalse', q: 'A metre is equal to 100 centimetres.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'A pencil is about ___ centimetres long.', answer: '19', accept: ['19', '19 or 20', '20', 'twenty', '19 or 20'] },
          { id: 'q13', type: 'multiple', q: 'What is the best unit to measure the mass of a pen?', opts: ['grams', 'kilograms', 'tonnes', 'millilitres'], ans: 'grams' },
          { id: 'q14', type: 'trueFalse', q: 'A bucket can hold about 10 litres.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '3 metres = ___ centimetres', answer: '300', accept: ['300', 'three hundred'] },
          { id: 'q16', type: 'multiple', q: 'Which is the smallest?', opts: ['1km', '1000m', '1cm', '10mm'], ans: '10mm' },
          { id: 'q17', type: 'trueFalse', q: '2 kilograms is heavier than 1500 grams.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '5 centimetres = ___ millimetres', answer: '50', accept: ['50', 'fifty'] },
          { id: 'q19', type: 'multiple', q: 'A glass of water is about ___', opts: ['50ml', '200ml', '1 litre', '5 litres'], ans: '200ml' },
          { id: 'q20', type: 'trueFalse', q: 'A ruler typically measures 30 centimetres.', ans: true },
          { id: 'q21', type: 'fillBlank', q: '1 litre = ___ millilitres', answer: '1000', accept: ['1000', 'one thousand'] },
          { id: 'q22', type: 'multiple', q: 'Which is NOT a unit of length?', opts: ['metre', 'litre', 'centimetre', 'millimetre'], ans: 'litre' }
        ]
      },
      {
        id: 'y3-maths-6',
        name: 'Time',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How many minutes are in 1 hour?', opts: ['30', '60', '90', '120'], ans: '60' },
          { id: 'q2', type: 'trueFalse', q: 'There are 24 hours in a day.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'How many seconds are in 1 minute? ___', answer: '60', accept: ['60', 'sixty'] },
          { id: 'q4', type: 'multiple', q: 'What time is shown on a clock at 3 o\'clock?', opts: ['12:30', '3:00', '3:30', '2:00'], ans: '3:00' },
          { id: 'q5', type: 'trueFalse', q: 'A quarter to 4 is the same as 3:45.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Half past 5 is written as 5:___', answer: '30', accept: ['30', 'thirty'] },
          { id: 'q7', type: 'multiple', q: 'In 24-hour time, what is 3pm?', opts: ['03:00', '15:00', '03:15', '23:00'], ans: '15:00' },
          { id: 'q8', type: 'trueFalse', q: 'A quarter past 9 is 9:15.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Quarter to 10 is ___:___', answer: '9:45', accept: ['9:45', '09:45'] },
          { id: 'q10', type: 'multiple', q: 'How many days are in a week?', opts: ['5', '6', '7', '8'], ans: '7' },
          { id: 'q11', type: 'trueFalse', q: 'There are 12 months in a year.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'How many weeks are in a year? Roughly ___', answer: '52', accept: ['52', 'fifty-two'] },
          { id: 'q13', type: 'multiple', q: 'If a film starts at 2pm and lasts 2 hours, when does it end?', opts: ['3pm', '4pm', '5pm', '6pm'], ans: '4pm' },
          { id: 'q14', type: 'trueFalse', q: 'A digital clock showing 7:30 means 30 minutes past 7.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'If it\'s 3pm in 12-hour time, it\'s ___:00 in 24-hour time.', answer: '15', accept: ['15'] },
          { id: 'q16', type: 'multiple', q: 'How many minutes are in half an hour?', opts: ['20', '30', '45', '60'], ans: '30' },
          { id: 'q17', type: 'trueFalse', q: '10pm in 24-hour time is 22:00.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'There are ___ minutes between 2:15 and 2:45.', answer: '30', accept: ['30', 'thirty'] },
          { id: 'q19', type: 'multiple', q: 'Which months have 31 days?', opts: ['February', 'April', 'June', 'July'], ans: 'July' },
          { id: 'q20', type: 'trueFalse', q: 'Roman numerals on clock faces use I, V, X, L, C, D, M.', ans: true },
          { id: 'q21', type: 'fillBlank', q: 'The Roman numeral for 6 is ___', answer: 'VI', accept: ['VI', 'vi'] },
          { id: 'q22', type: 'multiple', q: 'How many quarters of an hour are in 3 hours?', opts: ['6', '9', '12', '15'], ans: '12' }
        ]
      },
      {
        id: 'y3-maths-7',
        name: 'Shape',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How many sides does a triangle have?', opts: ['2', '3', '4', '5'], ans: '3' },
          { id: 'q2', type: 'trueFalse', q: 'A square has 4 equal sides.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'A circle has ___ corners.', answer: '0', accept: ['0', 'zero', 'none'] },
          { id: 'q4', type: 'multiple', q: 'How many faces does a cube have?', opts: ['4', '5', '6', '8'], ans: '6' },
          { id: 'q5', type: 'trueFalse', q: 'A rectangle has 4 right angles.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'A pentagon has ___ sides.', answer: '5', accept: ['5', 'five'] },
          { id: 'q7', type: 'multiple', q: 'What is a right angle?', opts: ['45 degrees', '90 degrees', '180 degrees', '360 degrees'], ans: '90 degrees' },
          { id: 'q8', type: 'trueFalse', q: 'A sphere is a 3D circle.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A hexagon has ___ sides.', answer: '6', accept: ['6', 'six'] },
          { id: 'q10', type: 'multiple', q: 'How many edges does a cube have?', opts: ['8', '10', '12', '16'], ans: '12' },
          { id: 'q11', type: 'trueFalse', q: 'Parallel lines never meet.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'How many vertices (corners) does a cube have? ___', answer: '8', accept: ['8', 'eight'] },
          { id: 'q13', type: 'multiple', q: 'Which shape has 3 vertices?', opts: ['square', 'triangle', 'pentagon', 'hexagon'], ans: 'triangle' },
          { id: 'q14', type: 'trueFalse', q: 'A pyramid has a square base and 4 triangular faces.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'A cylinder has ___ curved faces and ___ flat circular faces.', answer: '1 curved, 2 flat', accept: ['1 curved, 2 flat', '1 and 2'] },
          { id: 'q16', type: 'multiple', q: 'What do we call lines that cross at a right angle?', opts: ['parallel', 'perpendicular', 'diagonal', 'curved'], ans: 'perpendicular' },
          { id: 'q17', type: 'trueFalse', q: 'A triangle can have one right angle.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'An octagon has ___ sides.', answer: '8', accept: ['8', 'eight'] },
          { id: 'q19', type: 'multiple', q: 'How many sides does a quadrilateral have?', opts: ['3', '4', '5', '6'], ans: '4' },
          { id: 'q20', type: 'trueFalse', q: 'A rhombus is a quadrilateral with all sides equal.', ans: true },
          { id: 'q21', type: 'fillBlank', q: 'A cone has ___ vertex.', answer: '1', accept: ['1', 'one'] },
          { id: 'q22', type: 'multiple', q: 'Which 3D shape has 5 faces?', opts: ['cube', 'pyramid', 'cylinder', 'sphere'], ans: 'pyramid' }
        ]
      },
      {
        id: 'y3-maths-8',
        name: 'Statistics',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What type of chart shows data with rectangular bars?', opts: ['pie chart', 'bar chart', 'line graph', 'pictogram'], ans: 'bar chart' },
          { id: 'q2', type: 'trueFalse', q: 'A pictogram uses symbols to represent data.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'In a bar chart, the ___ axis shows categories.', answer: 'horizontal', accept: ['horizontal', 'x'] },
          { id: 'q4', type: 'multiple', q: 'If a pictogram shows one apple = 2 items, and there are 3 apples, how many items are represented?', opts: ['3', '5', '6', '8'], ans: '6' },
          { id: 'q5', type: 'trueFalse', q: 'A table can be used to organise data.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'The vertical axis on a graph is called the ___ axis.', answer: 'y', accept: ['y', 'vertical'] },
          { id: 'q7', type: 'multiple', q: 'Which is the best way to show the favourite colour of 50 children?', opts: ['line graph', 'pictogram', 'bar chart', 'table'], ans: 'bar chart' },
          { id: 'q8', type: 'trueFalse', q: 'The mode is the most frequently occurring value.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A ___ graph shows how something changes over time.', answer: 'line', accept: ['line', 'time'] },
          { id: 'q10', type: 'multiple', q: 'If you have the data: 3, 5, 3, 7, 3, what is the mode?', opts: ['3', '5', '7', '4.2'], ans: '3' },
          { id: 'q11', type: 'trueFalse', q: 'In a pictogram, partial symbols can be used.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'The ___ is the middle value in a set of numbers.', answer: 'median', accept: ['median'] },
          { id: 'q13', type: 'multiple', q: 'How many children chose blue if the bar reaches 12 on the scale?', opts: ['10', '11', '12', '13'], ans: '12' },
          { id: 'q14', type: 'trueFalse', q: 'A tally chart can be used to collect data.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The ___ is the total of all values divided by how many values there are.', answer: 'mean', accept: ['mean', 'average'] },
          { id: 'q16', type: 'multiple', q: 'What does a single square in a pictogram represent if it says "= 4 books"?', opts: ['1 book', '2 books', '4 books', '8 books'], ans: '4 books' },
          { id: 'q17', type: 'trueFalse', q: 'The range is the difference between the highest and lowest values.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A ___ is used to count data during a survey with tally marks.', answer: 'tally chart', accept: ['tally chart', 'tally', 'chart'] },
          { id: 'q19', type: 'multiple', q: 'If the data is 2, 4, 6, 8, 10, what is the range?', opts: ['4', '6', '8', '10'], ans: '8' },
          { id: 'q20', type: 'trueFalse', q: 'Bars in a bar chart must always start from zero.', ans: true },
          { id: 'q21', type: 'fillBlank', q: 'A ___ chart is circular and divided into sections.', answer: 'pie', accept: ['pie'] },
          { id: 'q22', type: 'multiple', q: 'What is the mean of 3, 5, 7?', opts: ['4', '5', '6', '7'], ans: '5' }
        ]
      }
    ]
  },
  english: {
    name: 'English',
    icon: '📖',
    color: '#2196F3',
    lessons: [
      {
        id: 'y3-english-1',
        name: 'Prefixes',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does the prefix "un-" mean?', opts: ['again', 'not', 'before', 'wrongly'], ans: 'not' },
          { id: 'q2', type: 'fillBlank', q: 'The opposite of "happy" is "___happy".', answer: 'unhappy', accept: ['unhappy', 'un-happy'] },
          { id: 'q3', type: 'trueFalse', q: '"Redo" means to do something wrong.', ans: false },
          { id: 'q4', type: 'multiple', q: 'Which word has the prefix "re-"?', opts: ['unlock', 'rebuild', 'dislike', 'restart'], ans: 'rebuild' },
          { id: 'q5', type: 'fillBlank', q: 'To do something again is to ___ it (use re- prefix).', answer: 'redo', accept: ['redo', 're-do'] },
          { id: 'q6', type: 'trueFalse', q: '"Mistaken" means made a mistake.', ans: true },
          { id: 'q7', type: 'multiple', q: 'What does "dis-" mean in "disagree"?', opts: ['not', 'wrongly', 'opposite of', 'again'], ans: 'opposite of' },
          { id: 'q8', type: 'fillBlank', q: '"Misbehave" means to behave ___.', answer: 'wrongly', accept: ['wrongly', 'badly', 'wrong'] },
          { id: 'q9', type: 'trueFalse', q: '"Unlock" means to lock something.', ans: false },
          { id: 'q10', type: 'fillBlank', q: 'The opposite of "like" is "___like".', answer: 'dislike', accept: ['dislike', 'dis-like'] },
          { id: 'q11', type: 'multiple', q: 'Which is a word with the prefix "un-"?', opts: ['unable', 'rewrite', 'disobey', 'misread'], ans: 'unable' },
          { id: 'q12', type: 'fillBlank', q: '"Unkind" is the opposite of ___.', answer: 'kind', accept: ['kind'] },
          { id: 'q13', type: 'trueFalse', q: '"Reconstruct" means to build again.', ans: true },
          { id: 'q14', type: 'multiple', q: 'What does "pre-" mean?', opts: ['again', 'not', 'before', 'wrongly'], ans: 'before' },
          { id: 'q15', type: 'fillBlank', q: '"Dishonest" means not ___.', answer: 'honest', accept: ['honest'] },
          { id: 'q16', type: 'trueFalse', q: '"Precook" means to cook before something else.', ans: true },
          { id: 'q17', type: 'multiple', q: 'Which word uses the prefix "mis-"?', opts: ['unhappy', 'misspell', 'rewrite', 'disagree'], ans: 'misspell' },
          { id: 'q18', type: 'fillBlank', q: '"Unpack" means to ___ something from a bag.', answer: 'remove', accept: ['remove', 'take out'] },
          { id: 'q19', type: 'trueFalse', q: '"Discomfort" uses the prefix "dis-".', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"Unclear" means not ___.', answer: 'clear', accept: ['clear'] },
          { id: 'q21', type: 'multiple', q: 'Which prefix means "not"?', opts: ['re-', 'un-', 'pre-', 'dis-'], ans: 'un-' },
          { id: 'q22', type: 'trueFalse', q: '"Unsafe" is the opposite of safe.', ans: true }
        ]
      },
      {
        id: 'y3-english-2',
        name: 'Suffixes',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What suffix means "in a certain way"?', opts: ['-ment', '-ly', '-ness', '-ful'], ans: '-ly' },
          { id: 'q2', type: 'fillBlank', q: '"Quick" becomes "___ly" which means in a quick way.', answer: 'quickly', accept: ['quickly', 'quick-ly'] },
          { id: 'q3', type: 'trueFalse', q: '"-ness" can be added to adjectives to make nouns.', ans: true },
          { id: 'q4', type: 'multiple', q: 'Which word has the suffix "-ment"?', opts: ['quickly', 'sadness', 'enjoyment', 'helpful'], ans: 'enjoyment' },
          { id: 'q5', type: 'fillBlank', q: '"Happy" becomes "___ness" meaning the state of being happy.', answer: 'happiness', accept: ['happiness', 'happy-ness'] },
          { id: 'q6', type: 'trueFalse', q: '"-ful" means without.', ans: false },
          { id: 'q7', type: 'multiple', q: 'What does the suffix "-ful" mean?', opts: ['without', 'full of', 'in the way of', 'the quality of'], ans: 'full of' },
          { id: 'q8', type: 'fillBlank', q: '"Beautiful" means ___ of beauty.', answer: 'full', accept: ['full'] },
          { id: 'q9', type: 'trueFalse', q: '"-ment" is used to turn verbs into nouns.', ans: true },
          { id: 'q10', type: 'fillBlank', q: '"Careful" means full of ___.', answer: 'care', accept: ['care'] },
          { id: 'q11', type: 'multiple', q: 'Which word uses the suffix "-less"?', opts: ['kindness', 'hopeless', 'payment', 'nervous'], ans: 'hopeless' },
          { id: 'q12', type: 'fillBlank', q: '"-less" means without or ___. "Homeless" means without a ___.', answer: 'home', accept: ['home'] },
          { id: 'q13', type: 'trueFalse', q: '"Dangerous" uses the suffix "-ous".', ans: true },
          { id: 'q14', type: 'multiple', q: 'What does "-ous" mean at the end of an adjective?', opts: ['full of', 'in a way', 'without', 'the quality of'], ans: 'full of' },
          { id: 'q15', type: 'fillBlank', q: '"Nervous" means full of ___.', answer: 'nerves', accept: ['nerves', 'nervousness'] },
          { id: 'q16', type: 'trueFalse', q: '"Enjoyment" is a noun made from the verb "enjoy".', ans: true },
          { id: 'q17', type: 'multiple', q: 'Which word has the suffix "-ness"?', opts: ['slowly', 'darkness', 'joyful', 'famous'], ans: 'darkness' },
          { id: 'q18', type: 'fillBlank', q: '"Sadness" means the state of being ___.', answer: 'sad', accept: ['sad'] },
          { id: 'q19', type: 'trueFalse', q: '"Fearless" means full of fear.', ans: false },
          { id: 'q20', type: 'fillBlank', q: '"Famous" means ___ of being known.', answer: 'full', accept: ['full'] },
          { id: 'q21', type: 'multiple', q: 'Which suffix means "without"?', opts: ['-ment', '-ful', '-less', '-ly'], ans: '-less' },
          { id: 'q22', type: 'trueFalse', q: '"-ly" is usually added to adjectives to make adverbs.', ans: true }
        ]
      },
      {
        id: 'y3-english-3',
        name: 'Word Classes',
        questions: [
          { id: 'q1', type: 'multiple', q: 'Which word is a noun?', opts: ['run', 'happy', 'table', 'quickly'], ans: 'table' },
          { id: 'q2', type: 'trueFalse', q: 'A verb is a doing or being word.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Beautiful" is an ___ (word class).', answer: 'adjective', accept: ['adjective'] },
          { id: 'q4', type: 'multiple', q: 'What is a verb?', opts: ['a person or thing', 'an action', 'a describing word', 'a joining word'], ans: 'an action' },
          { id: 'q5', type: 'trueFalse', q: '"Slowly" is an adverb.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Run" is a ___. It is what someone does.', answer: 'verb', accept: ['verb'] },
          { id: 'q7', type: 'multiple', q: 'Which is an adjective?', opts: ['jump', 'clever', 'under', 'happily'], ans: 'clever' },
          { id: 'q8', type: 'fillBlank', q: '"Dog" is a ___ because it is a person or thing.', answer: 'noun', accept: ['noun'] },
          { id: 'q9', type: 'trueFalse', q: 'An adjective describes a noun.', ans: true },
          { id: 'q10', type: 'multiple', q: 'Which word is an adverb?', opts: ['blue', 'sing', 'quickly', 'car'], ans: 'quickly' },
          { id: 'q11', type: 'trueFalse', q: '"Red" is a verb.', ans: false },
          { id: 'q12', type: 'fillBlank', q: 'An adverb tells us ___ a verb happens.', answer: 'how', accept: ['how'] },
          { id: 'q13', type: 'multiple', q: 'What word class is "and"?', opts: ['noun', 'verb', 'adjective', 'conjunction'], ans: 'conjunction' },
          { id: 'q14', type: 'trueFalse', q: '"Tired" can be both an adjective and describe someone.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'A ___ is a word that joins words or sentences.', answer: 'conjunction', accept: ['conjunction'] },
          { id: 'q16', type: 'multiple', q: 'Which is a noun?', opts: ['enjoy', 'tall', 'friendship', 'loudly'], ans: 'friendship' },
          { id: 'q17', type: 'trueFalse', q: '"Dance" can be both a noun and a verb.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'In "the big dog", "big" is an ___.', answer: 'adjective', accept: ['adjective'] },
          { id: 'q19', type: 'trueFalse', q: '"Very" is an adverb that can modify an adjective.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"The", "a", and "an" are called ___.', answer: 'articles', accept: ['articles', 'determiners'] },
          { id: 'q21', type: 'multiple', q: 'Which is NOT a verb?', opts: ['skip', 'laugh', 'happiness', 'dance'], ans: 'happiness' },
          { id: 'q22', type: 'trueFalse', q: 'Prepositions show the relationship between words.', ans: true }
        ]
      },
      {
        id: 'y3-english-4',
        name: 'Conjunctions',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a conjunction?', opts: ['a noun', 'a joining word', 'an adjective', 'a verb'], ans: 'a joining word' },
          { id: 'q2', type: 'trueFalse', q: '"But" is a conjunction.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'I went to the shop ___ I bought milk.', answer: 'and', accept: ['and'] },
          { id: 'q4', type: 'multiple', q: 'Which conjunction shows a contrast?', opts: ['because', 'and', 'but', 'when'], ans: 'but' },
          { id: 'q5', type: 'trueFalse', q: '"Because" explains a reason.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'I like football ___ I don\'t like tennis.', answer: 'but', accept: ['but'] },
          { id: 'q7', type: 'multiple', q: 'Which word is a conjunction?', opts: ['happy', 'although', 'quickly', 'red'], ans: 'although' },
          { id: 'q8', type: 'fillBlank', q: '"I went outside ___ the sun was shining." The conjunction is ___.', answer: 'because', accept: ['because'] },
          { id: 'q9', type: 'trueFalse', q: '"While" can be a conjunction.', ans: true },
          { id: 'q10', type: 'fillBlank', q: '"___ I came in, everyone said hello." The conjunction is ___.', answer: 'when', accept: ['when'] },
          { id: 'q11', type: 'multiple', q: 'What does "before" show?', opts: ['a reason', 'time order', 'a contrast', 'a joining'], ans: 'time order' },
          { id: 'q12', type: 'fillBlank', q: 'I washed my hands ___ I ate dinner.', answer: 'before', accept: ['before'] },
          { id: 'q13', type: 'trueFalse', q: '"After" is a time conjunction.', ans: true },
          { id: 'q14', type: 'fillBlank', q: 'I went to bed ___ I watched the film.', answer: 'after', accept: ['after'] },
          { id: 'q15', type: 'trueFalse', q: '"Although" and "but" have similar meanings.', ans: true },
          { id: 'q16', type: 'fillBlank', q: 'I like pizza ___ I like pasta. (Show two things you like)', answer: 'and', accept: ['and'] },
          { id: 'q17', type: 'multiple', q: 'Which is true about "while"?', opts: ['it shows why', 'it shows when', 'it shows a contrast', 'it joins equal things'], ans: 'it shows when' },
          { id: 'q18', type: 'fillBlank', q: '"It was hot ___ it was raining." The conjunction is ___.', answer: 'although', accept: ['although', 'but'] },
          { id: 'q19', type: 'trueFalse', q: 'Conjunctions help join words and sentences.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"I didn\'t go out ___ the weather was bad." The conjunction is ___.', answer: 'because', accept: ['because'] },
          { id: 'q21', type: 'multiple', q: 'What comes after "because"?', opts: ['a noun', 'a reason', 'an adjective', 'a verb'], ans: 'a reason' },
          { id: 'q22', type: 'trueFalse', q: 'Conjunctions only join words, not sentences.', ans: false }
        ]
      },
      {
        id: 'y3-english-5',
        name: 'Prepositions',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a preposition?', opts: ['a verb', 'a word showing position or relationship', 'an adjective', 'a noun'], ans: 'a word showing position or relationship' },
          { id: 'q2', type: 'trueFalse', q: '"Under" is a preposition.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'The ball is ___ the table.', answer: 'under', accept: ['under', 'on', 'in front of'] },
          { id: 'q4', type: 'multiple', q: 'Which preposition shows something is at a higher level?', opts: ['under', 'behind', 'above', 'during'], ans: 'above' },
          { id: 'q5', type: 'trueFalse', q: '"Before" and "after" are prepositions.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'The cat is ___ the fence.', answer: 'behind', accept: ['behind'] },
          { id: 'q7', type: 'multiple', q: 'Which is a preposition?', opts: ['run', 'happy', 'in', 'quickly'], ans: 'in' },
          { id: 'q8', type: 'fillBlank', q: '"I waited ___ the lesson." The preposition is ___.', answer: 'during', accept: ['during'] },
          { id: 'q9', type: 'trueFalse', q: '"On" can show position.', ans: true },
          { id: 'q10', type: 'fillBlank', q: 'The book is ___ the shelf.', answer: 'on', accept: ['on'] },
          { id: 'q11', type: 'multiple', q: 'What does "in front of" show?', opts: ['time', 'position', 'reason', 'manner'], ans: 'position' },
          { id: 'q12', type: 'fillBlank', q: 'I sat ___ the classroom.', answer: 'in', accept: ['in'] },
          { id: 'q13', type: 'trueFalse', q: '"After" only shows position.', ans: false },
          { id: 'q14', type: 'fillBlank', q: 'The toy is ___ the box and the car.', answer: 'between', accept: ['between'] },
          { id: 'q15', type: 'trueFalse', q: '"Before" is a preposition of time.', ans: true },
          { id: 'q16', type: 'multiple', q: 'Which preposition means at a lower level?', opts: ['above', 'under', 'over', 'below'], ans: 'under' },
          { id: 'q17', type: 'fillBlank', q: 'The picture is ___ the wall.', answer: 'on', accept: ['on'] },
          { id: 'q18', type: 'trueFalse', q: 'Prepositions can show time, position, or relationship.', ans: true },
          { id: 'q19', type: 'fillBlank', q: '"I worked ___ Monday." The preposition is ___.', answer: 'during', accept: ['during', 'on'] },
          { id: 'q20', type: 'multiple', q: 'What does "above" mean?', opts: ['at a lower level', 'at a higher level', 'in the middle', 'somewhere else'], ans: 'at a higher level' },
          { id: 'q21', type: 'fillBlank', q: 'I walked ___ the park.', answer: 'through', accept: ['through'] },
          { id: 'q22', type: 'trueFalse', q: 'Prepositions usually come before a noun or noun phrase.', ans: true }
        ]
      },
      {
        id: 'y3-english-6',
        name: 'Present Perfect Tense',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How do we form the present perfect?', opts: ['verb + -ed', 'have/has + past participle', 'will + verb', 'is/are + -ing'], ans: 'have/has + past participle' },
          { id: 'q2', type: 'trueFalse', q: '"I have eaten" is present perfect.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"She ___ gone to school." Use has or have.', answer: 'has', accept: ['has'] },
          { id: 'q4', type: 'multiple', q: 'Which is present perfect?', opts: ['I eat', 'I am eating', 'I have eaten', 'I will eat'], ans: 'I have eaten' },
          { id: 'q5', type: 'trueFalse', q: '"They have arrived" means something is finished recently.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"I ___ finished my homework." Fill with have or has.', answer: 'have', accept: ['have'] },
          { id: 'q7', type: 'multiple', q: 'What is the past participle of "go"?', opts: ['going', 'goes', 'gone', 'goed'], ans: 'gone' },
          { id: 'q8', type: 'trueFalse', q: '"He has worked here for two years" describes recent action.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"We ___ been to London." Use have or has.', answer: 'have', accept: ['have'] },
          { id: 'q10', type: 'multiple', q: 'What is the past participle of "eat"?', opts: ['eating', 'eats', 'eaten', 'ate'], ans: 'eaten' },
          { id: 'q11', type: 'trueFalse', q: 'Present perfect is used to link the past and present.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"It ___ started raining." Fill with has or have.', answer: 'has', accept: ['has'] },
          { id: 'q13', type: 'multiple', q: 'Choose the correct sentence.', opts: ['I has gone', 'She have arrived', 'You have come', 'It are finished'], ans: 'You have come' },
          { id: 'q14', type: 'trueFalse', q: '"The children has eaten" is correct.', ans: false },
          { id: 'q15', type: 'fillBlank', q: '"I ___ never seen that film." Fill with have or has.', answer: 'have', accept: ['have'] },
          { id: 'q16', type: 'multiple', q: 'What is the past participle of "see"?', opts: ['saw', 'seeing', 'seen', 'sees'], ans: 'seen' },
          { id: 'q17', type: 'trueFalse', q: '"She have been to France" uses correct grammar.', ans: false },
          { id: 'q18', type: 'fillBlank', q: '"You ___ made a mistake." Fill with have or has.', answer: 'have', accept: ['have'] },
          { id: 'q19', type: 'trueFalse', q: '"They have arrived" is present perfect tense.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"My friend ___ lost her keys." Fill with have or has.', answer: 'has', accept: ['has'] },
          { id: 'q21', type: 'multiple', q: 'What is the past participle of "write"?', opts: ['writing', 'wrote', 'written', 'writes'], ans: 'written' },
          { id: 'q22', type: 'trueFalse', q: 'Present perfect is always formed with "to be" + -ing.', ans: false }
        ]
      },
      {
        id: 'y3-english-7',
        name: 'Paragraphs',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a paragraph?', opts: ['a single sentence', 'a group of sentences about one idea', 'a page of writing', 'a chapter'], ans: 'a group of sentences about one idea' },
          { id: 'q2', type: 'trueFalse', q: 'A paragraph should have a clear topic.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'The first sentence of a paragraph is called a ___ sentence.', answer: 'topic', accept: ['topic'] },
          { id: 'q4', type: 'multiple', q: 'What does a topic sentence do?', opts: ['ends the paragraph', 'introduces the main idea', 'repeats information', 'is always at the end'], ans: 'introduces the main idea' },
          { id: 'q5', type: 'trueFalse', q: 'A paragraph can be about many different topics.', ans: false },
          { id: 'q6', type: 'fillBlank', q: 'Supporting sentences ___ the topic sentence.', answer: 'develop', accept: ['develop', 'support', 'explain'] },
          { id: 'q7', type: 'multiple', q: 'How should you start a new paragraph?', opts: ['in the middle of the line', 'on a new line with an indent', 'without any space', 'anywhere'], ans: 'on a new line with an indent' },
          { id: 'q8', type: 'trueFalse', q: 'The closing sentence should summarise the paragraph.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Related ideas should be grouped in the ___ paragraph.', answer: 'same', accept: ['same'] },
          { id: 'q10', type: 'multiple', q: 'Which belongs in a paragraph about animals?', opts: ['the taste of ice cream', 'how elephants live', 'cooking pasta', 'wearing a hat'], ans: 'how elephants live' },
          { id: 'q11', type: 'trueFalse', q: 'A paragraph should be very short.', ans: false },
          { id: 'q12', type: 'fillBlank', q: 'A ___ sentence ends and summarises the paragraph.', answer: 'closing', accept: ['closing', 'concluding', 'final'] },
          { id: 'q13', type: 'multiple', q: 'What is NOT part of a paragraph structure?', opts: ['topic sentence', 'supporting details', 'multiple unrelated ideas', 'concluding sentence'], ans: 'multiple unrelated ideas' },
          { id: 'q14', type: 'trueFalse', q: 'You should use the same idea across different paragraphs.', ans: false },
          { id: 'q15', type: 'fillBlank', q: 'A good paragraph stays ___ to one main idea.', answer: 'focused', accept: ['focused'] },
          { id: 'q16', type: 'trueFalse', q: 'Details should support the topic sentence.', ans: true },
          { id: 'q17', type: 'multiple', q: 'Which is a feature of good paragraphs?', opts: ['all sentences are the same', 'clear organisation around one idea', 'no sentences', 'random order'], ans: 'clear organisation around one idea' },
          { id: 'q18', type: 'fillBlank', q: 'Sentences in a paragraph should be ___ to each other.', answer: 'related', accept: ['related', 'connected'] },
          { id: 'q19', type: 'trueFalse', q: 'A paragraph indent shows you are starting a new topic.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'The ___ sentence introduces the main idea of the paragraph.', answer: 'topic', accept: ['topic'] },
          { id: 'q21', type: 'multiple', q: 'Why is organisation important in paragraphs?', opts: ['for decoration', 'to help readers understand ideas', 'to use more words', 'no reason'], ans: 'to help readers understand ideas' },
          { id: 'q22', type: 'trueFalse', q: 'A paragraph should link to the next paragraph.', ans: true }
        ]
      },
      {
        id: 'y3-english-8',
        name: 'Punctuation',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What are inverted commas used for?', opts: ['quotation marks', 'showing direct speech', 'both of the above', 'none of the above'], ans: 'both of the above' },
          { id: 'q2', type: 'trueFalse', q: 'Inverted commas show what someone says.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"___ said, ___I am happy.__" (Fill in quote marks)', answer: 'She "I am happy."', accept: ['"I am happy."', 'She said, "I am happy."'] },
          { id: 'q4', type: 'multiple', q: 'How should direct speech be punctuated?', opts: ['no marks', 'with inverted commas', 'with brackets', 'with dashes'], ans: 'with inverted commas' },
          { id: 'q5', type: 'trueFalse', q: 'A comma separates items in a list.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'I like apples___ oranges___ and bananas. (Use commas)', answer: ',', accept: [',', ', ,'] },
          { id: 'q7', type: 'multiple', q: 'Which sentence has correct commas in a list?', opts: ['apples oranges bananas', 'apples, oranges, and bananas', 'apples; oranges; bananas', 'apples oranges, bananas'], ans: 'apples, oranges, and bananas' },
          { id: 'q8', type: 'trueFalse', q: 'Commas help separate ideas in writing.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"___What is your name___" she asked. (Add quotation marks)', answer: '"What is your name?"', accept: ['"What is your name?"'] },
          { id: 'q10', type: 'multiple', q: 'Which list is punctuated correctly?', opts: ['red blue green', 'red, blue, green', 'red blue, green', 'red, blue green'], ans: 'red, blue, green' },
          { id: 'q11', type: 'trueFalse', q: 'Direct speech always needs a comma or question mark inside the inverted commas.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '___Go away___ he shouted. (Add quotation marks)', answer: '"Go away!"', accept: ['"Go away!"'] },
          { id: 'q13', type: 'trueFalse', q: 'A list of three items needs two commas.', ans: true },
          { id: 'q14', type: 'fillBlank', q: 'The items in a list are ___ by commas.', answer: 'separated', accept: ['separated', 'divided'] },
          { id: 'q15', type: 'trueFalse', q: 'Inverted commas always go at the beginning and end of direct speech.', ans: true },
          { id: 'q16', type: 'multiple', q: 'Which is NOT punctuated correctly?', opts: ['"Hello," said Tom', '"Help me!" she cried', 'Apples, pears, and oranges', 'He said ___I am tired___'], ans: 'He said ___I am tired___' },
          { id: 'q17', type: 'fillBlank', q: '___Can you help___ asked Sam. (Add quotation marks)', answer: '"Can you help?"', accept: ['"Can you help?"'] },
          { id: 'q18', type: 'trueFalse', q: 'When writing lists, the final comma before "and" is optional.', ans: true },
          { id: 'q19', type: 'fillBlank', q: 'Lists can contain: nouns___ adjectives___ or verbs. (Add commas)', answer: ',', accept: [','] },
          { id: 'q20', type: 'trueFalse', q: 'Direct speech is what someone actually says.', ans: true },
          { id: 'q21', type: 'fillBlank', q: '"___Let\'s play___ said Mia. (Add quotation marks)', answer: '"Let\'s play!"', accept: ['"Let\'s play!"'] },
          { id: 'q22', type: 'multiple', q: 'What punctuation goes inside inverted commas?', opts: ['only commas', 'all punctuation marks', 'nothing', 'only full stops'], ans: 'all punctuation marks' }
        ]
      }
    ]
  },
  science: {
    name: 'Science',
    icon: '🔬',
    color: '#9C27B0',
    lessons: [
      {
        id: 'y3-science-1',
        name: 'Plants',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does the root of a plant do?', opts: ['makes food', 'absorbs water and nutrients', 'catches sunlight', 'produces seeds'], ans: 'absorbs water and nutrients' },
          { id: 'q2', type: 'trueFalse', q: 'Leaves capture sunlight for photosynthesis.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'The ___ holds the plant upright.', answer: 'stem', accept: ['stem'] },
          { id: 'q4', type: 'multiple', q: 'What is the main function of flowers?', opts: ['to absorb water', 'to store food', 'to produce seeds', 'to support the plant'], ans: 'to produce seeds' },
          { id: 'q5', type: 'trueFalse', q: 'Water travels up from the roots through the stem.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Plants need water___ sunlight___ and ___ to grow.', answer: 'soil', accept: ['soil', 'nutrients'] },
          { id: 'q7', type: 'multiple', q: 'Which part of a plant makes food?', opts: ['roots', 'stem', 'leaves', 'flowers'], ans: 'leaves' },
          { id: 'q8', type: 'trueFalse', q: 'Plants need soil to survive.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'The ___ holds the seeds.', answer: 'fruit', accept: ['fruit'] },
          { id: 'q10', type: 'multiple', q: 'What does a plant need to grow?', opts: ['only water', 'water, sunlight, and soil nutrients', 'only sunlight', 'only soil'], ans: 'water, sunlight, and soil nutrients' },
          { id: 'q11', type: 'trueFalse', q: 'Roots grow downward to find water.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'The process plants use to make food is called ___.', answer: 'photosynthesis', accept: ['photosynthesis'] },
          { id: 'q13', type: 'multiple', q: 'Why do plants need sunlight?', opts: ['to absorb water', 'to make food', 'to grow roots', 'to reproduce'], ans: 'to make food' },
          { id: 'q14', type: 'trueFalse', q: 'Flowers are important for making seeds.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The ___ transports water and nutrients through the plant.', answer: 'stem', accept: ['stem', 'xylem'] },
          { id: 'q16', type: 'multiple', q: 'What colour are leaves usually?', opts: ['brown', 'green', 'yellow', 'red'], ans: 'green' },
          { id: 'q17', type: 'trueFalse', q: 'Plants produce their own food.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'The part of a plant that grows underground is the ___.', answer: 'root', accept: ['root', 'roots'] },
          { id: 'q19', type: 'trueFalse', q: 'Roots can absorb nutrients from soil.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A plant with colourful petals is likely a ___.', answer: 'flower', accept: ['flower'] },
          { id: 'q21', type: 'trueFalse', q: 'Plants release oxygen during photosynthesis.', ans: true },
          { id: 'q22', type: 'multiple', q: 'Which is a root function?', opts: ['making food', 'absorbing water and minerals', 'catching sunlight', 'protecting seeds'], ans: 'absorbing water and minerals' }
        ]
      },
      {
        id: 'y3-science-2',
        name: 'Animals & Nutrition',
        questions: [
          { id: 'q1', type: 'multiple', q: 'Which is a food group?', opts: ['water', 'carbohydrates', 'air', 'light'], ans: 'carbohydrates' },
          { id: 'q2', type: 'trueFalse', q: 'A balanced diet includes fruits and vegetables.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'Our bones are supported by a ___.', answer: 'skeleton', accept: ['skeleton'] },
          { id: 'q4', type: 'multiple', q: 'What do muscles help us do?', opts: ['digest food', 'move', 'see clearly', 'hear sounds'], ans: 'move' },
          { id: 'q5', type: 'trueFalse', q: 'Protein helps build muscles.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Our ___ are the framework of our body.', answer: 'bones', accept: ['bones', 'skeleton'] },
          { id: 'q7', type: 'multiple', q: 'Which food provides energy?', opts: ['water', 'carbohydrates', 'bones', 'skin'], ans: 'carbohydrates' },
          { id: 'q8', type: 'trueFalse', q: 'We have about 206 bones in our body.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Fish is a good source of ___.', answer: 'protein', accept: ['protein'] },
          { id: 'q10', type: 'multiple', q: 'How many food groups are there in a balanced diet?', opts: ['3', '4', '5', '6'], ans: '5' },
          { id: 'q11', type: 'trueFalse', q: 'Dairy provides calcium for strong bones.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'Muscles work together with ___ to move our body.', answer: 'bones', accept: ['bones'] },
          { id: 'q13', type: 'multiple', q: 'Which is NOT part of a balanced diet?', opts: ['vegetables', 'fruit', 'protein', 'sugar and salt only'], ans: 'sugar and salt only' },
          { id: 'q14', type: 'trueFalse', q: 'The skeleton protects our internal organs.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'We should eat lots of ___ and vegetables.', answer: 'fruit', accept: ['fruit'] },
          { id: 'q16', type: 'multiple', q: 'What does our digestive system do?', opts: ['moves blood', 'breaks down food', 'catches light', 'conducts electricity'], ans: 'breaks down food' },
          { id: 'q17', type: 'trueFalse', q: 'Eating a variety of foods is important for health.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'Our ___ help us chew food.', answer: 'teeth', accept: ['teeth'] },
          { id: 'q19', type: 'trueFalse', q: 'Carbohydrates give our body energy.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A balanced meal includes proteins___ carbohydrates___ and ___.', answer: 'vegetables', accept: ['vegetables', 'fruits'] },
          { id: 'q21', type: 'trueFalse', q: 'Exercise strengthens muscles and bones.', ans: true },
          { id: 'q22', type: 'multiple', q: 'What connects muscles to bones?', opts: ['skin', 'tendons', 'veins', 'organs'], ans: 'tendons' }
        ]
      },
      {
        id: 'y3-science-3',
        name: 'Rocks & Fossils',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What are the three types of rock?', opts: ['hard, soft, liquid', 'igneous, sedimentary, metamorphic', 'light, dark, colorful', 'old, new, ancient'], ans: 'igneous, sedimentary, metamorphic' },
          { id: 'q2', type: 'trueFalse', q: 'Fossils are remains of ancient plants and animals.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'Rocks are made of ___.', answer: 'minerals', accept: ['minerals'] },
          { id: 'q4', type: 'multiple', q: 'How are fossils formed?', opts: ['rocks combine', 'organisms die and become trapped in sediment over time', 'minerals dissolve', 'rocks break'], ans: 'organisms die and become trapped in sediment over time' },
          { id: 'q5', type: 'trueFalse', q: 'Granite is an igneous rock.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Soil is made from broken down ___.', answer: 'rocks', accept: ['rocks'] },
          { id: 'q7', type: 'multiple', q: 'Which rock is sedimentary?', opts: ['granite', 'sandstone', 'basalt', 'marble'], ans: 'sandstone' },
          { id: 'q8', type: 'trueFalse', q: 'Fossils tell us about ancient life.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Igneous rocks form when ___ cools.', answer: 'lava', accept: ['lava', 'magma'] },
          { id: 'q10', type: 'multiple', q: 'What is a fossil impression?', opts: ['a rock impression of an organism shape', 'a complete skeleton', 'a drawing', 'a painting'], ans: 'a rock impression of an organism shape' },
          { id: 'q11', type: 'trueFalse', q: 'Rocks can be hard or soft.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'Different rocks have different ___ and colours.', answer: 'textures', accept: ['textures'] },
          { id: 'q13', type: 'multiple', q: 'What does soil contain?', opts: ['only sand', 'rocks, minerals, and organic material', 'only clay', 'water'], ans: 'rocks, minerals, and organic material' },
          { id: 'q14', type: 'trueFalse', q: 'Rocks are weathered by wind and water.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'Chalk is a type of ___ rock.', answer: 'sedimentary', accept: ['sedimentary'] },
          { id: 'q16', type: 'multiple', q: 'Which type of rock is formed under heat and pressure?', opts: ['igneous', 'sedimentary', 'metamorphic', 'none'], ans: 'metamorphic' },
          { id: 'q17', type: 'trueFalse', q: 'Marble is a metamorphic rock.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A ___ is a preserved footprint or shell in rock.', answer: 'fossil', accept: ['fossil'] },
          { id: 'q19', type: 'trueFalse', q: 'Stones in soil can be very small or very large.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Sedimentary rocks are formed from layers of ___.', answer: 'sediment', accept: ['sediment'] },
          { id: 'q21', type: 'trueFalse', q: 'Fossils only show animals, not plants.', ans: false },
          { id: 'q22', type: 'multiple', q: 'What is the main ingredient of soil?', opts: ['water', 'sand', 'broken-down rock', 'metal'], ans: 'broken-down rock' }
        ]
      },
      {
        id: 'y3-science-4',
        name: 'Light',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a light source?', opts: ['something dark', 'something that produces light', 'something transparent', 'something cold'], ans: 'something that produces light' },
          { id: 'q2', type: 'trueFalse', q: 'The sun is a light source.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'Dark means the ___ of light.', answer: 'absence', accept: ['absence', 'lack'] },
          { id: 'q4', type: 'multiple', q: 'What is a shadow?', opts: ['a light', 'a dark area caused by blocking light', 'a colour', 'heat'], ans: 'a dark area caused by blocking light' },
          { id: 'q5', type: 'trueFalse', q: 'Light bounces off reflective surfaces.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'A ___ is a reflective surface.', answer: 'mirror', accept: ['mirror'] },
          { id: 'q7', type: 'multiple', q: 'What is reflection?', opts: ['light absorbing', 'light bouncing back', 'light disappearing', 'light moving forward'], ans: 'light bouncing back' },
          { id: 'q8', type: 'trueFalse', q: 'The moon reflects light from the sun.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A shadow forms when light is ___ by an object.', answer: 'blocked', accept: ['blocked'] },
          { id: 'q10', type: 'multiple', q: 'What happens to light in darkness?', opts: ['it stays', 'it multiplies', 'there is no light', 'it gets bigger'], ans: 'there is no light' },
          { id: 'q11', type: 'trueFalse', q: 'We need light to see.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'Light travels in straight ___.', answer: 'lines', accept: ['lines'] },
          { id: 'q13', type: 'multiple', q: 'Which is a light source?', opts: ['the moon', 'a lamp', 'a mirror', 'a window'], ans: 'a lamp' },
          { id: 'q14', type: 'trueFalse', q: 'You should never look directly at the sun.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'We should use ___ when in the sun to protect our skin.', answer: 'sunscreen', accept: ['sunscreen', 'sun cream'] },
          { id: 'q16', type: 'multiple', q: 'What is transparent?', opts: ['dark', 'shiny', 'allows light to pass through', 'solid'], ans: 'allows light to pass through' },
          { id: 'q17', type: 'trueFalse', q: 'Glass is transparent.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A torch is an ___ light source.', answer: 'artificial', accept: ['artificial', 'electric'] },
          { id: 'q19', type: 'trueFalse', q: 'Shadows are always the same size.', ans: false },
          { id: 'q20', type: 'fillBlank', q: 'The size of a shadow depends on the ___ of light and the object.', answer: 'position', accept: ['position'] },
          { id: 'q21', type: 'trueFalse', q: 'Opaque objects block light.', ans: true },
          { id: 'q22', type: 'multiple', q: 'What colour is a shadow?', opts: ['grey', 'brown', 'black', 'depends on the surface'], ans: 'black' }
        ]
      },
      {
        id: 'y3-science-5',
        name: 'Forces & Magnets',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a force?', opts: ['heat', 'a push or pull', 'movement', 'energy'], ans: 'a push or pull' },
          { id: 'q2', type: 'trueFalse', q: 'A magnet attracts all metals.', ans: false },
          { id: 'q3', type: 'fillBlank', q: 'A magnet has ___ poles.', answer: '2', accept: ['2', 'two'] },
          { id: 'q4', type: 'multiple', q: 'What do magnets attract?', opts: ['plastic', 'wood', 'iron', 'paper'], ans: 'iron' },
          { id: 'q5', type: 'trueFalse', q: 'Opposite poles of magnets attract each other.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'The two poles of a magnet are north and ___.', answer: 'south', accept: ['south'] },
          { id: 'q7', type: 'multiple', q: 'What is a contact force?', opts: ['a force from distance', 'a force requiring contact', 'a magnetic force', 'gravity'], ans: 'a force requiring contact' },
          { id: 'q8', type: 'trueFalse', q: 'Gravity is a non-contact force.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Pushing or pulling is a ___ force.', answer: 'contact', accept: ['contact'] },
          { id: 'q10', type: 'multiple', q: 'What is repel?', opts: ['to attract', 'to push away', 'to pull', 'to stop'], ans: 'to push away' },
          { id: 'q11', type: 'trueFalse', q: 'Like poles of magnets repel each other.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'A magnet can work through ___ without touching.', answer: 'air', accept: ['air'] },
          { id: 'q13', type: 'multiple', q: 'Which is a magnetic material?', opts: ['copper', 'steel', 'gold', 'silver'], ans: 'steel' },
          { id: 'q14', type: 'trueFalse', q: 'Friction is a contact force.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'Gravity pulls objects ___.', answer: 'down', accept: ['down', 'downwards', 'towards the Earth'] },
          { id: 'q16', type: 'multiple', q: 'What does friction do?', opts: ['attracts objects', 'slows down movement', 'speeds up objects', 'pushes objects'], ans: 'slows down movement' },
          { id: 'q17', type: 'trueFalse', q: 'You can see magnetic fields.', ans: false },
          { id: 'q18', type: 'fillBlank', q: 'A compass needle points to the ___ pole.', answer: 'north', accept: ['north'] },
          { id: 'q19', type: 'trueFalse', q: 'Earth behaves like a giant magnet.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Iron and ___ are magnetic materials.', answer: 'steel', accept: ['steel', 'nickel', 'cobalt'] },
          { id: 'q21', type: 'trueFalse', q: 'Magnetic force can work over a distance.', ans: true },
          { id: 'q22', type: 'multiple', q: 'What is an example of a non-contact force?', opts: ['pushing', 'rubbing', 'gravity', 'kicking'], ans: 'gravity' }
        ]
      },
      {
        id: 'y3-science-6',
        name: 'Working Scientifically',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a fair test?', opts: ['a test that is fun', 'a test where only one thing changes', 'a test that is short', 'a test with many changes'], ans: 'a test where only one thing changes' },
          { id: 'q2', type: 'trueFalse', q: 'A prediction is an educated guess.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'In an experiment, the ___ is what we change.', answer: 'variable', accept: ['variable', 'independent variable'] },
          { id: 'q4', type: 'multiple', q: 'Why do we record results?', opts: ['to decorate', 'to remember and analyse data', 'to confuse others', 'for no reason'], ans: 'to remember and analyse data' },
          { id: 'q5', type: 'trueFalse', q: 'We should repeat experiments to check results.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'We keep things the ___ in a fair test except one thing.', answer: 'same', accept: ['same'] },
          { id: 'q7', type: 'multiple', q: 'What should we observe?', opts: ['nothing', 'what happens during the experiment', 'only what we want to see', 'nothing carefully'], ans: 'what happens during the experiment' },
          { id: 'q8', type: 'trueFalse', q: 'Results can be recorded in a table.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A ___ is a suggested explanation based on observations.', answer: 'hypothesis', accept: ['hypothesis'] },
          { id: 'q10', type: 'multiple', q: 'What makes a test unfair?', opts: ['asking questions', 'changing more than one variable', 'measuring carefully', 'taking notes'], ans: 'changing more than one variable' },
          { id: 'q11', type: 'trueFalse', q: 'We should measure accurately.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'A conclusion is based on ___.', answer: 'results', accept: ['results', 'data', 'observations'] },
          { id: 'q13', type: 'multiple', q: 'What is observation?', opts: ['guessing', 'noticing carefully', 'talking', 'listening'], ans: 'noticing carefully' },
          { id: 'q14', type: 'trueFalse', q: 'Safety is important in experiments.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'We should use appropriate ___ when measuring.', answer: 'equipment', accept: ['equipment', 'tools'] },
          { id: 'q16', type: 'multiple', q: 'Why is it important to repeat tests?', opts: ['to waste time', 'to check if results are reliable', 'for no reason', 'to change results'], ans: 'to check if results are reliable' },
          { id: 'q17', type: 'trueFalse', q: 'Evidence is information we gather.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'We write a ___ to summarise what we learned.', answer: 'conclusion', accept: ['conclusion'] },
          { id: 'q19', type: 'trueFalse', q: 'A fair test has controlled variables.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Before an experiment, we make a ___.', answer: 'prediction', accept: ['prediction'] },
          { id: 'q21', type: 'trueFalse', q: 'We should always follow safety rules.', ans: true },
          { id: 'q22', type: 'multiple', q: 'What is the purpose of a prediction?', opts: ['to know the answer', 'to guess before testing', 'to plan the experiment', 'both b and c'], ans: 'both b and c' }
        ]
      }
    ]
  },
  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#FF5722',
    lessons: [
      {
        id: 'y3-french-1',
        name: 'Greetings & Feelings',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does "Bonjour" mean?', opts: ['goodbye', 'hello', 'thank you', 'please'], ans: 'hello' },
          { id: 'q2', type: 'trueFalse', q: '"Au revoir" means goodbye.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Comment ça va?" means "How are ___?"', answer: 'you', accept: ['you'] },
          { id: 'q4', type: 'multiple', q: 'How do you respond "I am happy"?', opts: ['Je suis triste', 'Je suis content', 'Je suis fatigué', 'Je suis froid'], ans: 'Je suis content' },
          { id: 'q5', type: 'trueFalse', q: '"Je suis triste" means I am sad.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Ça va bien" means "I am ___."', answer: 'well', accept: ['well', 'fine', 'good'] },
          { id: 'q7', type: 'multiple', q: 'What is the French word for tired?', opts: ['fatigué', 'heureux', 'malade', 'content'], ans: 'fatigué' },
          { id: 'q8', type: 'trueFalse', q: '"S\'il vous plaît" is a formal "please".', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Merci" means ___. "De rien" means "You\'re ___."', answer: 'thank you', accept: ['thank you', 'thanks'] },
          { id: 'q10', type: 'multiple', q: 'What does "Excusez-moi" mean?', opts: ['hello', 'goodbye', 'excuse me', 'thank you'], ans: 'excuse me' },
          { id: 'q11', type: 'trueFalse', q: '"Bonsoir" means good evening.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Je suis malade" means "I am ___."', answer: 'ill', accept: ['ill', 'sick'] },
          { id: 'q13', type: 'multiple', q: 'How do you say "Nice to meet you" in French?', opts: ['Enchanteur', 'Enchanté', 'En français', 'En anglais'], ans: 'Enchanté' },
          { id: 'q14', type: 'trueFalse', q: '"Ça ne va pas" means "I am not well".', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"Je suis ___ " means "I am scared".', answer: 'effrayé', accept: ['effrayé', 'avoir peur'] },
          { id: 'q16', type: 'multiple', q: 'What feeling is "Je suis heureux"?', opts: ['sad', 'happy', 'tired', 'cold'], ans: 'happy' },
          { id: 'q17', type: 'trueFalse', q: '"Pardon" means sorry.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"À bientôt" means "See you ___."', answer: 'soon', accept: ['soon'] },
          { id: 'q19', type: 'trueFalse', q: '"Je suis froid" is correct French for "I am cold".', ans: false },
          { id: 'q20', type: 'fillBlank', q: '"Et toi?" means "And ___?"', answer: 'you', accept: ['you'] },
          { id: 'q21', type: 'multiple', q: 'What does "Bonne nuit" mean?', opts: ['good day', 'good morning', 'good night', 'good evening'], ans: 'good night' },
          { id: 'q22', type: 'trueFalse', q: '"Je suis en forme" means I am in good form or feeling well.', ans: true }
        ]
      },
      {
        id: 'y3-french-2',
        name: 'Numbers & Alphabet',
        questions: [
          { id: 'q1', type: 'fillBlank', q: 'The French number 3 is "___.', answer: 'trois', accept: ['trois'] },
          { id: 'q2', type: 'multiple', q: 'What is the number 5 in French?', opts: ['trois', 'quatre', 'cinq', 'six'], ans: 'cinq' },
          { id: 'q3', type: 'trueFalse', q: '"Un" is the number 1 in French.', ans: true },
          { id: 'q4', type: 'fillBlank', q: 'The number 10 in French is "___.', answer: 'dix', accept: ['dix'] },
          { id: 'q5', type: 'multiple', q: 'What is 7 in French?', opts: ['six', 'sept', 'huit', 'neuf'], ans: 'sept' },
          { id: 'q6', type: 'trueFalse', q: '"Neuf" means 9.', ans: true },
          { id: 'q7', type: 'fillBlank', q: 'The number 2 in French is "___.', answer: 'deux', accept: ['deux'] },
          { id: 'q8', type: 'multiple', q: 'What is 8 in French?', opts: ['sept', 'huit', 'neuf', 'dix'], ans: 'huit' },
          { id: 'q9', type: 'trueFalse', q: '"Quatre" means 4.', ans: true },
          { id: 'q10', type: 'fillBlank', q: 'The number 6 in French is "___.', answer: 'six', accept: ['six'] },
          { id: 'q11', type: 'multiple', q: 'How do you count 0 in French?', opts: ['nul', 'zéro', 'nil', 'néant'], ans: 'zéro' },
          { id: 'q12', type: 'fillBlank', q: 'The letter "A" is spelled "___ " in French alphabet.', answer: 'A', accept: ['A', 'a'] },
          { id: 'q13', type: 'trueFalse', q: '"Vingt" is the number 20.', ans: true },
          { id: 'q14', type: 'fillBlank', q: 'The letter "C" in French is pronounced "___."', answer: 'cé', accept: ['cé'] },
          { id: 'q15', type: 'multiple', q: 'What is 11 in French?', opts: ['dix', 'onze', 'douze', 'treize'], ans: 'onze' },
          { id: 'q16', type: 'trueFalse', q: '"Douze" means 12.', ans: true },
          { id: 'q17', type: 'fillBlank', q: 'How many letters are in the French alphabet? ___', answer: '26', accept: ['26', 'twenty-six'] },
          { id: 'q18', type: 'multiple', q: 'What is the number 15 in French?', opts: ['douze', 'treize', 'quatorze', 'quinze'], ans: 'quinze' },
          { id: 'q19', type: 'trueFalse', q: '"Quatorze" is 14.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'The number 16 in French is "___.', answer: 'seize', accept: ['seize'] },
          { id: 'q21', type: 'multiple', q: 'What is 18 in French?', opts: ['quinze', 'seize', 'dix-huit', 'vingt'], ans: 'dix-huit' },
          { id: 'q22', type: 'trueFalse', q: '"Dix-neuf" is 19.', ans: true }
        ]
      },
      {
        id: 'y3-french-3',
        name: 'Days, Months & Birthdays',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does "Quel jour sommes-nous?" mean?', opts: ['What month is it?', 'What day is it?', 'What time is it?', 'What year is it?'], ans: 'What day is it?' },
          { id: 'q2', type: 'trueFalse', q: '"Lundi" is Monday.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'Tuesday in French is "___.', answer: 'mardi', accept: ['mardi'] },
          { id: 'q4', type: 'multiple', q: 'What is Wednesday?', opts: ['lundi', 'mardi', 'mercredi', 'jeudi'], ans: 'mercredi' },
          { id: 'q5', type: 'trueFalse', q: '"Vendredi" is Friday.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Saturday in French is "___.', answer: 'samedi', accept: ['samedi'] },
          { id: 'q7', type: 'multiple', q: 'What is Sunday?', opts: ['samedi', 'dimanche', 'lundi', 'mercredi'], ans: 'dimanche' },
          { id: 'q8', type: 'trueFalse', q: '"Jeudi" means Thursday.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"C\'est quand ton anniversaire?" means "When is your ___?"', answer: 'birthday', accept: ['birthday'] },
          { id: 'q10', type: 'multiple', q: 'How do you say January in French?', opts: ['Février', 'Mars', 'Janvier', 'Avril'], ans: 'Janvier' },
          { id: 'q11', type: 'trueFalse', q: '"Février" is February.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'March in French is "___.', answer: 'mars', accept: ['mars'] },
          { id: 'q13', type: 'multiple', q: 'What is April in French?', opts: ['mars', 'avril', 'mai', 'juin'], ans: 'avril' },
          { id: 'q14', type: 'trueFalse', q: '"Mai" is May.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'June in French is "___.', answer: 'juin', accept: ['juin'] },
          { id: 'q16', type: 'multiple', q: 'What is July?', opts: ['juin', 'juillet', 'août', 'septembre'], ans: 'juillet' },
          { id: 'q17', type: 'trueFalse', q: '"Août" is August.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'September in French is "___.', answer: 'septembre', accept: ['septembre'] },
          { id: 'q19', type: 'trueFalse', q: '"Octobre" is October.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'November in French is "___.', answer: 'novembre', accept: ['novembre'] },
          { id: 'q21', type: 'multiple', q: 'What is December?', opts: ['novembre', 'décembre', 'janvier', 'octobre'], ans: 'décembre' },
          { id: 'q22', type: 'trueFalse', q: '"Mon anniversaire est en juillet" means "My birthday is in July".', ans: true }
        ]
      },
      {
        id: 'y3-french-4',
        name: 'Classroom Objects',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a pencil in French?', opts: ['un stylo', 'un crayon', 'une règle', 'un livre'], ans: 'un crayon' },
          { id: 'q2', type: 'trueFalse', q: '"Une règle" is a ruler.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'A book in French is "___."', answer: 'un livre', accept: ['un livre', 'livre'] },
          { id: 'q4', type: 'multiple', q: 'What is a notebook?', opts: ['un crayon', 'un cahier', 'une gomme', 'un stylo'], ans: 'un cahier' },
          { id: 'q5', type: 'trueFalse', q: '"Une gomme" is an eraser.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Scissors in French are "___."', answer: 'des ciseaux', accept: ['des ciseaux', 'ciseaux'] },
          { id: 'q7', type: 'multiple', q: 'What is a pen?', opts: ['un crayon', 'une règle', 'un stylo', 'un cahier'], ans: 'un stylo' },
          { id: 'q8', type: 'trueFalse', q: '"Un tableau" is a blackboard.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Glue in French is "___."', answer: 'la colle', accept: ['la colle', 'colle'] },
          { id: 'q10', type: 'multiple', q: 'What is a desk?', opts: ['une chaise', 'un bureau', 'une table', 'une porte'], ans: 'un bureau' },
          { id: 'q11', type: 'trueFalse', q: '"Une chaise" is a chair.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'A door in French is "___."', answer: 'une porte', accept: ['une porte', 'porte'] },
          { id: 'q13', type: 'multiple', q: 'What is a window?', opts: ['une porte', 'une fenêtre', 'un mur', 'un toit'], ans: 'une fenêtre' },
          { id: 'q14', type: 'trueFalse', q: '"Un mur" is a wall.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'A table in French is "___."', answer: 'une table', accept: ['une table', 'table'] },
          { id: 'q16', type: 'multiple', q: 'What is a teacher\'s desk?', opts: ['un bureau', 'une table', 'une chaise', 'un cahier'], ans: 'un bureau' },
          { id: 'q17', type: 'trueFalse', q: '"Un crayon de couleur" is a coloured pencil.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A pencil case in French is "___."', answer: 'une trousse', accept: ['une trousse', 'trousse'] },
          { id: 'q19', type: 'trueFalse', q: '"Du papier" is paper.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A sharpener in French is "___."', answer: 'un taille-crayon', accept: ['un taille-crayon', 'taille-crayon'] },
          { id: 'q21', type: 'multiple', q: 'What is "un sac"?', opts: ['a pen', 'a book', 'a bag', 'a desk'], ans: 'a bag' },
          { id: 'q22', type: 'trueFalse', q: '"Des feutres" are markers.', ans: true }
        ]
      },
      {
        id: 'y3-french-5',
        name: 'Animals',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a cat?', opts: ['un chien', 'un chat', 'un lapin', 'un oiseau'], ans: 'un chat' },
          { id: 'q2', type: 'trueFalse', q: '"Un chien" is a dog.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'A rabbit in French is "___."', answer: 'un lapin', accept: ['un lapin', 'lapin'] },
          { id: 'q4', type: 'multiple', q: 'What is a fish?', opts: ['un chat', 'une souris', 'un poisson', 'un oiseau'], ans: 'un poisson' },
          { id: 'q5', type: 'trueFalse', q: '"Un oiseau" is a bird.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'A mouse in French is "___."', answer: 'une souris', accept: ['une souris', 'souris'] },
          { id: 'q7', type: 'multiple', q: 'What is a horse?', opts: ['un oiseau', 'un cheval', 'un poisson', 'une souris'], ans: 'un cheval' },
          { id: 'q8', type: 'trueFalse', q: '"Un hamster" is a hamster.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A tortoise in French is "___."', answer: 'une tortue', accept: ['une tortue', 'tortue'] },
          { id: 'q10', type: 'multiple', q: 'What is a cow?', opts: ['un cheval', 'une vache', 'un mouton', 'un cochon'], ans: 'une vache' },
          { id: 'q11', type: 'trueFalse', q: '"Un mouton" is a sheep.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'A pig in French is "___."', answer: 'un cochon', accept: ['un cochon', 'cochon'] },
          { id: 'q13', type: 'multiple', q: 'What is a duck?', opts: ['un cygne', 'un canard', 'une oie', 'une poule'], ans: 'un canard' },
          { id: 'q14', type: 'trueFalse', q: '"Une poule" is a hen.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'A lion in French is "___."', answer: 'un lion', accept: ['un lion', 'lion'] },
          { id: 'q16', type: 'multiple', q: 'What is an elephant?', opts: ['un lion', 'un zèbre', 'un éléphant', 'une girafe'], ans: 'un éléphant' },
          { id: 'q17', type: 'trueFalse', q: '"Une girafe" is a giraffe.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A snake in French is "___."', answer: 'un serpent', accept: ['un serpent', 'serpent'] },
          { id: 'q19', type: 'trueFalse', q: '"Un singe" is a monkey.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A spider in French is "___."', answer: 'une araignée', accept: ['une araignée', 'araignée'] },
          { id: 'q21', type: 'multiple', q: 'What is a butterfly?', opts: ['une abeille', 'un papillon', 'une fourmi', 'une coccinelle'], ans: 'un papillon' },
          { id: 'q22', type: 'trueFalse', q: '"Une abeille" is a bee.', ans: true }
        ]
      }
    ]
  }
};
