window.YEAR_2_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        id: 'y2-maths-1',
        title: 'Place Value to 100',
        description: 'Understand tens and ones, compare and order numbers up to 100',
        questions: [
          { type: 'multiple', q: 'What is the value of the tens digit in 47?', options: ['4', '7', '40', '10'], answer: 2 },
          { type: 'multiple', q: 'Which number has 3 tens and 8 ones?', options: ['83', '38', '308', '88'], answer: 1 },
          { type: 'trueFalse', q: '65 is greater than 56', answer: true },
          { type: 'fillBlank', q: 'In the number 72, the 7 represents ___ tens', answer: '7', accept: ['7', 'seven'] },
          { type: 'multiple', q: 'Put these numbers in order from smallest to biggest: 34, 43, 24, 42', options: ['24, 34, 42, 43', '34, 24, 43, 42', '24, 34, 43, 42', '43, 42, 34, 24'], answer: 0 },
          { type: 'trueFalse', q: '10 + 10 + 10 + 10 + 10 = 50', answer: true },
          { type: 'fillBlank', q: '50 + 6 = ___', answer: '56', accept: ['56'] },
          { type: 'multiple', q: 'Which number is one more than 99?', options: ['98', '90', '100', '109'], answer: 2 },
          { type: 'trueFalse', q: 'The ones digit in 85 is 5', answer: true },
          { type: 'multiple', q: 'What does the digit 2 represent in the number 28?', options: ['2 ones', '2 tens', '20 ones', '200'], answer: 1 },
          { type: 'fillBlank', q: '30 + 17 = ___', answer: '47', accept: ['47'] },
          { type: 'trueFalse', q: '91 is less than 19', answer: false },
          { type: 'multiple', q: 'Which number has the same value as 40 + 8?', options: ['48', '84', '4 + 8', '80 + 4'], answer: 0 },
          { type: 'multiple', q: 'Complete the pattern: 10, 20, 30, ___, 50', options: ['35', '40', '45', '55'], answer: 1 },
          { type: 'fillBlank', q: '___ tens and 3 ones make 63', answer: '6', accept: ['6', 'six'] },
          { type: 'trueFalse', q: '25 + 25 = 50', answer: true },
          { type: 'multiple', q: 'What is 100 - 1?', options: ['99', '101', '10', '90'], answer: 0 },
          { type: 'fillBlank', q: '70 is 10 more than ___', answer: '60', accept: ['60'] },
          { type: 'trueFalse', q: 'The number 55 has 5 tens and 5 ones', answer: true },
          { type: 'multiple', q: 'Which comes next in the sequence: 15, 25, 35, 45, ___?', options: ['55', '50', '46', '54'], answer: 0 },
          { type: 'fillBlank', q: 'If you have 3 tens, you have ___', answer: '30', accept: ['30'] },
          { type: 'trueFalse', q: '78 is between 70 and 90', answer: true }
        ]
      },
      {
        id: 'y2-maths-2',
        title: 'Addition & Subtraction within 100',
        description: 'Add and subtract mentally, using column method and number bonds',
        questions: [
          { type: 'multiple', q: 'What is 24 + 13?', options: ['37', '36', '38', '47'], answer: 0 },
          { type: 'fillBlank', q: '15 + 20 = ___', answer: '35', accept: ['35'] },
          { type: 'trueFalse', q: '32 + 8 = 40', answer: true },
          { type: 'multiple', q: 'If 10 + 10 = 20, what is 20 + 20?', options: ['30', '40', '50', '60'], answer: 1 },
          { type: 'fillBlank', q: '50 - 15 = ___', answer: '35', accept: ['35'] },
          { type: 'trueFalse', q: '25 + 25 = 50', answer: true },
          { type: 'multiple', q: 'What must be added to 34 to make 50?', options: ['14', '16', '18', '20'], answer: 0 },
          { type: 'fillBlank', q: '___ + 12 = 27', answer: '15', accept: ['15'] },
          { type: 'trueFalse', q: '60 - 20 = 40', answer: true },
          { type: 'multiple', q: 'What is 42 + 30?', options: ['72', '70', '75', '82'], answer: 0 },
          { type: 'fillBlank', q: '18 + 7 = ___', answer: '25', accept: ['25'] },
          { type: 'trueFalse', q: '45 - 10 = 35', answer: true },
          { type: 'multiple', q: 'Which is the same as 20 + 15 + 10?', options: ['45', '40', '50', '55'], answer: 0 },
          { type: 'fillBlank', q: '___ - 9 = 21', answer: '30', accept: ['30'] },
          { type: 'trueFalse', q: '33 + 7 = 40', answer: true },
          { type: 'multiple', q: 'What is 75 - 25?', options: ['50', '45', '55', '60'], answer: 0 },
          { type: 'fillBlank', q: '16 + ___ = 24', answer: '8', accept: ['8'] },
          { type: 'multiple', q: 'If you add 17 and 13, what do you get?', options: ['30', '28', '32', '25'], answer: 0 },
          { type: 'trueFalse', q: '100 - 35 = 65', answer: true },
          { type: 'fillBlank', q: '22 + 18 = ___', answer: '40', accept: ['40'] },
          { type: 'multiple', q: 'What is 38 + 12?', options: ['50', '48', '52', '55'], answer: 0 },
          { type: 'trueFalse', q: '50 - 30 - 10 = 10', answer: true }
        ]
      },
      {
        id: 'y2-maths-3',
        title: 'Multiplication & Division',
        description: 'Learn 2×, 5× and 10× tables, arrays and sharing equally',
        questions: [
          { type: 'multiple', q: 'What is 5 × 2?', options: ['7', '10', '8', '15'], answer: 1 },
          { type: 'fillBlank', q: '10 × 2 = ___', answer: '20', accept: ['20'] },
          { type: 'trueFalse', q: '2 × 4 = 8', answer: true },
          { type: 'multiple', q: 'How many groups of 5 are in 15?', options: ['2', '3', '4', '5'], answer: 1 },
          { type: 'fillBlank', q: '___ × 5 = 25', answer: '5', accept: ['5'] },
          { type: 'trueFalse', q: '5 × 3 = 15', answer: true },
          { type: 'multiple', q: 'What is 2 × 7?', options: ['9', '14', '12', '16'], answer: 1 },
          { type: 'fillBlank', q: '10 × 3 = ___', answer: '30', accept: ['30'] },
          { type: 'trueFalse', q: 'There are 4 groups of 2 in 8', answer: true },
          { type: 'multiple', q: 'If there are 5 flowers in each pot and 4 pots, how many flowers altogether?', options: ['9', '15', '20', '25'], answer: 2 },
          { type: 'fillBlank', q: '2 × 9 = ___', answer: '18', accept: ['18'] },
          { type: 'trueFalse', q: '5 × 5 = 25', answer: true },
          { type: 'multiple', q: 'Complete: 2, 4, 6, ___, 10', options: ['7', '8', '9', '12'], answer: 1 },
          { type: 'fillBlank', q: 'Share 10 toys equally between 2 children. Each gets ___', answer: '5', accept: ['5'] },
          { type: 'trueFalse', q: '10 × 4 = 40', answer: true },
          { type: 'multiple', q: 'What is 5 × 6?', options: ['25', '30', '35', '40'], answer: 1 },
          { type: 'fillBlank', q: '___ × 2 = 12', answer: '6', accept: ['6'] },
          { type: 'multiple', q: 'How many groups of 10 in 50?', options: ['3', '4', '5', '6'], answer: 2 },
          { type: 'trueFalse', q: '2 × 5 = 5 × 2', answer: true },
          { type: 'fillBlank', q: '14 ÷ 2 = ___', answer: '7', accept: ['7'] },
          { type: 'multiple', q: 'If 20 ÷ 5 = 4, what is 5 × 4?', options: ['15', '20', '25', '30'], answer: 1 },
          { type: 'trueFalse', q: 'In an array of 3 rows and 5 columns, there are 15 squares', answer: true }
        ]
      },
      {
        id: 'y2-maths-4',
        title: 'Fractions',
        description: 'Identify halves, quarters and thirds of shapes and quantities',
        questions: [
          { type: 'multiple', q: 'How many quarters make one whole?', options: ['2', '3', '4', '5'], answer: 2 },
          { type: 'fillBlank', q: 'Half of 10 is ___', answer: '5', accept: ['5'] },
          { type: 'trueFalse', q: 'A quarter is smaller than a half', answer: true },
          { type: 'multiple', q: 'If a pizza is cut into 3 equal pieces, what is each piece called?', options: ['half', 'quarter', 'third', 'quarter circle'], answer: 2 },
          { type: 'fillBlank', q: '1/4 of 12 = ___', answer: '3', accept: ['3'] },
          { type: 'trueFalse', q: '1/2 of 20 = 10', answer: true },
          { type: 'multiple', q: 'How many halves are in a whole?', options: ['1', '2', '3', '4'], answer: 1 },
          { type: 'fillBlank', q: 'A half of 16 is ___', answer: '8', accept: ['8'] },
          { type: 'trueFalse', q: 'A quarter of a circle is 1/4', answer: true },
          { type: 'multiple', q: 'What fraction is shaded if 3 out of 4 equal parts are coloured?', options: ['1/4', '2/4', '3/4', '1/2'], answer: 2 },
          { type: 'fillBlank', q: '1/3 of 9 = ___', answer: '3', accept: ['3'] },
          { type: 'trueFalse', q: '1/2 and 2/4 are the same', answer: true },
          { type: 'multiple', q: 'If you eat 1/2 of 8 biscuits, how many are left?', options: ['2', '4', '6', '8'], answer: 1 },
          { type: 'fillBlank', q: '___ is one quarter of 20', answer: '5', accept: ['5'] },
          { type: 'trueFalse', q: 'Three thirds make one whole', answer: true },
          { type: 'multiple', q: 'What fraction of this shape is unshaded? (3/4 shaded)', options: ['1/4', '1/2', '2/4', '3/4'], answer: 0 },
          { type: 'fillBlank', q: '1/2 of 14 = ___', answer: '7', accept: ['7'] },
          { type: 'multiple', q: 'Quarter of 16 is:', options: ['4', '8', '12', '16'], answer: 0 },
          { type: 'trueFalse', q: '1/4 of 24 = 6', answer: true },
          { type: 'fillBlank', q: 'If 1/2 = 6, then the whole is ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'How many thirds in 2 wholes?', options: ['2', '3', '5', '6'], answer: 3 },
          { type: 'trueFalse', q: '1/3 of 15 = 5', answer: true }
        ]
      },
      {
        id: 'y2-maths-5',
        title: 'Measurement',
        description: 'Use cm, m, g, kg, ml, L; compare and estimate lengths and weights',
        questions: [
          { type: 'multiple', q: 'How many centimetres in 1 metre?', options: ['50', '100', '10', '1000'], answer: 1 },
          { type: 'fillBlank', q: 'A pencil is about ___ cm long', answer: '19', accept: ['15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25'] },
          { type: 'trueFalse', q: 'A kilogram is heavier than a gram', answer: true },
          { type: 'multiple', q: 'Which is the best way to measure the weight of an apple?', options: ['metre', 'centimetre', 'kilogram', 'litre'], answer: 2 },
          { type: 'fillBlank', q: '1 metre = ___ cm', answer: '100', accept: ['100'] },
          { type: 'trueFalse', q: 'A litre is used to measure length', answer: false },
          { type: 'multiple', q: 'What would you use to measure milk in a cup?', options: ['grams', 'metres', 'millilitres', 'kilograms'], answer: 2 },
          { type: 'fillBlank', q: 'A bottle holds about ___ ml', answer: '500', accept: ['500', '750', '1000'] },
          { type: 'trueFalse', q: '50 cm is half a metre', answer: true },
          { type: 'multiple', q: 'Which is the heaviest?', options: ['500g', '1kg', '100g', '250g'], answer: 1 },
          { type: 'fillBlank', q: 'A desk is about 1 ___ long', answer: 'metre', accept: ['metre', 'meter', 'm'] },
          { type: 'trueFalse', q: '1 litre = 1000 millilitres', answer: true },
          { type: 'multiple', q: 'How much heavier is 2kg than 500g?', options: ['500g', '1000g', '1500g', '2500g'], answer: 2 },
          { type: 'fillBlank', q: 'Your height is measured in ___', answer: 'centimetres', accept: ['centimetres', 'cm', 'metres', 'meter'] },
          { type: 'trueFalse', q: 'A ruler measures length in centimetres', answer: true },
          { type: 'multiple', q: 'A car is about:', options: ['4 cm', '40 cm', '4 m', '40 m'], answer: 2 },
          { type: 'fillBlank', q: 'A mug holds about ___ ml', answer: '250', accept: ['200', '250', '300'] },
          { type: 'trueFalse', q: 'You would measure flour in kilograms', answer: false },
          { type: 'multiple', q: 'Which is shorter, 75cm or 1m?', options: ['75cm', '1m', 'same length', 'cannot compare'], answer: 0 },
          { type: 'fillBlank', q: '2kg is the same as ___ g', answer: '2000', accept: ['2000'] },
          { type: 'trueFalse', q: 'A classroom is about 20 metres long', answer: false },
          { type: 'multiple', q: 'What is the best estimate for a book\'s width?', options: ['15 cm', '1.5 m', '150 mm', '15 mm'], answer: 0 }
        ]
      },
      {
        id: 'y2-maths-6',
        title: 'Time',
        description: 'Tell time at o\'clock, half past, quarter past/to; 5-minute intervals; days and months',
        questions: [
          { type: 'multiple', q: 'What time is shown when the hour hand points at 3 and the minute hand points at 12?', options: ['3:30', '3:00', '30 minutes', '12:03'], answer: 1 },
          { type: 'fillBlank', q: 'Half past 2 is written as 2:___', answer: '30', accept: ['30'] },
          { type: 'trueFalse', q: 'Quarter past 5 is 5:15', answer: true },
          { type: 'multiple', q: 'How many minutes are there in 1 hour?', options: ['30', '60', '90', '120'], answer: 1 },
          { type: 'fillBlank', q: 'Quarter to 7 is ___', answer: '6:45', accept: ['6:45'] },
          { type: 'trueFalse', q: 'There are 7 days in a week', answer: true },
          { type: 'multiple', q: 'What comes after Wednesday?', options: ['Tuesday', 'Thursday', 'Friday', 'Saturday'], answer: 1 },
          { type: 'fillBlank', q: 'There are ___ months in a year', answer: '12', accept: ['12'] },
          { type: 'trueFalse', q: 'April comes after May', answer: false },
          { type: 'multiple', q: 'At what time do you usually eat breakfast?', options: ['7:00', '3:30 pm', '7:00 pm', '11:00 pm'], answer: 0 },
          { type: 'fillBlank', q: 'Half past 7 is 7:___', answer: '30', accept: ['30'] },
          { type: 'trueFalse', q: 'A quarter of an hour is 15 minutes', answer: true },
          { type: 'multiple', q: 'How many 5-minute intervals in 20 minutes?', options: ['2', '3', '4', '5'], answer: 2 },
          { type: 'fillBlank', q: 'The first month of the year is ___', answer: 'January', accept: ['January', 'january', 'Jan'] },
          { type: 'trueFalse', q: '10:30 means half past ten', answer: true },
          { type: 'multiple', q: 'What is 5 minutes after 2:15?', options: ['2:10', '2:20', '2:25', '3:15'], answer: 1 },
          { type: 'fillBlank', q: 'The time 4:45 is quarter ___ 5', answer: 'to', accept: ['to'] },
          { type: 'trueFalse', q: 'December is the last month of the year', answer: true },
          { type: 'multiple', q: 'Monday comes before which day?', options: ['Sunday', 'Tuesday', 'Wednesday', 'Friday'], answer: 1 },
          { type: 'fillBlank', q: 'There are ___ minutes in half an hour', answer: '30', accept: ['30'] },
          { type: 'trueFalse', q: 'February comes after January', answer: true },
          { type: 'multiple', q: 'What time is 15 minutes after 8:45?', options: ['9:00', '8:60', '8:45', '9:15'], answer: 0 }
        ]
      },
      {
        id: 'y2-maths-7',
        title: '2D and 3D Shapes',
        description: 'Identify shapes, count vertices/edges/faces; symmetry, turns, right angles',
        questions: [
          { type: 'multiple', q: 'How many sides does a square have?', options: ['3', '4', '5', '6'], answer: 1 },
          { type: 'fillBlank', q: 'A triangle has ___ vertices', answer: '3', accept: ['3'] },
          { type: 'trueFalse', q: 'A circle has 1 curved side', answer: true },
          { type: 'multiple', q: 'How many faces does a cube have?', options: ['4', '6', '8', '12'], answer: 1 },
          { type: 'fillBlank', q: 'A rectangle has ___ corners', answer: '4', accept: ['4'] },
          { type: 'trueFalse', q: 'A pentagon has 5 sides', answer: true },
          { type: 'multiple', q: 'Which shape has no corners?', options: ['square', 'triangle', 'circle', 'rectangle'], answer: 2 },
          { type: 'fillBlank', q: 'A ___ has 3 sides', answer: 'triangle', accept: ['triangle'] },
          { type: 'trueFalse', q: 'All rectangles are squares', answer: false },
          { type: 'multiple', q: 'How many edges does a cube have?', options: ['8', '12', '6', '4'], answer: 1 },
          { type: 'fillBlank', q: 'A shape with 4 equal sides and 4 right angles is a ___', answer: 'square', accept: ['square'] },
          { type: 'trueFalse', q: 'A line of symmetry divides a shape into two equal parts', answer: true },
          { type: 'multiple', q: 'How many lines of symmetry does a square have?', options: ['1', '2', '4', '8'], answer: 2 },
          { type: 'fillBlank', q: 'A ___ is a 3D shape that looks like a ball', answer: 'sphere', accept: ['sphere'] },
          { type: 'trueFalse', q: 'A right angle is the corner of a square', answer: true },
          { type: 'multiple', q: 'Which 2D shape has infinite lines of symmetry?', options: ['square', 'triangle', 'circle', 'rectangle'], answer: 2 },
          { type: 'fillBlank', q: 'A cuboid has ___ faces', answer: '6', accept: ['6'] },
          { type: 'multiple', q: 'How many vertices does a pyramid with a square base have?', options: ['4', '5', '8', '9'], answer: 1 },
          { type: 'trueFalse', q: 'An equilateral triangle has 1 line of symmetry', answer: false },
          { type: 'fillBlank', q: 'A shape that has turned around has made a ___', answer: 'turn', accept: ['turn', 'rotation'] },
          { type: 'trueFalse', q: 'A sphere has no vertices or edges', answer: true },
          { type: 'multiple', q: 'Which shape has 6 equal square faces?', options: ['cuboid', 'cube', 'rectangular prism', 'prism'], answer: 1 }
        ]
      },
      {
        id: 'y2-maths-8',
        title: 'Statistics',
        description: 'Read and create tally charts, pictograms, block diagrams and tables',
        questions: [
          { type: 'multiple', q: 'What does one tally mark (|) represent?', options: ['1', '5', '10', '2'], answer: 0 },
          { type: 'fillBlank', q: 'A group of 5 tally marks is written as ___', answer: '||||/', accept: ['||||/', '||||/'] },
          { type: 'trueFalse', q: 'In a pictogram, each picture can represent more than one object', answer: true },
          { type: 'multiple', q: 'If 10 children like red and this is shown as 2 pictures, what does each picture represent?', options: ['1', '5', '10', '20'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ is used to show information using pictures or symbols', answer: 'pictogram', accept: ['pictogram', 'picture graph'] },
          { type: 'trueFalse', q: 'A block diagram shows information using blocks or bars', answer: true },
          { type: 'multiple', q: 'In a tally chart, how many marks make a complete group?', options: ['4', '5', '10', '20'], answer: 1 },
          { type: 'fillBlank', q: 'A table is a way to organize ___ in rows and columns', answer: 'data', accept: ['data', 'information'] },
          { type: 'trueFalse', q: 'A bar chart shows data using vertical or horizontal bars', answer: true },
          { type: 'multiple', q: 'If |||| = 4 children, what does ||||  |||  mean?', options: ['7 children', '6 children', '8 children', '4 children'], answer: 0 },
          { type: 'fillBlank', q: 'If each apple picture = 2 apples, then 5 pictures = ___ apples', answer: '10', accept: ['10'] },
          { type: 'trueFalse', q: 'You can represent the same data in different ways', answer: true },
          { type: 'multiple', q: 'What is the most common way to read information from a block diagram?', options: ['height of blocks', 'colour of blocks', 'number of blocks', 'width of blocks'], answer: 0 },
          { type: 'fillBlank', q: 'The ___ is the number that appears most often', answer: 'mode', accept: ['mode'] },
          { type: 'trueFalse', q: 'A pictogram must use symbols that match the data', answer: false },
          { type: 'multiple', q: 'If you count ||||  ||||  |||  how many tally marks are there?', options: ['12', '13', '14', '15'], answer: 2 },
          { type: 'fillBlank', q: 'In a bar chart, the height of the bar shows the ___', answer: 'amount', accept: ['amount', 'number', 'frequency'] },
          { type: 'trueFalse', q: 'A tally chart can only count up to 10', answer: false },
          { type: 'multiple', q: 'Which is NOT a way to show data?', options: ['table', 'pictogram', 'story', 'bar chart'], answer: 2 },
          { type: 'fillBlank', q: 'A ___ chart shows information using columns of blocks', answer: 'block', accept: ['block', 'bar'] },
          { type: 'trueFalse', q: 'You can compare two sets of data using different diagrams', answer: true },
          { type: 'multiple', q: 'If a pictogram shows 3 stars and each = 4 votes, how many votes total?', options: ['7', '12', '10', '15'], answer: 1 }
        ]
      }
    ]
  },
  english: {
    name: 'English',
    icon: '📚',
    color: '#2196F3',
    lessons: [
      {
        id: 'y2-english-1',
        title: 'Noun Phrases & Adjectives',
        description: 'Create expanded noun phrases; use adjectives to describe',
        questions: [
          { type: 'multiple', q: 'What is a noun?', options: ['a doing word', 'a word that names a person, animal, place or thing', 'a word that describes', 'a joining word'], answer: 1 },
          { type: 'fillBlank', q: 'Complete: The ___ cat sat on the mat', answer: 'black', accept: ['black', 'lazy', 'fat', 'sleepy', 'striped'] },
          { type: 'trueFalse', q: '"Happy" is an adjective', answer: true },
          { type: 'multiple', q: 'Which word is an adjective?', options: ['run', 'blue', 'happy', 'jump'], answer: 1 },
          { type: 'fillBlank', q: 'The ___ dog barked loudly', answer: 'big', accept: ['big', 'loud', 'large', 'scary', 'brown'] },
          { type: 'trueFalse', q: 'An expanded noun phrase has a noun and an adjective', answer: true },
          { type: 'multiple', q: 'What is wrong with this: "A tall tree"?', options: ['Nothing wrong', 'Needs more words', 'Missing a noun', 'Misspelled'], answer: 0 },
          { type: 'fillBlank', q: 'Complete: "The ___, ___ princess"', answer: 'beautiful, tall', accept: ['beautiful tall', 'tall beautiful', 'pretty brave', 'golden beautiful'] },
          { type: 'trueFalse', q: 'You can use more than one adjective in a noun phrase', answer: true },
          { type: 'multiple', q: 'Which is an expanded noun phrase?', options: ['dog', 'ran fast', 'the big red dog', 'jumped'], answer: 2 },
          { type: 'fillBlank', q: 'The ___ ___ apple fell from the tree', answer: 'sweet red', accept: ['sweet red', 'red sweet', 'red juicy', 'green crisp'] },
          { type: 'trueFalse', q: '"Quickly" is an adjective', answer: false },
          { type: 'multiple', q: 'How many adjectives are in "the small, dark cave"?', options: ['0', '1', '2', '3'], answer: 2 },
          { type: 'fillBlank', q: 'Adjectives describe ___ or ___', answer: 'nouns, things', accept: ['nouns', 'people', 'things'] },
          { type: 'trueFalse', q: '"Cat" is a noun', answer: true },
          { type: 'multiple', q: 'Which sentence uses an expanded noun phrase?', options: ['I run fast', 'The dog is happy', 'A fluffy white kitten played', 'She jumped'], answer: 2 },
          { type: 'fillBlank', q: 'Complete: The ___ ___ rabbit hopped away', answer: 'white, fluffy', accept: ['fluffy white', 'white fluffy', 'soft white', 'quick grey'] },
          { type: 'multiple', q: 'What describes the noun in "the shiny silver coin"?', options: ['coin', 'shiny silver', 'the', 'shiny'], answer: 1 },
          { type: 'trueFalse', q: 'Adjectives always come before nouns in a sentence', answer: false },
          { type: 'fillBlank', q: 'The ___ robot had ___ eyes', answer: 'tall, red', accept: ['tall red', 'big red', 'silver red', 'large blue'] },
          { type: 'multiple', q: 'Which word best expands the noun phrase "a ___ book"?', options: ['run', 'exciting', 'quickly', 'jumped'], answer: 1 },
          { type: 'trueFalse', q: '"Beautiful" and "ugly" are opposites and both are adjectives', answer: true }
        ]
      },
      {
        id: 'y2-english-2',
        title: 'Sentence Types',
        description: 'Identify and create statements, questions, exclamations and commands',
        questions: [
          { type: 'multiple', q: 'What does a sentence that asks need at the end?', options: ['full stop', 'question mark', 'exclamation mark', 'comma'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ tells you something', answer: 'statement', accept: ['statement', 'sentence'] },
          { type: 'trueFalse', q: '"Do you like ice cream?" is a question', answer: true },
          { type: 'multiple', q: 'Which is an exclamation?', options: ['I like cats', 'Do you like cats?', 'What a big cat!', 'Sit down'], answer: 2 },
          { type: 'fillBlank', q: 'A command tells someone to ___', answer: 'do', accept: ['do', 'do something', 'do an action'] },
          { type: 'trueFalse', q: '"Close the door!" is a command', answer: true },
          { type: 'multiple', q: 'What mark ends an exclamation?', options: ['full stop', 'question mark', 'exclamation mark', 'comma'], answer: 2 },
          { type: 'fillBlank', q: '"Sit down" is a ___', answer: 'command', accept: ['command', 'order'] },
          { type: 'trueFalse', q: 'A statement always starts with a capital letter', answer: true },
          { type: 'multiple', q: 'Which sentence is a question?', options: ['I am happy', 'Run away!', 'Are you happy?', 'Stay here'], answer: 2 },
          { type: 'fillBlank', q: 'Sentences end with a ___, ___, or ___', answer: '.!?', accept: ['full stop question mark exclamation mark', '.!?', '. ! ?'] },
          { type: 'trueFalse', q: '"What an amazing day!" shows strong feeling', answer: true },
          { type: 'multiple', q: 'A question asks for ___', options: ['information', 'action', 'attention', 'help'], answer: 0 },
          { type: 'fillBlank', q: '"___ down now" is a command', answer: 'Sit', accept: ['Sit', 'Lay', 'Stay', 'Stand'] },
          { type: 'trueFalse', q: 'Commands usually end with a full stop', answer: false },
          { type: 'multiple', q: 'What type of sentence is "I love chocolate!"?', options: ['statement', 'question', 'command', 'exclamation'], answer: 3 },
          { type: 'fillBlank', q: 'A question starts with words like "Can you", "Do you", "What", or "___"', answer: 'Why', accept: ['Why', 'Where', 'How', 'When'] },
          { type: 'trueFalse', q: '"The cat is sleeping" is a statement', answer: true },
          { type: 'multiple', q: 'Which shows the strongest feeling?', options: ['I am happy', 'I am very happy', 'I am so happy!', 'I am quite happy'], answer: 2 },
          { type: 'fillBlank', q: 'Write a question about the weather: "___ is it today?"', answer: 'What', accept: ['What', 'How', 'Is', 'Will'] },
          { type: 'trueFalse', q: 'All sentences start with a capital letter and end with a punctuation mark', answer: true },
          { type: 'multiple', q: 'Which is NOT a sentence type?', options: ['statement', 'question', 'exclamation', 'whisper'], answer: 3 }
        ]
      },
      {
        id: 'y2-english-3',
        title: 'Conjunctions',
        description: 'Use and, but, or, because, when, if, that to join clauses',
        questions: [
          { type: 'multiple', q: 'Which word joins two ideas together?', options: ['the', 'and', 'is', 'a'], answer: 1 },
          { type: 'fillBlank', q: 'Complete: "I like apples ___ oranges"', answer: 'and', accept: ['and'] },
          { type: 'trueFalse', q: '"But" is a conjunction that shows contrast', answer: true },
          { type: 'multiple', q: 'Which sentence uses "but" correctly?', options: ['I like apples but oranges', 'I like apples, but I don\'t like pears', 'I like but apples', 'But I like apples'], answer: 1 },
          { type: 'fillBlank', q: '"I want to go ___ it might rain"', answer: 'but', accept: ['but'] },
          { type: 'trueFalse', q: '"Because" explains why something happens', answer: true },
          { type: 'multiple', q: 'What conjunction gives a reason?', options: ['and', 'or', 'because', 'when'], answer: 2 },
          { type: 'fillBlank', q: '"She was happy ___ it was her birthday"', answer: 'because', accept: ['because'] },
          { type: 'trueFalse', q: '"Or" is used to show one thing or another', answer: true },
          { type: 'multiple', q: 'Complete: "You can have tea ___ coffee"', options: ['and', 'but', 'or', 'because'], answer: 2 },
          { type: 'fillBlank', q: '"___ I see you, I smile"', answer: 'When', accept: ['When'] },
          { type: 'trueFalse', q: '"When" tells you about the time something happens', answer: true },
          { type: 'multiple', q: 'Which uses "if" correctly?', options: ['If you are happy', 'Happy you if are', 'If happy you are', 'You if happy are'], answer: 0 },
          { type: 'fillBlank', q: '"___ you eat too many sweets, you get a tummy ache"', answer: 'If', accept: ['If'] },
          { type: 'trueFalse', q: '"That" can join two ideas in a sentence', answer: true },
          { type: 'multiple', q: 'I like the dog ___ is black ___ brown', options: ['that and is', 'that is and', 'and that is', 'that is brown or'], answer: 1 },
          { type: 'fillBlank', q: '"I think ___ you are kind"', answer: 'that', accept: ['that'] },
          { type: 'multiple', q: 'Which conjunction shows a problem ___ solution?', options: ['and', 'but', 'or', 'because'], answer: 1 },
          { type: 'trueFalse', q: 'You can use more than one conjunction in a sentence', answer: true },
          { type: 'fillBlank', q: '"I run fast ___ my friends can\'t catch me"', answer: 'because', accept: ['because'] },
          { type: 'multiple', q: 'What comes after "because" or "when"?', options: ['a noun', 'an adjective', 'an explanation', 'nothing'], answer: 2 },
          { type: 'trueFalse', q: '"I eat fruit and vegetables because they are healthy" uses two conjunctions', answer: true }
        ]
      },
      {
        id: 'y2-english-4',
        title: 'Past & Present Tense',
        description: 'Use -ed endings and irregular past tense verbs correctly',
        questions: [
          { type: 'multiple', q: 'What is happening in "I walk to school"?', options: ['past', 'present', 'future', 'question'], answer: 1 },
          { type: 'fillBlank', q: 'Complete: "I walk" in past tense is "I ___"', answer: 'walked', accept: ['walked'] },
          { type: 'trueFalse', q: 'Past tense tells about something that already happened', answer: true },
          { type: 'multiple', q: 'Which is past tense?', options: ['run', 'runs', 'ran', 'running'], answer: 2 },
          { type: 'fillBlank', q: '"Jump" in past tense is "___"', answer: 'jumped', accept: ['jumped'] },
          { type: 'trueFalse', q: '"Talked" is past tense', answer: true },
          { type: 'multiple', q: 'How do you make most verbs past tense?', options: ['add -ing', 'add -ed', 'add -er', 'change the first letter'], answer: 1 },
          { type: 'fillBlank', q: '"Play" becomes "___" in past tense', answer: 'played', accept: ['played'] },
          { type: 'trueFalse', q: 'All past tense verbs end in -ed', answer: false },
          { type: 'multiple', q: 'What is the past tense of "go"?', options: ['goed', 'goes', 'went', 'going'], answer: 2 },
          { type: 'fillBlank', q: '"Eat" in past tense is "___"', answer: 'ate', accept: ['ate'] },
          { type: 'trueFalse', q: '"Came" is an irregular past tense verb', answer: true },
          { type: 'multiple', q: 'Which sentence is past tense?', options: ['I am happy', 'I was happy', 'I will be happy', 'I am going'], answer: 1 },
          { type: 'fillBlank', q: '"Put" in present tense is "___" (for he/she/it)', answer: 'puts', accept: ['puts'] },
          { type: 'trueFalse', q: '"Sleep" becomes "sleeped" in past tense', answer: false },
          { type: 'multiple', q: 'The past tense of "see" is ___', options: ['sawed', 'saw', 'seeded', 'seeing'], answer: 1 },
          { type: 'fillBlank', q: '"Give" changes to "___" in past tense', answer: 'gave', accept: ['gave'] },
          { type: 'trueFalse', q: '"He walked to school" is past tense', answer: true },
          { type: 'multiple', q: 'Which is present tense?', options: ['I walked', 'I will walk', 'I walk', 'I have walked'], answer: 2 },
          { type: 'fillBlank', q: '"Get" becomes "___" in past tense', answer: 'got', accept: ['got'] },
          { type: 'trueFalse', q: 'Regular verbs add -ed to make past tense', answer: true },
          { type: 'multiple', q: 'What\'s the past tense of "make"?', options: ['maked', 'made', 'making', 'makes'], answer: 1 }
        ]
      },
      {
        id: 'y2-english-5',
        title: 'Apostrophes',
        description: 'Use apostrophes in contractions and possession',
        questions: [
          { type: 'multiple', q: 'What do apostrophes show in "can\'t"?', options: ['a missing word', 'ownership', 'a plural', 'shouting'], answer: 0 },
          { type: 'fillBlank', q: '"Do not" becomes "___"', answer: 'don\'t', accept: ['dont', 'don\'t'] },
          { type: 'trueFalse', q: '"Can\'t" means "can not"', answer: true },
          { type: 'multiple', q: 'Which uses an apostrophe correctly?', options: ['the dogs collar', 'the dog\'s collar', 'the dogs\' collar', 'the dog collar\'s'], answer: 1 },
          { type: 'fillBlank', q: '"Will not" becomes "___"', answer: 'won\'t', accept: ['wont', 'won\'t'] },
          { type: 'trueFalse', q: 'An apostrophe in "Sarah\'s book" shows that Sarah owns the book', answer: true },
          { type: 'multiple', q: 'What does "isn\'t" mean?', options: ['is not', 'is', 'is now', 'will be'], answer: 0 },
          { type: 'fillBlank', q: '"I am" becomes "I\'___"', answer: 'm', accept: ['m'] },
          { type: 'trueFalse', q: '"It\'s" means "it is"', answer: true },
          { type: 'multiple', q: 'Complete: "The ___ pencil"', options: ['girl\'s', 'girls\'', 'girls', 'girl'], answer: 0 },
          { type: 'fillBlank', q: '"He is" can be written as "He\'___"', answer: 's', accept: ['s'] },
          { type: 'trueFalse', q: '"Don\'t" is a contraction', answer: true },
          { type: 'multiple', q: 'Which shows possession?', options: ['can\'t', 'won\'t', 'cat\'s', 'isn\'t'], answer: 2 },
          { type: 'fillBlank', q: '"They are" becomes "They\'___"', answer: 're', accept: ['re'] },
          { type: 'trueFalse', q: 'Contractions always use apostrophes', answer: true },
          { type: 'multiple', q: 'What does "hasn\'t" mean?', options: ['has not', 'have not', 'has', 'is not'], answer: 0 },
          { type: 'fillBlank', q: '"Tom\'s book" means the book belongs to ___', answer: 'Tom', accept: ['Tom'] },
          { type: 'trueFalse', q: '"There\'s" means "there is"', answer: true },
          { type: 'multiple', q: 'Which is a contraction?', options: ['teacher\'s pen', 'I\'m', 'cat\'s whiskers', 'dogs\' house'], answer: 1 },
          { type: 'fillBlank', q: '"Let us" becomes "Let\'___"', answer: 's', accept: ['s'] },
          { type: 'trueFalse', q: 'Possessive apostrophes show ownership', answer: true },
          { type: 'multiple', q: 'What punctuation is in "shouldn\'t"?', options: ['hyphen', 'apostrophe', 'comma', 'full stop'], answer: 1 }
        ]
      },
      {
        id: 'y2-english-6',
        title: 'Commas in Lists',
        description: 'Use commas to separate items in a list',
        questions: [
          { type: 'multiple', q: 'What does a comma do in a list?', options: ['ends the sentence', 'separates items', 'shows shouting', 'questions'], answer: 1 },
          { type: 'fillBlank', q: 'Complete: "I like apples, oranges, ___ bananas"', answer: 'and', accept: ['and'] },
          { type: 'trueFalse', q: 'You put a comma between each item in a list', answer: true },
          { type: 'multiple', q: 'Which uses commas correctly?', options: ['apples oranges bananas', 'apples, oranges, and bananas', 'apples and oranges, and bananas', 'apples oranges, and bananas'], answer: 1 },
          { type: 'fillBlank', q: 'In a list, the last comma is often before the word "___"', answer: 'and', accept: ['and'] },
          { type: 'trueFalse', q: 'A list needs at least 2 items', answer: true },
          { type: 'multiple', q: 'Complete: "The shop sells milk___ bread___ eggs"', options: [', and ,', 'and , and', ', and ,', ', , and'], answer: 2 },
          { type: 'fillBlank', q: '"Cats, dogs, birds ___ fish are animals"', answer: 'and', accept: ['and'] },
          { type: 'trueFalse', q: 'Commas in lists help separate ideas', answer: true },
          { type: 'multiple', q: 'Which sentence uses commas correctly?', options: ['I like red blue, and green', 'I like red, blue, and green', 'I like, red blue and green', 'I like red blue green'], answer: 1 },
          { type: 'fillBlank', q: '"For the picnic we need cups, plates___ napkins"', answer: 'and', accept: ['and'] },
          { type: 'trueFalse', q: 'You do not put a comma before the first item', answer: true },
          { type: 'multiple', q: 'How many commas are in "cats, dogs and birds"?', options: ['0', '1', '2', '3'], answer: 1 },
          { type: 'fillBlank', q: 'I bought a pencil, rubber, ruler ___ book', answer: 'and', accept: ['and'] },
          { type: 'trueFalse', q: 'A comma is a short pause in a sentence', answer: true },
          { type: 'multiple', q: 'Which list is written correctly?', options: ['apple banana orange', 'apple, banana orange', 'apple, banana, orange', 'apple banana, orange'], answer: 2 },
          { type: 'fillBlank', q: '"The colours are red___ blue___ yellow ___ green"', answer: ', , and', accept: [', , and', ', and , and'] },
          { type: 'trueFalse', q: 'In the sentence "I like reading, writing and maths" commas are used', answer: true },
          { type: 'multiple', q: 'What does a list usually end with?', options: ['a comma', 'an apostrophe', 'a full stop', 'nothing'], answer: 2 },
          { type: 'fillBlank', q: 'In a list of four things, you need ___ commas (with "and")', answer: '3', accept: ['3', 'three'] },
          { type: 'trueFalse', q: 'Commas separate different items in a list', answer: true },
          { type: 'multiple', q: 'Which needs commas?', options: ['apples', 'apples and oranges', 'apples, oranges, bananas and grapes', 'eating apples'], answer: 2 }
        ]
      },
      {
        id: 'y2-english-7',
        title: 'Suffixes',
        description: 'Add -ness, -ment, -ful, -less, -ly, -er, -est to change word meanings',
        questions: [
          { type: 'multiple', q: 'What does the suffix "-ness" make?', options: ['past tense', 'a noun showing a feeling', 'a verb', 'plural'], answer: 1 },
          { type: 'fillBlank', q: 'Happy becomes "___" when you add -ness', answer: 'happiness', accept: ['happiness'] },
          { type: 'trueFalse', q: '"-ment" creates nouns that describe feelings', answer: false },
          { type: 'multiple', q: 'Which word has the suffix "-ful"?', options: ['sadness', 'careful', 'walking', 'quicker'], answer: 1 },
          { type: 'fillBlank', q: '"Enjoy" becomes "enjoyment" when you add the suffix ___', answer: '-ment', accept: ['-ment', 'ment'] },
          { type: 'trueFalse', q: '"-ful" means "full of"', answer: true },
          { type: 'multiple', q: 'What does "-less" mean?', options: ['full of', 'more', 'without', 'past tense'], answer: 2 },
          { type: 'fillBlank', q: 'Hopeful means "full of ___"', answer: 'hope', accept: ['hope'] },
          { type: 'trueFalse', q: '"Hopeless" means without hope', answer: true },
          { type: 'multiple', q: 'Which word uses the suffix "-ly"?', options: ['darkness', 'quickly', 'smaller', 'playing'], answer: 1 },
          { type: 'fillBlank', q: '"Quick" becomes "___" when you add -ly', answer: 'quickly', accept: ['quickly'] },
          { type: 'trueFalse', q: '"-ly" usually makes an adverb that describes how you do something', answer: true },
          { type: 'multiple', q: 'What suffix means "more"?', options: ['-ness', '-ment', '-er', '-ful'], answer: 2 },
          { type: 'fillBlank', q: '"Tall" becomes "___" with the suffix -er', answer: 'taller', accept: ['taller'] },
          { type: 'trueFalse', q: '"-est" is used for comparing three or more things', answer: true },
          { type: 'multiple', q: 'Which word has "-est"?', options: ['sadness', 'smallest', 'helpful', 'slowly'], answer: 1 },
          { type: 'fillBlank', q: '"Kind" becomes "___" with -ness', answer: 'kindness', accept: ['kindness'] },
          { type: 'trueFalse', q: '"Careless" means you are not careful', answer: true },
          { type: 'multiple', q: 'Complete: "She is the ___ girl" (tall)', options: ['tall', 'taller', 'tallest', 'talling'], answer: 2 },
          { type: 'fillBlank', q: 'The noun from "happy" is "___"', answer: 'happiness', accept: ['happiness'] },
          { type: 'trueFalse', q: 'You can add more than one suffix to a word', answer: false },
          { type: 'multiple', q: 'What does "painless" mean?', options: ['full of pain', 'without pain', 'more pain', 'painful'], answer: 1 }
        ]
      },
      {
        id: 'y2-english-8',
        title: 'Spelling Patterns',
        description: 'Spell common exception words; identify and spell homophones correctly',
        questions: [
          { type: 'multiple', q: 'What is a homophone?', options: ['a word with two meanings', 'a word that sounds the same but has a different meaning', 'a word that rhymes', 'a word with a silent letter'], answer: 1 },
          { type: 'fillBlank', q: '"There" means a ___', answer: 'place', accept: ['place', 'location'] },
          { type: 'trueFalse', q: '"Their" shows ownership', answer: true },
          { type: 'multiple', q: 'Which is the correct homophone for "to" (direction)?', options: ['too', 'two', 'tu', 'tew'], answer: 1 },
          { type: 'fillBlank', q: '"___ dog is running" (shows ownership)', answer: 'Their', accept: ['Their'] },
          { type: 'trueFalse', q: '"They\'re" is a contraction of "they are"', answer: true },
          { type: 'multiple', q: 'Which spelling is correct: "where" or "wear"?', options: ['Both correct', 'where (a place)', 'wear (clothing)', 'neither'], answer: 1 },
          { type: 'fillBlank', q: '"I will ___ my coat" (put on clothing)', answer: 'wear', accept: ['wear'] },
          { type: 'trueFalse', q: '"To" and "too" sound the same but mean different things', answer: true },
          { type: 'multiple', q: 'What does "two" mean?', options: ['a direction', 'a number', 'the same as "to"', 'also'], answer: 1 },
          { type: 'fillBlank', q: '"Eye" and "___ " are homophones', answer: 'I', accept: ['I'] },
          { type: 'trueFalse', q: '"Knew" sounds like "new"', answer: true },
          { type: 'multiple', q: 'Which is spelled correctly?', options: ['hear', 'here', 'hare', 'heer'], answer: 0 },
          { type: 'fillBlank', q: '"I ___ you singing" (past tense of hear)', answer: 'heard', accept: ['heard'] },
          { type: 'trueFalse', q: '"Write" and "right" are homophones', answer: true },
          { type: 'multiple', q: 'How do you spell the past tense of "write"?', options: ['writed', 'wrote', 'wroted', 'writing'], answer: 1 },
          { type: 'fillBlank', q: '"By" means "next to" or ___', answer: 'near', accept: ['near', 'close to'] },
          { type: 'trueFalse', q: '"Buy" means to purchase', answer: true },
          { type: 'multiple', q: 'Which common exception word is spelled correctly?', options: ['porque', 'because', 'becuz', 'becaus'], answer: 1 },
          { type: 'fillBlank', q: '"___ are you?" is a common exception word', answer: 'Where', accept: ['Where'] },
          { type: 'trueFalse', q: '"Would" is a common exception word', answer: true },
          { type: 'multiple', q: 'Which pair are homophones?', options: ['cat and dog', 'read and red', 'book and look', 'happy and sad'], answer: 1 }
        ]
      }
    ]
  },
  science: {
    name: 'Science',
    icon: '🔬',
    color: '#FF9800',
    lessons: [
      {
        id: 'y2-science-1',
        title: 'Living Things & Habitats',
        description: 'Identify living, dead and never-alive things; understand habitats and food chains',
        questions: [
          { type: 'multiple', q: 'Which is a living thing?', options: ['rock', 'tree', 'water', 'plastic'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ is a place where an animal or plant lives', answer: 'habitat', accept: ['habitat'] },
          { type: 'trueFalse', q: 'A book is a living thing', answer: false },
          { type: 'multiple', q: 'What is a food chain?', options: ['where animals sleep', 'how plants and animals are linked by eating', 'a chain made of food', 'where food is grown'], answer: 1 },
          { type: 'fillBlank', q: 'Plants are producers because they ___ their own food', answer: 'make', accept: ['make', 'produce'] },
          { type: 'trueFalse', q: 'All living things need water', answer: true },
          { type: 'multiple', q: 'Which best describes a woodland habitat?', options: ['sand and rocks', 'trees, plants and animals living together', 'water only', 'human buildings'], answer: 1 },
          { type: 'fillBlank', q: 'An animal that hunts other animals is called a ___', answer: 'predator', accept: ['predator'] },
          { type: 'trueFalse', q: 'Grass grows in grassland habitats', answer: true },
          { type: 'multiple', q: 'What is prey?', options: ['a type of prayer', 'an animal that is hunted by another', 'a habitat', 'a plant'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ is a living thing that eats other living things', answer: 'animal', accept: ['animal', 'consumer'] },
          { type: 'trueFalse', q: 'Bees visit flowers to make nectar', answer: false },
          { type: 'multiple', q: 'Which is never-alive?', options: ['cat', 'flower', 'metal', 'insect'], answer: 2 },
          { type: 'fillBlank', q: 'In a simple food chain, the sun provides ___', answer: 'energy', accept: ['energy'] },
          { type: 'trueFalse', q: 'Some animals are herbivores and only eat plants', answer: true },
          { type: 'multiple', q: 'What would happen if a habitat was destroyed?', options: ['nothing', 'animals and plants would have nowhere to live', 'more food would grow', 'weather would change'], answer: 1 },
          { type: 'fillBlank', q: 'A habitat that is mostly water is called a ___', answer: 'pond', accept: ['pond', 'river', 'lake', 'aquatic'] },
          { type: 'trueFalse', q: 'Food chains show how energy moves through nature', answer: true },
          { type: 'multiple', q: 'Which habitat would a fish live in?', options: ['desert', 'mountain', 'water', 'forest'], answer: 2 },
          { type: 'fillBlank', q: 'A ___ eats both plants and animals', answer: 'omnivore', accept: ['omnivore', 'consumer'] },
          { type: 'trueFalse', q: 'Living things grow and change', answer: true },
          { type: 'multiple', q: 'What is dead?', options: ['something that is sleeping', 'something that was once alive but is no longer', 'something hard', 'something you cannot see'], answer: 1 }
        ]
      },
      {
        id: 'y2-science-2',
        title: 'Plants',
        description: 'Understand seeds, bulbs and growth conditions (water, light, warmth)',
        questions: [
          { type: 'multiple', q: 'What grows from a seed?', options: ['a rock', 'an animal', 'a plant', 'water'], answer: 2 },
          { type: 'fillBlank', q: 'Plants need sunlight, water, and ___ to grow', answer: 'warmth', accept: ['warmth', 'heat'] },
          { type: 'trueFalse', q: 'A bulb is a bulb that grows into a plant', answer: true },
          { type: 'multiple', q: 'What part of a plant takes in water from the soil?', options: ['stem', 'leaves', 'roots', 'flowers'], answer: 2 },
          { type: 'fillBlank', q: 'Plants make their own ___ using sunlight', answer: 'food', accept: ['food'] },
          { type: 'trueFalse', q: 'Leaves are green because they have chlorophyll', answer: true },
          { type: 'multiple', q: 'What does the stem do?', options: ['makes seeds', 'holds up the plant', 'stores water', 'makes flowers only'], answer: 1 },
          { type: 'fillBlank', q: 'A plant needs water from the ___ to grow', answer: 'soil', accept: ['soil'] },
          { type: 'trueFalse', q: 'Plants can grow without light', answer: false },
          { type: 'multiple', q: 'What would happen if you didn\'t water a plant?', options: ['it would grow faster', 'it would die', 'it would grow leaves', 'nothing'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ grows from a bulb in the spring', answer: 'daffodil', accept: ['daffodil', 'tulip', 'crocus', 'snowdrop'] },
          { type: 'trueFalse', q: 'Seeds need the right conditions to germinate', answer: true },
          { type: 'multiple', q: 'Which plant part produces flowers?', options: ['root', 'stem', 'the plant itself', 'leaf'], answer: 2 },
          { type: 'fillBlank', q: 'Plants grow ___ in warmer temperatures', answer: 'faster', accept: ['faster'] },
          { type: 'trueFalse', q: 'A flower becomes a seed pod', answer: true },
          { type: 'multiple', q: 'What does a seed contain?', options: ['water', 'a baby plant and food', 'soil', 'light'], answer: 1 },
          { type: 'fillBlank', q: 'Plants are called "green" because their leaves are ___', answer: 'green', accept: ['green'] },
          { type: 'trueFalse', q: 'Bulbs store energy for the plant to grow', answer: true },
          { type: 'multiple', q: 'How do flowers help plants?', options: ['they store water', 'they make seeds', 'they absorb light', 'they drink water'], answer: 1 },
          { type: 'fillBlank', q: 'If a plant is in darkness, the leaves become ___', answer: 'pale', accept: ['pale', 'yellow', 'white'] },
          { type: 'trueFalse', q: 'All seeds produce flowers', answer: false },
          { type: 'multiple', q: 'Which is a seed?', options: ['a leaf', 'a rock', 'a bean', 'a water drop'], answer: 2 }
        ]
      },
      {
        id: 'y2-science-3',
        title: 'Animals Including Humans',
        description: 'Identify offspring, basic needs, exercise, hygiene and food for health',
        questions: [
          { type: 'multiple', q: 'What is an offspring?', options: ['a young animal', 'a parent', 'a wild animal', 'an insect'], answer: 0 },
          { type: 'fillBlank', q: 'A young dog is called a ___', answer: 'puppy', accept: ['puppy'] },
          { type: 'trueFalse', q: 'All animals need food, water and shelter', answer: true },
          { type: 'multiple', q: 'What does exercise do for your body?', options: ['makes you tired', 'keeps you healthy and strong', 'hurts you', 'is bad for you'], answer: 1 },
          { type: 'fillBlank', q: 'You should wash your hands before eating to prevent ___', answer: 'germs', accept: ['germs', 'dirt', 'illness'] },
          { type: 'trueFalse', q: 'Brushing your teeth is important for hygiene', answer: true },
          { type: 'multiple', q: 'Which food is healthy?', options: ['sweets', 'apples and carrots', 'crisps', 'chocolate'], answer: 1 },
          { type: 'fillBlank', q: 'A baby rabbit is called a ___', answer: 'kitten', accept: ['kitten', 'youngster', 'bunny'] },
          { type: 'trueFalse', q: 'Humans need water to survive', answer: true },
          { type: 'multiple', q: 'How does a baby learn from its parent?', options: ['it doesn\'t', 'by copying and learning', 'instantly', 'never'], answer: 1 },
          { type: 'fillBlank', q: 'A young cat is called a ___', answer: 'kitten', accept: ['kitten'] },
          { type: 'trueFalse', q: 'You grow from a baby to an adult', answer: true },
          { type: 'multiple', q: 'Which is a basic need for animals?', options: ['clothes', 'shelter', 'toys', 'books'], answer: 1 },
          { type: 'fillBlank', q: 'You need ___ to stay healthy', answer: 'sleep', accept: ['sleep'] },
          { type: 'trueFalse', q: 'All animals produce offspring', answer: true },
          { type: 'multiple', q: 'What should you do after using the toilet?', options: ['nothing', 'wash your hands', 'eat', 'go to bed'], answer: 1 },
          { type: 'fillBlank', q: 'Eating ___ helps you grow strong bones', answer: 'calcium', accept: ['calcium', 'milk', 'cheese'] },
          { type: 'trueFalse', q: 'Exercise makes your body stronger', answer: true },
          { type: 'multiple', q: 'Which shows poor hygiene?', options: ['washing hands', 'brushing teeth', 'not washing after playing', 'bathing'], answer: 2 },
          { type: 'fillBlank', q: 'Fruits and vegetables give you ___', answer: 'vitamins', accept: ['vitamins', 'energy', 'nutrients'] },
          { type: 'trueFalse', q: 'Parents look after their young until they can survive alone', answer: true },
          { type: 'multiple', q: 'What is the name of a baby swan?', options: ['calf', 'chick', 'cygnet', 'foal'], answer: 2 }
        ]
      },
      {
        id: 'y2-science-4',
        title: 'Uses of Everyday Materials',
        description: 'Understand material properties and suitability; identify recyclable materials',
        questions: [
          { type: 'multiple', q: 'What is a material?', options: ['something you draw with', 'a substance that something is made from', 'a color', 'a shape'], answer: 1 },
          { type: 'fillBlank', q: 'Wood is a natural material that comes from ___', answer: 'trees', accept: ['trees'] },
          { type: 'trueFalse', q: 'Glass is fragile and can break easily', answer: true },
          { type: 'multiple', q: 'Which material would be best for a cup?', options: ['paper', 'glass', 'soap', 'sand'], answer: 1 },
          { type: 'fillBlank', q: 'Plastic is useful because it is ___', answer: 'flexible', accept: ['flexible', 'light', 'waterproof', 'cheap'] },
          { type: 'trueFalse', q: 'Metal can conduct heat and electricity', answer: true },
          { type: 'multiple', q: 'Why would you use plastic for a raincoat?', options: ['it is soft', 'it is waterproof', 'it is flexible', 'it is metallic'], answer: 2 },
          { type: 'fillBlank', q: 'Recycling means using materials ___', answer: 'again', accept: ['again', 'reusing', 'a second time'] },
          { type: 'trueFalse', q: 'All materials can be recycled', answer: false },
          { type: 'multiple', q: 'Which material is best for a toy that might be chewed?', options: ['paper', 'rubber', 'glass', 'metal'], answer: 1 },
          { type: 'fillBlank', q: 'Paper comes from ___ and can be recycled', answer: 'trees', accept: ['trees'] },
          { type: 'trueFalse', q: 'Leather is a natural material from animal skin', answer: true },
          { type: 'multiple', q: 'What would happen if you tried to use cardboard for a spoon?', options: ['it would work', 'it would get wet and fall apart', 'it would be hard', 'it would be hot'], answer: 1 },
          { type: 'fillBlank', q: 'Materials are chosen because they are ___ for a job', answer: 'suitable', accept: ['suitable', 'right'] },
          { type: 'trueFalse', q: 'Plastic is harmful to the environment', answer: true },
          { type: 'multiple', q: 'Which material is strongest?', options: ['paper', 'plastic', 'metal', 'cloth'], answer: 2 },
          { type: 'fillBlank', q: 'Cotton is a ___ material used for clothes', answer: 'natural', accept: ['natural'] },
          { type: 'trueFalse', q: 'Fabric absorbs water', answer: true },
          { type: 'multiple', q: 'Which item would be made from metal?', options: ['shirt', 'spoon', 'leaf', 'flower'], answer: 1 },
          { type: 'fillBlank', q: 'Recycling bins collect materials like plastic, ___, and ___', answer: 'paper, metal', accept: ['paper metal', 'glass paper metal'] },
          { type: 'trueFalse', q: 'We should recycle to protect the environment', answer: true },
          { type: 'multiple', q: 'What is a material that is not natural?', options: ['wood', 'wool', 'plastic', 'cotton'], answer: 2 }
        ]
      },
      {
        id: 'y2-science-5',
        title: 'Properties of Materials',
        description: 'Describe materials as hard/soft, stretchy/stiff, rough/smooth, waterproof/absorbent',
        questions: [
          { type: 'multiple', q: 'What is a property of a material?', options: ['its shape', 'a quality or characteristic', 'its color only', 'its name'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ material is difficult to bend or change shape', answer: 'stiff', accept: ['stiff', 'rigid'] },
          { type: 'trueFalse', q: 'Rubber is stretchy', answer: true },
          { type: 'multiple', q: 'Which word describes a rock?', options: ['soft', 'stretchy', 'hard', 'smooth'], answer: 2 },
          { type: 'fillBlank', q: 'A surface that is not smooth is ___', answer: 'rough', accept: ['rough'] },
          { type: 'trueFalse', q: 'Silk is smooth to touch', answer: true },
          { type: 'multiple', q: 'Which material is waterproof?', options: ['paper', 'plastic', 'cloth', 'wood'], answer: 1 },
          { type: 'fillBlank', q: 'A material that absorbs water is called ___', answer: 'absorbent', accept: ['absorbent'] },
          { type: 'trueFalse', q: 'A metal spoon is hard', answer: true },
          { type: 'multiple', q: 'What does absorbent mean?', options: ['reflects light', 'soaks up water', 'is waterproof', 'is smooth'], answer: 1 },
          { type: 'fillBlank', q: 'A pillow is ___ to touch', answer: 'soft', accept: ['soft'] },
          { type: 'trueFalse', q: 'Sandpaper is rough to touch', answer: true },
          { type: 'multiple', q: 'Which would be best for cleaning up water?', options: ['plastic sheet', 'tissue paper', 'glass', 'metal'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ material bends easily', answer: 'stretchy', accept: ['stretchy', 'flexible'] },
          { type: 'trueFalse', q: 'Wood is hard and does not stretch', answer: true },
          { type: 'multiple', q: 'Which material is soft?', options: ['diamond', 'wool', 'bone', 'metal'], answer: 1 },
          { type: 'fillBlank', q: 'Glass is ___ which means it breaks easily', answer: 'fragile', accept: ['fragile', 'hard', 'brittle'] },
          { type: 'trueFalse', q: 'A sponge is absorbent', answer: true },
          { type: 'multiple', q: 'What property makes a towel useful?', options: ['it is hard', 'it is absorbent', 'it is waterproof', 'it is metal'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ material does not allow water through', answer: 'waterproof', accept: ['waterproof', 'water-resistant'] },
          { type: 'trueFalse', q: 'Different materials have different properties', answer: true },
          { type: 'multiple', q: 'Which description best matches a book?', options: ['stretchy', 'soft', 'hard pages with a stiff cover', 'smooth metal'], answer: 2 }
        ]
      },
      {
        id: 'y2-science-6',
        title: 'Seasonal Changes',
        description: 'Observe weather, day length and temperature changes through the seasons',
        questions: [
          { type: 'multiple', q: 'How many seasons are there?', options: ['2', '3', '4', '5'], answer: 2 },
          { type: 'fillBlank', q: 'In winter, the days are ___ and nights are long', answer: 'short', accept: ['short'] },
          { type: 'trueFalse', q: 'Summer is the warmest season', answer: true },
          { type: 'multiple', q: 'What happens to leaves in autumn?', options: ['they grow', 'they fall off', 'they stay green', 'they freeze'], answer: 1 },
          { type: 'fillBlank', q: 'Spring is when plants start to ___', answer: 'grow', accept: ['grow', 'bloom', 'flower'] },
          { type: 'trueFalse', q: 'Winter is the coldest season', answer: true },
          { type: 'multiple', q: 'In summer, the days are:', options: ['short', 'long', 'same as winter', 'getting shorter'], answer: 1 },
          { type: 'fillBlank', q: 'The four seasons are spring, summer, autumn, and ___', answer: 'winter', accept: ['winter'] },
          { type: 'trueFalse', q: 'The temperature changes throughout the year', answer: true },
          { type: 'multiple', q: 'When do flowers usually bloom?', options: ['winter', 'autumn', 'spring', 'never'], answer: 2 },
          { type: 'fillBlank', q: 'In ___, the weather can be rainy and muddy', answer: 'autumn', accept: ['autumn', 'spring'] },
          { type: 'trueFalse', q: 'Animals hibernate in winter to stay warm', answer: true },
          { type: 'multiple', q: 'What is a sign of autumn?', options: ['snow', 'leaves changing colour', 'long days', 'ice'], answer: 1 },
          { type: 'fillBlank', q: 'Day length changes from ___ days in summer to ___ days in winter', answer: 'long, short', accept: ['long short'] },
          { type: 'trueFalse', q: 'Birds migrate in some seasons', answer: true },
          { type: 'multiple', q: 'Which season is best for outdoor activities?', options: ['winter', 'summer', 'autumn', 'all seasons'], answer: 1 },
          { type: 'fillBlank', q: 'In winter, water can turn to ___ when it is very cold', answer: 'ice', accept: ['ice'] },
          { type: 'trueFalse', q: 'Seasonal changes affect animals and plants', answer: true },
          { type: 'multiple', q: 'What happens to temperature in spring?', options: ['it gets colder', 'it gets warmer', 'it stays the same', 'it freezes'], answer: 1 },
          { type: 'fillBlank', q: 'Animals need to adapt to seasonal ___', answer: 'changes', accept: ['changes'] },
          { type: 'trueFalse', q: 'The sun is higher in the sky in summer', answer: true },
          { type: 'multiple', q: 'What weather is common in spring?', options: ['snow', 'rain and sunshine', 'very hot', 'ice'], answer: 1 }
        ]
      },
      {
        id: 'y2-science-7',
        title: 'Simple Food Chains',
        description: 'Identify producers, consumers, predators and prey in food chains',
        questions: [
          { type: 'multiple', q: 'What is a producer in a food chain?', options: ['an animal', 'a plant that makes food', 'a predator', 'a human'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ is an animal that eats other animals', answer: 'predator', accept: ['predator', 'carnivore'] },
          { type: 'trueFalse', q: 'A simple food chain shows how energy flows', answer: true },
          { type: 'multiple', q: 'What does an herbivore eat?', options: ['meat', 'plants', 'insects', 'anything'], answer: 1 },
          { type: 'fillBlank', q: 'In a food chain: plant → grasshopper → ___', answer: 'bird', accept: ['bird', 'robin', 'frog'] },
          { type: 'trueFalse', q: 'Consumers eat other living things', answer: true },
          { type: 'multiple', q: 'Which best describes the role of a plant in a food chain?', options: ['it hunts', 'it produces energy from the sun', 'it eats animals', 'it moves around'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ eats both plants and animals', answer: 'omnivore', accept: ['omnivore'] },
          { type: 'trueFalse', q: 'The sun provides energy for all food chains', answer: true },
          { type: 'multiple', q: 'What would happen if all plants died?', options: ['nothing', 'the food chain would break', 'more animals would grow', 'the sun would disappear'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ is hunted by a predator', answer: 'prey', accept: ['prey'] },
          { type: 'trueFalse', q: 'A food chain can have more than 3 organisms', answer: true },
          { type: 'multiple', q: 'In the chain: grass → rabbit → fox, what is the prey?', options: ['fox', 'rabbit', 'grass', 'none'], answer: 1 },
          { type: 'fillBlank', q: 'A carnivore eats only ___', answer: 'meat', accept: ['meat', 'animals'] },
          { type: 'trueFalse', q: 'Energy moves from the sun to plants to animals', answer: true },
          { type: 'multiple', q: 'Which animal is a consumer?', options: ['grass', 'tree', 'cat', 'sun'], answer: 2 },
          { type: 'fillBlank', q: 'Grass is a ___ because it makes its own food', answer: 'producer', accept: ['producer'] },
          { type: 'trueFalse', q: 'All animals are consumers', answer: true },
          { type: 'multiple', q: 'What does a primary consumer eat?', options: ['other animals', 'plants', 'the sun', 'rocks'], answer: 1 },
          { type: 'fillBlank', q: 'In "grass → rabbit → fox", the fox is a ___ consumer', answer: 'secondary', accept: ['secondary', 'top'] },
          { type: 'trueFalse', q: 'Food chains show how organisms depend on each other', answer: true },
          { type: 'multiple', q: 'Which is a complete simple food chain?', options: ['grass', 'rabbit → fox', 'sun → grass → rabbit → fox', 'grass → sun'], answer: 2 }
        ]
      },
      {
        id: 'y2-science-8',
        title: 'Caring for the Environment',
        description: 'Understand pollution, habitats, conservation and caring for our planet',
        questions: [
          { type: 'multiple', q: 'What is pollution?', options: ['a habitat', 'dirty air, water or soil', 'a plant', 'a food'], answer: 1 },
          { type: 'fillBlank', q: 'Plastic in the ocean is a form of ___', answer: 'pollution', accept: ['pollution'] },
          { type: 'trueFalse', q: 'Littering damages the environment', answer: true },
          { type: 'multiple', q: 'What can we do to protect habitats?', options: ['destroy them', 'keep them safe and clean', 'hunt animals', 'cut down trees'], answer: 1 },
          { type: 'fillBlank', q: 'Conservation means ___ our environment', answer: 'protecting', accept: ['protecting', 'saving', 'caring for'] },
          { type: 'trueFalse', q: 'Recycling helps save the environment', answer: true },
          { type: 'multiple', q: 'Which is bad for the environment?', options: ['planting trees', 'littering', 'caring for animals', 'using less water'], answer: 1 },
          { type: 'fillBlank', q: 'Reducing waste means using ___ materials', answer: 'less', accept: ['less'] },
          { type: 'trueFalse', q: 'Pollution can hurt animals and plants', answer: true },
          { type: 'multiple', q: 'What should you do with rubbish?', options: ['throw it anywhere', 'put it in a bin', 'burn it', 'leave it on the ground'], answer: 1 },
          { type: 'fillBlank', q: 'Saving ___ helps the environment', answer: 'water', accept: ['water', 'energy'] },
          { type: 'trueFalse', q: 'Cutting down all the forests is good for the environment', answer: false },
          { type: 'multiple', q: 'How can you help the environment?', options: ['be wasteful', 'recycle and reduce waste', 'pollute', 'ignore nature'], answer: 1 },
          { type: 'fillBlank', q: 'Renewable energy comes from ___ and wind', answer: 'sun', accept: ['sun', 'water'] },
          { type: 'trueFalse', q: 'Walking or cycling is better for the environment than driving', answer: true },
          { type: 'multiple', q: 'What does it mean to be eco-friendly?', options: ['be lazy', 'not damage the environment', 'waste resources', 'pollute'], answer: 1 },
          { type: 'fillBlank', q: 'To care for the environment, we must ___ natural resources', answer: 'protect', accept: ['protect', 'save'] },
          { type: 'trueFalse', q: 'Plants help clean our air', answer: true },
          { type: 'multiple', q: 'Which action helps the environment?', options: ['leaving taps running', 'recycling paper', 'throwing away plastic', 'using lots of electricity'], answer: 1 },
          { type: 'fillBlank', q: 'A ___ is a place where plants and animals live together', answer: 'habitat', accept: ['habitat'] },
          { type: 'trueFalse', q: 'We have a responsibility to look after our planet', answer: true },
          { type: 'multiple', q: 'What pollution harms fish?', options: ['clean water', 'dirty water', 'rocks', 'plants'], answer: 1 }
        ]
      }
    ]
  },
  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#E91E63',
    lessons: [
      {
        id: 'y2-french-1',
        title: 'Greetings & Introductions',
        description: 'Learn bonjour, au revoir, comment t\'appelles-tu and basic introductions',
        questions: [
          { type: 'multiple', q: 'How do you say "hello" in French?', options: ['au revoir', 'bonjour', 'merci', 'oui'], answer: 1 },
          { type: 'fillBlank', q: '"Goodbye" in French is "___"', answer: 'au revoir', accept: ['au revoir'] },
          { type: 'trueFalse', q: '"Bonjour" means good morning or hello', answer: true },
          { type: 'multiple', q: 'How do you ask "What is your name?"', options: ['Tu t\'appelles?', 'Comment t\'appelles-tu?', 'Quel est ton nom?', 'Tu es?'], answer: 1 },
          { type: 'fillBlank', q: '"Je m\'appelle ___" means "My name is..."', answer: 'Sophie', accept: ['Sophie', 'Pierre', 'Paul', 'Marie'] },
          { type: 'trueFalse', q: '"Comment ça va?" means "How are you?"', answer: true },
          { type: 'multiple', q: 'What does "merci" mean?', options: ['please', 'thank you', 'no', 'yes'], answer: 1 },
          { type: 'fillBlank', q: '"S\'il vous plaît" means "___"', answer: 'please', accept: ['please'] },
          { type: 'trueFalse', q: '"Oui" means "yes"', answer: true },
          { type: 'multiple', q: 'How do you respond to "Comment ça va?"', options: ['Au revoir', 'Ça va bien', 'Bonjour', 'Merci'], answer: 1 },
          { type: 'fillBlank', q: '"Non" means "___"', answer: 'no', accept: ['no'] },
          { type: 'trueFalse', q: '"Je m\'appelle" means "I am called"', answer: true },
          { type: 'multiple', q: 'What is the polite way to say "please"?', options: ['merci', 's\'il vous plaît', 'bonjour', 'au revoir'], answer: 1 },
          { type: 'fillBlank', q: '"De rien" means "___"', answer: 'you\'re welcome', accept: ['you\'re welcome', 'you are welcome'] },
          { type: 'trueFalse', q: '"Excusez-moi" means "Excuse me"', answer: true },
          { type: 'multiple', q: 'How do you say "I\'m fine"?', options: ['Ça va mal', 'Ça va bien', 'Je suis fatigué', 'Ça va comme ci comme ça'], answer: 1 },
          { type: 'fillBlank', q: '"Enchanté" means "___" (pleased to meet you)', answer: 'pleased', accept: ['pleased', 'delighted', 'charmed'] },
          { type: 'trueFalse', q: '"Bonsoir" means "good evening"', answer: true },
          { type: 'multiple', q: 'What do you say before eating?', options: ['Bonjour', 'Bon appétit', 'Au revoir', 'Merci'], answer: 1 },
          { type: 'fillBlank', q: '"À bientôt" means "See you ___"', answer: 'soon', accept: ['soon'] },
          { type: 'trueFalse', q: '"Tu t\'appelles comment?" is another way to ask someone\'s name', answer: true },
          { type: 'multiple', q: 'How would you greet someone politely?', options: ['Au revoir', 'Bonjour, comment allez-vous?', 'Non', 'Merci'], answer: 1 }
        ]
      },
      {
        id: 'y2-french-2',
        title: 'Numbers 1-20',
        description: 'Count and recognize French numbers from 1 to 20',
        questions: [
          { type: 'multiple', q: 'What is "1" in French?', options: ['deux', 'un', 'trois', 'quatre'], answer: 1 },
          { type: 'fillBlank', q: '"Two" in French is "___"', answer: 'deux', accept: ['deux'] },
          { type: 'trueFalse', q: '"Trois" means "3"', answer: true },
          { type: 'multiple', q: 'How do you say "5"?', options: ['quatre', 'cinq', 'six', 'sept'], answer: 1 },
          { type: 'fillBlank', q: '"10" is "___ " in French', answer: 'dix', accept: ['dix'] },
          { type: 'trueFalse', q: '"Neuf" means "9"', answer: true },
          { type: 'multiple', q: 'Which number is "sept"?', options: ['6', '7', '8', '9'], answer: 1 },
          { type: 'fillBlank', q: '"Twelve" is "___ " in French', answer: 'douze', accept: ['douze'] },
          { type: 'trueFalse', q: '"Quinze" means "15"', answer: true },
          { type: 'multiple', q: 'What is "4" in French?', options: ['trois', 'quatre', 'cinq', 'six'], answer: 1 },
          { type: 'fillBlank', q: '"Eight" is "___" in French', answer: 'huit', accept: ['huit'] },
          { type: 'trueFalse', q: '"Dix-huit" means "18"', answer: true },
          { type: 'multiple', q: 'How do you say "11"?', options: ['dix', 'onze', 'douze', 'treize'], answer: 1 },
          { type: 'fillBlank', q: '"Vingt" means "___"', answer: '20', accept: ['20', 'twenty'] },
          { type: 'trueFalse', q: '"Six" means "6"', answer: true },
          { type: 'multiple', q: 'What is "13" in French?', options: ['douze', 'treize', 'quatorze', 'quinze'], answer: 1 },
          { type: 'fillBlank', q: '"Fourteen" is "___" in French', answer: 'quatorze', accept: ['quatorze'] },
          { type: 'trueFalse', q: '"Dix-sept" means "17"', answer: true },
          { type: 'multiple', q: 'How do you say "19"?', options: ['dix-sept', 'dix-huit', 'dix-neuf', 'vingt'], answer: 2 },
          { type: 'fillBlank', q: '"Three" is "___" in French', answer: 'trois', accept: ['trois'] },
          { type: 'trueFalse', q: '"Neuf" is pronounced "nuf"', answer: true },
          { type: 'multiple', q: 'In French, which number comes after "dix"?', options: ['onze', 'douze', 'treize', 'quatorze'], answer: 0 }
        ]
      },
      {
        id: 'y2-french-3',
        title: 'Colours',
        description: 'Learn French colour words: rouge, bleu, vert, jaune and more',
        questions: [
          { type: 'multiple', q: 'What colour is "rouge"?', options: ['blue', 'red', 'green', 'yellow'], answer: 1 },
          { type: 'fillBlank', q: '"Blue" in French is "___"', answer: 'bleu', accept: ['bleu'] },
          { type: 'trueFalse', q: '"Vert" means "green"', answer: true },
          { type: 'multiple', q: 'How do you say "yellow"?', options: ['bleu', 'vert', 'jaune', 'rose'], answer: 2 },
          { type: 'fillBlank', q: '"Orange" in French is "___"', answer: 'orange', accept: ['orange'] },
          { type: 'trueFalse', q: '"Noir" means "black"', answer: true },
          { type: 'multiple', q: 'What is "white" in French?', options: ['noir', 'blanc', 'gris', 'marron'], answer: 1 },
          { type: 'fillBlank', q: '"Pink" is "___" in French', answer: 'rose', accept: ['rose'] },
          { type: 'trueFalse', q: '"Gris" means "grey"', answer: true },
          { type: 'multiple', q: 'How do you say "brown"?', options: ['noir', 'marron', 'orange', 'gris'], answer: 1 },
          { type: 'fillBlank', q: '"Purple" is "___" in French', answer: 'violet', accept: ['violet', 'pourpre'] },
          { type: 'trueFalse', q: '"Bleu" is pronounced "bloo"', answer: true },
          { type: 'multiple', q: 'Which colour is "rouge"?', options: ['yellow', 'blue', 'red', 'green'], answer: 2 },
          { type: 'fillBlank', q: 'A leaf is "___" (green)', answer: 'vert', accept: ['vert'] },
          { type: 'trueFalse', q: '"Rose" means "pink"', answer: true },
          { type: 'multiple', q: 'What colour is "jaune"?', options: ['red', 'green', 'yellow', 'blue'], answer: 2 },
          { type: 'fillBlank', q: '"Gold" in French is "___"', answer: 'or', accept: ['or'] },
          { type: 'trueFalse', q: '"Argent" means "silver"', answer: true },
          { type: 'multiple', q: 'Which colour is "noir"?', options: ['white', 'black', 'grey', 'brown'], answer: 1 },
          { type: 'fillBlank', q: '"Turquoise" in French is "___"', answer: 'turquoise', accept: ['turquoise'] },
          { type: 'trueFalse', q: 'Colours in French change for masculine and feminine', answer: true },
          { type: 'multiple', q: 'What colour would a penguin be?', options: ['blanc et noir', 'bleu', 'gris', 'marron'], answer: 0 }
        ]
      },
      {
        id: 'y2-french-4',
        title: 'Animals',
        description: 'Learn French animal names: le chat, le chien, l\'oiseau, le poisson',
        questions: [
          { type: 'multiple', q: 'What is "cat" in French?', options: ['le chien', 'le chat', 'l\'oiseau', 'le poisson'], answer: 1 },
          { type: 'fillBlank', q: '"Dog" in French is "le ___"', answer: 'chien', accept: ['chien'] },
          { type: 'trueFalse', q: '"L\'oiseau" means "bird"', answer: true },
          { type: 'multiple', q: 'How do you say "fish"?', options: ['le chat', 'le chien', 'le poisson', 'le papillon'], answer: 2 },
          { type: 'fillBlank', q: '"Horse" is "le ___" in French', answer: 'cheval', accept: ['cheval'] },
          { type: 'trueFalse', q: '"Le lapin" means "rabbit"', answer: true },
          { type: 'multiple', q: 'What animal is "la vache"?', options: ['duck', 'cow', 'pig', 'sheep'], answer: 1 },
          { type: 'fillBlank', q: '"Lion" in French is "le ___"', answer: 'lion', accept: ['lion'] },
          { type: 'trueFalse', q: '"Le cochon" means "pig"', answer: true },
          { type: 'multiple', q: 'How do you say "butterfly"?', options: ['l\'oiseau', 'le papillon', 'la mouche', 'l\'abeille'], answer: 1 },
          { type: 'fillBlank', q: '"Elephant" is "l\'___" in French', answer: 'éléphant', accept: ['éléphant', 'elephant'] },
          { type: 'trueFalse', q: '"Le serpent" means "snake"', answer: true },
          { type: 'multiple', q: 'What is "duck" in French?', options: ['l\'oiseau', 'le canard', 'la grenouille', 'le poulet'], answer: 1 },
          { type: 'fillBlank', q: '"Frog" is "la ___" in French', answer: 'grenouille', accept: ['grenouille'] },
          { type: 'trueFalse', q: '"L\'abeille" means "bee"', answer: true },
          { type: 'multiple', q: 'How do you say "monkey"?', options: ['l\'ours', 'le singe', 'la girafe', 'le gorille'], answer: 1 },
          { type: 'fillBlank', q: '"Bear" is "l\'___" in French', answer: 'ours', accept: ['ours'] },
          { type: 'trueFalse', q: '"La girafe" means "giraffe"', answer: true },
          { type: 'multiple', q: 'What animal is "le tigre"?', options: ['lion', 'leopard', 'tiger', 'cheetah'], answer: 2 },
          { type: 'fillBlank', q: '"Whale" is "la ___" in French', answer: 'baleine', accept: ['baleine'] },
          { type: 'trueFalse', q: 'French animal names use "le", "la" or "l\'" for "the"', answer: true },
          { type: 'multiple', q: 'How do you say "squirrel"?', options: ['le lièvre', 'l\'écureuil', 'le blaireau', 'la souris'], answer: 1 }
        ]
      },
      {
        id: 'y2-french-5',
        title: 'Family Members',
        description: 'Learn French family words: mère, père, frère, sœur',
        questions: [
          { type: 'multiple', q: 'What is "mother" in French?', options: ['le père', 'la mère', 'la sœur', 'le frère'], answer: 1 },
          { type: 'fillBlank', q: '"Father" in French is "le ___"', answer: 'père', accept: ['père'] },
          { type: 'trueFalse', q: '"La sœur" means "sister"', answer: true },
          { type: 'multiple', q: 'How do you say "brother"?', options: ['la mère', 'le père', 'le frère', 'la sœur'], answer: 2 },
          { type: 'fillBlank', q: '"Grandmother" is "la ___" in French', answer: 'grand-mère', accept: ['grand-mère', 'grandmère'] },
          { type: 'trueFalse', q: '"Le grand-père" means "grandfather"', answer: true },
          { type: 'multiple', q: 'What family member is "l\'oncle"?', options: ['aunt', 'uncle', 'cousin', 'cousin'], answer: 1 },
          { type: 'fillBlank', q: '"Aunt" is "la ___" in French', answer: 'tante', accept: ['tante'] },
          { type: 'trueFalse', q: '"Le cousin" means "cousin" (male)', answer: true },
          { type: 'multiple', q: 'How do you say "baby"?', options: ['l\'enfant', 'le bébé', 'le garçon', 'la fille'], answer: 1 },
          { type: 'fillBlank', q: '"Boy" is "le ___" in French', answer: 'garçon', accept: ['garçon'] },
          { type: 'trueFalse', q: '"La fille" means "girl"', answer: true },
          { type: 'multiple', q: 'What is "family" in French?', options: ['la maison', 'la famille', 'la fratrie', 'la parente'], answer: 1 },
          { type: 'fillBlank', q: '"Cousin" (female) is "la ___" in French', answer: 'cousine', accept: ['cousine'] },
          { type: 'trueFalse', q: '"L\'enfant" means "child"', answer: true },
          { type: 'multiple', q: 'How do you say "stepmother"?', options: ['la mère', 'la belle-mère', 'la belle-sœur', 'la mère adoptive'], answer: 1 },
          { type: 'fillBlank', q: '"Parent" is "le ___" in French', answer: 'parent', accept: ['parent'] },
          { type: 'trueFalse', q: '"La mère" means "mother"', answer: true },
          { type: 'multiple', q: 'What family member is "la belle-sœur"?', options: ['aunt', 'sister-in-law', 'stepsister', 'grandmother'], answer: 1 },
          { type: 'fillBlank', q: '"Parent" (female) is "la ___" in French', answer: 'mère', accept: ['mère', 'parent', 'parente'] },
          { type: 'trueFalse', q: 'French family words change for male and female members', answer: true },
          { type: 'multiple', q: 'How do you say "twin"?', options: ['la fratrie', 'le jumeau', 'l\'enfant', 'le pair'], answer: 1 }
        ]
      },
      {
        id: 'y2-french-6',
        title: 'Food & Drink',
        description: 'Learn French food words: le pain, le fromage, l\'eau, le lait',
        questions: [
          { type: 'multiple', q: 'What is "bread" in French?', options: ['le fromage', 'le pain', 'le riz', 'la pâte'], answer: 1 },
          { type: 'fillBlank', q: '"Cheese" in French is "le ___"', answer: 'fromage', accept: ['fromage'] },
          { type: 'trueFalse', q: '"L\'eau" means "water"', answer: true },
          { type: 'multiple', q: 'How do you say "milk"?', options: ['l\'eau', 'le lait', 'le jus', 'le café'], answer: 1 },
          { type: 'fillBlank', q: '"Apple" is "la ___" in French', answer: 'pomme', accept: ['pomme'] },
          { type: 'trueFalse', q: '"Le fruit" means "fruit"', answer: true },
          { type: 'multiple', q: 'What is "egg" in French?', options: ['la viande', 'l\'œuf', 'le poulet', 'la carotte'], answer: 1 },
          { type: 'fillBlank', q: '"Fish" (as food) is "le ___" in French', answer: 'poisson', accept: ['poisson'] },
          { type: 'trueFalse', q: '"La viande" means "meat"', answer: true },
          { type: 'multiple', q: 'How do you say "rice"?', options: ['la pâte', 'le riz', 'le pain', 'la pomme'], answer: 1 },
          { type: 'fillBlank', q: '"Chocolate" is "le ___" in French', answer: 'chocolat', accept: ['chocolat'] },
          { type: 'trueFalse', q: '"Le lait" means "milk"', answer: true },
          { type: 'multiple', q: 'What is "carrot" in French?', options: ['la tomate', 'la carotte', 'la laitue', 'le concombre'], answer: 1 },
          { type: 'fillBlank', q: '"Orange" (fruit) is "l\'___" in French', answer: 'orange', accept: ['orange'] },
          { type: 'trueFalse', q: '"Le sucre" means "sugar"', answer: true },
          { type: 'multiple', q: 'How do you say "juice"?', options: ['l\'eau', 'le lait', 'le jus', 'le café'], answer: 2 },
          { type: 'fillBlank', q: '"Butter" is "le ___" in French', answer: 'beurre', accept: ['beurre'] },
          { type: 'trueFalse', q: '"La soupe" means "soup"', answer: true },
          { type: 'multiple', q: 'What is "strawberry" in French?', options: ['la pomme', 'la fraise', 'la cerise', 'la banane'], answer: 1 },
          { type: 'fillBlank', q: '"Chicken" is "le ___" in French', answer: 'poulet', accept: ['poulet'] },
          { type: 'trueFalse', q: '"Le riz" means "rice"', answer: true },
          { type: 'multiple', q: 'How do you say "tea"?', options: ['le café', 'le thé', 'le lait', 'l\'eau'], answer: 1 }
        ]
      },
      {
        id: 'y2-french-7',
        title: 'Days of the Week',
        description: 'Learn French day names: lundi to dimanche',
        questions: [
          { type: 'multiple', q: 'What is "Monday" in French?', options: ['lundi', 'samedi', 'mercredi', 'jeudi'], answer: 0 },
          { type: 'fillBlank', q: '"Tuesday" in French is "___"', answer: 'mardi', accept: ['mardi'] },
          { type: 'trueFalse', q: '"Mercredi" means "Wednesday"', answer: true },
          { type: 'multiple', q: 'How do you say "Thursday"?', options: ['mardi', 'jeudi', 'vendredi', 'samedi'], answer: 1 },
          { type: 'fillBlank', q: '"Friday" is "___" in French', answer: 'vendredi', accept: ['vendredi'] },
          { type: 'trueFalse', q: '"Samedi" means "Saturday"', answer: true },
          { type: 'multiple', q: 'What is "Sunday" in French?', options: ['lundi', 'samedi', 'dimanche', 'jeudi'], answer: 2 },
          { type: 'fillBlank', q: '"Week" in French is "la ___"', answer: 'semaine', accept: ['semaine'] },
          { type: 'trueFalse', q: '"Lundi" is the first day of the week in French', answer: true },
          { type: 'multiple', q: 'Which day comes after "mercredi"?', options: ['mardi', 'jeudi', 'vendredi', 'samedi'], answer: 1 },
          { type: 'fillBlank', q: '"Today" in French is "___"', answer: 'aujourd\'hui', accept: ['aujourd\'hui', 'aujourdhui'] },
          { type: 'trueFalse', q: '"Demain" means "tomorrow"', answer: true },
          { type: 'multiple', q: 'What is "yesterday" in French?', options: ['hier', 'demain', 'aujourd\'hui', 'week'], answer: 0 },
          { type: 'fillBlank', q: '"Tomorrow" is "___" in French', answer: 'demain', accept: ['demain'] },
          { type: 'trueFalse', q: '"La semaine" means "week"', answer: true },
          { type: 'multiple', q: 'In French, which comes first: "lundi" or "dimanche"?', options: ['lundi', 'dimanche', 'same time', 'varies'], answer: 0 },
          { type: 'fillBlank', q: '"Yesterday" is "___" in French', answer: 'hier', accept: ['hier'] },
          { type: 'trueFalse', q: 'In French, Monday is the start of the week', answer: true },
          { type: 'multiple', q: 'What are "jours de la semaine"?', options: ['months', 'days of the week', 'holidays', 'seasons'], answer: 1 },
          { type: 'fillBlank', q: 'The day after "vendredi" is "___"', answer: 'samedi', accept: ['samedi'] },
          { type: 'trueFalse', q: 'There are 7 days in a week in French', answer: true },
          { type: 'multiple', q: 'How do you say "next week"?', options: ['cette semaine', 'la semaine prochaine', 'la semaine dernière', 'aujourd\'hui'], answer: 1 }
        ]
      },
      {
        id: 'y2-french-8',
        title: 'Classroom Objects',
        description: 'Learn classroom words: le stylo, le livre, la règle, le crayon',
        questions: [
          { type: 'multiple', q: 'What is "pen" in French?', options: ['le crayon', 'le stylo', 'la règle', 'le papier'], answer: 1 },
          { type: 'fillBlank', q: '"Pencil" in French is "le ___"', answer: 'crayon', accept: ['crayon'] },
          { type: 'trueFalse', q: '"Le livre" means "book"', answer: true },
          { type: 'multiple', q: 'How do you say "ruler"?', options: ['le crayon', 'la règle', 'le stylo', 'le papier'], answer: 1 },
          { type: 'fillBlank', q: '"Paper" is "le ___" in French', answer: 'papier', accept: ['papier'] },
          { type: 'trueFalse', q: '"L\'école" means "school"', answer: true },
          { type: 'multiple', q: 'What is "desk" in French?', options: ['la chaise', 'la table', 'le pupitre', 'le tableau'], answer: 2 },
          { type: 'fillBlank', q: '"Chair" is "la ___" in French', answer: 'chaise', accept: ['chaise'] },
          { type: 'trueFalse', q: '"Le tableau noir" means "blackboard"', answer: true },
          { type: 'multiple', q: 'How do you say "eraser"?', options: ['la règle', 'la gomme', 'l\'encre', 'le marqueur'], answer: 1 },
          { type: 'fillBlank', q: '"Notebook" is "le ___" in French', answer: 'cahier', accept: ['cahier'] },
          { type: 'trueFalse', q: '"Le sac" means "bag"', answer: true },
          { type: 'multiple', q: 'What is "scissors" in French?', options: ['les ciseaux', 'la colle', 'le ruban', 'la pince'], answer: 0 },
          { type: 'fillBlank', q: '"Glue" is "la ___" in French', answer: 'colle', accept: ['colle'] },
          { type: 'trueFalse', q: '"Le crayons de couleur" means "coloured pencils"', answer: true },
          { type: 'multiple', q: 'How do you say "classroom"?', options: ['l\'école', 'la classe', 'la salle', 'le bureau'], answer: 1 },
          { type: 'fillBlank', q: '"Teacher" is "le ___" or "la ___" in French', answer: 'professeur, maître', accept: ['professeur', 'maître', 'prof'] },
          { type: 'trueFalse', q: '"L\'élève" means "student"', answer: true },
          { type: 'multiple', q: 'What is "chalk" in French?', options: ['le stylo', 'la craie', 'le crayon', 'l\'encre'], answer: 1 },
          { type: 'fillBlank', q: '"Pencil case" is "la ___" in French', answer: 'trousse', accept: ['trousse'] },
          { type: 'trueFalse', q: '"Le pupille" means "student"', answer: false },
          { type: 'multiple', q: 'How do you say "ink"?', options: ['le papier', 'l\'encre', 'la colle', 'le marqueur'], answer: 1 }
        ]
      }
    ]
  }
};
