window.YEAR_3_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        name: 'Place Value to 1000',
        questions: [
          { type: 'multiple', q: 'What is the value of the digit 7 in the number 375?', options: ['7', '70', '700', '3'], answer: 1 },
          { type: 'multiple', q: 'In the number 842, which digit is in the tens place?', options: ['8', '4', '2', '0'], answer: 1 },
          { type: 'fillBlank', q: 'The number 5 hundreds, 3 tens and 6 ones is ___', answer: '536', accept: ['536'] },
          { type: 'trueFalse', q: '306 is the same as 30 tens and 6 ones.', answer: false },
          { type: 'multiple', q: 'Which number is larger: 627 or 726?', options: ['627', '726', 'They are equal', 'Cannot tell'], answer: 1 },
          { type: 'fillBlank', q: '___ = 300 + 40 + 9', answer: '349', accept: ['349'] },
          { type: 'trueFalse', q: 'The digit 5 in 658 represents 500.', answer: false },
          { type: 'multiple', q: 'What comes after 399 on a number line?', options: ['398', '400', '401', '390'], answer: 1 },
          { type: 'trueFalse', q: '852 is less than 825.', answer: false },
          { type: 'fillBlank', q: 'Write the number that is 10 more than 456: ___', answer: '466', accept: ['466'] },
          { type: 'multiple', q: 'In 741, the 4 represents:', options: ['4', '40', '400', '4000'], answer: 1 },
          { type: 'trueFalse', q: '900 + 5 = 905', answer: true },
          { type: 'fillBlank', q: 'The number between 599 and 601 is ___', answer: '600', accept: ['600'] },
          { type: 'multiple', q: 'Which number is closest to 500?', options: ['450', '520', '540', '490'], answer: 1 },
          { type: 'trueFalse', q: 'In 389, the hundreds digit is 8.', answer: false },
          { type: 'fillBlank', q: '7 hundreds and 2 ones = ___', answer: '702', accept: ['702'] },
          { type: 'multiple', q: 'Which correctly shows 1000 in a different way?', options: ['100 tens', '10 hundreds', '1000 ones', 'All of these'], answer: 3 },
          { type: 'trueFalse', q: 'When counting in tens from 240, the next number is 250.', answer: true },
          { type: 'fillBlank', q: 'The number with 8 in the hundreds, 0 in the tens, and 3 in the ones is ___', answer: '803', accept: ['803'] },
          { type: 'multiple', q: 'Order from smallest to largest: 315, 351, 531', options: ['315, 531, 351', '315, 351, 531', '531, 351, 315', '351, 315, 531'], answer: 1 },
          { type: 'trueFalse', q: '467 has 6 tens and 4 hundreds.', answer: true },
          { type: 'fillBlank', q: 'Count on from 798 in ones: 798, 799, ___, 801', answer: '800', accept: ['800'] }
        ]
      },
      {
        name: 'Addition & Subtraction',
        questions: [
          { type: 'fillBlank', q: '234 + 125 = ___', answer: '359', accept: ['359'] },
          { type: 'multiple', q: 'What is 300 + 50 + 200 + 25?', options: ['500', '525', '575', '625'], answer: 2 },
          { type: 'trueFalse', q: '156 + 244 = 400', answer: true },
          { type: 'fillBlank', q: '500 - 238 = ___', answer: '262', accept: ['262'] },
          { type: 'multiple', q: 'Which calculation is correct?', options: ['245 + 135 = 370', '245 + 135 = 380', '245 + 135 = 390', '245 + 135 = 380'], answer: 3 },
          { type: 'trueFalse', q: '387 - 123 = 264', answer: true },
          { type: 'fillBlank', q: '___  + 167 = 400', answer: '233', accept: ['233'] },
          { type: 'multiple', q: 'Estimate: 298 + 195 is approximately:', options: ['400', '500', '600', '700'], answer: 1 },
          { type: 'trueFalse', q: 'When adding in columns, we always start from the left.', answer: false },
          { type: 'fillBlank', q: '600 - 275 = ___', answer: '325', accept: ['325'] },
          { type: 'multiple', q: 'What do we need to exchange when adding 167 + 245?', options: ['ones', 'tens', 'hundreds', 'No exchange needed'], answer: 1 },
          { type: 'trueFalse', q: '450 + 150 = 600', answer: true },
          { type: 'fillBlank', q: '350 - ___ = 200', answer: '150', accept: ['150'] },
          { type: 'multiple', q: 'Which subtraction needs us to exchange?', options: ['234 - 120', '345 - 142', '400 - 150', 'All of them'], answer: 1 },
          { type: 'trueFalse', q: '523 - 234 = 289', answer: true },
          { type: 'fillBlank', q: '100 + 100 + 100 + 87 = ___', answer: '387', accept: ['387'] },
          { type: 'multiple', q: 'Use mental maths: 250 + 150 = ?', options: ['300', '350', '400', '450'], answer: 2 },
          { type: 'trueFalse', q: 'We exchange 10 ones for 1 ten when there are 10 or more ones.', answer: true },
          { type: 'fillBlank', q: '456 + 234 = ___', answer: '690', accept: ['690'] },
          { type: 'multiple', q: 'What is the difference between 500 and 275?', options: ['200', '225', '250', '275'], answer: 1 },
          { type: 'trueFalse', q: '789 - 456 = 333', answer: true },
          { type: 'fillBlank', q: 'If you start at 300 and add 145, you reach ___', answer: '445', accept: ['445'] }
        ]
      },
      {
        name: 'Multiplication & Division',
        questions: [
          { type: 'fillBlank', q: '3 × 7 = ___', answer: '21', accept: ['21'] },
          { type: 'multiple', q: 'Complete the 4 times table: 4, 8, 12, ___', options: ['14', '15', '16', '17'], answer: 2 },
          { type: 'trueFalse', q: '8 × 5 = 40', answer: true },
          { type: 'fillBlank', q: '4 × 9 = ___', answer: '36', accept: ['36'] },
          { type: 'multiple', q: 'How many are 3 groups of 8?', options: ['21', '24', '27', '30'], answer: 1 },
          { type: 'trueFalse', q: '6 × 4 = 24', answer: true },
          { type: 'fillBlank', q: '___ × 8 = 64', answer: '8', accept: ['8'] },
          { type: 'multiple', q: '12 ÷ 3 = ?', options: ['2', '3', '4', '6'], answer: 2 },
          { type: 'trueFalse', q: '36 ÷ 4 = 9', answer: true },
          { type: 'fillBlank', q: '20 ÷ 4 = ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'If you share 24 sweets equally between 3 friends, each gets:', options: ['6', '7', '8', '9'], answer: 2 },
          { type: 'trueFalse', q: '48 ÷ 8 = 6', answer: true },
          { type: 'fillBlank', q: '7 × 6 = ___', answer: '42', accept: ['42'] },
          { type: 'multiple', q: 'The 8 times table: 8, 16, 24, ___', options: ['30', '32', '34', '36'], answer: 1 },
          { type: 'trueFalse', q: '3 × 12 = 36', answer: true },
          { type: 'fillBlank', q: '32 ÷ 8 = ___', answer: '4', accept: ['4'] },
          { type: 'multiple', q: 'How many legs do 4 dogs have? (4 legs each)', options: ['8', '12', '16', '20'], answer: 2 },
          { type: 'trueFalse', q: '5 × 9 = 45', answer: true },
          { type: 'fillBlank', q: '___  ÷ 3 = 7', answer: '21', accept: ['21'] },
          { type: 'multiple', q: '18 ÷ 3 = ?', options: ['4', '5', '6', '7'], answer: 2 },
          { type: 'trueFalse', q: '9 × 4 = 36', answer: true },
          { type: 'fillBlank', q: '6 × 8 = ___', answer: '48', accept: ['48'] }
        ]
      },
      {
        name: 'Fractions',
        questions: [
          { type: 'multiple', q: 'What fraction is shaded? (1 out of 4 equal parts)', options: ['1/2', '1/3', '1/4', '1/5'], answer: 2 },
          { type: 'trueFalse', q: '1/3 means one part out of three equal parts.', answer: true },
          { type: 'fillBlank', q: '1/2 of 8 = ___', answer: '4', accept: ['4'] },
          { type: 'multiple', q: 'Which fraction is larger: 2/4 or 3/4?', options: ['2/4', '3/4', 'They are equal', 'Cannot tell'], answer: 1 },
          { type: 'trueFalse', q: '1/2 and 2/4 are equivalent fractions.', answer: true },
          { type: 'fillBlank', q: '1/3 of 9 = ___', answer: '3', accept: ['3'] },
          { type: 'multiple', q: 'What is 2/3 of 12?', options: ['4', '6', '8', '10'], answer: 2 },
          { type: 'trueFalse', q: '1/4 is smaller than 1/2.', answer: true },
          { type: 'fillBlank', q: '3/4 of 20 = ___', answer: '15', accept: ['15'] },
          { type: 'multiple', q: 'If you cut a pizza into 8 slices and eat 2, what fraction did you eat?', options: ['1/4', '2/8', '1/2', 'Both 1/4 and 2/8'], answer: 3 },
          { type: 'trueFalse', q: '1/2 of 6 = 3', answer: true },
          { type: 'fillBlank', q: '2/4 of 16 = ___', answer: '8', accept: ['8'] },
          { type: 'multiple', q: 'Add: 1/4 + 2/4 = ?', options: ['2/4', '3/4', '1/2', '3/8'], answer: 1 },
          { type: 'trueFalse', q: '2/3 of 6 = 4', answer: true },
          { type: 'fillBlank', q: '___ of 10 = 5', answer: '1/2', accept: ['1/2', '2/4'] },
          { type: 'multiple', q: 'Which shows 2/3 shaded correctly?', options: ['2 out of 3 parts', '3 out of 2 parts', '2 out of 6 parts', '3 out of 6 parts'], answer: 0 },
          { type: 'trueFalse', q: '4/4 equals one whole.', answer: true },
          { type: 'fillBlank', q: '1/3 of 15 = ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: '3/3 + 1/3 = ?', options: ['3/3', '4/3', '1 1/3', 'Both b and c'], answer: 3 },
          { type: 'trueFalse', q: '1/4 of 12 = 3', answer: true },
          { type: 'fillBlank', q: '2/2 = ___', answer: '1', accept: ['1', 'one'] },
          { type: 'multiple', q: 'If 1/2 of a number is 7, what is the number?', options: ['3.5', '7', '14', '21'], answer: 2 }
        ]
      },
      {
        name: 'Measurement & Money',
        questions: [
          { type: 'fillBlank', q: '1 cm = ___ mm', answer: '10', accept: ['10'] },
          { type: 'multiple', q: 'How many cm are in 1 metre?', options: ['10', '50', '100', '1000'], answer: 2 },
          { type: 'trueFalse', q: '5 kg is heavier than 500g.', answer: true },
          { type: 'fillBlank', q: '1 litre = ___ ml', answer: '1000', accept: ['1000'] },
          { type: 'multiple', q: 'Which is heaviest?', options: ['1 kg', '500g', '100g', 'All equal'], answer: 0 },
          { type: 'trueFalse', q: '750 ml is more than 1 litre.', answer: false },
          { type: 'fillBlank', q: '___ cm = 40 mm', answer: '4', accept: ['4'] },
          { type: 'multiple', q: '£2.50 + £1.75 = ?', options: ['£3.25', '£4.00', '£4.25', '£5.00'], answer: 2 },
          { type: 'trueFalse', q: '8 × 5p = 40p', answer: true },
          { type: 'fillBlank', q: 'If a toy costs £3.45, what change from £5?', answer: '£1.55', accept: ['£1.55', '1.55', '155p'] },
          { type: 'multiple', q: 'Which costs more: 3 apples at 30p or 2 apples at 45p?', options: ['3 apples', '2 apples', 'Same price', 'Cannot tell'], answer: 0 },
          { type: 'trueFalse', q: '£1 = 100p', answer: true },
          { type: 'fillBlank', q: '6 × 20p = ___p', answer: '120', accept: ['120', '£1.20', '1.20'] },
          { type: 'multiple', q: 'A book costs £7.99. Estimate the cost of 3 books:', options: ['£15', '£21', '£24', '£30'], answer: 2 },
          { type: 'trueFalse', q: '2 metres = 200 cm', answer: true },
          { type: 'fillBlank', q: 'Change from £10 when you spend £6.32 = ___', answer: '£3.68', accept: ['£3.68', '3.68', '368p'] },
          { type: 'multiple', q: 'Which is longest: 3 metres, 250 cm, or 2.5 m?', options: ['3 metres', '250 cm', '2.5 m', 'Two are equal'], answer: 3 },
          { type: 'trueFalse', q: '500g + 500g = 1 kg', answer: true },
          { type: 'fillBlank', q: '___ g = 2 kg', answer: '2000', accept: ['2000'] },
          { type: 'multiple', q: '5 × £1.20 = ?', options: ['£5.00', '£5.50', '£6.00', '£6.50'], answer: 2 },
          { type: 'trueFalse', q: '300 ml + 700 ml = 1 litre', answer: true },
          { type: 'fillBlank', q: 'A ruler is about ___ cm long', answer: '30', accept: ['30', '15', '20'] }
        ]
      },
      {
        name: 'Time',
        questions: [
          { type: 'multiple', q: 'What time does the clock show at 25 minutes past 3?', options: ['3:15', '3:25', '3:35', '4:25'], answer: 1 },
          { type: 'trueFalse', q: 'There are 60 minutes in one hour.', answer: true },
          { type: 'fillBlank', q: 'Quarter past 2 is written as ___', answer: '2:15', accept: ['2:15', '14:15'] },
          { type: 'multiple', q: 'How many minutes are there between 3:10 and 3:40?', options: ['10', '20', '30', '40'], answer: 2 },
          { type: 'trueFalse', q: 'Half past 5 is the same as 5:30.', answer: true },
          { type: 'fillBlank', q: 'Quarter to 7 is ___:___', answer: '6:45', accept: ['6:45', '18:45'] },
          { type: 'multiple', q: 'In 24-hour time, 14:00 is:', options: ['2 pm', '2 am', '4 pm', '12 pm'], answer: 0 },
          { type: 'trueFalse', q: 'There are 7 days in a week.', answer: true },
          { type: 'fillBlank', q: 'How many minutes in 2 hours? ___', answer: '120', accept: ['120'] },
          { type: 'multiple', q: 'A PE lesson starts at 2:00 pm and lasts 45 minutes. When does it end?', options: ['2:45 pm', '2:30 pm', '3:00 pm', '3:45 pm'], answer: 0 },
          { type: 'trueFalse', q: '12:30 am is noon.', answer: false },
          { type: 'fillBlank', q: 'The month of December has ___ days', answer: '31', accept: ['31'] },
          { type: 'multiple', q: 'Which month comes after February?', options: ['January', 'March', 'April', 'May'], answer: 1 },
          { type: 'trueFalse', q: 'There are 52 weeks in a year.', answer: true },
          { type: 'fillBlank', q: 'How many seconds in one minute? ___', answer: '60', accept: ['60'] },
          { type: 'multiple', q: 'If today is Thursday, what day is it in 2 days?', options: ['Saturday', 'Friday', 'Sunday', 'Monday'], answer: 0 },
          { type: 'trueFalse', q: '20:00 in 24-hour time is 8 pm.', answer: true },
          { type: 'fillBlank', q: 'A lesson starts at 10:20 and ends at 11:05. How long is it? ___ minutes', answer: '45', accept: ['45'] },
          { type: 'multiple', q: 'The digital time 15:30 on a clock shows:', options: ['3:30 am', '3:30 pm', '5:30 pm', '12:30 pm'], answer: 1 },
          { type: 'trueFalse', q: 'June comes before May.', answer: false },
          { type: 'fillBlank', q: '12:00 in the middle of the day is ___', answer: 'noon', accept: ['noon', 'midday'] },
          { type: 'multiple', q: 'How many minutes from 2:15 to 2:50?', options: ['25', '30', '35', '40'], answer: 2 }
        ]
      },
      {
        name: 'Properties of Shape',
        questions: [
          { type: 'multiple', q: 'How many sides does a square have?', options: ['3', '4', '5', '6'], answer: 1 },
          { type: 'trueFalse', q: 'A rectangle has 4 right angles.', answer: true },
          { type: 'fillBlank', q: 'A triangle has ___ sides', answer: '3', accept: ['3'] },
          { type: 'multiple', q: 'Which shape has 6 faces?', options: ['Cube', 'Sphere', 'Cylinder', 'Pyramid'], answer: 0 },
          { type: 'trueFalse', q: 'Horizontal lines go from side to side.', answer: true },
          { type: 'fillBlank', q: 'A pentagon has ___ sides', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'Parallel lines are:', options: ['The same length', 'Never touching', 'Always equal', 'All of the above'], answer: 1 },
          { type: 'trueFalse', q: 'All rectangles are squares.', answer: false },
          { type: 'fillBlank', q: 'A right angle measures ___ degrees', answer: '90', accept: ['90'] },
          { type: 'multiple', q: 'Which shape has no corners?', options: ['Cube', 'Circle', 'Pyramid', 'Triangle'], answer: 1 },
          { type: 'trueFalse', q: 'Vertical lines go up and down.', answer: true },
          { type: 'fillBlank', q: 'A cube has ___ vertices (corners)', answer: '8', accept: ['8'] },
          { type: 'multiple', q: 'Perpendicular lines meet at:', options: ['30 degrees', '45 degrees', '90 degrees', '180 degrees'], answer: 2 },
          { type: 'trueFalse', q: 'A circle is a 2D shape.', answer: true },
          { type: 'fillBlank', q: 'A hexagon has ___ sides', answer: '6', accept: ['6'] },
          { type: 'multiple', q: 'Which 3D shape has a circular base and 1 vertex?', options: ['Cylinder', 'Cone', 'Sphere', 'Cube'], answer: 1 },
          { type: 'trueFalse', q: 'A quadrilateral has 4 sides.', answer: true },
          { type: 'fillBlank', q: 'A sphere has ___ faces', answer: '1', accept: ['1', 'one'] },
          { type: 'multiple', q: 'Which shows perpendicular lines?', options: ['Two lines going the same direction', 'Two lines crossing at 90 degrees', 'Two lines never meeting', 'Two lines at 45 degrees'], answer: 1 },
          { type: 'trueFalse', q: 'An isosceles triangle has two equal sides.', answer: true },
          { type: 'fillBlank', q: 'A cuboid has ___ edges', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'Which shape has exactly 1 edge?', options: ['Cube', 'Cylinder', 'Sphere', 'Cone'], answer: 3 }
        ]
      },
      {
        name: 'Statistics & Data',
        questions: [
          { type: 'multiple', q: 'What is shown on the x-axis of a bar chart?', options: ['Labels', 'Numbers', 'Both', 'Neither'], answer: 2 },
          { type: 'trueFalse', q: 'A tally is a way to record data.', answer: true },
          { type: 'fillBlank', q: 'When counting tallies, every 5th mark is written as ___', answer: 'a diagonal line', accept: ['a diagonal line', 'diagonal', 'crossed'] },
          { type: 'multiple', q: 'If a bar chart shows children\'s favorite animals and cat has the highest bar, this means:', options: ['Cats are the best', 'Most children chose cats', 'Cats are the tallest', 'Dogs are not popular'], answer: 1 },
          { type: 'trueFalse', q: 'A pictogram uses pictures to show data.', answer: true },
          { type: 'fillBlank', q: 'In a tally, |||| | represents ___', answer: '6', accept: ['6'] },
          { type: 'multiple', q: 'What does a table help us do with data?', options: ['Organize it', 'Record it', 'Understand it quickly', 'All of the above'], answer: 3 },
          { type: 'trueFalse', q: 'The mode is the most common value in a set of data.', answer: true },
          { type: 'fillBlank', q: 'In a simple pictogram where each symbol = 2 people, 4 symbols represents ___ people', answer: '8', accept: ['8'] },
          { type: 'multiple', q: 'If we ask 20 children their favorite fruit and 7 choose apples, what fraction chose apples?', options: ['7/20', '7/13', '1/3', '1/2'], answer: 0 },
          { type: 'trueFalse', q: 'Data can be organized in many different ways.', answer: true },
          { type: 'fillBlank', q: 'The range is the ___ value minus the ___ value', answer: 'highest', accept: ['highest', 'difference', 'max'] },
          { type: 'multiple', q: 'Which is the best way to show information about how many books each child read?', options: ['Picture', 'Bar chart', 'Story', 'Song'], answer: 1 },
          { type: 'trueFalse', q: 'A tally of |||| represents 5 items.', answer: false },
          { type: 'fillBlank', q: 'If the data shows: 2, 5, 5, 8, 9, the mode is ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'In a bar chart, the height of a bar shows:', options: ['The label', 'The quantity', 'The color', 'The position'], answer: 1 },
          { type: 'trueFalse', q: 'You cannot represent the same data in different ways.', answer: false },
          { type: 'fillBlank', q: 'If 3 children chose red, 5 chose blue, and 2 chose green, blue was chosen ___ times more than green', answer: '2.5', accept: ['2.5', '2', '3'] },
          { type: 'multiple', q: 'Which statement is true about data?', options: ['All data is numbers', 'Data can be colors or categories', 'Data must be from surveys', 'Data is always the same'], answer: 1 },
          { type: 'trueFalse', q: 'A bar chart must always have the same width bars.', answer: true },
          { type: 'fillBlank', q: 'The median of 3, 5, 7 is ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'What is the range of: 10, 15, 8, 20, 12?', options: ['12', '20', '8', '12'], answer: 0 }
        ]
      }
    ]
  },
  english: {
    name: 'English',
    icon: '📚',
    color: '#2196F3',
    lessons: [
      {
        name: 'Word Classes',
        questions: [
          { type: 'multiple', q: 'Which word is a noun?', options: ['run', 'happy', 'dog', 'quickly'], answer: 2 },
          { type: 'trueFalse', q: 'A verb is a doing or being word.', answer: true },
          { type: 'fillBlank', q: 'In the sentence "The cat is sleeping", "cat" is a ___', answer: 'noun', accept: ['noun'] },
          { type: 'multiple', q: 'Which is an adjective?', options: ['jump', 'yellow', 'carefully', 'under'], answer: 1 },
          { type: 'trueFalse', q: 'An adverb describes how something is done.', answer: true },
          { type: 'fillBlank', q: 'The word "slowly" is an ___', answer: 'adverb', accept: ['adverb'] },
          { type: 'multiple', q: 'Which word is a preposition?', options: ['beautiful', 'under', 'laugh', 'bright'], answer: 1 },
          { type: 'trueFalse', q: '"Very" is a noun.', answer: false },
          { type: 'fillBlank', q: 'In "She ran quickly", "ran" is a ___', answer: 'verb', accept: ['verb'] },
          { type: 'multiple', q: 'Which is the adjective in: "The blue book is on the shelf"?', options: ['book', 'blue', 'shelf', 'on'], answer: 1 },
          { type: 'trueFalse', q: 'Nouns are words for people, places, or things.', answer: true },
          { type: 'fillBlank', q: 'The word "between" is a ___', answer: 'preposition', accept: ['preposition'] },
          { type: 'multiple', q: 'Which sentence has an adverb?', options: ['The cat jumps', 'The cat jumps high', 'The cat is happy', 'The jumping cat'], answer: 1 },
          { type: 'trueFalse', q: '"Sad" and "happy" are both adjectives.', answer: true },
          { type: 'fillBlank', q: 'In "He plays football", "plays" is a ___', answer: 'verb', accept: ['verb'] },
          { type: 'multiple', q: 'What does a preposition tell us?', options: ['How', 'When', 'Where or relationship', 'What'], answer: 2 },
          { type: 'trueFalse', q: 'An adverb can describe a verb or an adjective.', answer: true },
          { type: 'fillBlank', q: '"London" is a proper ___', answer: 'noun', accept: ['noun'] },
          { type: 'multiple', q: 'Which word best completes: "She walked ___ through the park"?', options: ['slow', 'slowly', 'slow.', 'very slow'], answer: 1 },
          { type: 'trueFalse', q: '"And" and "but" are conjunctions.', answer: true },
          { type: 'fillBlank', q: 'In "The tall building", "tall" is an ___', answer: 'adjective', accept: ['adjective'] },
          { type: 'multiple', q: 'Which shows the correct use of an adverb?', options: ['He is very happy', 'He is happy very', 'He happy is very', 'Very is he happy'], answer: 0 }
        ]
      },
      {
        name: 'Paragraphs & Text Structure',
        questions: [
          { type: 'trueFalse', q: 'A paragraph is a group of sentences about one topic.', answer: true },
          { type: 'multiple', q: 'What is a topic sentence?', options: ['The first sentence of a book', 'The main idea of a paragraph', 'The last sentence always', 'A sentence with a topic'], answer: 1 },
          { type: 'fillBlank', q: 'A heading tells the reader what the section is ___', answer: 'about', accept: ['about'] },
          { type: 'multiple', q: 'Which helps organize a text into sections?', options: ['Commas', 'Headings', 'Capital letters', 'Full stops'], answer: 1 },
          { type: 'trueFalse', q: 'All sentences in a paragraph should be about the same topic.', answer: true },
          { type: 'fillBlank', q: 'Good writing is organized into ___ instead of one big block', answer: 'paragraphs', accept: ['paragraphs'] },
          { type: 'multiple', q: 'A new paragraph usually starts:', options: ['When we change topics', 'When a new person speaks', 'When we have a new idea', 'All of the above'], answer: 3 },
          { type: 'trueFalse', q: 'A story must have a beginning, middle, and end.', answer: true },
          { type: 'fillBlank', q: 'The ___ paragraph introduces what you will write about', answer: 'introduction', accept: ['introduction', 'opening', 'first'] },
          { type: 'multiple', q: 'What does a subheading do?', options: ['Starts a new sentence', 'Divides text into smaller parts', 'Replaces paragraphs', 'Makes text bold'], answer: 1 },
          { type: 'trueFalse', q: 'You should indent the first line of a paragraph.', answer: true },
          { type: 'fillBlank', q: 'The final paragraph often ___ the main ideas', answer: 'summarizes', accept: ['summarizes', 'concludes', 'sums up'] },
          { type: 'multiple', q: 'Good text structure helps the reader:', options: ['Read faster', 'Understand better', 'Lose interest', 'Skip sections'], answer: 1 },
          { type: 'trueFalse', q: 'Bullet points can help organize information in a text.', answer: true },
          { type: 'fillBlank', q: 'A ___ is used to show where a new paragraph starts', answer: 'new line', accept: ['new line', 'indent', 'line break'] },
          { type: 'multiple', q: 'Which text structure is best for instructions?', options: ['Story order', 'Step by step', 'Random order', 'Alphabetical'], answer: 1 },
          { type: 'trueFalse', q: 'Paragraphs can be different lengths.', answer: true },
          { type: 'fillBlank', q: 'A heading should be ___ so readers know what is coming', answer: 'clear', accept: ['clear', 'descriptive'] },
          { type: 'multiple', q: 'When should you start a new paragraph?', options: ['When you feel like it', 'When the topic changes', 'Every 5 sentences', 'Only at the end'], answer: 1 },
          { type: 'trueFalse', q: 'Text structure can help you find information quickly.', answer: true },
          { type: 'fillBlank', q: 'The ___ paragraph wraps up your ideas', answer: 'conclusion', accept: ['conclusion', 'closing'] },
          { type: 'multiple', q: 'What is the purpose of a topic sentence?', options: ['To end the text', 'To introduce the main idea', 'To add details', 'To ask questions'], answer: 1 }
        ]
      },
      {
        name: 'Prefixes',
        questions: [
          { type: 'multiple', q: 'What does the prefix "un-" mean?', options: ['Again', 'Not', 'Before', 'Under'], answer: 1 },
          { type: 'fillBlank', q: 'happy → ___ (opposite)', answer: 'unhappy', accept: ['unhappy'] },
          { type: 'trueFalse', q: 'The prefix "re-" means "again".', answer: true },
          { type: 'fillBlank', q: 'build → re___ (do again)', answer: 'rebuild', accept: ['rebuild'] },
          { type: 'multiple', q: 'Which word uses the prefix "dis-"?', options: ['disagree', 'discount', 'display', 'disease'], answer: 0 },
          { type: 'trueFalse', q: '"Misread" means to read incorrectly.', answer: true },
          { type: 'fillBlank', q: 'The prefix "mis-" means ___ or ___', answer: 'wrong, badly', accept: ['wrong', 'badly', 'incorrectly'] },
          { type: 'multiple', q: 'What does "pre-" mean?', options: ['After', 'Before', 'Not', 'Under'], answer: 1 },
          { type: 'trueFalse', q: '"Untrue" means the opposite of true.', answer: true },
          { type: 'fillBlank', q: 'lock → un___ (to open)', answer: 'unlock', accept: ['unlock'] },
          { type: 'multiple', q: 'Which has a prefix?', options: ['happy', 'unhappy', 'happily', 'happier'], answer: 1 },
          { type: 'trueFalse', q: 'The prefix "sub-" means "under".', answer: true },
          { type: 'fillBlank', q: 'play → re___ (to play again)', answer: 'replay', accept: ['replay'] },
          { type: 'multiple', q: '"Disappear" means:', options: ['To appear again', 'To appear first', 'To stop appearing', 'To appear below'], answer: 2 },
          { type: 'trueFalse', q: 'You can add a prefix to the beginning of a word.', answer: true },
          { type: 'fillBlank', q: 'agree → dis___ (to not agree)', answer: 'disagree', accept: ['disagree'] },
          { type: 'multiple', q: 'Which prefix do we use to mean "not"?', options: ['re-', 'un-', 'pre-', 'sub-'], answer: 1 },
          { type: 'trueFalse', q: '"Misunderstand" means to understand wrongly.', answer: true },
          { type: 'fillBlank', q: 'appear → dis___ (to vanish)', answer: 'disappear', accept: ['disappear'] },
          { type: 'multiple', q: 'What does "pre-school" mean?', options: ['After school', 'School again', 'Before school', 'Below school'], answer: 2 },
          { type: 'trueFalse', q: 'The prefix "re-" changes the whole meaning of a word.', answer: false },
          { type: 'fillBlank', q: 'connect → dis___ (to separate)', answer: 'disconnect', accept: ['disconnect'] }
        ]
      },
      {
        name: 'Conjunctions & Subordination',
        questions: [
          { type: 'multiple', q: 'What is a conjunction?', options: ['A type of noun', 'A joining word', 'A describing word', 'A naming word'], answer: 1 },
          { type: 'trueFalse', q: '"Because" is a conjunction.', answer: true },
          { type: 'fillBlank', q: 'I wanted to play, ___ it was raining.', answer: 'but', accept: ['but'] },
          { type: 'multiple', q: 'Which conjunction shows a reason?', options: ['and', 'because', 'or', 'but'], answer: 1 },
          { type: 'trueFalse', q: '"And" joins two ideas of equal importance.', answer: true },
          { type: 'fillBlank', q: 'She was happy ___ she passed the test.', answer: 'because', accept: ['because'] },
          { type: 'multiple', q: '"Although" is used to show:', options: ['Addition', 'Contrast', 'Choice', 'Time'], answer: 1 },
          { type: 'trueFalse', q: 'A subordinate clause can stand alone as a sentence.', answer: false },
          { type: 'fillBlank', q: 'I will come to the party ___ I finish my homework.', answer: 'when', accept: ['when', 'after'] },
          { type: 'multiple', q: 'Which sentence uses "if" correctly?', options: ['If it rains tomorrow', 'If you study, you will pass', 'If the game is', 'If very cold'], answer: 1 },
          { type: 'trueFalse', q: '"Or" shows a choice between options.', answer: true },
          { type: 'fillBlank', q: 'The cat slept ___ the fire was warm.', answer: 'because', accept: ['because'] },
          { type: 'multiple', q: 'What does "while" usually indicate?', options: ['Reason', 'Time', 'Choice', 'Cause'], answer: 1 },
          { type: 'trueFalse', q: 'A main clause needs a subordinate clause to make sense.', answer: false },
          { type: 'fillBlank', q: 'I like football ___ I also like tennis.', answer: 'and', accept: ['and'] },
          { type: 'multiple', q: '"Although it was cold, she wore a thin coat." This shows:', options: ['Reason', 'Contrast', 'Time', 'Condition'], answer: 1 },
          { type: 'trueFalse', q: 'You can start a sentence with a conjunction.', answer: true },
          { type: 'fillBlank', q: '___ it rains, we will stay inside.', answer: 'If', accept: ['If'] },
          { type: 'multiple', q: 'Which is a subordinate clause?', options: ['The dog ran', 'Because she was late', 'He jumped high', 'She danced'], answer: 1 },
          { type: 'trueFalse', q: '"When" can introduce a time clause.', answer: true },
          { type: 'fillBlank', q: 'He studied hard ___ he wanted to pass.', answer: 'because', accept: ['because'] },
          { type: 'multiple', q: 'A complex sentence has:', options: ['One clause', 'Two clauses', 'No clauses', 'Always four clauses'], answer: 1 }
        ]
      },
      {
        name: 'Present Perfect Tense',
        questions: [
          { type: 'multiple', q: 'Which is present perfect?', options: ['I eat', 'I am eating', 'I have eaten', 'I ate'], answer: 2 },
          { type: 'trueFalse', q: 'The present perfect uses "have" or "has" + past participle.', answer: true },
          { type: 'fillBlank', q: 'I ___ (eat) my breakfast already.', answer: 'have eaten', accept: ['have eaten', '\'ve eaten'] },
          { type: 'multiple', q: 'She ___ her homework.', options: ['does', 'have done', 'has done', 'doing'], answer: 2 },
          { type: 'trueFalse', q: '"I have gone" means I went in the past.', answer: true },
          { type: 'fillBlank', q: 'We ___ (see) that film before.', answer: 'have seen', accept: ['have seen', '\'ve seen'] },
          { type: 'multiple', q: 'Use "has" with:', options: ['I, we, they', 'he, she, it', 'You', 'All people'], answer: 1 },
          { type: 'trueFalse', q: '"She have been" is correct.', answer: false },
          { type: 'fillBlank', q: 'They ___ (finish) their work.', answer: 'have finished', accept: ['have finished', '\'ve finished'] },
          { type: 'multiple', q: 'Which shows present perfect?', options: ['He runs', 'He has run', 'He is running', 'He will run'], answer: 1 },
          { type: 'trueFalse', q: 'Present perfect can show something that happened recently.', answer: true },
          { type: 'fillBlank', q: 'It ___ (rain) all day.', answer: 'has rained', accept: ['has rained', '\'s rained'] },
          { type: 'multiple', q: '"I have been to the zoo" means:', options: ['I am at the zoo now', 'I went to the zoo in the past', 'I will go to the zoo', 'I am going to the zoo'], answer: 1 },
          { type: 'trueFalse', q: 'The past tense and present perfect are the same.', answer: false },
          { type: 'fillBlank', q: 'She ___ (write) three stories.', answer: 'has written', accept: ['has written', '\'s written'] },
          { type: 'multiple', q: 'Which sentence is present perfect?', options: ['They played games', 'They have played games', 'They are playing games', 'They will play games'], answer: 1 },
          { type: 'trueFalse', q: 'Present perfect can show an action that started in the past and continues now.', answer: true },
          { type: 'fillBlank', q: 'You ___ (grow) very tall.', answer: 'have grown', accept: ['have grown', '\'ve grown'] },
          { type: 'multiple', q: '"I have learned my times tables" tells us:', options: ['I am learning now', 'I learned and still know them', 'I will learn soon', 'I forgot them'], answer: 1 },
          { type: 'trueFalse', q: '"He has gone" is present perfect.', answer: true },
          { type: 'fillBlank', q: 'We ___ (eat) our lunch already.', answer: 'have eaten', accept: ['have eaten', '\'ve eaten'] },
          { type: 'multiple', q: 'Use "have" with:', options: ['He', 'She', 'I, we, you, they', 'It'], answer: 2 }
        ]
      },
      {
        name: 'Inverted Commas & Speech Marks',
        questions: [
          { type: 'multiple', q: 'What do inverted commas (speech marks) show?', options: ['Shouting', 'Excitement', 'Direct speech', 'Underlining'], answer: 2 },
          { type: 'trueFalse', q: '"Hello," said Tom. This is correct punctuation.', answer: true },
          { type: 'fillBlank', q: 'Inverted commas are also called ___', answer: 'speech marks', accept: ['speech marks', 'quotation marks', 'quotes'] },
          { type: 'multiple', q: 'Where do speech marks go?', options: ['After the sentence', 'Around the spoken words', 'At the beginning only', 'Before and after'], answer: 1 },
          { type: 'trueFalse', q: '"Come here," said the teacher. The comma goes inside the commas.', answer: true },
          { type: 'fillBlank', q: '"I love animals," ___ Sarah.', answer: 'said', accept: ['said'] },
          { type: 'multiple', q: 'Which is correct?', options: ['"Help me" shouted Jim.', '"Help me", shouted Jim.', '"Help me," shouted Jim.', 'Help me said Jim'], answer: 2 },
          { type: 'trueFalse', q: 'A reporting clause tells us who is speaking.', answer: true },
          { type: 'fillBlank', q: '"Watch out_" Tom said. What punctuation is missing?', answer: '!', accept: ['!', 'exclamation', 'exclamation mark'] },
          { type: 'multiple', q: 'In "Are you coming?" asked Emma. The question mark goes:', options: ['Outside the commas', 'Inside the commas', 'After "asked"', 'Before the commas'], answer: 1 },
          { type: 'trueFalse', q: '"I am cold," she whispered. This is correctly punctuated.', answer: true },
          { type: 'fillBlank', q: 'The ___ clause tells us who spoke and how', answer: 'reporting', accept: ['reporting'] },
          { type: 'multiple', q: 'Which sentence uses speech marks correctly?', options: ['She said "hello" to me.', 'She "said" hello to me.', '"She said hello to me."', '"Good morning," she said.'], answer: 3 },
          { type: 'trueFalse', q: 'You must use a capital letter at the start of direct speech.', answer: true },
          { type: 'fillBlank', q: '"Can I help_" asked the teacher. What\'s missing?', answer: '?', accept: ['?', 'question mark'] },
          { type: 'multiple', q: '"Stop!" shouted the guard. The exclamation mark shows:', options: ['Excitement', 'Anger', 'Strong feeling', 'All of these'], answer: 2 },
          { type: 'trueFalse', q: 'The reporting clause can come at the start of the sentence.', answer: true },
          { type: 'fillBlank', q: 'She asked, "___ do you want to go?" What word starts the quote?', answer: 'Where', accept: ['Where'] },
          { type: 'multiple', q: 'How do we show someone is speaking?', options: ['Use bold', 'Use italics', 'Use speech marks', 'Use capitals'], answer: 2 },
          { type: 'trueFalse', q: '"I want to play," said Sam. "Let\'s go," replied Tom. Both are correct.', answer: true },
          { type: 'fillBlank', q: '"Hello," she said. The comma position is ___', answer: 'inside', accept: ['inside', 'inside the commas'] },
          { type: 'multiple', q: 'In dialogue, what shows a new speaker?', options: ['Comma', 'New line', 'Full stop', 'Capital letter'], answer: 1 }
        ]
      },
      {
        name: 'Spelling Rules',
        questions: [
          { type: 'multiple', q: 'When adding "-ing" to "hop", what happens?', options: ['hopping', 'hoping', 'hoping', 'hoppping'], answer: 0 },
          { type: 'trueFalse', q: 'Double the consonant before adding "-ing" to short words.', answer: true },
          { type: 'fillBlank', q: 'run + ing = ___ (double the n)', answer: 'running', accept: ['running'] },
          { type: 'multiple', q: 'How do we spell the -tion ending sound?', options: ['-tion', '-sion', '-shun', 'a or b'], answer: 3 },
          { type: 'trueFalse', q: '"Action" ends with the -tion sound.', answer: true },
          { type: 'fillBlank', q: 'Words ending in -tion usually have the /shan/ ___', answer: 'sound', accept: ['sound'] },
          { type: 'multiple', q: 'Which word uses -sion?', options: ['Nation', 'Station', 'Decision', 'Motion'], answer: 2 },
          { type: 'trueFalse', q: 'Family words often have the same spelling pattern.', answer: true },
          { type: 'fillBlank', q: 'cat → cats, bat → bats, mat → ___ (word family)', answer: 'mats', accept: ['mats'] },
          { type: 'multiple', q: 'What happens to "e" in "make" when adding "-ing"?', options: ['Stays', 'Doubles', 'Drops', 'Changes to a'], answer: 2 },
          { type: 'trueFalse', q: 'The -tion ending is common in English.', answer: true },
          { type: 'fillBlank', q: 'like + ing = ___ (drop the e)', answer: 'liking', accept: ['liking'] },
          { type: 'multiple', q: 'Which word belongs to the "art" family?', options: ['Eat', 'Start', 'Orange', 'Plant'], answer: 1 },
          { type: 'trueFalse', q: 'We double consonants before adding "-ing" to all words.', answer: false },
          { type: 'fillBlank', q: '"___tion" often sounds like /shan/', answer: 'tion', accept: ['tion'] },
          { type: 'multiple', q: 'Which shows correct doubling?', options: ['hopp + ing', 'plan + ing = planing', 'stop + ing = stoping', 'sit + ing = sitting'], answer: 3 },
          { type: 'trueFalse', q: 'Words in the same family usually share letters.', answer: true },
          { type: 'fillBlank', q: 'Words with -sion often come from words ending in ___', answer: '-se', accept: ['-se', 'e'] },
          { type: 'multiple', q: 'How is "position" spelled?', options: ['posision', 'position', 'posisshun', 'posishen'], answer: 1 },
          { type: 'trueFalse', q: '"Tension" ends with -sion.', answer: true },
          { type: 'fillBlank', q: 'hat → hats, bat → ___ (simple family)', answer: 'bats', accept: ['bats'] },
          { type: 'multiple', q: 'Which word follows the doubling rule?', options: ['Run-ring', 'Step-steping', 'Walk-walking', 'Sit-siting'], answer: 0 }
        ]
      },
      {
        name: 'Homophones & Confusable Words',
        questions: [
          { type: 'multiple', q: 'Which sentence uses "their" correctly?', options: ['They went to there house.', 'Their house is big.', 'There going to the park.', 'They\'re house is blue.'], answer: 1 },
          { type: 'trueFalse', q: '"There" means a place.', answer: true },
          { type: 'fillBlank', q: '"They are" can be shortened to ___', answer: 'they\'re', accept: ['they\'re', 'theyre'] },
          { type: 'multiple', q: 'What do "to", "too", and "two" sound like?', options: ['Different', 'The same', 'Almost the same', 'No similarity'], answer: 1 },
          { type: 'trueFalse', q: '"To" shows direction or purpose.', answer: true },
          { type: 'fillBlank', q: '"Too" means ___ or also', answer: 'also', accept: ['also', 'excessive', 'more than enough'] },
          { type: 'multiple', q: 'Which is spelled correctly?', options: ['I went two the shop.', 'I went to the shop.', 'I went too the shop.', 'I went tu the shop.'], answer: 1 },
          { type: 'trueFalse', q: '"Two" is the number 2.', answer: true },
          { type: 'fillBlank', q: 'This cake is ___ sweet! (more than enough)', answer: 'too', accept: ['too'] },
          { type: 'multiple', q: 'Which sentence is correct?', options: ['Where did you go?', 'Wear did you go?', 'Ware did you go?', 'Whair did you go?'], answer: 0 },
          { type: 'trueFalse', q: '"Wear" means to have clothes on.', answer: true },
          { type: 'fillBlank', q: 'I ___ my blue shirt.', answer: 'wear', accept: ['wear'] },
          { type: 'multiple', q: 'Homophones are words that:', options: ['Mean the same', 'Sound the same but have different spellings', 'Are opposites', 'Have the same letters'], answer: 1 },
          { type: 'trueFalse', q: '"Were" is a past tense of "to be".', answer: true },
          { type: 'fillBlank', q: 'You ___ at the park yesterday.', answer: 'were', accept: ['were'] },
          { type: 'multiple', q: 'Which sentence uses the correct homophone?', options: ['I see there coming.', 'I see their coming.', 'I see they\'re coming.', 'Both b and c'], answer: 3 },
          { type: 'trueFalse', q: '"New" and "knew" are homophones.', answer: true },
          { type: 'fillBlank', q: 'I ___ the answer already.', answer: 'knew', accept: ['knew'] },
          { type: 'multiple', q: '"Hear" and "here" - which one relates to ears?', options: ['Hear', 'Here', 'They are the same', 'Neither'], answer: 0 },
          { type: 'trueFalse', q: '"Here" means in this place.', answer: true },
          { type: 'fillBlank', q: 'Can you ___ me?', answer: 'hear', accept: ['hear'] },
          { type: 'multiple', q: 'Which is correct?', options: ['Their going to the beach.', 'They\'re going to the beach.', 'There going to the beach.', 'Thare going to the beach.'], answer: 1 }
        ]
      }
    ]
  },
  science: {
    name: 'Science',
    icon: '🔬',
    color: '#FF9800',
    lessons: [
      {
        name: 'Rocks & Soils',
        questions: [
          { type: 'multiple', q: 'What are the three types of rocks?', options: ['Hard and soft', 'Igneous, sedimentary, metamorphic', 'Big and small', 'Old and new'], answer: 1 },
          { type: 'trueFalse', q: 'Igneous rocks form from cooled lava.', answer: true },
          { type: 'fillBlank', q: '___ rocks are formed from layers of sediment pressed together.', answer: 'Sedimentary', accept: ['Sedimentary'] },
          { type: 'multiple', q: 'What is a fossil?', options: ['A type of soil', 'Remains of dead organisms', 'A volcanic rock', 'Compressed sand'], answer: 1 },
          { type: 'trueFalse', q: 'Soil contains only rocks.', answer: false },
          { type: 'fillBlank', q: 'Soil is made of rocks, ___, and air.', answer: 'organic matter', accept: ['organic matter', 'decomposed plants', 'animals'] },
          { type: 'multiple', q: 'Which rock floats on water?', options: ['Marble', 'Pumice', 'Granite', 'Slate'], answer: 1 },
          { type: 'trueFalse', q: 'Metamorphic rocks form from heat and pressure.', answer: true },
          { type: 'fillBlank', q: '___ rocks come from extinct plants and animals in sedimentary rock.', answer: 'Fossils', accept: ['Fossils'] },
          { type: 'multiple', q: 'Granite is an example of:', options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Organic'], answer: 2 },
          { type: 'trueFalse', q: 'All rocks are hard.', answer: true },
          { type: 'fillBlank', q: 'Clay soil holds ___ well.', answer: 'water', accept: ['water'] },
          { type: 'multiple', q: 'Which is NOT a type of soil?', options: ['Clay', 'Sand', 'Silt', 'Rock'], answer: 3 },
          { type: 'trueFalse', q: 'Sandstone is a sedimentary rock.', answer: true },
          { type: 'fillBlank', q: '___ soil is light and drains water quickly.', answer: 'Sandy', accept: ['Sandy'] },
          { type: 'multiple', q: 'Fossils teach us about:', options: ['Rainfall', 'Ancient life', 'Modern animals', 'Current rocks'], answer: 1 },
          { type: 'trueFalse', q: 'Soil can support plant growth.', answer: true },
          { type: 'fillBlank', q: 'Slate is a ___ rock formed under pressure.', answer: 'metamorphic', accept: ['metamorphic'] },
          { type: 'multiple', q: 'Which rock is used to build houses?', options: ['Pumice', 'Granite', 'Obsidian', 'Chalk'], answer: 1 },
          { type: 'trueFalse', q: 'Rocks are the only thing in soil.', answer: false },
          { type: 'fillBlank', q: 'Coal is formed from ___ buried under pressure.', answer: 'dead plants', accept: ['dead plants', 'plants'] },
          { type: 'multiple', q: 'How long do rocks take to form?', options: ['Days', 'Months', 'Millions of years', 'Never formed'], answer: 2 }
        ]
      },
      {
        name: 'Light',
        questions: [
          { type: 'multiple', q: 'Which is a light source?', options: ['Moon', 'Sun', 'Mirror', 'Wall'], answer: 1 },
          { type: 'trueFalse', q: 'Light travels in straight lines.', answer: true },
          { type: 'fillBlank', q: 'A ___ is created when light is blocked by an object.', answer: 'shadow', accept: ['shadow'] },
          { type: 'multiple', q: 'What happens when light hits a mirror?', options: ['It disappears', 'It reflects back', 'It changes color', 'It slows down'], answer: 1 },
          { type: 'trueFalse', q: 'We see objects because light bounces off them.', answer: true },
          { type: 'fillBlank', q: 'Darkness is the ___ of light.', answer: 'absence', accept: ['absence'] },
          { type: 'multiple', q: 'Which is a natural light source?', options: ['Lamp', 'Fire', 'Stars', 'All of these'], answer: 2 },
          { type: 'trueFalse', q: 'Shadows are always the same size.', answer: false },
          { type: 'fillBlank', q: 'The Sun is the main ___ source for Earth.', answer: 'light', accept: ['light'] },
          { type: 'multiple', q: 'When does a shadow get longer?', options: ['Midday', 'When the sun is higher', 'Early morning or late afternoon', 'Never'], answer: 2 },
          { type: 'trueFalse', q: 'A reflective surface bounces light back.', answer: true },
          { type: 'fillBlank', q: 'We should never look directly at the ___ for safety.', answer: 'Sun', accept: ['Sun'] },
          { type: 'multiple', q: 'Which surface reflects light best?', options: ['Black paper', 'Mirror', 'Cloth', 'Wood'], answer: 1 },
          { type: 'trueFalse', q: 'Some materials are opaque and block all light.', answer: true },
          { type: 'fillBlank', q: 'A ___ material lets some light through.', answer: 'translucent', accept: ['translucent'] },
          { type: 'multiple', q: 'What is transparent?', options: ['Paper', 'Glass', 'Metal', 'Plastic bag'], answer: 1 },
          { type: 'trueFalse', q: 'Light can bend through a prism.', answer: true },
          { type: 'fillBlank', q: 'Looking at the Sun without protection can cause ___ damage.', answer: 'eye', accept: ['eye'] },
          { type: 'multiple', q: 'A shadow shows the ___ of an object:', options: ['Color', 'Shape', 'Weight', 'Texture'], answer: 1 },
          { type: 'trueFalse', q: 'All light sources are hot.', answer: false },
          { type: 'fillBlank', q: 'A ___ object does not let any light through.', answer: 'opaque', accept: ['opaque'] },
          { type: 'multiple', q: 'Why do we see a shadow?', options: ['The object glows', 'Light is blocked', 'The Sun is moving', 'Air is thick'], answer: 1 }
        ]
      },
      {
        name: 'Forces & Magnets',
        questions: [
          { type: 'multiple', q: 'A force is:', options: ['A heavy object', 'A push or pull', 'A speed', 'A sound'], answer: 1 },
          { type: 'trueFalse', q: 'Friction stops objects from sliding easily.', answer: true },
          { type: 'fillBlank', q: 'A ___ is a force that opposes motion between surfaces.', answer: 'friction', accept: ['friction'] },
          { type: 'multiple', q: 'What happens when you push harder on an object?', options: ['It slows down', 'It moves the same', 'It accelerates more', 'It stops'], answer: 2 },
          { type: 'trueFalse', q: 'Magnets only attract metal.', answer: false },
          { type: 'fillBlank', q: 'A magnet has a North pole and a ___ pole.', answer: 'South', accept: ['South'] },
          { type: 'multiple', q: 'What happens when two north poles of magnets meet?', options: ['They stick together', 'They repel (push apart)', 'Nothing happens', 'They merge'], answer: 1 },
          { type: 'trueFalse', q: 'Iron is magnetic.', answer: true },
          { type: 'fillBlank', q: 'Opposite magnetic poles ___', answer: 'attract', accept: ['attract'] },
          { type: 'multiple', q: 'Which material is NOT magnetic?', options: ['Iron', 'Steel', 'Aluminum', 'Nickel'], answer: 2 },
          { type: 'trueFalse', q: 'Friction can be helpful and unhelpful.', answer: true },
          { type: 'fillBlank', q: 'We reduce friction with ___.', answer: 'lubricants', accept: ['lubricants', 'oil', 'grease'] },
          { type: 'multiple', q: 'Which shows the most friction?', options: ['Ice sliding on ice', 'Roller skates', 'Shoes on rough concrete', 'Skis on snow'], answer: 2 },
          { type: 'trueFalse', q: 'Every object has two magnetic poles.', answer: false },
          { type: 'fillBlank', q: 'A ___ attracts certain metals.', answer: 'magnet', accept: ['magnet'] },
          { type: 'multiple', q: 'What is the force that pulls objects to the ground?', options: ['Magnetism', 'Friction', 'Gravity', 'Push'], answer: 2 },
          { type: 'trueFalse', q: 'Gravity affects all objects.', answer: true },
          { type: 'fillBlank', q: '___ makes it harder to push something across a rough surface.', answer: 'Friction', accept: ['Friction'] },
          { type: 'multiple', q: 'Which metal is not attracted to magnets?', options: ['Copper', 'Steel', 'Iron', 'Nickel'], answer: 0 },
          { type: 'trueFalse', q: 'You can magnetize some objects.', answer: true },
          { type: 'fillBlank', q: 'A ___ compass uses Earth\'s magnetic field.', answer: 'magnetic', accept: ['magnetic'] },
          { type: 'multiple', q: 'What force slows down a bicycle?', options: ['Magnetism', 'Gravity', 'Friction and air resistance', 'Push'], answer: 2 }
        ]
      },
      {
        name: 'Plants',
        questions: [
          { type: 'multiple', q: 'What do plant roots do?', options: ['Make food', 'Absorb water', 'Produce flowers', 'Make oxygen'], answer: 1 },
          { type: 'trueFalse', q: 'Leaves make food for the plant using sunlight.', answer: true },
          { type: 'fillBlank', q: 'The ___ transports water from the roots to the leaves.', answer: 'stem', accept: ['stem'] },
          { type: 'multiple', q: 'What do flowers do?', options: ['Store water', 'Support the plant', 'Produce seeds', 'Absorb nutrients'], answer: 2 },
          { type: 'trueFalse', q: 'Plants need sunlight, water, and oxygen to grow.', answer: true },
          { type: 'fillBlank', q: '___ helps move pollen from flower to flower.', answer: 'Pollination', accept: ['Pollination', 'Bees', 'Insects'] },
          { type: 'multiple', q: 'Which part stores seeds?', options: ['Leaf', 'Fruit', 'Stem', 'Root'], answer: 1 },
          { type: 'trueFalse', q: 'All plants have flowers.', answer: false },
          { type: 'fillBlank', q: '___ dispersal spreads seeds to new places.', answer: 'Seed', accept: ['Seed'] },
          { type: 'multiple', q: 'How are seeds dispersed?', options: ['By wind', 'By animals', 'By water', 'All of these'], answer: 3 },
          { type: 'trueFalse', q: 'A bulb is a storage organ of some plants.', answer: true },
          { type: 'fillBlank', q: 'Plants absorb nutrients from the ___', answer: 'soil', accept: ['soil'] },
          { type: 'multiple', q: 'What is photosynthesis?', options: ['Plant movement', 'Making food from sunlight', 'Absorbing water', 'Producing flowers'], answer: 1 },
          { type: 'trueFalse', q: 'The stem supports the leaves and flowers.', answer: true },
          { type: 'fillBlank', q: 'Leaves are usually ___ for absorbing sunlight.', answer: 'green', accept: ['green'] },
          { type: 'multiple', q: 'Which plant part is usually underground?', options: ['Stem', 'Leaf', 'Root', 'Flower'], answer: 2 },
          { type: 'trueFalse', q: 'Pollen helps plants reproduce.', answer: true },
          { type: 'fillBlank', q: 'A ___ grows from a seed into a plant.', answer: 'seedling', accept: ['seedling'] },
          { type: 'multiple', q: 'What does the xylem transport?', options: ['Pollen', 'Seeds', 'Water', 'Nutrients'], answer: 2 },
          { type: 'trueFalse', q: 'Some plants are pollinated by wind.', answer: true },
          { type: 'fillBlank', q: 'Plants produce ___ as a byproduct of photosynthesis.', answer: 'oxygen', accept: ['oxygen'] },
          { type: 'multiple', q: 'What helps bees pollinate flowers?', options: ['Leaves', 'Pollen', 'Roots', 'Stems'], answer: 1 }
        ]
      },
      {
        name: 'Animals & Humans',
        questions: [
          { type: 'multiple', q: 'What is the skeleton?', options: ['Muscles', 'Framework of bones', 'Skin', 'Fat'], answer: 1 },
          { type: 'trueFalse', q: 'All animals have skeletons.', answer: false },
          { type: 'fillBlank', q: 'A ___ is a dense tissue that makes up the skeleton.', answer: 'bone', accept: ['bone'] },
          { type: 'multiple', q: 'What is the skull?', options: ['Neck bone', 'Protects the brain', 'Part of the spine', 'Jaw bone'], answer: 1 },
          { type: 'trueFalse', q: 'Muscles pull on bones to create movement.', answer: true },
          { type: 'fillBlank', q: 'The ___ is a long bone in your upper arm.', answer: 'humerus', accept: ['humerus'] },
          { type: 'multiple', q: 'What do animals need to survive?', options: ['Food', 'Water and air', 'Shelter', 'All of these'], answer: 3 },
          { type: 'trueFalse', q: 'Nutrition means getting the right food.', answer: true },
          { type: 'fillBlank', q: 'A balanced diet includes ___, proteins, and fats.', answer: 'carbohydrates', accept: ['carbohydrates', 'fruits', 'vegetables'] },
          { type: 'multiple', q: 'Which is a protein source?', options: ['Bread', 'Apples', 'Eggs', 'Potatoes'], answer: 2 },
          { type: 'trueFalse', q: 'Your spine protects your spinal cord.', answer: true },
          { type: 'fillBlank', q: 'There are ___ bones in the human skeleton.', answer: '206', accept: ['206', 'two hundred'] },
          { type: 'multiple', q: 'What do joints do?', options: ['Support weight', 'Allow movement', 'Protect organs', 'Produce blood'], answer: 1 },
          { type: 'trueFalse', q: 'Carnivores eat only meat.', answer: true },
          { type: 'fillBlank', q: 'A ___ eats both plants and meat.', answer: 'omnivore', accept: ['omnivore'] },
          { type: 'multiple', q: 'What is an herbivore?', options: ['Meat eater', 'Plant eater', 'Both', 'Neither'], answer: 1 },
          { type: 'trueFalse', q: 'Teeth help break down food.', answer: true },
          { type: 'fillBlank', q: 'The ___ is responsible for digesting food.', answer: 'stomach', accept: ['stomach'] },
          { type: 'multiple', q: 'What is a food chain?', options: ['A store', 'Energy transfer through eating', 'A type of food', 'A restaurant'], answer: 1 },
          { type: 'trueFalse', q: 'Humans are omnivores.', answer: true },
          { type: 'fillBlank', q: 'Animals need ___ to move and grow.', answer: 'energy', accept: ['energy'] },
          { type: 'multiple', q: 'Which is an herbivore?', options: ['Lion', 'Dog', 'Sheep', 'Wolf'], answer: 2 }
        ]
      },
      {
        name: 'States of Matter',
        questions: [
          { type: 'multiple', q: 'What are the three states of matter?', options: ['Solid, liquid, vapor', 'Solid, liquid, gas', 'Soft, hard, cold', 'Hot, warm, cold'], answer: 1 },
          { type: 'trueFalse', q: 'A solid has a fixed shape.', answer: true },
          { type: 'fillBlank', q: 'A ___ takes the shape of its container.', answer: 'liquid', accept: ['liquid'] },
          { type: 'multiple', q: 'Which best describes a gas?', options: ['Takes shape of container', 'Has fixed volume', 'Can be invisible', 'All of these'], answer: 2 },
          { type: 'trueFalse', q: 'Water is a liquid at room temperature.', answer: true },
          { type: 'fillBlank', q: 'When a liquid heats up, it becomes a ___', answer: 'gas', accept: ['gas', 'vapor'] },
          { type: 'multiple', q: 'What is melting?', options: ['Freezing', 'A solid becoming liquid', 'Gas to liquid', 'Liquid to solid'], answer: 1 },
          { type: 'trueFalse', q: 'Freezing is when a liquid becomes a solid.', answer: true },
          { type: 'fillBlank', q: 'Ice melts at ___ degrees Celsius.', answer: '0', accept: ['0'] },
          { type: 'multiple', q: 'What is evaporation?', options: ['Liquid to solid', 'Solid to liquid', 'Liquid to gas', 'Gas to liquid'], answer: 2 },
          { type: 'trueFalse', q: 'Condensation is when gas becomes liquid.', answer: true },
          { type: 'fillBlank', q: 'Water ___ at 100 degrees Celsius.', answer: 'boils', accept: ['boils'] },
          { type: 'multiple', q: 'Which is a physical change?', options: ['Burning', 'Melting', 'Cooking', 'Rusting'], answer: 1 },
          { type: 'trueFalse', q: 'All solids are hard.', answer: false },
          { type: 'fillBlank', q: 'A gas has no fixed ___ or shape.', answer: 'volume', accept: ['volume'] },
          { type: 'multiple', q: 'What causes matter to change state?', options: ['Light', 'Heat or cooling', 'Movement', 'Color'], answer: 1 },
          { type: 'trueFalse', q: 'Sublimation is a change in state.', answer: true },
          { type: 'fillBlank', q: 'Water vapor is ___ that has evaporated.', answer: 'water', accept: ['water'] },
          { type: 'multiple', q: 'Which is an example of a gas at room temperature?', options: ['Water', 'Rock', 'Air', 'Ice'], answer: 2 },
          { type: 'trueFalse', q: 'A liquid flows.', answer: true },
          { type: 'fillBlank', q: 'The ___ is the temperature at which something melts.', answer: 'melting point', accept: ['melting point'] },
          { type: 'multiple', q: 'What happens when you cool a gas?', options: ['Becomes solid', 'Becomes liquid', 'Stays the same', 'Disappears'], answer: 1 }
        ]
      },
      {
        name: 'Healthy Eating & Nutrition',
        questions: [
          { type: 'multiple', q: 'What is a balanced diet?', options: ['Only vegetables', 'Right amounts of different foods', 'No sugary foods', 'Lots of meat'], answer: 1 },
          { type: 'trueFalse', q: 'Carbohydrates provide energy.', answer: true },
          { type: 'fillBlank', q: '___ help your body grow and repair.', answer: 'Proteins', accept: ['Proteins'] },
          { type: 'multiple', q: 'Which is a healthy fat?', options: ['Oil from olives', 'Butter', 'Lard', 'None of these'], answer: 0 },
          { type: 'trueFalse', q: 'Fiber helps with digestion.', answer: true },
          { type: 'fillBlank', q: 'Fruits and vegetables contain ___.', answer: 'vitamins', accept: ['vitamins', 'minerals'] },
          { type: 'multiple', q: 'What does vitamin C do?', options: ['Builds bones', 'Helps immune system', 'Gives energy', 'Helps digestion'], answer: 1 },
          { type: 'trueFalse', q: 'All food is bad for you.', answer: false },
          { type: 'fillBlank', q: '___ helps your bones grow strong.', answer: 'Calcium', accept: ['Calcium'] },
          { type: 'multiple', q: 'Which food has calcium?', options: ['Chocolate', 'Milk', 'Bread', 'Chicken'], answer: 1 },
          { type: 'trueFalse', q: 'Water is important for your body.', answer: true },
          { type: 'fillBlank', q: 'You should drink ___ glasses of water a day.', answer: '6-8', accept: ['6-8', '6', '8', 'six to eight'] },
          { type: 'multiple', q: 'Which is a healthy snack?', options: ['Candy', 'Crisps', 'Apple', 'Cake'], answer: 2 },
          { type: 'trueFalse', q: 'Sugar gives you quick energy but can cause health problems.', answer: true },
          { type: 'fillBlank', q: 'Iron helps carry ___ in your blood.', answer: 'oxygen', accept: ['oxygen'] },
          { type: 'multiple', q: 'Which food contains iron?', options: ['Spinach', 'Cake', 'Crisps', 'Sweets'], answer: 0 },
          { type: 'trueFalse', q: 'You should eat mainly whole grains.', answer: true },
          { type: 'fillBlank', q: 'Too much ___ can cause health problems.', answer: 'salt', accept: ['salt', 'sugar'] },
          { type: 'multiple', q: 'What is a food pyramid?', options: ['A building', 'A guide for healthy eating', 'A type of food', 'A restaurant'], answer: 1 },
          { type: 'trueFalse', q: 'Breakfast is an important meal.', answer: true },
          { type: 'fillBlank', q: 'A balanced plate includes vegetables, protein, and ___', answer: 'carbohydrates', accept: ['carbohydrates', 'grains'] },
          { type: 'multiple', q: 'How many food groups are there?', options: ['3', '4', '5', '6'], answer: 2 }
        ]
      },
      {
        name: 'Scientific Investigation',
        questions: [
          { type: 'multiple', q: 'What is the first step in a fair test?', options: ['Conclude', 'Ask a question', 'Record data', 'Predict'], answer: 1 },
          { type: 'trueFalse', q: 'A prediction is a guess based on what you know.', answer: true },
          { type: 'fillBlank', q: 'A ___ variable is the thing you change in an experiment.', answer: 'independent', accept: ['independent'] },
          { type: 'multiple', q: 'What is a dependent variable?', options: ['The variable you change', 'The variable you measure', 'The variable you ignore', 'All variables'], answer: 1 },
          { type: 'trueFalse', q: 'A control variable is kept the same.', answer: true },
          { type: 'fillBlank', q: 'A ___ test has only one thing that changes.', answer: 'fair', accept: ['fair'] },
          { type: 'multiple', q: 'Why do we repeat experiments?', options: ['For fun', 'To check our work', 'To change results', 'Not necessary'], answer: 1 },
          { type: 'trueFalse', q: 'Data should be recorded carefully.', answer: true },
          { type: 'fillBlank', q: 'A ___ helps organize experimental data.', answer: 'table', accept: ['table', 'chart'] },
          { type: 'multiple', q: 'What should an experiment have?', options: ['A question', 'A prediction', 'Fair test conditions', 'All of these'], answer: 3 },
          { type: 'trueFalse', q: 'You can change more than one variable at a time in a fair test.', answer: false },
          { type: 'fillBlank', q: 'A ___ is used to measure length.', answer: 'ruler', accept: ['ruler'] },
          { type: 'multiple', q: 'How should you record observations?', options: ['In your head', 'In writing', 'On video', 'a and b'], answer: 3 },
          { type: 'trueFalse', q: 'A graph can show experimental results clearly.', answer: true },
          { type: 'fillBlank', q: 'To make a fair test, everything except the ___ should stay the same.', answer: 'independent variable', accept: ['independent variable', 'variable'] },
          { type: 'multiple', q: 'What is a conclusion?', options: ['A guess', 'A summary of what you learned', 'The start of the experiment', 'The data'], answer: 1 },
          { type: 'trueFalse', q: 'You should record unexpected results.', answer: true },
          { type: 'fillBlank', q: 'A thermometer measures ___', answer: 'temperature', accept: ['temperature'] },
          { type: 'multiple', q: 'Why is it important to have a fair test?', options: ['To be safe', 'To get reliable results', 'To save time', 'To use less equipment'], answer: 1 },
          { type: 'trueFalse', q: 'Scientists repeat experiments to check their results.', answer: true },
          { type: 'fillBlank', q: 'An experiment should answer your ___', answer: 'question', accept: ['question'] },
          { type: 'multiple', q: 'What tool measures volume?', options: ['Ruler', 'Scale', 'Measuring cylinder', 'Thermometer'], answer: 2 }
        ]
      }
    ]
  },
  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#E91E63',
    lessons: [
      {
        name: 'Self Introduction',
        questions: [
          { type: 'multiple', q: 'How do you say "My name is..." in French?', options: ['Je suis', 'Je m\'appelle', 'Mon nom', 'Je habite'], answer: 1 },
          { type: 'trueFalse', q: '"Je m\'appelle Jean" means my name is Jean.', answer: true },
          { type: 'fillBlank', q: '"Je m\'appelle ___" completes: My name is Sophie.', answer: 'Sophie', accept: ['Sophie'] },
          { type: 'multiple', q: 'What does "j\'ai" mean?', options: ['You have', 'I am', 'I have', 'He has'], answer: 2 },
          { type: 'trueFalse', q: '"J\'ai 8 ans" means I am 8 years old.', answer: true },
          { type: 'fillBlank', q: 'Complete: J\'ai ___ ans. (I am 7 years old)', answer: '7', accept: ['7', 'sept'] },
          { type: 'multiple', q: 'How do you say "I live" in French?', options: ['Je suis', 'Je habite', 'J\'habite', 'Je vis'], answer: 2 },
          { type: 'trueFalse', q: '"J\'habite à Paris" means I live in Paris.', answer: true },
          { type: 'fillBlank', q: '"J\'habite à ___" - where do you live?', answer: 'London', accept: ['London', 'Londres', 'l\'école'] },
          { type: 'multiple', q: 'What is the correct way to introduce yourself?', options: ['Je m\'appelle... et j\'ai... ans', 'Je suis heureux', 'Je joue', 'Je regarde'], answer: 0 },
          { type: 'trueFalse', q: 'In French, you say your age using "avoir" (to have).', answer: true },
          { type: 'fillBlank', q: '"Enchantée" means ___ (female greeting)', answer: 'pleased to meet you', accept: ['pleased', 'nice to meet you'] },
          { type: 'multiple', q: 'How do you say "How old are you?"', options: ['Quel est ton nom?', 'Quel âge as-tu?', 'Tu habites où?', 'C\'est qui?'], answer: 1 },
          { type: 'trueFalse', q: '"Tu t\'appelles quoi?" means What is your name?', answer: true },
          { type: 'fillBlank', q: 'Complete the response: "Je m\'appelle ___"', answer: 'Your name', accept: ['Your name', 'your name'] },
          { type: 'multiple', q: 'What do you say when introducing yourself to a friend?', options: ['Bonjour Madame', 'Salut!', 'Au revoir!', 'S\'il vous plaît'], answer: 1 },
          { type: 'trueFalse', q: '"J\'habite à l\'école" means I live at school.', answer: true },
          { type: 'fillBlank', q: '"Je m\'appelle" requires a ___ after it.', answer: 'name', accept: ['name', 'noun'] },
          { type: 'multiple', q: 'What is the French for "I am happy"?', options: ['Je suis heureux', 'Je suis fatigué', 'Je suis petit', 'Je suis grand'], answer: 0 },
          { type: 'trueFalse', q: 'You would say "J\'ai faim" to say you are hungry.', answer: true },
          { type: 'fillBlank', q: 'Complete: "J\'ai ___ ans" - I am 10 years old.', answer: '10', accept: ['10', 'dix'] },
          { type: 'multiple', q: 'How would you ask "Where do you live?"', options: ['Tu habites où?', 'Où habites-tu?', 'Où tu habites?', 'All correct'], answer: 3 }
        ]
      },
      {
        name: 'Numbers 1-50',
        questions: [
          { type: 'fillBlank', q: 'How do you count 1? ___', answer: 'un', accept: ['un', '1', 'one'] },
          { type: 'multiple', q: 'What is 2 in French?', options: ['Un', 'Deux', 'Trois', 'Quatre'], answer: 1 },
          { type: 'trueFalse', q: '"Cinq" means 5.', answer: true },
          { type: 'fillBlank', q: '10 = ___', answer: 'dix', accept: ['dix'] },
          { type: 'multiple', q: 'What is 15 in French?', options: ['Douze', 'Treize', 'Quinze', 'Seize'], answer: 2 },
          { type: 'trueFalse', q: '"Dix-neuf" means 19.', answer: true },
          { type: 'fillBlank', q: '20 = ___', answer: 'vingt', accept: ['vingt'] },
          { type: 'multiple', q: 'How do you say 21 in French?', options: ['Vingt-un', 'Vingt-deux', 'Vingt et un', 'Vingt-dix'], answer: 2 },
          { type: 'trueFalse', q: '"Trente" means 30.', answer: true },
          { type: 'fillBlank', q: '25 = ___', answer: 'vingt-cinq', accept: ['vingt-cinq', 'vingtcinq'] },
          { type: 'multiple', q: 'What is 40 in French?', options: ['Trente', 'Quarante', 'Cinquante', 'Soixante'], answer: 1 },
          { type: 'trueFalse', q: '"Quarante-deux" means 42.', answer: true },
          { type: 'fillBlank', q: '50 = ___', answer: 'cinquante', accept: ['cinquante'] },
          { type: 'multiple', q: 'Count in French: 8, 9, 10:', options: ['Huit, Neuf, Dix', 'Sept, Huit, Neuf', 'Six, Sept, Huit', 'Neuf, Dix, Onze'], answer: 0 },
          { type: 'trueFalse', q: '"Onze" means 11.', answer: true },
          { type: 'fillBlank', q: '13 = ___', answer: 'treize', accept: ['treize'] },
          { type: 'multiple', q: 'What comes after "Quarante"?', options: ['Quarante-un', 'Cinquante', 'Quarante-dix', 'Trente'], answer: 0 },
          { type: 'trueFalse', q: '"Seize" means 16.', answer: true },
          { type: 'fillBlank', q: '35 = ___', answer: 'trente-cinq', accept: ['trente-cinq'] },
          { type: 'multiple', q: 'How many are there from 1 to 10?', options: ['8', '9', '10', '11'], answer: 2 },
          { type: 'trueFalse', q: 'Numbers from 21-99 in French use "et" (and) for 21, 31, 41 etc.', answer: true },
          { type: 'fillBlank', q: '44 = ___', answer: 'quarante-quatre', accept: ['quarante-quatre'] }
        ]
      },
      {
        name: 'Body Parts',
        questions: [
          { type: 'multiple', q: 'What is "head" in French?', options: ['La tête', 'Le corps', 'Le cou', 'Les cheveux'], answer: 0 },
          { type: 'trueFalse', q: '"Les yeux" means the eyes.', answer: true },
          { type: 'fillBlank', q: 'The mouth in French is ___', answer: 'la bouche', accept: ['la bouche', 'bouche'] },
          { type: 'multiple', q: 'What is the nose?', options: ['L\'oreille', 'Le nez', 'Les lèvres', 'Le doigt'], answer: 1 },
          { type: 'trueFalse', q: '"L\'oreille" means the ear.', answer: true },
          { type: 'fillBlank', q: 'The hair is ___', answer: 'les cheveux', accept: ['les cheveux', 'cheveux'] },
          { type: 'multiple', q: 'What is "arm" in French?', options: ['La jambe', 'Le bras', 'La main', 'Le pied'], answer: 1 },
          { type: 'trueFalse', q: '"La jambe" is the leg.', answer: true },
          { type: 'fillBlank', q: 'The hand is ___', answer: 'la main', accept: ['la main', 'main'] },
          { type: 'multiple', q: 'What is the tooth?', options: ['La dent', 'La bouche', 'La langue', 'Les lèvres'], answer: 0 },
          { type: 'trueFalse', q: '"Les dents" means the teeth.', answer: true },
          { type: 'fillBlank', q: 'The tongue is ___', answer: 'la langue', accept: ['la langue', 'langue'] },
          { type: 'multiple', q: 'What is the foot?', options: ['Le pied', 'La cheville', 'Les orteils', 'La jambe'], answer: 0 },
          { type: 'trueFalse', q: '"Le coeur" means the heart.', answer: true },
          { type: 'fillBlank', q: 'The back is ___', answer: 'le dos', accept: ['le dos', 'dos'] },
          { type: 'multiple', q: 'What is the body?', options: ['La tête', 'Le corps', 'Les mains', 'Les pieds'], answer: 1 },
          { type: 'trueFalse', q: '"L\'estomac" means the stomach.', answer: true },
          { type: 'fillBlank', q: 'The finger is ___', answer: 'le doigt', accept: ['le doigt', 'doigt'] },
          { type: 'multiple', q: 'What is the knee?', options: ['Le genou', 'La cheville', 'Le talon', 'L\'orteil'], answer: 0 },
          { type: 'trueFalse', q: '"Le cou" is the neck.', answer: true },
          { type: 'fillBlank', q: 'The skin is ___', answer: 'la peau', accept: ['la peau', 'peau'] },
          { type: 'multiple', q: 'What is the chin?', options: ['Le menton', 'Le front', 'Les joues', 'Le nez'], answer: 0 }
        ]
      },
      {
        name: 'Clothes',
        questions: [
          { type: 'multiple', q: 'What is "trousers" in French?', options: ['La jupe', 'Le pantalon', 'La robe', 'Le gilet'], answer: 1 },
          { type: 'trueFalse', q: '"La chemise" means the shirt.', answer: true },
          { type: 'fillBlank', q: 'A skirt is ___', answer: 'la jupe', accept: ['la jupe', 'jupe'] },
          { type: 'multiple', q: 'What are shoes?', options: ['Les chaussettes', 'Les chaussures', 'Les bottes', 'Les sandales'], answer: 1 },
          { type: 'trueFalse', q: '"Le chapeau" means the hat.', answer: true },
          { type: 'fillBlank', q: 'A coat is ___', answer: 'le manteau', accept: ['le manteau', 'manteau'] },
          { type: 'multiple', q: 'What is a dress?', options: ['Le pantalon', 'La robe', 'La jupe', 'Le costume'], answer: 1 },
          { type: 'trueFalse', q: '"Les chaussettes" means socks.', answer: true },
          { type: 'fillBlank', q: 'A sweater is ___', answer: 'un pull', accept: ['un pull', 'pull'] },
          { type: 'multiple', q: 'What is a tie?', options: ['Le noeud', 'La cravate', 'L\'écharpe', 'Le gilet'], answer: 1 },
          { type: 'trueFalse', q: '"Un gilet" means a vest or waistcoat.', answer: true },
          { type: 'fillBlank', q: 'Gloves are ___', answer: 'les gants', accept: ['les gants', 'gants'] },
          { type: 'multiple', q: 'What is a scarf?', options: ['Un chapeau', 'Une écharpe', 'Des gants', 'Une robe'], answer: 1 },
          { type: 'trueFalse', q: '"Le costume" means the suit.', answer: true },
          { type: 'fillBlank', q: 'A T-shirt is ___', answer: 'un t-shirt', accept: ['un t-shirt', 't-shirt'] },
          { type: 'multiple', q: 'What are boots?', options: ['Les chaussures', 'Les bottes', 'Les sandales', 'Les pantoufles'], answer: 1 },
          { type: 'trueFalse', q: '"Les chaussures" means shoes.', answer: true },
          { type: 'fillBlank', q: 'A belt is ___', answer: 'une ceinture', accept: ['une ceinture', 'ceinture'] },
          { type: 'multiple', q: 'What is shorts?', options: ['Le pantalon', 'Le short', 'La jupe', 'La robe'], answer: 1 },
          { type: 'trueFalse', q: '"Une robe" is a dress.', answer: true },
          { type: 'fillBlank', q: 'Socks are ___', answer: 'les chaussettes', accept: ['les chaussettes', 'chaussettes'] },
          { type: 'multiple', q: 'What is a jacket?', options: ['Un gilet', 'Une veste', 'Un manteau', 'Un costume'], answer: 1 }
        ]
      },
      {
        name: 'Weather',
        questions: [
          { type: 'multiple', q: 'How do you say "the weather is good" in French?', options: ['Il fait froid', 'Il fait beau', 'Il pleut', 'Il neige'], answer: 1 },
          { type: 'trueFalse', q: '"Il pleut" means it is raining.', answer: true },
          { type: 'fillBlank', q: 'It is snowing: ___', answer: 'Il neige', accept: ['Il neige', 'neige'] },
          { type: 'multiple', q: 'What does "Il fait froid" mean?', options: ['It\'s hot', 'It\'s cold', 'It\'s windy', 'It\'s foggy'], answer: 1 },
          { type: 'trueFalse', q: '"Il fait chaud" means it is hot.', answer: true },
          { type: 'fillBlank', q: 'It is sunny: ___', answer: 'Il fait du soleil', accept: ['Il fait du soleil', 'soleil'] },
          { type: 'multiple', q: 'How do you say "It is cloudy"?', options: ['Il pleut', 'Il neige', 'Il y a des nuages', 'Il gèle'], answer: 2 },
          { type: 'trueFalse', q: '"Il y a du vent" means it is windy.', answer: true },
          { type: 'fillBlank', q: 'It is foggy: ___', answer: 'Il y a du brouillard', accept: ['Il y a du brouillard', 'brouillard'] },
          { type: 'multiple', q: 'What does "Il gèle" mean?', options: ['It\'s raining', 'It\'s snowing', 'It\'s freezing', 'It\'s thundering'], answer: 2 },
          { type: 'trueFalse', q: '"Il fait mauvais" means the weather is bad.', answer: true },
          { type: 'fillBlank', q: 'What\'s the weather like?: ___', answer: 'Quel temps fait-il', accept: ['Quel temps', 'Quel est le temps'] },
          { type: 'multiple', q: 'How do you describe the weather?', options: ['Je suis', 'Il fait', 'C\'est', 'a and b'], answer: 3 },
          { type: 'trueFalse', q: '"L\'orage" means thunder.', answer: true },
          { type: 'fillBlank', q: 'The weather is nice: ___', answer: 'Il fait beau', accept: ['Il fait beau', 'beau'] },
          { type: 'multiple', q: 'What is "thunder"?', options: ['Le vent', 'L\'orage', 'L\'éclair', 'La pluie'], answer: 1 },
          { type: 'trueFalse', q: '"L\'éclair" means lightning.', answer: true },
          { type: 'fillBlank', q: 'It is raining: ___', answer: 'Il pleut', accept: ['Il pleut', 'pleut'] },
          { type: 'multiple', q: 'Which weather word is an adjective?', options: ['Pluie', 'Neige', 'Beau', 'Froid'], answer: 2 },
          { type: 'trueFalse', q: '"La température" means temperature.', answer: true },
          { type: 'fillBlank', q: 'It is warm: ___', answer: 'Il fait doux', accept: ['Il fait doux', 'doux'] },
          { type: 'multiple', q: 'What does "Il y a de la pluie" mean?', options: ['It\'s raining', 'It\'s snowing', 'It\'s windy', 'It\'s hot'], answer: 0 }
        ]
      },
      {
        name: 'Months & Seasons',
        questions: [
          { type: 'fillBlank', q: 'January is ___', answer: 'janvier', accept: ['janvier'] },
          { type: 'multiple', q: 'What is February in French?', options: ['Janvier', 'Février', 'Mars', 'Avril'], answer: 1 },
          { type: 'trueFalse', q: '"Mars" means March.', answer: true },
          { type: 'fillBlank', q: 'April is ___', answer: 'avril', accept: ['avril'] },
          { type: 'multiple', q: 'What is the 5th month?', options: ['Avril', 'Mai', 'Juin', 'Juillet'], answer: 1 },
          { type: 'trueFalse', q: '"Juin" means June.', answer: true },
          { type: 'fillBlank', q: 'July is ___', answer: 'juillet', accept: ['juillet'] },
          { type: 'multiple', q: 'What is August in French?', options: ['Juillet', 'Août', 'Septembre', 'Octobre'], answer: 1 },
          { type: 'trueFalse', q: '"Septembre" means September.', answer: true },
          { type: 'fillBlank', q: 'October is ___', answer: 'octobre', accept: ['octobre'] },
          { type: 'multiple', q: 'What is November?', options: ['Octobre', 'Novembre', 'Décembre', 'Janvier'], answer: 1 },
          { type: 'trueFalse', q: '"Décembre" is December.', answer: true },
          { type: 'fillBlank', q: 'Spring is ___', answer: 'le printemps', accept: ['le printemps', 'printemps'] },
          { type: 'multiple', q: 'What is summer in French?', options: ['L\'printemps', 'L\'été', 'L\'automne', 'L\'hiver'], answer: 1 },
          { type: 'trueFalse', q: '"L\'automne" means autumn.', answer: true },
          { type: 'fillBlank', q: 'Winter is ___', answer: 'l\'hiver', accept: ['l\'hiver', 'hiver'] },
          { type: 'multiple', q: 'Which season has the shortest days?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], answer: 3 },
          { type: 'trueFalse', q: 'In France, the seasons are the same as in the UK.', answer: true },
          { type: 'fillBlank', q: 'May is ___', answer: 'mai', accept: ['mai'] },
          { type: 'multiple', q: 'When is Christmas?', options: ['Novembre', 'Décembre', 'Janvier', 'Février'], answer: 1 },
          { type: 'trueFalse', q: '"Le mois" means the month.', answer: true },
          { type: 'fillBlank', q: 'The season is ___', answer: 'la saison', accept: ['la saison', 'saison'] }
        ]
      },
      {
        name: 'Hobbies & Sports',
        questions: [
          { type: 'multiple', q: 'What is "football" in French?', options: ['Le rugby', 'Le football', 'Le tennis', 'Le basketball'], answer: 1 },
          { type: 'trueFalse', q: '"La natation" means swimming.', answer: true },
          { type: 'fillBlank', q: 'Tennis is ___', answer: 'le tennis', accept: ['le tennis', 'tennis'] },
          { type: 'multiple', q: 'What is cycling?', options: ['La natation', 'Le cyclisme', 'L\'équitation', 'La danse'], answer: 1 },
          { type: 'trueFalse', q: '"J\'aime" means I like.', answer: true },
          { type: 'fillBlank', q: 'I do not like: ___', answer: 'Je n\'aime pas', accept: ['Je n\'aime pas'] },
          { type: 'multiple', q: 'How do you say "I love football"?', options: ['J\'aime le football', 'J\'adore le football', 'Je joue au football', 'Both a and b'], answer: 3 },
          { type: 'trueFalse', q: '"Je n\'aime pas" means I don\'t like.', answer: true },
          { type: 'fillBlank', q: 'I like: ___', answer: 'J\'aime', accept: ['J\'aime'] },
          { type: 'multiple', q: 'What is "badminton"?', options: ['Le badminton', 'Le hockey', 'Le squash', 'Le golf'], answer: 0 },
          { type: 'trueFalse', q: '"L\'équitation" is horse-riding.', answer: true },
          { type: 'fillBlank', q: 'Basketball is ___', answer: 'le basketball', accept: ['le basketball', 'basketball'] },
          { type: 'multiple', q: 'What is dancing?', options: ['Le sport', 'La musique', 'La danse', 'L\'art'], answer: 2 },
          { type: 'trueFalse', q: '"Je joue au football" means I play football.', answer: true },
          { type: 'fillBlank', q: 'Drawing is ___', answer: 'le dessin', accept: ['le dessin', 'dessin'] },
          { type: 'multiple', q: 'What is reading?', options: ['L\'écriture', 'La lecture', 'La musique', 'L\'art'], answer: 1 },
          { type: 'trueFalse', q: '"J\'adore" means I love.', answer: true },
          { type: 'fillBlank', q: 'Hockey is ___', answer: 'le hockey', accept: ['le hockey', 'hockey'] },
          { type: 'multiple', q: 'What sport uses a ball and racket?', options: ['Le football', 'Le tennis', 'La natation', 'L\'équitation'], answer: 1 },
          { type: 'trueFalse', q: '"La musique" is music.', answer: true },
          { type: 'fillBlank', q: 'Singing is ___', answer: 'la chanson', accept: ['la chanson', 'chanson'] },
          { type: 'multiple', q: 'What is rugby?', options: ['Un ballon', 'Le rugby', 'Le tennis', 'Le golf'], answer: 1 }
        ]
      },
      {
        name: 'Food Opinions',
        questions: [
          { type: 'multiple', q: 'What does "J\'aime le chocolat" mean?', options: ['I dislike chocolate', 'I like chocolate', 'I eat chocolate', 'I love chocolate very much'], answer: 1 },
          { type: 'trueFalse', q: '"Je déteste" means I hate.', answer: true },
          { type: 'fillBlank', q: 'I hate vegetables: ___', answer: 'Je déteste les légumes', accept: ['Je déteste les légumes'] },
          { type: 'multiple', q: 'What does "C\'est délicieux" mean?', options: ['It\'s disgusting', 'It\'s delicious', 'It\'s okay', 'It\'s cold'], answer: 1 },
          { type: 'trueFalse', q: '"C\'est bon" means it is good.', answer: true },
          { type: 'fillBlank', q: 'It is tasty: ___', answer: 'C\'est savoureux', accept: ['C\'est savoureux', 'savoureux'] },
          { type: 'multiple', q: 'What is "bad tasting"?', options: ['Délicieux', 'Bon', 'Mauvais', 'Savoureux'], answer: 2 },
          { type: 'trueFalse', q: '"J\'adore la pizza" means I love pizza.', answer: true },
          { type: 'fillBlank', q: 'I like bread: ___', answer: 'J\'aime le pain', accept: ['J\'aime le pain'] },
          { type: 'multiple', q: 'What is milk in French?', options: ['L\'eau', 'Le lait', 'Le jus', 'Le café'], answer: 1 },
          { type: 'trueFalse', q: '"Le fromage" is cheese.', answer: true },
          { type: 'fillBlank', q: 'I like cheese: ___', answer: 'J\'aime le fromage', accept: ['J\'aime le fromage'] },
          { type: 'multiple', q: 'What is juice?', options: ['L\'eau', 'Le jus', 'Le lait', 'Le café'], answer: 1 },
          { type: 'trueFalse', q: '"La pomme" is an apple.', answer: true },
          { type: 'fillBlank', q: 'I like fruit: ___', answer: 'J\'aime les fruits', accept: ['J\'aime les fruits'] },
          { type: 'multiple', q: 'What does "Je n\'aime pas la glace" mean?', options: ['I like ice cream', 'I don\'t like ice cream', 'I love ice cream', 'Ice cream is cold'], answer: 1 },
          { type: 'trueFalse', q: '"Le poulet" is chicken.', answer: true },
          { type: 'fillBlank', q: 'Bread is ___', answer: 'le pain', accept: ['le pain', 'pain'] },
          { type: 'multiple', q: 'What is an egg?', options: ['Un oeuf', 'Une pomme', 'Un tomate', 'Un carotte'], answer: 0 },
          { type: 'trueFalse', q: '"C\'est horrible" means it is horrible.', answer: true },
          { type: 'fillBlank', q: 'I don\'t like fish: ___', answer: 'Je n\'aime pas le poisson', accept: ['Je n\'aime pas le poisson'] },
          { type: 'multiple', q: 'What is "rice"?', options: ['Le riz', 'Les pâtes', 'Le pain', 'La pomme'], answer: 0 }
        ]
      }
    ]
  }
};
