window.YEAR_4_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        id: 'y4-maths-1',
        name: 'Place Value to 10,000',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How many digits does 10,000 have?', opts: ['3', '4', '5', '6'], ans: '5' },
          { id: 'q2', type: 'trueFalse', q: 'In 5,432, the 5 represents 5 thousands.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '7,329 = 7 thousands + ___ hundreds + 2 tens + 9 ones.', answer: '3', accept: ['3', 'three'] },
          { id: 'q4', type: 'multiple', q: 'What is the value of 8 in 8,764?', opts: ['8', '80', '800', '8000'], ans: '8000' },
          { id: 'q5', type: 'trueFalse', q: '1,999 is less than 2,001.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Round 4,567 to the nearest 10: ___', answer: '4570', accept: ['4570'] },
          { id: 'q7', type: 'multiple', q: 'Round 3,456 to the nearest 100.', opts: ['3400', '3450', '3500', '3600'], ans: '3500' },
          { id: 'q8', type: 'trueFalse', q: 'Round 5,678 to the nearest 1000 = 6,000.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'The Roman numeral for 50 is ___', answer: 'L', accept: ['L', 'l'] },
          { id: 'q10', type: 'multiple', q: 'What is the Roman numeral for 100?', opts: ['C', 'D', 'L', 'X'], ans: 'C' },
          { id: 'q11', type: 'trueFalse', q: 'V represents 5 in Roman numerals.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'The number 49 in Roman numerals is ___', answer: 'XLIX', accept: ['XLIX', 'xlix'] },
          { id: 'q13', type: 'multiple', q: 'What does XL mean in Roman numerals?', opts: ['40', '50', '60', '70'], ans: '40' },
          { id: 'q14', type: 'trueFalse', q: 'IX means 9 in Roman numerals.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The number 2,000 is written as ___ in Roman numerals.', answer: 'MM', accept: ['MM', 'mm'] },
          { id: 'q16', type: 'multiple', q: 'Compare: 6,789 ___ 6,879', opts: ['is greater than', 'is less than', 'is equal to', 'cannot compare'], ans: 'is less than' },
          { id: 'q17', type: 'trueFalse', q: '9,999 is the largest 4-digit number.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'The smallest 5-digit number is ___', answer: '10000', accept: ['10000', '10,000'] },
          { id: 'q19', type: 'trueFalse', q: '3,050 + 1,000 = 4,050', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Round 1,234 to the nearest 1000: ___', answer: '1000', accept: ['1000', '1,000'] },
          { id: 'q21', type: 'multiple', q: 'What is 10 times 345?', opts: ['345', '3,450', '34,500', '345,000'], ans: '3,450' },
          { id: 'q22', type: 'trueFalse', q: 'In 7,080, there are zero hundreds.', ans: false }
        ]
      },
      {
        id: 'y4-maths-2',
        name: 'Addition & Subtraction',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is 2,345 + 1,234?', opts: ['3,479', '3,579', '3,679', '3,779'], ans: '3,579' },
          { id: 'q2', type: 'trueFalse', q: '5,678 - 2,345 = 3,333', ans: true },
          { id: 'q3', type: 'fillBlank', q: '4,567 + 3,221 = ___', answer: '7788', accept: ['7788', '7,788'] },
          { id: 'q4', type: 'multiple', q: 'Estimate 6,234 + 2,789 (to nearest 1000).', opts: ['8000', '9000', '10000', '11000'], ans: '9000' },
          { id: 'q5', type: 'trueFalse', q: 'Inverse operations: If 5,000 - 2,000 = 3,000, then 3,000 + 2,000 = 5,000.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '8,000 - 3,456 = ___', answer: '4544', accept: ['4544', '4,544'] },
          { id: 'q7', type: 'multiple', q: 'What is 7,890 + 1,110?', opts: ['8,900', '8,990', '9,000', '9,100'], ans: '9,000' },
          { id: 'q8', type: 'trueFalse', q: '9,999 - 1 = 9,998', ans: true },
          { id: 'q9', type: 'fillBlank', q: '6,543 + 2,457 = ___', answer: '9000', accept: ['9000', '9,000'] },
          { id: 'q10', type: 'multiple', q: 'If I add 100 to 4,555, what do I get?', opts: ['4,555', '4,556', '4,655', '5,555'], ans: '4,655' },
          { id: 'q11', type: 'trueFalse', q: '3,000 + 4,000 = 7,000', ans: true },
          { id: 'q12', type: 'fillBlank', q: '10,000 - 5,000 = ___', answer: '5000', accept: ['5000', '5,000'] },
          { id: 'q13', type: 'multiple', q: 'What is 1,234 + 5,678?', opts: ['6,812', '6,912', '7,012', '7,112'], ans: '6,912' },
          { id: 'q14', type: 'trueFalse', q: 'The order doesn\'t matter in addition: 2,000 + 3,000 = 3,000 + 2,000', ans: true },
          { id: 'q15', type: 'fillBlank', q: '7,777 - 3,333 = ___', answer: '4444', accept: ['4444', '4,444'] },
          { id: 'q16', type: 'multiple', q: 'Estimate 3,456 - 1,234 (to nearest 100).', opts: ['2100', '2200', '2300', '2400'], ans: '2200' },
          { id: 'q17', type: 'trueFalse', q: 'I have £5,000. I spend £2,456. I have £2,544 left.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'What number added to 2,000 gives 9,000? ___', answer: '7000', accept: ['7000', '7,000'] },
          { id: 'q19', type: 'trueFalse', q: '8,765 + 1,235 = 10,000', ans: true },
          { id: 'q20', type: 'fillBlank', q: '4,321 + 3,210 = ___', answer: '7531', accept: ['7531', '7,531'] },
          { id: 'q21', type: 'trueFalse', q: 'Column method is useful for adding larger numbers.', ans: true },
          { id: 'q22', type: 'fillBlank', q: '5,600 - 2,345 = ___', answer: '3255', accept: ['3255', '3,255'] }
        ]
      },
      {
        id: 'y4-maths-3',
        name: 'Multiplication & Division',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is 6 × 7?', opts: ['40', '42', '44', '48'], ans: '42' },
          { id: 'q2', type: 'trueFalse', q: 'The 12 times table: 12, 24, 36, 48, 60...', ans: true },
          { id: 'q3', type: 'fillBlank', q: '9 × 11 = ___', answer: '99', accept: ['99', 'ninety-nine'] },
          { id: 'q4', type: 'multiple', q: 'What is 8 × 9?', opts: ['70', '72', '74', '76'], ans: '72' },
          { id: 'q5', type: 'trueFalse', q: '48 ÷ 6 = 8', ans: true },
          { id: 'q6', type: 'fillBlank', q: '7 × 8 = ___', answer: '56', accept: ['56', 'fifty-six'] },
          { id: 'q7', type: 'multiple', q: 'Find the factor pairs of 24.', opts: ['1,24; 2,12; 3,8; 4,6', '2,12; 4,6', '1,24; 2,12', 'only 4,6'], ans: '1,24; 2,12; 3,8; 4,6' },
          { id: 'q8', type: 'trueFalse', q: '11 × 9 = 99', ans: true },
          { id: 'q9', type: 'fillBlank', q: '60 ÷ 12 = ___', answer: '5', accept: ['5', 'five'] },
          { id: 'q10', type: 'multiple', q: 'What is 7 × 12?', opts: ['84', '85', '86', '87'], ans: '84' },
          { id: 'q11', type: 'trueFalse', q: 'Factor pairs help us understand multiplication.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '6 × 6 = ___', answer: '36', accept: ['36', 'thirty-six'] },
          { id: 'q13', type: 'multiple', q: 'What factors make 36?', opts: ['1,36; 2,18; 3,12; 4,9; 6,6', '6,6 only', '1,36 only', '2,18; 3,12'], ans: '1,36; 2,18; 3,12; 4,9; 6,6' },
          { id: 'q14', type: 'trueFalse', q: '8 × 12 = 96', ans: true },
          { id: 'q15', type: 'fillBlank', q: '72 ÷ 8 = ___', answer: '9', accept: ['9', 'nine'] },
          { id: 'q16', type: 'multiple', q: 'What is 9 × 6?', opts: ['52', '54', '56', '58'], ans: '54' },
          { id: 'q17', type: 'trueFalse', q: '11 × 11 = 121', ans: true },
          { id: 'q18', type: 'fillBlank', q: '144 ÷ 12 = ___', answer: '12', accept: ['12', 'twelve'] },
          { id: 'q19', type: 'trueFalse', q: '10 × 10 = 100', ans: true },
          { id: 'q20', type: 'fillBlank', q: '2 × 7 × 3 = ___', answer: '42', accept: ['42', 'forty-two'] },
          { id: 'q21', type: 'multiple', q: 'What is the inverse of 6 × 8 = 48?', opts: ['48 ÷ 6 = 8', '48 ÷ 8 = 6', 'both of above', 'neither'], ans: 'both of above' },
          { id: 'q22', type: 'trueFalse', q: 'Prime numbers have exactly two factors: 1 and themselves.', ans: true }
        ]
      },
      {
        id: 'y4-maths-4',
        name: 'Fractions & Decimals',
        questions: [
          { id: 'q1', type: 'multiple', q: 'Are 2/4 and 1/2 equivalent?', opts: ['no', 'yes', 'sometimes', 'cannot tell'], ans: 'yes' },
          { id: 'q2', type: 'trueFalse', q: '3/4 = 6/8', ans: true },
          { id: 'q3', type: 'fillBlank', q: '1/4 + 2/4 = ___', answer: '3/4', accept: ['3/4', 'three-quarters'] },
          { id: 'q4', type: 'multiple', q: 'What is 3/4 + 1/4?', opts: ['1/4', '4/8', '1 whole', '5/8'], ans: '1 whole' },
          { id: 'q5', type: 'trueFalse', q: '5/10 = 1/2', ans: true },
          { id: 'q6', type: 'fillBlank', q: '4/5 - 2/5 = ___', answer: '2/5', accept: ['2/5', 'two-fifths'] },
          { id: 'q7', type: 'multiple', q: 'What is 0.5 as a fraction?', opts: ['1/4', '1/2', '1/3', '1/5'], ans: '1/2' },
          { id: 'q8', type: 'trueFalse', q: '0.1 = 1/10', ans: true },
          { id: 'q9', type: 'fillBlank', q: '0.25 = ___ fraction', answer: '1/4', accept: ['1/4', 'one-quarter'] },
          { id: 'q10', type: 'multiple', q: 'What is 3/10 as a decimal?', opts: ['0.3', '0.03', '0.30', 'both a and c'], ans: 'both a and c' },
          { id: 'q11', type: 'trueFalse', q: '0.75 = 75/100 = 3/4', ans: true },
          { id: 'q12', type: 'fillBlank', q: '2/3 + 1/3 = ___', answer: '1', accept: ['1', 'one', '1 whole'] },
          { id: 'q13', type: 'multiple', q: 'Which is larger: 2/5 or 3/5?', opts: ['2/5', '3/5', 'same', 'cannot tell'], ans: '3/5' },
          { id: 'q14', type: 'trueFalse', q: '1/4 is less than 1/2.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '0.5 + 0.25 = ___', answer: '0.75', accept: ['0.75'] },
          { id: 'q16', type: 'multiple', q: 'What is 1/2 of 16?', opts: ['6', '8', '10', '12'], ans: '8' },
          { id: 'q17', type: 'trueFalse', q: '0.01 = 1/100', ans: true },
          { id: 'q18', type: 'fillBlank', q: '50/100 = ___', answer: '1/2', accept: ['1/2', '0.5'] },
          { id: 'q19', type: 'trueFalse', q: '1 - 1/4 = 3/4', ans: true },
          { id: 'q20', type: 'fillBlank', q: '0.1 + 0.2 = ___', answer: '0.3', accept: ['0.3'] },
          { id: 'q21', type: 'multiple', q: 'How many hundredths in 1?', opts: ['10', '50', '100', '1000'], ans: '100' },
          { id: 'q22', type: 'trueFalse', q: 'Tenths and hundredths use decimal places.', ans: true }
        ]
      },
      {
        id: 'y4-maths-5',
        name: 'Measurement',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is perimeter?', opts: ['area inside', 'distance around', 'length only', 'width only'], ans: 'distance around' },
          { id: 'q2', type: 'trueFalse', q: 'Perimeter is measured in square units.', ans: false },
          { id: 'q3', type: 'fillBlank', q: 'The perimeter of a rectangle with sides 5cm and 3cm is ___cm.', answer: '16', accept: ['16'] },
          { id: 'q4', type: 'multiple', q: 'What is area?', opts: ['the length', 'the perimeter', 'the space inside a shape', 'the height'], ans: 'the space inside a shape' },
          { id: 'q5', type: 'trueFalse', q: 'Area is measured in square units (cm²).', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'The area of a rectangle 4cm long and 3cm wide is ___cm².', answer: '12', accept: ['12'] },
          { id: 'q7', type: 'multiple', q: 'How many metres in 3 km?', opts: ['30', '300', '3000', '30000'], ans: '3000' },
          { id: 'q8', type: 'trueFalse', q: '1 kg = 1000 g', ans: true },
          { id: 'q9', type: 'fillBlank', q: '2500g = ___kg and ___g.', answer: '2.5', accept: ['2.5', '2 and 0.5', '2 half'] },
          { id: 'q10', type: 'multiple', q: 'Convert 5000ml to litres.', opts: ['0.5', '5', '50', '500'], ans: '5' },
          { id: 'q11', type: 'trueFalse', q: '1 litre = 1000 millilitres', ans: true },
          { id: 'q12', type: 'fillBlank', q: '3000m = ___km.', answer: '3', accept: ['3', 'three'] },
          { id: 'q13', type: 'multiple', q: 'How many centimetres in 5 metres?', opts: ['50', '500', '5000', '50000'], ans: '500' },
          { id: 'q14', type: 'trueFalse', q: '2 kg is heavier than 2500 grams.', ans: false },
          { id: 'q15', type: 'fillBlank', q: 'The perimeter of a square with sides 4cm is ___cm.', answer: '16', accept: ['16'] },
          { id: 'q16', type: 'multiple', q: 'What is the area of a square with 5cm sides?', opts: ['10 cm²', '20 cm²', '25 cm²', '30 cm²'], ans: '25 cm²' },
          { id: 'q17', type: 'trueFalse', q: '1 metre = 100 centimetres', ans: true },
          { id: 'q18', type: 'fillBlank', q: '3.5 litres = ___millilitres.', answer: '3500', accept: ['3500'] },
          { id: 'q19', type: 'trueFalse', q: 'We use m² for area measurements.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '1500g = ___kg.', answer: '1.5', accept: ['1.5'] },
          { id: 'q21', type: 'multiple', q: 'How many 100g weights equal 1kg?', opts: ['5', '10', '15', '20'], ans: '10' },
          { id: 'q22', type: 'trueFalse', q: 'Perimeter can be different even if area is the same.', ans: true }
        ]
      },
      {
        id: 'y4-maths-6',
        name: 'Time',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What time is 15:30 in 12-hour format?', opts: ['3:30am', '3:30pm', '1:30pm', '5:30pm'], ans: '3:30pm' },
          { id: 'q2', type: 'trueFalse', q: '20:00 in 24-hour time is 8pm.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '12-hour 7:15pm = 24-hour ___:___', answer: '19:15', accept: ['19:15'] },
          { id: 'q4', type: 'multiple', q: 'How many minutes between 2:15pm and 3:45pm?', opts: ['60', '75', '90', '105'], ans: '90' },
          { id: 'q5', type: 'trueFalse', q: 'A.M. means before noon.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'If a film starts at 19:00 and lasts 2 hours 30 minutes, it ends at ___:___', answer: '21:30', accept: ['21:30', '9:30pm'] },
          { id: 'q7', type: 'multiple', q: 'What is 12:00 noon in 24-hour time?', opts: ['00:00', '12:00', '24:00', '12:30'], ans: '12:00' },
          { id: 'q8', type: 'trueFalse', q: 'Midnight is 00:00 in 24-hour format.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'From 10:45am to 12:15pm is ___ minutes.', answer: '90', accept: ['90', 'one hour and thirty minutes'] },
          { id: 'q10', type: 'multiple', q: 'How many seconds in 5 minutes?', opts: ['300', '350', '400', '450'], ans: '300' },
          { id: 'q11', type: 'trueFalse', q: 'An analogue clock has a second hand.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '12-hour 2:30am = 24-hour 0___:___', answer: '02:30', accept: ['02:30'] },
          { id: 'q13', type: 'multiple', q: 'A journey takes 2 hours 45 minutes. If it starts at 14:20, when does it end?', opts: ['16:55', '17:05', '17:15', '17:25'], ans: '17:05' },
          { id: 'q14', type: 'trueFalse', q: 'P.M. means after noon.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'There are ___ minutes in a quarter hour.', answer: '15', accept: ['15'] },
          { id: 'q16', type: 'multiple', q: 'What time is 13:00 in 12-hour format?', opts: ['1:00am', '1:00pm', '3:00pm', '11:00pm'], ans: '1:00pm' },
          { id: 'q17', type: 'trueFalse', q: 'A digital clock displays time numerically.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'From 11:30am to 2:00pm is ___ hours ___ minutes.', answer: '2', accept: ['2', '2 hours 30 minutes'] },
          { id: 'q19', type: 'trueFalse', q: '23:59 is one minute before midnight.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '12-hour 11:45pm = 24-hour ___:___', answer: '23:45', accept: ['23:45'] },
          { id: 'q21', type: 'multiple', q: 'How many half-hours in 3 hours?', opts: ['3', '4', '5', '6'], ans: '6' },
          { id: 'q22', type: 'trueFalse', q: 'The hour hand moves faster than the minute hand.', ans: false }
        ]
      },
      {
        id: 'y4-maths-7',
        name: 'Shape & Angles',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How many sides does a quadrilateral have?', opts: ['3', '4', '5', '6'], ans: '4' },
          { id: 'q2', type: 'trueFalse', q: 'An isosceles triangle has two equal sides.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'An equilateral triangle has ___ equal sides.', answer: '3', accept: ['3', 'three'] },
          { id: 'q4', type: 'multiple', q: 'How many right angles does a rectangle have?', opts: ['0', '2', '4', '8'], ans: '4' },
          { id: 'q5', type: 'trueFalse', q: 'A square is a type of rectangle.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'A line of symmetry divides a shape into ___ halves.', answer: 'equal', accept: ['equal'] },
          { id: 'q7', type: 'multiple', q: 'How many lines of symmetry does a square have?', opts: ['1', '2', '4', '8'], ans: '4' },
          { id: 'q8', type: 'trueFalse', q: 'A circle has infinite lines of symmetry.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'How many lines of symmetry in a rectangle? ___', answer: '2', accept: ['2', 'two'] },
          { id: 'q10', type: 'multiple', q: 'What is a right angle?', opts: ['45°', '90°', '180°', '360°'], ans: '90°' },
          { id: 'q11', type: 'trueFalse', q: 'An acute angle is less than 90°.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'An obtuse angle is between ___° and ___°.', answer: '90', accept: ['90 and 180'] },
          { id: 'q13', type: 'multiple', q: 'How many degrees in a straight line?', opts: ['90', '180', '270', '360'], ans: '180' },
          { id: 'q14', type: 'trueFalse', q: 'A reflex angle is greater than 180°.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The total of angles in a triangle is ___°.', answer: '180', accept: ['180'] },
          { id: 'q16', type: 'multiple', q: 'How many degrees in a full rotation?', opts: ['90', '180', '270', '360'], ans: '360' },
          { id: 'q17', type: 'trueFalse', q: 'A scalene triangle has no equal sides.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'Perpendicular lines meet at a ___ angle.', answer: 'right', accept: ['right', '90'] },
          { id: 'q19', type: 'trueFalse', q: 'Parallel lines never meet.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A parallelogram has ___ pairs of parallel sides.', answer: '2', accept: ['2', 'two'] },
          { id: 'q21', type: 'multiple', q: 'Which shape has 1 line of symmetry?', opts: ['square', 'isosceles triangle', 'circle', 'rectangle'], ans: 'isosceles triangle' },
          { id: 'q22', type: 'trueFalse', q: 'A rhombus has 4 equal sides.', ans: true }
        ]
      },
      {
        id: 'y4-maths-8',
        name: 'Statistics',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What type of graph shows change over time?', opts: ['bar chart', 'line graph', 'pictogram', 'table'], ans: 'line graph' },
          { id: 'q2', type: 'trueFalse', q: 'A line graph connects points with lines.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'In statistics, the ___ is the middle value.', answer: 'median', accept: ['median'] },
          { id: 'q4', type: 'multiple', q: 'What is the mode in: 2, 5, 5, 5, 8?', opts: ['2', '5', '8', '5.5'], ans: '5' },
          { id: 'q5', type: 'trueFalse', q: 'The mean is the average of all values.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'The ___ is the difference between the highest and lowest values.', answer: 'range', accept: ['range'] },
          { id: 'q7', type: 'multiple', q: 'Find the mean of: 3, 5, 7', opts: ['4', '5', '6', '7'], ans: '5' },
          { id: 'q8', type: 'trueFalse', q: 'The mode is always useful for all types of data.', ans: false },
          { id: 'q9', type: 'fillBlank', q: 'The range of 2, 8, 12, 15 is ___', answer: '13', accept: ['13'] },
          { id: 'q10', type: 'multiple', q: 'Which best shows how a value changes over time?', opts: ['bar chart', 'time graph', 'pie chart', 'pictogram'], ans: 'time graph' },
          { id: 'q11', type: 'trueFalse', q: 'A pie chart shows parts of a whole.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'The median of 1, 3, 5, 7, 9 is ___', answer: '5', accept: ['5'] },
          { id: 'q13', type: 'multiple', q: 'Find the mean of: 10, 20, 30, 40', opts: ['20', '25', '30', '35'], ans: '25' },
          { id: 'q14', type: 'trueFalse', q: 'A bar graph uses vertical or horizontal bars.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The median of 2, 4, 6, 8 is ___', answer: '5', accept: ['5'] },
          { id: 'q16', type: 'multiple', q: 'What does the y-axis usually show?', opts: ['time', 'frequency or values', 'dates', 'names'], ans: 'frequency or values' },
          { id: 'q17', type: 'trueFalse', q: 'Data can be displayed in different ways.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A ___ uses rectangles to represent data.', answer: 'histogram', accept: ['histogram', 'bar chart'] },
          { id: 'q19', type: 'trueFalse', q: 'The range is always a single value.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'To find the mean, add all values and divide by the number of values: ___', answer: 'yes', accept: ['yes', 'correct'] },
          { id: 'q21', type: 'multiple', q: 'Which measure is most affected by extreme values?', opts: ['median', 'mode', 'mean', 'range'], ans: 'mean' },
          { id: 'q22', type: 'trueFalse', q: 'You can compare two sets of data using statistical measures.', ans: true }
        ]
      }
    ]
  },
  english: {
    name: 'English',
    icon: '📖',
    color: '#2196F3',
    lessons: [
      {
        id: 'y4-english-1',
        name: 'Prefixes',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does "in-" mean?', opts: ['again', 'not/opposite', 'before', 'under'], ans: 'not/opposite' },
          { id: 'q2', type: 'trueFalse', q: '"Incomplete" means not complete.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Immoral" means not ___', answer: 'moral', accept: ['moral'] },
          { id: 'q4', type: 'multiple', q: 'Which prefix means "before"?', opts: ['sub-', 'super-', 'pre-', 'anti-'], ans: 'pre-' },
          { id: 'q5', type: 'trueFalse', q: '"Submarine" means under the sea.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Superhero" means a very ___ hero.', answer: 'powerful', accept: ['powerful', 'strong'] },
          { id: 'q7', type: 'multiple', q: 'What does "anti-" mean?', opts: ['before', 'under', 'against', 'very'], ans: 'against' },
          { id: 'q8', type: 'trueFalse', q: '"Antibacterial" means against bacteria.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Automatic" means working on its own without ___.', answer: 'human', accept: ['human', 'manual control'] },
          { id: 'q10', type: 'multiple', q: 'Which word uses "im-"?', opts: ['insincere', 'incomplete', 'impossible', 'all of above'], ans: 'impossible' },
          { id: 'q11', type: 'trueFalse', q: '"Illogical" means not logical.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Irregular" means not ___.', answer: 'regular', accept: ['regular'] },
          { id: 'q13', type: 'multiple', q: 'What is the prefix in "submarine"?', opts: ['sub-', 'sub', '-sub', 'marine'], ans: 'sub-' },
          { id: 'q14', type: 'trueFalse', q: '"Superhero" uses the prefix "super-".', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"Predator" means ___ hunter.', answer: 'predatory', accept: ['predatory', 'hunting'] },
          { id: 'q16', type: 'multiple', q: 'Which is an "anti-" word?', opts: ['antique', 'anticipate', 'antisocial', 'antennae'], ans: 'antisocial' },
          { id: 'q17', type: 'trueFalse', q: '"Autopilot" means self-controlling.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Irresponsible" means not ___.', answer: 'responsible', accept: ['responsible'] },
          { id: 'q19', type: 'trueFalse', q: '"Immature" uses the prefix "im-".', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"Precaution" means care taken ___', answer: 'beforehand', accept: ['beforehand', 'before', 'in advance'] },
          { id: 'q21', type: 'multiple', q: 'Which prefix means "below" or "under"?', opts: ['super-', 'sub-', 'pre-', 'anti-'], ans: 'sub-' },
          { id: 'q22', type: 'trueFalse', q: 'Prefixes are added to the end of words.', ans: false }
        ]
      },
      {
        id: 'y4-english-2',
        name: 'Suffixes',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does "-ation" do to a word?', opts: ['makes it an adverb', 'makes it a noun', 'makes it an adjective', 'makes it a verb'], ans: 'makes it a noun' },
          { id: 'q2', type: 'trueFalse', q: '"Organisation" uses the suffix "-ation".', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Creation" comes from the verb "___".', answer: 'create', accept: ['create'] },
          { id: 'q4', type: 'multiple', q: 'What is the difference "-tion" and "-sion"?', opts: ['none', 'both make nouns', 'one is British', 'context determines usage'], ans: 'context determines usage' },
          { id: 'q5', type: 'trueFalse', q: '"Conclusion" uses "-sion".', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Television" comes from "___."', answer: 'televise', accept: ['televise'] },
          { id: 'q7', type: 'multiple', q: 'Which suffix makes an adjective?', opts: ['-ous', '-ment', '-ation', '-ly'], ans: '-ous' },
          { id: 'q8', type: 'trueFalse', q: '"Dangerous" means full of danger.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Monstrous" means ___', answer: 'like a monster', accept: ['like a monster', 'terrible', 'huge'] },
          { id: 'q10', type: 'multiple', q: 'What suffix means "full of"?', opts: ['-ous', '-less', '-ment', '-tion'], ans: '-ous' },
          { id: 'q11', type: 'trueFalse', q: '"-ly" is typically added to adjectives to make adverbs.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Silently" comes from the adjective "___".', answer: 'silent', accept: ['silent'] },
          { id: 'q13', type: 'multiple', q: 'Which suffix forms abstract nouns?', opts: ['-ment', '-ous', '-ly', '-able'], ans: '-ment' },
          { id: 'q14', type: 'trueFalse', q: '"Achievement" uses the suffix "-ment".', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"Amazement" means the state of being ___', answer: 'amazed', accept: ['amazed'] },
          { id: 'q16', type: 'multiple', q: 'What does "-able" mean?', opts: ['without', 'capable of', 'full of', 'state of'], ans: 'capable of' },
          { id: 'q17', type: 'trueFalse', q: '"Comfortable" means you can be comfortable.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Unreliable" means not ___', answer: 'reliable', accept: ['reliable'] },
          { id: 'q19', type: 'trueFalse', q: 'Suffixes often change a word\'s part of speech.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"Precious" uses the suffix "-___.', answer: 'ous', accept: ['ous'] },
          { id: 'q21', type: 'multiple', q: 'Which is a "-tion" word?', opts: ['television', 'transportation', 'both a and b', 'neither'], ans: 'both a and b' },
          { id: 'q22', type: 'trueFalse', q: 'Suffixes are added to the beginning of words.', ans: false }
        ]
      },
      {
        id: 'y4-english-3',
        name: 'Determiners & Pronouns',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a determiner?', opts: ['a verb', 'a word that specifies a noun', 'an adjective', 'an adverb'], ans: 'a word that specifies a noun' },
          { id: 'q2', type: 'trueFalse', q: '"The" is a definite article.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"A" and "an" are called ___ articles.', answer: 'indefinite', accept: ['indefinite'] },
          { id: 'q4', type: 'multiple', q: 'Which is a demonstrative pronoun?', opts: ['I', 'this', 'she', 'mine'], ans: 'this' },
          { id: 'q5', type: 'trueFalse', q: '"These" and "those" are demonstrative pronouns.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"He", "she", "it" are ___ pronouns.', answer: 'personal', accept: ['personal'] },
          { id: 'q7', type: 'multiple', q: 'What is a possessive pronoun?', opts: ['mine', 'me', 'my', 'I'], ans: 'mine' },
          { id: 'q8', type: 'trueFalse', q: '"My" is a possessive determiner, and "mine" is a possessive pronoun.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"You", "we", "they" are ___ pronouns.', answer: 'personal', accept: ['personal'] },
          { id: 'q10', type: 'multiple', q: 'Which is NOT a pronoun?', opts: ['he', 'yours', 'happy', 'those'], ans: 'happy' },
          { id: 'q11', type: 'trueFalse', q: '"Your" is a possessive determiner.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"His", "her", "its" are possessive ___.', answer: 'determiners', accept: ['determiners'] },
          { id: 'q13', type: 'multiple', q: 'What is a relative pronoun?', opts: ['which', 'who', 'that', 'all of above'], ans: 'all of above' },
          { id: 'q14', type: 'trueFalse', q: '"Who" introduces relative clauses.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"___ boy went to school" - choose "that", "this", or "those".', answer: 'that', accept: ['that', 'this'] },
          { id: 'q16', type: 'multiple', q: 'Which sentence is correct?', opts: ['The book is mine', 'The book is my', 'The book is me', 'The book is I'], ans: 'The book is mine' },
          { id: 'q17', type: 'trueFalse', q: 'Pronouns replace nouns.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"___ is your sister?" - use "who" or "whose".', answer: 'who', accept: ['who'] },
          { id: 'q19', type: 'trueFalse', q: '"Whose" shows possession.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'In "I saw the girl who runs fast," "who" is a ___ pronoun.', answer: 'relative', accept: ['relative'] },
          { id: 'q21', type: 'multiple', q: 'Which is a possessive pronoun?', opts: ['his', 'ours', 'your', 'their'], ans: 'ours' },
          { id: 'q22', type: 'trueFalse', q: 'Articles (the, a, an) are types of determiners.', ans: true }
        ]
      },
      {
        id: 'y4-english-4',
        name: 'Noun Phrases',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a noun phrase?', opts: ['a group of verbs', 'a noun and its modifiers', 'only a noun', 'a verb and noun'], ans: 'a noun and its modifiers' },
          { id: 'q2', type: 'trueFalse', q: 'Adjectives modify nouns.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'In "the big red house," "big" and "red" are ___', answer: 'adjectives', accept: ['adjectives'] },
          { id: 'q4', type: 'multiple', q: 'Which is an expanded noun phrase?', opts: ['cat', 'the cat', 'the big, fluffy cat', 'cats'], ans: 'the big, fluffy cat' },
          { id: 'q5', type: 'trueFalse', q: 'Noun phrases can start with "the".', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"The old, rusty gate" - "old" and "rusty" are ___', answer: 'adjectives', accept: ['adjectives'] },
          { id: 'q7', type: 'multiple', q: 'How many adjectives modify the noun in "the small, white dog"?', opts: ['1', '2', '3', '0'], ans: '2' },
          { id: 'q8', type: 'trueFalse', q: 'Prepositions can extend noun phrases.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"The girl in the red coat" contains a ___ phrase.', answer: 'prepositional', accept: ['prepositional', 'preposition'] },
          { id: 'q10', type: 'multiple', q: 'Which is NOT part of a noun phrase?', opts: ['adjective', 'article', 'verb', 'noun'], ans: 'verb' },
          { id: 'q11', type: 'trueFalse', q: 'Articles are always the first word in a noun phrase.', ans: false },
          { id: 'q12', type: 'fillBlank', q: '"The beautiful golden sunset" uses ___ adjectives to modify "sunset".', answer: '2', accept: ['2', 'two'] },
          { id: 'q13', type: 'multiple', q: 'In "a really tall building," "really" is an ___', opts: ['adjective', 'noun', 'adverb', 'verb'], ans: 'adverb' },
          { id: 'q14', type: 'trueFalse', q: 'Expanded noun phrases make writing more interesting.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The phrase "the dark, mysterious castle" has ___ adjectives.', answer: '2', accept: ['2', 'two'] },
          { id: 'q16', type: 'multiple', q: 'Which makes the noun phrase longer?', opts: ['removing adjectives', 'adding adjectives', 'changing the noun', 'removing articles'], ans: 'adding adjectives' },
          { id: 'q17', type: 'trueFalse', q: '"Big house" is a noun phrase.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'In "the yellow flowers in the garden," the prepositional phrase is "___"', answer: 'in the garden', accept: ['in the garden'] },
          { id: 'q19', type: 'trueFalse', q: 'Commas can separate adjectives in a noun phrase.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"The soft, smooth silk fabric" has ___ adjectives modifying the noun.', answer: '3', accept: ['3', 'three'] },
          { id: 'q21', type: 'multiple', q: 'What can improve a simple noun phrase?', opts: ['adding adjectives', 'using prepositional phrases', 'both a and b', 'removing words'], ans: 'both a and b' },
          { id: 'q22', type: 'trueFalse', q: 'Noun phrases can act as the subject of a sentence.', ans: true }
        ]
      },
      {
        id: 'y4-english-5',
        name: 'Fronted Adverbials',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a fronted adverbial?', opts: ['an adverb at the end', 'an adverbial at the start of a sentence', 'a verb at the start', 'never used'], ans: 'an adverbial at the start of a sentence' },
          { id: 'q2', type: 'trueFalse', q: 'Fronted adverbials are followed by a comma.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"___, the children came home late." Fill in a fronted adverbial.', answer: 'Unfortunately', accept: ['Unfortunately', 'Later', 'Suddenly'] },
          { id: 'q4', type: 'multiple', q: 'Which is a fronted adverbial?', opts: ['Happily running', 'Happily, she ran', 'She ran happily', 'Ran happily'], ans: 'Happily, she ran' },
          { id: 'q5', type: 'trueFalse', q: '"Beyond the hill, there was a village." Uses a fronted adverbial.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Before long, ___ will arrive." Complete the sentence.', answer: 'everyone', accept: ['everyone', 'the train', 'they'] },
          { id: 'q7', type: 'multiple', q: 'What type of word is "suddenly" in "Suddenly, it rained"?', opts: ['verb', 'noun', 'adverb', 'adjective'], ans: 'adverb' },
          { id: 'q8', type: 'trueFalse', q: '"During the night, owls hoot." - "during the night" is fronted.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"___, I realised the truth." Fill in a fronted adverbial.', answer: 'Gradually', accept: ['Gradually', 'Eventually', 'Finally', 'Suddenly'] },
          { id: 'q10', type: 'multiple', q: 'Why use fronted adverbials?', opts: ['no reason', 'to make writing more interesting', 'to confuse readers', 'they\'re required'], ans: 'to make writing more interesting' },
          { id: 'q11', type: 'trueFalse', q: 'Fronted adverbials always need a comma after them.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"In the morning, ___." Complete with a main clause.', answer: 'I woke up', accept: ['I woke up', 'the sun rose', 'birds sing'] },
          { id: 'q13', type: 'multiple', q: 'Which is correct?', opts: ['Carefully, the glass was placed', 'Carefully glass was placed', 'The glass, carefully, was placed', 'Glass carefully was placed'], ans: 'Carefully, the glass was placed' },
          { id: 'q14', type: 'trueFalse', q: '"After the film, we had ice cream." - "After the film" is fronted.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"___, we went to the park." Choose fronted adverbial: Yesterday/The park.', answer: 'Yesterday', accept: ['Yesterday'] },
          { id: 'q16', type: 'multiple', q: 'What follows a fronted adverbial?', opts: ['nothing', 'a comma', 'a full stop', 'a question mark'], ans: 'a comma' },
          { id: 'q17', type: 'trueFalse', q: 'Fronted adverbials are optional in writing.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"___ did the cat catch the mouse." (How quickly)_', answer: 'Quickly', accept: ['Quickly'] },
          { id: 'q19', type: 'trueFalse', q: '"Later on, the sun set." Uses a fronted adverbial.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"All day long, ___." Complete the sentence.', answer: 'it rained', accept: ['it rained', 'the party continued'] },
          { id: 'q21', type: 'multiple', q: 'Which example has a fronted adverbial?', opts: ['The sun rose early', 'Early, the sun rose', 'The early sun rose', 'The sun rose, early'], ans: 'Early, the sun rose' },
          { id: 'q22', type: 'trueFalse', q: 'Fronted adverbials add variety to sentence structure.', ans: true }
        ]
      },
      {
        id: 'y4-english-6',
        name: 'Paragraphs & Headings',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is the purpose of a heading?', opts: ['decorate', 'summarise the topic', 'fill space', 'confuse readers'], ans: 'summarise the topic' },
          { id: 'q2', type: 'trueFalse', q: 'Headings help readers quickly find information.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'A ___ is a mini-heading that organises sections.', answer: 'subheading', accept: ['subheading'] },
          { id: 'q4', type: 'multiple', q: 'How should a heading be formatted?', opts: ['same as body text', 'larger and bold', 'very small', 'any style'], ans: 'larger and bold' },
          { id: 'q5', type: 'trueFalse', q: 'Multiple paragraphs should each have a topic sentence.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Each paragraph should focus on ___ main idea.', answer: 'one', accept: ['one'] },
          { id: 'q7', type: 'multiple', q: 'What makes good paragraph organisation?', opts: ['random order', 'logical sequence', 'no plan', 'alphabetical'], ans: 'logical sequence' },
          { id: 'q8', type: 'trueFalse', q: 'Subheadings break up long text.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A ___ sentence should introduce the paragraph\'s idea.', answer: 'topic', accept: ['topic'] },
          { id: 'q10', type: 'multiple', q: 'Why use subheadings?', opts: ['decoration', 'to help readers navigate', 'no reason', 'to add length'], ans: 'to help readers navigate' },
          { id: 'q11', type: 'trueFalse', q: 'Paragraphs should be very long.', ans: false },
          { id: 'q12', type: 'fillBlank', q: 'A ___ sentence concludes the paragraph.', answer: 'closing', accept: ['closing', 'concluding'] },
          { id: 'q13', type: 'multiple', q: 'How should paragraphs be linked?', opts: ['no linking', 'use connecting words', 'don\'t repeat', 'separate completely'], ans: 'use connecting words' },
          { id: 'q14', type: 'trueFalse', q: 'Headings should match the content.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'Transition words like "First", "Next", "Finally" help ___ paragraphs.', answer: 'link', accept: ['link', 'connect'] },
          { id: 'q16', type: 'multiple', q: 'Which is a good heading style?', opts: ['too long', 'clear and brief', 'vague', 'question and answer'], ans: 'clear and brief' },
          { id: 'q17', type: 'trueFalse', q: 'Indenting shows the start of a new paragraph.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'Supporting ___ should explain the topic sentence.', answer: 'sentences', accept: ['sentences', 'details'] },
          { id: 'q19', type: 'trueFalse', q: 'All paragraphs in an essay should relate to the main topic.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A good heading tells the reader ___', answer: 'what\'s coming', accept: ['what\'s coming', 'the topic'] },
          { id: 'q21', type: 'multiple', q: 'How do you make text scannable?', opts: ['use small text', 'use headings and subheadings', 'no organisation', 'use only paragraphs'], ans: 'use headings and subheadings' },
          { id: 'q22', type: 'trueFalse', q: 'Consistent heading format makes text look professional.', ans: true }
        ]
      },
      {
        id: 'y4-english-7',
        name: 'Direct Speech',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What are speech marks used for?', opts: ['underlining', 'showing direct speech', 'indenting', 'numbering'], ans: 'showing direct speech' },
          { id: 'q2', type: 'trueFalse', q: 'Direct speech shows the exact words someone said.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"___I am happy.___ said Emma." Add speech marks.', answer: '"I am happy."', accept: ['"I am happy."'] },
          { id: 'q4', type: 'multiple', q: 'Where does the punctuation go inside speech marks?', opts: ['outside', 'inside', 'both', 'neither'], ans: 'inside' },
          { id: 'q5', type: 'trueFalse', q: '"Come here!" shouted Tom.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '___Can you help me?___ asked Sarah. (Add speech marks)', answer: '"Can you help me?"', accept: ['"Can you help me?"'] },
          { id: 'q7', type: 'multiple', q: 'What is a reporting clause?', opts: ['the speech', 'said Emma', 'the noun', 'the verb only'], ans: 'said Emma' },
          { id: 'q8', type: 'trueFalse', q: 'The reporting clause comes after or before the speech.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A comma separates the reporting clause from the ___.', answer: 'speech', accept: ['speech', 'direct speech'] },
          { id: 'q10', type: 'multiple', q: 'Which is correct?', opts: ['"I am tired" said Jo.', '"I am tired.", said Jo.', '"I am tired." said Jo.', '"I am tired", said Jo.'], ans: '"I am tired," said Jo.' },
          { id: 'q11', type: 'trueFalse', q: 'A question mark can be inside speech marks.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '___Wake up!___ she called. (Add speech marks)', answer: '"Wake up!"', accept: ['"Wake up!"'] },
          { id: 'q13', type: 'multiple', q: 'What follows a reporting clause before speech?', opts: ['period', 'comma', 'colon', 'semicolon'], ans: 'comma' },
          { id: 'q14', type: 'trueFalse', q: 'Exclamation marks can be inside speech marks.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The reporting clause can be: "said Tom." or "Tom said."' __blank__', answer: 'yes', accept: ['yes', 'correct'] },
          { id: 'q16', type: 'multiple', q: 'Which uses correct speech mark placement?', opts: ['He said, "Hello".', 'He said, "Hello."', '"He said hello."', 'He said "Hello"'], ans: 'He said, "Hello."' },
          { id: 'q17', type: 'trueFalse', q: 'Each new speaker should start a new paragraph.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Please come here," ___ Ben. Fill with a reporting verb.', answer: 'said', accept: ['said', 'asked', 'whispered'] },
          { id: 'q19', type: 'trueFalse', q: 'Speech marks show someone\'s exact words.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'In "Come with me," said Amy." the reporting clause is "___"', answer: 'said Amy', accept: ['said Amy'] },
          { id: 'q21', type: 'multiple', q: 'How should dialogue be formatted?', opts: ['all in one paragraph', 'new paragraph per speaker', 'any way', 'no special format'], ans: 'new paragraph per speaker' },
          { id: 'q22', type: 'trueFalse', q: 'Inverted commas and speech marks are the same thing.', ans: true }
        ]
      },
      {
        id: 'y4-english-8',
        name: 'Apostrophes',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does an apostrophe show in possession?', opts: ['deletion', 'ownership', 'time', 'questions'], ans: 'ownership' },
          { id: 'q2', type: 'trueFalse', q: '"The cat\'s toy" shows the toy belongs to the cat.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'For one owner: "John___ book" = "John\'s book"', answer: "'s", accept: ["'s", "'"] },
          { id: 'q4', type: 'multiple', q: 'How do you show plural possession?', opts: ['add \'s', 'add s\'', 'add \'', 'no change'], ans: 'add s\'' },
          { id: 'q5', type: 'trueFalse', q: '"The girls\' books" means books belonging to multiple girls.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"The children___ toys" = "The children\'s toys"', answer: "'s", accept: ["'s", "'"] },
          { id: 'q7', type: 'multiple', q: 'Where does the apostrophe go in plural possession?', opts: ['before s', 'after s', 'no plural apostrophe', 'anywhere'], ans: 'after s' },
          { id: 'q8', type: 'trueFalse', q: '"The dogs\' kennel" is correct for multiple dogs.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"James___ bike" - one person named James.', answer: "'s", accept: ["'s"] },
          { id: 'q10', type: 'multiple', q: 'Apostrophes are also used for ___', opts: ['questions', 'contractions', 'lists', 'capitals'], ans: 'contractions' },
          { id: 'q11', type: 'trueFalse', q: '"It\'s" means "it is".', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Don\'t" is a contraction of "___" and "not"', answer: 'do', accept: ['do'] },
          { id: 'q13', type: 'multiple', q: 'What is "they\'re"?', opts: ['possessive', 'plural', 'contraction of "they are"', 'not a word'], ans: 'contraction of "they are"' },
          { id: 'q14', type: 'trueFalse', q: '"I\'ll" is a contraction of "I will".', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"You\'re" means "you ___"', answer: 'are', accept: ['are'] },
          { id: 'q16', type: 'multiple', q: 'Correct the sentence: "The childrens toys"', opts: ['The children\'s toys', 'The childs toys', 'The children toys', 'The childress toys'], ans: 'The children\'s toys' },
          { id: 'q17', type: 'trueFalse', q: '"Can\'t" is a contraction of "cannot".', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"We\'ve" means "we ___"', answer: 'have', accept: ['have'] },
          { id: 'q19', type: 'trueFalse', q: 'Apostrophes make plurals (like cats\' becomes cats\'s).', ans: false },
          { id: 'q20', type: 'fillBlank', q: '"The boys\' team" shows the team belongs to multiple ___', answer: 'boys', accept: ['boys'] },
          { id: 'q21', type: 'multiple', q: 'Which is correct?', opts: ['the girls book', 'the girl\'s book', 'the girls\'s book', 'the girl book'], ans: 'the girl\'s book' },
          { id: 'q22', type: 'trueFalse', q: 'Contractions use apostrophes to show missing letters.', ans: true }
        ]
      }
    ]
  },
  science: {
    name: 'Science',
    icon: '🔬',
    color: '#9C27B0',
    lessons: [
      {
        id: 'y4-science-1',
        name: 'Living Things & Classification',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What are vertebrates?', opts: ['without backbones', 'with backbones', 'without legs', 'with wings'], ans: 'with backbones' },
          { id: 'q2', type: 'trueFalse', q: 'Fish are vertebrates.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'Animals without backbones are called ___', answer: 'invertebrates', accept: ['invertebrates'] },
          { id: 'q4', type: 'multiple', q: 'Which is an invertebrate?', opts: ['dog', 'snake', 'insect', 'penguin'], ans: 'insect' },
          { id: 'q5', type: 'trueFalse', q: 'Insects are invertebrates.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'A ___ helps us identify organisms by asking questions.', answer: 'classification key', accept: ['classification key', 'dichotomous key', 'key'] },
          { id: 'q7', type: 'multiple', q: 'How do classification keys work?', opts: ['randomly', 'by asking yes/no questions', 'alphabetically', 'by size only'], ans: 'by asking yes/no questions' },
          { id: 'q8', type: 'trueFalse', q: 'Mammals have fur.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A ___ is a place where organisms live.', answer: 'habitat', accept: ['habitat'] },
          { id: 'q10', type: 'multiple', q: 'What is a forest habitat?', opts: ['a sandy area', 'an area with many trees', 'a water body', 'a mountain'], ans: 'an area with many trees' },
          { id: 'q11', type: 'trueFalse', q: 'Vertebrate classes include fish, amphibians, reptiles, birds, and mammals.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'Amphibians live partly in ___ and partly on land.', answer: 'water', accept: ['water'] },
          { id: 'q13', type: 'multiple', q: 'How many legs do insects have?', opts: ['4', '6', '8', 'varies'], ans: '6' },
          { id: 'q14', type: 'trueFalse', q: 'Spiders are insects.', ans: false },
          { id: 'q15', type: 'fillBlank', q: 'Birds lay ___', answer: 'eggs', accept: ['eggs'] },
          { id: 'q16', type: 'multiple', q: 'Which is a reptile?', opts: ['frog', 'lizard', 'newt', 'toad'], ans: 'lizard' },
          { id: 'q17', type: 'trueFalse', q: 'Animals can be grouped by their characteristics.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'The seashore is a ___ where sea creatures live.', answer: 'habitat', accept: ['habitat'] },
          { id: 'q19', type: 'trueFalse', q: 'Fish breathe through gills.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'A ___ is a group of animals that move and eat similarly.', answer: 'class', accept: ['class', 'group'] },
          { id: 'q21', type: 'trueFalse', q: 'Local habitats can include woodlands and ponds.', ans: true },
          { id: 'q22', type: 'multiple', q: 'Why is classification important?', opts: ['for decoration', 'to organise and study living things', 'no reason', 'to count animals'], ans: 'to organise and study living things' }
        ]
      },
      {
        id: 'y4-science-2',
        name: 'Digestion & Teeth',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What do incisors do?', opts: ['grind food', 'tear food', 'cut food', 'point food'], ans: 'cut food' },
          { id: 'q2', type: 'trueFalse', q: 'Canines are pointed teeth.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'Molars help us ___ food.', answer: 'grind', accept: ['grind', 'crush'] },
          { id: 'q4', type: 'multiple', q: 'How many types of teeth do we have?', opts: ['1', '2', '3', '4'], ans: '4' },
          { id: 'q5', type: 'trueFalse', q: 'Humans have two sets of teeth in their lifetime.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'Baby teeth are called ___ teeth.', answer: 'primary', accept: ['primary', 'milk', 'deciduous'] },
          { id: 'q7', type: 'multiple', q: 'What is the digestive system?', opts: ['the breathing system', 'the system that breaks down food', 'the nervous system', 'the bones'], ans: 'the system that breaks down food' },
          { id: 'q8', type: 'trueFalse', q: 'The mouth is the first part of the digestive system.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'The ___ pushes food down to the stomach.', answer: 'oesophagus', accept: ['oesophagus', 'gullet'] },
          { id: 'q10', type: 'multiple', q: 'What happens in the stomach?', opts: ['absorbs water', 'breaks down food', 'makes blood', 'grows bigger'], ans: 'breaks down food' },
          { id: 'q11', type: 'trueFalse', q: 'The small intestine absorbs nutrients.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'The large intestine absorbs ___', answer: 'water', accept: ['water'] },
          { id: 'q13', type: 'multiple', q: 'What is a food chain?', opts: ['linked by nutrients', 'who eats whom', 'plant growth', 'oxygen'], ans: 'who eats whom' },
          { id: 'q14', type: 'trueFalse', q: 'In a food chain, plants are producers.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'Animals that eat plants are called ___', answer: 'herbivores', accept: ['herbivores'] },
          { id: 'q16', type: 'multiple', q: 'What do carnivores eat?', opts: ['plants', 'meat', 'both', 'insects'], ans: 'meat' },
          { id: 'q17', type: 'trueFalse', q: 'Omnivores eat both plants and meat.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A simple food chain: grass → ___ → fox', answer: 'rabbit', accept: ['rabbit', 'mouse', 'deer'] },
          { id: 'q19', type: 'trueFalse', q: 'Saliva starts breaking down food in the mouth.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'The ___ is where digestion mainly happens.', answer: 'stomach', accept: ['stomach'] },
          { id: 'q21', type: 'trueFalse', q: 'We should brush our teeth to keep them healthy.', ans: true },
          { id: 'q22', type: 'multiple', q: 'Why are teeth important?', opts: ['decoration', 'breaking down food', 'breathing', 'hearing'], ans: 'breaking down food' }
        ]
      },
      {
        id: 'y4-science-3',
        name: 'States of Matter',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a solid?', opts: ['flows easily', 'has fixed shape and volume', 'no mass', 'invisible'], ans: 'has fixed shape and volume' },
          { id: 'q2', type: 'trueFalse', q: 'A liquid has a fixed shape.', ans: false },
          { id: 'q3', type: 'fillBlank', q: 'A gas has no fixed ___ or volume.', answer: 'shape', accept: ['shape'] },
          { id: 'q4', type: 'multiple', q: 'What happens when you heat a solid?', opts: ['stays solid', 'becomes a liquid', 'becomes gas', 'disappears'], ans: 'becomes a liquid' },
          { id: 'q5', type: 'trueFalse', q: 'Melting is the change from solid to liquid.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'When a liquid becomes a solid, it ___.', answer: 'freezes', accept: ['freezes'] },
          { id: 'q7', type: 'multiple', q: 'What is evaporation?', opts: ['liquid to solid', 'liquid to gas', 'gas to solid', 'solid to gas'], ans: 'liquid to gas' },
          { id: 'q8', type: 'trueFalse', q: 'Condensation is gas turning to liquid.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'When water boils, it turns into steam (a ___)' , answer: 'gas', accept: ['gas'] },
          { id: 'q10', type: 'multiple', q: 'What happens when steam cools?', opts: ['stays steam', 'becomes liquid', 'becomes solid', 'disappears'], ans: 'becomes liquid' },
          { id: 'q11', type: 'trueFalse', q: 'Temperature affects state of matter.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'Ice is a ___ (state of matter).', answer: 'solid', accept: ['solid'] },
          { id: 'q13', type: 'multiple', q: 'What temperature does water freeze at?', opts: ['0°C', '10°C', '100°C', '-10°C'], ans: '0°C' },
          { id: 'q14', type: 'trueFalse', q: 'Water boils at 100°C.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The water cycle includes evaporation, condensation, and ___', answer: 'precipitation', accept: ['precipitation'] },
          { id: 'q16', type: 'multiple', q: 'What is sublimation?', opts: ['solid to liquid', 'liquid to gas', 'solid directly to gas', 'gas to solid'], ans: 'solid directly to gas' },
          { id: 'q17', type: 'trueFalse', q: 'All solids melt at the same temperature.', ans: false },
          { id: 'q18', type: 'fillBlank', q: 'A ___ is the temperature at which a liquid becomes a solid.', answer: 'freezing point', accept: ['freezing point'] },
          { id: 'q19', type: 'trueFalse', q: 'Heating and cooling can change states of matter.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'When a gas cools and becomes a liquid, it ___', answer: 'condenses', accept: ['condenses'] },
          { id: 'q21', type: 'trueFalse', q: 'Matter cannot change states.', ans: false },
          { id: 'q22', type: 'multiple', q: 'How are heating and cooling related to state changes?', opts: ['no relation', 'heating causes melting/evaporation', 'cooling causes freezing/condensation', 'both b and c'], ans: 'both b and c' }
        ]
      },
      {
        id: 'y4-science-4',
        name: 'Sound',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What causes sound?', opts: ['light', 'vibrations', 'heat', 'movement'], ans: 'vibrations' },
          { id: 'q2', type: 'trueFalse', q: 'Sound travels in waves.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'The ___ of a sound is how high or low it is.', answer: 'pitch', accept: ['pitch'] },
          { id: 'q4', type: 'multiple', q: 'What makes a sound louder?', opts: ['smaller vibrations', 'larger vibrations', 'slower vibrations', 'no vibrations'], ans: 'larger vibrations' },
          { id: 'q5', type: 'trueFalse', q: 'Pitch is the loudness of a sound.', ans: false },
          { id: 'q6', type: 'fillBlank', q: 'The ___ of sound is how loud or quiet it is.', answer: 'volume', accept: ['volume'] },
          { id: 'q7', type: 'multiple', q: 'How does sound travel?', opts: ['through light', 'through matter (air, water, solids)', 'through nothing', 'instantly'], ans: 'through matter (air, water, solids)' },
          { id: 'q8', type: 'trueFalse', q: 'Sound travels faster in solid than in air.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'Sound cannot travel through a ___', answer: 'vacuum', accept: ['vacuum'] },
          { id: 'q10', type: 'multiple', q: 'What vibrates to make sound from a drum?', opts: ['stick', 'drum skin', 'air', 'hand'], ans: 'drum skin' },
          { id: 'q11', type: 'trueFalse', q: 'Sound insulation reduces noise.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'Materials that stop sound are called ___ materials.', answer: 'sound-absorbing', accept: ['sound-absorbing', 'insulating'] },
          { id: 'q13', type: 'multiple', q: 'Which is a good sound insulator?', opts: ['glass', 'foam', 'metal', 'plastic'], ans: 'foam' },
          { id: 'q14', type: 'trueFalse', q: 'A vibrating tuning fork makes sound.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'The frequency of vibrations determines the ___ of sound.', answer: 'pitch', accept: ['pitch'] },
          { id: 'q16', type: 'multiple', q: 'What measure is sound in?', opts: ['metres', 'decibels', 'watts', 'hertz'], ans: 'decibels' },
          { id: 'q17', type: 'trueFalse', q: 'We hear sound through our ears.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'High-pitched sounds have ___ vibrations.', answer: 'fast', accept: ['fast', 'many', 'frequent'] },
          { id: 'q19', type: 'trueFalse', q: 'Lower-pitched sounds have slower vibrations.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Sound waves can be ___ or ___.', answer: 'soft loud', accept: ['soft loud', 'loud soft', 'loud or soft'] },
          { id: 'q21', type: 'trueFalse', q: 'Vibrations are essential for sound production.', ans: true },
          { id: 'q22', type: 'multiple', q: 'How can we reduce unwanted noise?', opts: ['use sound insulation', 'increase vibrations', 'remove all sound', 'no way'], ans: 'use sound insulation' }
        ]
      },
      {
        id: 'y4-science-5',
        name: 'Electricity',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a simple circuit?', opts: ['a loop of darkness', 'a complete loop of electrical conductors', 'a broken wire', 'a battery only'], ans: 'a complete loop of electrical conductors' },
          { id: 'q2', type: 'trueFalse', q: 'A battery provides electrical energy.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'A ___ controls whether current flows in a circuit.', answer: 'switch', accept: ['switch'] },
          { id: 'q4', type: 'multiple', q: 'What does a bulb do in a circuit?', opts: ['blocks current', 'produces light', 'stores energy', 'makes heat only'], ans: 'produces light' },
          { id: 'q5', type: 'trueFalse', q: 'Wires carry electrical current.', ans: true },
          { id: 'q6', type: 'fillBlank', q: 'A ___ is a material that allows electricity to flow.', answer: 'conductor', accept: ['conductor'] },
          { id: 'q7', type: 'multiple', q: 'What is an insulator?', opts: ['conducts electricity', 'stops electricity flow', 'makes light', 'provides energy'], ans: 'stops electricity flow' },
          { id: 'q8', type: 'trueFalse', q: 'Rubber is a good conductor.', ans: false },
          { id: 'q9', type: 'fillBlank', q: 'Copper is an excellent ___', answer: 'conductor', accept: ['conductor'] },
          { id: 'q10', type: 'multiple', q: 'What happens when a circuit is broken?', opts: ['light stays on', 'current stops', 'more current flows', 'heat increases'], ans: 'current stops' },
          { id: 'q11', type: 'trueFalse', q: 'A switch opens or closes a circuit.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'When a switch is ___, the circuit is closed.', answer: 'on', accept: ['on', 'closed'] },
          { id: 'q13', type: 'multiple', q: 'Which materials are conductors?', opts: ['plastic', 'wood', 'metal', 'rubber'], ans: 'metal' },
          { id: 'q14', type: 'trueFalse', q: 'Electricity can be dangerous.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'In a circuit, components are connected by ___', answer: 'wires', accept: ['wires'] },
          { id: 'q16', type: 'multiple', q: 'What is needed to make a bulb light?', opts: ['bulb only', 'battery only', 'wires only', 'battery, wires, and bulb'], ans: 'battery, wires, and bulb' },
          { id: 'q17', type: 'trueFalse', q: 'Current flows in a circuit only if it is complete.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A ___ converts electrical energy into light.', answer: 'bulb', accept: ['bulb', 'lamp'] },
          { id: 'q19', type: 'trueFalse', q: 'Different components can be added to circuits.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Plastic coating on wires acts as an ___', answer: 'insulator', accept: ['insulator'] },
          { id: 'q21', type: 'trueFalse', q: 'We should be careful with electricity.', ans: true },
          { id: 'q22', type: 'multiple', q: 'What connects a battery to other circuit components?', opts: ['plastic', 'wires', 'nothing', 'light'], ans: 'wires' }
        ]
      },
      {
        id: 'y4-science-6',
        name: 'Working Scientifically',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is a classification key?', opts: ['a puzzle', 'a tool to identify organisms', 'a drawing', 'a list'], ans: 'a tool to identify organisms' },
          { id: 'q2', type: 'trueFalse', q: 'Classification keys use yes/no questions.', ans: true },
          { id: 'q3', type: 'fillBlank', q: 'A ___ variable is what we change in an experiment.', answer: 'independent', accept: ['independent'] },
          { id: 'q4', type: 'multiple', q: 'What is a dependent variable?', opts: ['what we change', 'what we measure/observe', 'what stays same', 'nothing'], ans: 'what we measure/observe' },
          { id: 'q5', type: 'trueFalse', q: 'We keep variables the same in a fair test except for one.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '___ variables are what we keep the same.', answer: 'Control', accept: ['Control'] },
          { id: 'q7', type: 'multiple', q: 'What is evidence in science?', opts: ['opinion', 'measurements and observations', 'guesses', 'stories'], ans: 'measurements and observations' },
          { id: 'q8', type: 'trueFalse', q: 'Evidence should be based on observations.', ans: true },
          { id: 'q9', type: 'fillBlank', q: 'A ___ is supported by evidence.', answer: 'conclusion', accept: ['conclusion'] },
          { id: 'q10', type: 'multiple', q: 'What should we do with results?', opts: ['ignore them', 'record and analyse them', 'forget them', 'change them'], ans: 'record and analyse them' },
          { id: 'q11', type: 'trueFalse', q: 'Scientific conclusions should be based on evidence.', ans: true },
          { id: 'q12', type: 'fillBlank', q: 'A ___ is a suggested explanation for observations.', answer: 'hypothesis', accept: ['hypothesis'] },
          { id: 'q13', type: 'multiple', q: 'Why do we repeat experiments?', opts: ['no reason', 'to check reliability', 'to get different answers', 'to waste time'], ans: 'to check reliability' },
          { id: 'q14', type: 'trueFalse', q: 'Fair tests have only one variable changed.', ans: true },
          { id: 'q15', type: 'fillBlank', q: 'Results should be ___ and accurate.', answer: 'precise', accept: ['precise', 'careful'] },
          { id: 'q16', type: 'multiple', q: 'What do we use to present results?', opts: ['drawings', 'tables', 'graphs', 'all of above'], ans: 'all of above' },
          { id: 'q17', type: 'trueFalse', q: 'Observations help us form predictions.', ans: true },
          { id: 'q18', type: 'fillBlank', q: 'A ___ is made before an experiment is done.', answer: 'prediction', accept: ['prediction'] },
          { id: 'q19', type: 'trueFalse', q: 'We should always follow safety procedures.', ans: true },
          { id: 'q20', type: 'fillBlank', q: 'Scientists record data to avoid ___', answer: 'loss of information', accept: ['loss of information', 'forgetting'] },
          { id: 'q21', type: 'trueFalse', q: 'Classification keys help us identify living things.', ans: true },
          { id: 'q22', type: 'multiple', q: 'What makes a good scientific question?', opts: ['unanswerable', 'testable', 'obvious', 'impossible'], ans: 'testable' }
        ]
      }
    ]
  },
  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#FF5722',
    lessons: [
      {
        id: 'y4-french-1',
        name: 'Family',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is "la mère"?', opts: ['brother', 'mother', 'sister', 'father'], ans: 'mother' },
          { id: 'q2', type: 'trueFalse', q: '"Le père" is father.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"La sœur" is "___"', answer: 'sister', accept: ['sister'] },
          { id: 'q4', type: 'multiple', q: 'How do you say brother?', opts: ['la sœur', 'le frère', 'le mari', 'le fils'], ans: 'le frère' },
          { id: 'q5', type: 'trueFalse', q: '"Les grands-parents" are grandparents.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"La grand-mère" is "___"', answer: 'grandmother', accept: ['grandmother'] },
          { id: 'q7', type: 'multiple', q: 'What is "le grand-père"?', opts: ['sister', 'grandmother', 'grandfather', 'brother'], ans: 'grandfather' },
          { id: 'q8', type: 'trueFalse', q: '"La tante" is aunt.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"L\'oncle" is "___"', answer: 'uncle', accept: ['uncle'] },
          { id: 'q10', type: 'multiple', q: 'How do you say cousin (male)?', opts: ['la cousine', 'le cousin', 'le frère', 'la sœur'], ans: 'le cousin' },
          { id: 'q11', type: 'trueFalse', q: '"La cousine" is female cousin.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"La famille" means "___"', answer: 'family', accept: ['family'] },
          { id: 'q13', type: 'multiple', q: 'What is "le mari"?', opts: ['mother', 'brother', 'husband', 'father'], ans: 'husband' },
          { id: 'q14', type: 'trueFalse', q: '"La femme" can mean wife or woman.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"Le fils" is "___"', answer: 'son', accept: ['son'] },
          { id: 'q16', type: 'multiple', q: 'How do you say daughter?', opts: ['le fils', 'la fille', 'la mère', 'la femme'], ans: 'la fille' },
          { id: 'q17', type: 'trueFalse', q: '"Le parent" means parent.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Les enfants" are "___"', answer: 'children', accept: ['children'] },
          { id: 'q19', type: 'trueFalse', q: '"La mère" and "la femme" mean the same thing.', ans: false },
          { id: 'q20', type: 'fillBlank', q: '"Le bébé" is "___"', answer: 'baby', accept: ['baby'] },
          { id: 'q21', type: 'multiple', q: 'How do you say "my family"?', opts: ['la famille', 'ma famille', 'mon famille', 'mes famille'], ans: 'ma famille' },
          { id: 'q22', type: 'trueFalse', q: 'Family vocabulary is important for describing relations.', ans: true }
        ]
      },
      {
        id: 'y4-french-2',
        name: 'Descriptions & Colours',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What does "grand" mean?', opts: ['small', 'big/tall', 'red', 'happy'], ans: 'big/tall' },
          { id: 'q2', type: 'trueFalse', q: '"Petit" means small.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Beau" means "___"', answer: 'beautiful', accept: ['beautiful', 'handsome'] },
          { id: 'q4', type: 'multiple', q: 'What is "belle"?', opts: ['beautiful (masculine)', 'beautiful (feminine)', 'handsome', 'small'], ans: 'beautiful (feminine)' },
          { id: 'q5', type: 'trueFalse', q: '"Petit garçon" means small boy.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Grande fille" means "___"', answer: 'big girl', accept: ['big girl', 'tall girl'] },
          { id: 'q7', type: 'multiple', q: 'How do you describe a tall woman?', opts: ['petite femme', 'grande femme', 'belle femme', 'femme grand'], ans: 'grande femme' },
          { id: 'q8', type: 'trueFalse', q: 'In French, adjectives agree with the noun\'s gender.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Noir" is "___"', answer: 'black', accept: ['black'] },
          { id: 'q10', type: 'multiple', q: 'What colour is "blanc"?', opts: ['blue', 'white', 'yellow', 'purple'], ans: 'white' },
          { id: 'q11', type: 'trueFalse', q: '"Rouge" means red.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Bleu" is "___"', answer: 'blue', accept: ['blue'] },
          { id: 'q13', type: 'multiple', q: 'What is "jaune"?', opts: ['green', 'yellow', 'orange', 'pink'], ans: 'yellow' },
          { id: 'q14', type: 'trueFalse', q: '"Vert" means green.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"Orange" is the same in French and English and means "___"', answer: 'orange', accept: ['orange'] },
          { id: 'q16', type: 'multiple', q: 'How do you say "purple"?', opts: ['rose', 'violet', 'gris', 'marron'], ans: 'violet' },
          { id: 'q17', type: 'trueFalse', q: '"Rose" means pink.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Gris" is "___"', answer: 'grey', accept: ['grey', 'gray'] },
          { id: 'q19', type: 'trueFalse', q: '"Marron" means brown.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"Un beau garçon blond" means "___"', answer: 'a handsome blonde boy', accept: ['a handsome blonde boy', 'a beautiful blonde boy'] },
          { id: 'q21', type: 'multiple', q: 'Which is a female adjective form?', opts: ['grand', 'grande', 'grands', 'grands'], ans: 'grande' },
          { id: 'q22', type: 'trueFalse', q: 'Colour words can be masculine or feminine in French.', ans: true }
        ]
      },
      {
        id: 'y4-french-3',
        name: 'Food & Drink',
        questions: [
          { id: 'q1', type: 'multiple', q: 'What is "J\'aime"?', opts: ['I hate', 'I like', 'I love', 'I want'], ans: 'I like' },
          { id: 'q2', type: 'trueFalse', q: '"Je n\'aime pas" means I don\'t like.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Le pain" is "___"', answer: 'bread', accept: ['bread'] },
          { id: 'q4', type: 'multiple', q: 'What is "le fromage"?', opts: ['bread', 'milk', 'cheese', 'butter'], ans: 'cheese' },
          { id: 'q5', type: 'trueFalse', q: '"La pizza" is pizza (same in both languages).', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"L\'eau" is "___"', answer: 'water', accept: ['water'] },
          { id: 'q7', type: 'multiple', q: 'What is "le jus"?', opts: ['water', 'milk', 'juice', 'tea'], ans: 'juice' },
          { id: 'q8', type: 'trueFalse', q: '"Le lait" means milk.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Le café" is "___"', answer: 'coffee', accept: ['coffee'] },
          { id: 'q10', type: 'multiple', q: 'How do you say "tea"?', opts: ['le thé', 'le café', 'la tisane', 'le vin'], ans: 'le thé' },
          { id: 'q11', type: 'trueFalse', q: '"La viande" means meat.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Le poulet" is "___"', answer: 'chicken', accept: ['chicken'] },
          { id: 'q13', type: 'multiple', q: 'What is "le poisson"?', opts: ['meat', 'fish', 'chicken', 'beef'], ans: 'fish' },
          { id: 'q14', type: 'trueFalse', q: '"Les légumes" are vegetables.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"La pomme" is "___"', answer: 'apple', accept: ['apple'] },
          { id: 'q16', type: 'multiple', q: 'How do you say "banana"?', opts: ['la banane', 'la pomme', 'l\'orange', 'la poire'], ans: 'la banane' },
          { id: 'q17', type: 'trueFalse', q: '"L\'orange" is orange (the fruit).', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"J\'aime le fromage" means "___"', answer: 'I like cheese', accept: ['I like cheese'] },
          { id: 'q19', type: 'trueFalse', q: 'Food vocabulary helps describe preferences.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"Je n\'aime pas le poisson" means "___"', answer: 'I don\'t like fish', accept: ['I don\'t like fish'] },
          { id: 'q21', type: 'multiple', q: 'What does "aimer" mean?', opts: ['to eat', 'to drink', 'to like/love', 'to cook'], ans: 'to like/love' },
          { id: 'q22', type: 'trueFalse', q: 'Understanding preferences helps in conversation.', ans: true }
        ]
      },
      {
        id: 'y4-french-4',
        name: 'Weather',
        questions: [
          { id: 'q1', type: 'multiple', q: 'How do you say "it is hot"?', opts: ['Il fait froid', 'Il fait chaud', 'Il fait beau', 'Il fait mauvais'], ans: 'Il fait chaud' },
          { id: 'q2', type: 'trueFalse', q: '"Il fait froid" means it is cold.', ans: true },
          { id: 'q3', type: 'fillBlank', q: '"Il fait beau" means "___"', answer: 'it is nice/beautiful', accept: ['it is nice', 'it is beautiful', 'the weather is nice'] },
          { id: 'q4', type: 'multiple', q: 'What does "Il pleut" mean?', opts: ['it is snowing', 'it is raining', 'it is windy', 'it is foggy'], ans: 'it is raining' },
          { id: 'q5', type: 'trueFalse', q: '"Il neige" means it is snowing.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '"Le soleil" is "___"', answer: 'the sun', accept: ['the sun'] },
          { id: 'q7', type: 'multiple', q: 'How do you say "it is windy"?', opts: ['Il fait du vent', 'Il neige', 'Il pleut', 'Il fait chaud'], ans: 'Il fait du vent' },
          { id: 'q8', type: 'trueFalse', q: '"Il y a des nuages" means there are clouds.', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Il fait mauvais" means "___"', answer: 'it is bad weather', accept: ['it is bad weather', 'the weather is bad'] },
          { id: 'q10', type: 'multiple', q: 'What is "le temps"?', opts: ['time', 'weather', 'season', 'year'], ans: 'weather' },
          { id: 'q11', type: 'trueFalse', q: '"Quel temps fait-il?" means "What is the weather like?"', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Le brouillard" is "___"', answer: 'fog', accept: ['fog'] },
          { id: 'q13', type: 'multiple', q: 'How do you say "rain"?', opts: ['la pluie', 'la neige', 'le vent', 'le soleil'], ans: 'la pluie' },
          { id: 'q14', type: 'trueFalse', q: '"La neige" means snow.', ans: true },
          { id: 'q15', type: 'fillBlank', q: '"Le vent" is "___"', answer: 'wind', accept: ['wind'] },
          { id: 'q16', type: 'multiple', q: 'What are four basic weather expressions?', opts: ['chaud, froid, beau, mauvais', 'chaud, eau, beau, mauvais', 'chaud, froid, beau, bon', 'hot, cold, rain, sun'], ans: 'chaud, froid, beau, mauvais' },
          { id: 'q17', type: 'trueFalse', q: 'Weather is an important topic in French conversations.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Aujourd\'hui il pleut" means "___"', answer: 'today it is raining', accept: ['today it is raining'] },
          { id: 'q19', type: 'trueFalse', q: 'You can describe weather with "Il fait" or "Il y a".', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"Il fait très froid" means "___"', answer: 'it is very cold', accept: ['it is very cold'] },
          { id: 'q21', type: 'multiple', q: 'Which weather expressions use "Il fait"?', opts: ['chaud, froid, beau', 'pleut, neige, vent', 'both a and b', 'pluie, neige, brouillard'], ans: 'chaud, froid, beau' },
          { id: 'q22', type: 'trueFalse', q: 'Learning weather vocabulary helps with conversations.', ans: true }
        ]
      },
      {
        id: 'y4-french-5',
        name: 'Numbers & Age',
        questions: [
          { id: 'q1', type: 'fillBlank', q: 'How do you say "I am ... years old"? "J\'ai ___ ans"', answer: 'a number', accept: ['a number', 'an age number', '(a number)'] },
          { id: 'q2', type: 'trueFalse', q: '"Quel âge as-tu?" means "How old are you?"', ans: true },
          { id: 'q3', type: 'fillBlank', q: '21 in French is "___"', answer: 'vingt-et-un', accept: ['vingt-et-un'] },
          { id: 'q4', type: 'multiple', q: 'What is 30 in French?', opts: ['vingt-dix', 'trente', 'quarante', 'vingt'], ans: 'trente' },
          { id: 'q5', type: 'trueFalse', q: '"Quarante" is 40.', ans: true },
          { id: 'q6', type: 'fillBlank', q: '50 in French is "___"', answer: 'cinquante', accept: ['cinquante'] },
          { id: 'q7', type: 'multiple', q: 'How do you say 22?', opts: ['vingt-deux', 'vingt-deux', 'deux-vingt', 'trente-deux'], ans: 'vingt-deux' },
          { id: 'q8', type: 'trueFalse', q: '"J\'ai onze ans" means "I am eleven years old".', ans: true },
          { id: 'q9', type: 'fillBlank', q: '"Elle a douze ans" means "She is ___ years old"', answer: '12', accept: ['12', 'twelve'] },
          { id: 'q10', type: 'multiple', q: 'How old would someone be if "Il a quinze ans"?', opts: ['14', '15', '16', '17'], ans: '15' },
          { id: 'q11', type: 'trueFalse', q: '"Tu as quel âge?" is a polite way to ask someone\'s age.', ans: true },
          { id: 'q12', type: 'fillBlank', q: '"Nous avons neuf ans" means "We are ___ years old"', answer: '9', accept: ['9', 'nine'] },
          { id: 'q13', type: 'multiple', q: 'What is 25?', opts: ['vingt-cinq', 'trente-cinq', 'vingt-sept', 'trente'], ans: 'vingt-cinq' },
          { id: 'q14', type: 'trueFalse', q: '"Ils ont treize ans" means "They are 13 years old".', ans: true },
          { id: 'q15', type: 'fillBlank', q: '35 in French is "___"', answer: 'trente-cinq', accept: ['trente-cinq'] },
          { id: 'q16', type: 'multiple', q: 'How do you say 45?', opts: ['quarante-cinq', 'trente-cinq', 'cinquante-cinq', 'soixante-cinq'], ans: 'quarante-cinq' },
          { id: 'q17', type: 'trueFalse', q: '"Avoir" is the verb used to express age in French.', ans: true },
          { id: 'q18', type: 'fillBlank', q: '"Mon ami a seize ans" means "My friend is ___ years old"', answer: '16', accept: ['16', 'sixteen'] },
          { id: 'q19', type: 'trueFalse', q: 'Numbers 21-99 are important for expressing age.', ans: true },
          { id: 'q20', type: 'fillBlank', q: '"C\'est mon anniversaire demain. J\'ai ___ ans." (you complete with your age)', answer: '(a number)', accept: ['(a number)', 'a number'] },
          { id: 'q21', type: 'multiple', q: 'What is the pattern for French numbers 21+?', opts: ['twenty-one = "vingt-un"', 'thirty-five = "trente-cinq"', 'both a and b', 'no pattern'], ans: 'both a and b' },
          { id: 'q22', type: 'trueFalse', q: 'Learning to count and express age is useful in conversation.', ans: true }
        ]
      }
    ]
  }
};
