window.YEAR_5_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        id: 'y5-maths-1',
        name: 'Place Value',
        description: 'Numbers to 1,000,000, negative numbers, rounding',
        questions: [
          { type: 'multiple', q: 'What is the value of the 7 in 375,482?', options: ['7,000', '70,000', '700,000', '700'], answer: '70,000' },
          { type: 'multiple', q: 'Which number is larger: -5 or -12?', options: ['-5', '-12', 'They are equal', 'Cannot compare'], answer: '-5' },
          { type: 'multiple', q: 'Round 47,638 to the nearest 10,000', options: ['50,000', '47,000', '48,000', '40,000'], answer: '50,000' },
          { type: 'fillBlank', q: 'In the number 654,321, the digit 5 represents ___ thousands', answer: '5', accept: ['5', 'five'] },
          { type: 'multiple', q: 'What is 6 hundred thousands + 3 ten thousands + 2 thousands + 5 ones?', options: ['632,005', '632,500', '635,205', '623,500'], answer: '632,005' },
          { type: 'trueFalse', q: 'The number -8 is greater than -3', answer: false },
          { type: 'multiple', q: 'Round 123,456 to the nearest 100,000', options: ['100,000', '120,000', '123,000', '123,500'], answer: '100,000' },
          { type: 'fillBlank', q: 'The number 1,000,000 is one ___', answer: 'million', accept: ['million'] },
          { type: 'multiple', q: 'What is the place value of 8 in 589,203?', options: ['80', '800', '8,000', '80,000'], answer: '80,000' },
          { type: 'multiple', q: 'Order these from smallest to largest: -2, 5, -8, 0', options: ['-8, -2, 0, 5', '-2, -8, 0, 5', '0, -2, -8, 5', '5, 0, -2, -8'], answer: '-8, -2, 0, 5' },
          { type: 'trueFalse', q: 'When rounding 456 to the nearest 100, the answer is 500', answer: true },
          { type: 'fillBlank', q: 'Round 2,749 to the nearest 1,000. The answer is ___', answer: '3000', accept: ['3000', '3,000', 'three thousand'] },
          { type: 'multiple', q: 'Which digit is in the hundred thousands place in 987,654?', options: ['9', '8', '7', '6'], answer: '9' },
          { type: 'trueFalse', q: '-15 is colder than -5 degrees', answer: true },
          { type: 'multiple', q: 'What is 42,735 rounded to the nearest 10?', options: ['42,730', '42,740', '42,700', '42,800'], answer: '42,740' },
          { type: 'fillBlank', q: '5 million + 8 hundred thousands = ___', answer: '5800000', accept: ['5,800,000', '5800000', '5.8 million'] },
          { type: 'multiple', q: 'Which number comes next in the sequence: -10, -5, 0, 5, ___', options: ['10', '0', '-10', '15'], answer: '10' },
          { type: 'trueFalse', q: 'The number 999,999 rounded to the nearest 100,000 is 1,000,000', answer: true },
          { type: 'multiple', q: 'What is the value of 3 in 234,567?', options: ['3', '30', '300', '30,000'], answer: '30,000' },
          { type: 'fillBlank', q: 'The temperature is -3°C. If it gets 5 degrees warmer, it will be ___°C', answer: '2', accept: ['2', 'two'] },
          { type: 'multiple', q: 'Round 555,555 to the nearest 1,000', options: ['555,000', '556,000', '560,000', '600,000'], answer: '556,000' }
        ]
      },
      {
        id: 'y5-maths-2',
        name: 'Addition & Subtraction',
        description: 'Multi-step problems, mental strategies, estimation',
        questions: [
          { type: 'multiple', q: 'What is 34,567 + 23,456?', options: ['58,023', '57,923', '58,123', '57,023'], answer: '58,023' },
          { type: 'fillBlank', q: '567 + 234 + ___ = 1,000', answer: '199', accept: ['199'] },
          { type: 'multiple', q: 'What is 50,000 - 17,893?', options: ['32,107', '32,117', '31,107', '32,207'], answer: '32,107' },
          { type: 'trueFalse', q: 'Estimate: 2,456 + 3,678 ≈ 6,000', answer: true },
          { type: 'multiple', q: 'Sarah has £45.67 and spends £12.34, then gains £8.50. How much does she have?', options: ['£41.83', '£42.83', '£41.93', '£42.93'], answer: '£41.83' },
          { type: 'fillBlank', q: 'To add 267 + 498, I can do 267 + 500 - ___ = 765', answer: '2', accept: ['2'] },
          { type: 'multiple', q: 'What is the missing number: 12,345 + ___ = 20,000?', options: ['7,655', '8,655', '7,745', '8,745'], answer: '7,655' },
          { type: 'trueFalse', q: 'When estimating 4,821 + 2,156, rounding to the nearest 1,000 gives approximately 7,000', answer: true },
          { type: 'multiple', q: 'Calculate: 23,456 - 8,234 + 5,678', options: ['20,900', '20,800', '21,900', '20,900'], answer: '20,900' },
          { type: 'fillBlank', q: '100 - 27 - 15 = ___', answer: '58', accept: ['58'] },
          { type: 'multiple', q: 'A shop has 15,000 apples. It sells 3,456 on Monday and 2,345 on Tuesday. How many remain?', options: ['9,199', '9,299', '9,099', '8,199'], answer: '9,199' },
          { type: 'trueFalse', q: 'The sum of 1,234 + 2,345 + 3,456 is greater than 7,000', answer: true },
          { type: 'multiple', q: 'What is 567,890 + 234,567?', options: ['802,457', '802,357', '801,457', '802,467'], answer: '802,457' },
          { type: 'fillBlank', q: 'If you start with 1,000 and subtract 250 twice, you have ___', answer: '500', accept: ['500'] },
          { type: 'trueFalse', q: 'Estimate: 78,456 - 21,345 ≈ 60,000', answer: true },
          { type: 'multiple', q: 'What must be added to 34,567 to make 100,000?', options: ['65,433', '65,533', '66,433', '65,343'], answer: '65,433' },
          { type: 'fillBlank', q: '456 + 234 + 310 = ___', answer: '1000', accept: ['1,000', '1000'] },
          { type: 'multiple', q: 'A book has 345 pages. You read 123 on day 1 and 89 on day 2. How many remain?', options: ['133', '234', '234', '143'], answer: '133' },
          { type: 'trueFalse', q: '5,678 + 4,322 = 10,000', answer: true },
          { type: 'fillBlank', q: 'Estimate 19,876 + 30,245 to the nearest 1,000: approximately ___', answer: '50000', accept: ['50,000', '50000', 'fifty thousand'] },
          { type: 'multiple', q: 'What is 3,456 - 1,234 - 567?', options: ['1,655', '1,555', '1,745', '1,645'], answer: '1,655' }
        ]
      },
      {
        id: 'y5-maths-3',
        name: 'Multiplication',
        description: 'Multiply up to 4-digit × 2-digit, factors, primes, square/cube numbers',
        questions: [
          { type: 'multiple', q: 'What is 23 × 45?', options: ['1,035', '1,025', '1,045', '1,015'], answer: '1,035' },
          { type: 'multiple', q: 'Calculate: 234 × 12', options: ['2,808', '2,808', '2,818', '2,798'], answer: '2,808' },
          { type: 'fillBlank', q: '15 × 8 = ___', answer: '120', accept: ['120'] },
          { type: 'trueFalse', q: '7 is a prime number', answer: true },
          { type: 'multiple', q: 'Which is NOT a factor of 24?', options: ['6', '8', '5', '4'], answer: '5' },
          { type: 'fillBlank', q: '5 squared (5²) = ___', answer: '25', accept: ['25'] },
          { type: 'multiple', q: 'What is 1,234 × 11?', options: ['13,574', '13,574', '13,464', '13,684'], answer: '13,574' },
          { type: 'trueFalse', q: '12 is a prime number', answer: false },
          { type: 'multiple', q: 'Which number is a perfect square?', options: ['10', '16', '15', '18'], answer: '16' },
          { type: 'fillBlank', q: 'All factors of 12 are: 1, 2, 3, 4, 6, and ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'What is 3 cubed (3³)?', options: ['9', '27', '81', '6'], answer: '27' },
          { type: 'trueFalse', q: 'The first five prime numbers are 2, 3, 5, 7, 9', answer: false },
          { type: 'multiple', q: 'Calculate: 456 × 23', options: ['10,488', '10,388', '10,588', '10,288'], answer: '10,488' },
          { type: 'fillBlank', q: '6 squared (6²) = ___', answer: '36', accept: ['36'] },
          { type: 'multiple', q: 'Which number is a multiple of both 4 and 6?', options: ['10', '12', '14', '18'], answer: '12' },
          { type: 'trueFalse', q: 'The number 17 is prime', answer: true },
          { type: 'fillBlank', q: '2 cubed (2³) = ___', answer: '8', accept: ['8'] },
          { type: 'multiple', q: 'What are all the factors of 20?', options: ['1,2,4,5,10,20', '1,2,5,20', '1,2,4,10,20', '2,4,5,10,20'], answer: '1,2,4,5,10,20' },
          { type: 'multiple', q: 'Calculate: 789 × 32', options: ['25,248', '25,148', '25,348', '24,248'], answer: '25,248' },
          { type: 'trueFalse', q: '4² equals 4 × 4', answer: true },
          { type: 'fillBlank', q: '10 squared (10²) = ___', answer: '100', accept: ['100'] }
        ]
      },
      {
        id: 'y5-maths-4',
        name: 'Division',
        description: 'Short division, interpret remainders, divisibility rules',
        questions: [
          { type: 'multiple', q: 'What is 456 ÷ 12?', options: ['38', '37', '39', '36'], answer: '38' },
          { type: 'fillBlank', q: '144 ÷ 12 = ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'Calculate: 567 ÷ 7', options: ['81', '80', '82', '79'], answer: '81' },
          { type: 'trueFalse', q: 'A number is divisible by 2 if it ends in an odd number', answer: false },
          { type: 'multiple', q: 'What is 1,234 ÷ 6? Give the remainder.', options: ['205 r 4', '206 r 4', '205 r 5', '204 r 4'], answer: '205 r 4' },
          { type: 'fillBlank', q: '96 ÷ 8 = ___', answer: '12', accept: ['12'] },
          { type: 'trueFalse', q: 'A number is divisible by 5 if it ends in 0 or 5', answer: true },
          { type: 'multiple', q: 'Is 345 divisible by 3?', options: ['No', 'Yes', 'Cannot tell', 'Maybe'], answer: 'Yes' },
          { type: 'multiple', q: 'What is 2,456 ÷ 8?', options: ['307', '306', '308', '305'], answer: '307' },
          { type: 'fillBlank', q: '360 ÷ 9 = ___', answer: '40', accept: ['40'] },
          { type: 'trueFalse', q: 'A number is divisible by 10 if it ends in 0', answer: true },
          { type: 'multiple', q: 'Calculate: 789 ÷ 6', options: ['131 r 3', '130 r 9', '132 r 3', '131 r 5'], answer: '131 r 3' },
          { type: 'multiple', q: 'Which number is divisible by 4?', options: ['23', '45', '48', '51'], answer: '48' },
          { type: 'fillBlank', q: '100 ÷ 5 = ___', answer: '20', accept: ['20'] },
          { type: 'trueFalse', q: '234 is divisible by 6', answer: true },
          { type: 'multiple', q: 'What is 5,678 ÷ 4?', options: ['1,419 r 2', '1,419 r 1', '1,420 r 2', '1,418 r 2'], answer: '1,419 r 2' },
          { type: 'fillBlank', q: '225 ÷ 15 = ___', answer: '15', accept: ['15'] },
          { type: 'multiple', q: 'A baker has 240 buns to pack into boxes of 8. How many full boxes?', options: ['30', '29', '31', '32'], answer: '30' },
          { type: 'trueFalse', q: '765 is divisible by 9', answer: true },
          { type: 'multiple', q: 'Calculate: 3,456 ÷ 11', options: ['314 r 2', '313 r 2', '314 r 4', '315 r 2'], answer: '314 r 2' },
          { type: 'fillBlank', q: 'A number is divisible by 2 if it ends in ___', answer: 'even', accept: ['even', 'an even number', '0,2,4,6,8'] }
        ]
      },
      {
        id: 'y5-maths-5',
        name: 'Fractions',
        description: 'Equivalent fractions, improper/mixed numbers, add/subtract, multiply',
        questions: [
          { type: 'multiple', q: 'Which fraction is equivalent to 1/2?', options: ['2/4', '2/3', '2/5', '3/6'], answer: '2/4' },
          { type: 'fillBlank', q: '3/4 + 1/4 = ___', answer: '1', accept: ['1', '4/4'] },
          { type: 'multiple', q: 'What is 5/8 - 2/8?', options: ['3/8', '3/16', '2/8', '7/8'], answer: '3/8' },
          { type: 'trueFalse', q: 'The improper fraction 7/4 is the same as 1 3/4', answer: true },
          { type: 'multiple', q: 'What is 2/3 + 1/3?', options: ['3/3', '1', '3/6', 'Both A and B'], answer: 'Both A and B' },
          { type: 'fillBlank', q: 'Convert 11/4 to a mixed number: ___ ___/___', answer: '2 3/4', accept: ['2 3/4', '2three-fourths'] },
          { type: 'multiple', q: 'Which fraction is NOT equivalent to 2/5?', options: ['4/10', '6/15', '8/20', '5/10'], answer: '5/10' },
          { type: 'trueFalse', q: '3/5 > 2/5', answer: true },
          { type: 'multiple', q: 'What is 1/3 of 12?', options: ['4', '6', '3', '8'], answer: '4' },
          { type: 'fillBlank', q: '1/2 × 8 = ___', answer: '4', accept: ['4'] },
          { type: 'multiple', q: 'Add: 1/4 + 2/4 + 1/4', options: ['4/4', '1', '4/8', 'Both A and B'], answer: 'Both A and B' },
          { type: 'trueFalse', q: 'The mixed number 2 1/2 equals the improper fraction 5/2', answer: true },
          { type: 'multiple', q: 'What is 3/4 - 1/4?', options: ['2/4', '1/2', '2/8', 'Both A and B'], answer: 'Both A and B' },
          { type: 'fillBlank', q: '5/6 - 2/6 = ___', answer: '3/6', accept: ['3/6', '1/2'] },
          { type: 'multiple', q: 'Order from smallest to largest: 1/2, 3/4, 1/4', options: ['1/4, 1/2, 3/4', '1/2, 1/4, 3/4', '3/4, 1/2, 1/4', '1/4, 3/4, 1/2'], answer: '1/4, 1/2, 3/4' },
          { type: 'trueFalse', q: '2/3 is greater than 3/5', answer: true },
          { type: 'fillBlank', q: 'The numerator in the fraction 7/9 is ___', answer: '7', accept: ['7'] },
          { type: 'multiple', q: 'What is 1/5 of 20?', options: ['4', '5', '3', '6'], answer: '4' },
          { type: 'trueFalse', q: '4/5 and 8/10 are equivalent', answer: true },
          { type: 'multiple', q: 'Which mixed number equals 9/4?', options: ['2 1/4', '2 2/4', '1 1/4', '3 1/4'], answer: '2 1/4' },
          { type: 'fillBlank', q: '2/3 + 1/3 = ___', answer: '1', accept: ['1', '3/3'] }
        ]
      },
      {
        id: 'y5-maths-6',
        name: 'Decimals & Percentages',
        description: '3 decimal places, ordering, converting fractions/decimals/percentages',
        questions: [
          { type: 'multiple', q: 'What is 0.5 as a percentage?', options: ['50%', '5%', '0.5%', '500%'], answer: '50%' },
          { type: 'fillBlank', q: '1/4 as a decimal is ___', answer: '0.25', accept: ['0.25', '.25'] },
          { type: 'multiple', q: 'Which decimal is the largest?', options: ['0.45', '0.54', '0.405', '0.504'], answer: '0.54' },
          { type: 'trueFalse', q: '0.75 equals 75%', answer: true },
          { type: 'fillBlank', q: '3/10 as a percentage is ___', answer: '30%', accept: ['30%', '30'] },
          { type: 'multiple', q: 'Order these decimals from smallest to largest: 0.3, 0.03, 0.33', options: ['0.03, 0.3, 0.33', '0.03, 0.33, 0.3', '0.3, 0.33, 0.03', '0.33, 0.3, 0.03'], answer: '0.03, 0.3, 0.33' },
          { type: 'trueFalse', q: '1/2 = 0.5 = 50%', answer: true },
          { type: 'multiple', q: 'What is 25% as a decimal?', options: ['0.25', '2.5', '0.025', '25'], answer: '0.25' },
          { type: 'fillBlank', q: '0.7 as a fraction is ___', answer: '7/10', accept: ['7/10', 'seven tenths'] },
          { type: 'multiple', q: 'Which is NOT equivalent to 0.5?', options: ['1/2', '50%', '5/10', '0.50'], answer: 'None of these' },
          { type: 'trueFalse', q: '0.123 has three decimal places', answer: true },
          { type: 'fillBlank', q: '0.8 as a percentage is ___', answer: '80%', accept: ['80%', '80'] },
          { type: 'multiple', q: 'What is 3/4 as a decimal?', options: ['0.75', '0.34', '0.7', '0.25'], answer: '0.75' },
          { type: 'trueFalse', q: '0.456 is less than 0.465', answer: true },
          { type: 'fillBlank', q: '10% as a decimal is ___', answer: '0.1', accept: ['0.1', '.1'] },
          { type: 'multiple', q: 'Order from smallest to largest: 0.101, 0.11, 0.011', options: ['0.011, 0.101, 0.11', '0.11, 0.101, 0.011', '0.011, 0.11, 0.101', '0.101, 0.011, 0.11'], answer: '0.011, 0.101, 0.11' },
          { type: 'trueFalse', q: '0.25 = 25% = 1/4', answer: true },
          { type: 'fillBlank', q: 'As a percentage, 0.05 is ___', answer: '5%', accept: ['5%', '5'] },
          { type: 'multiple', q: 'What is 2/5 as a decimal?', options: ['0.4', '0.25', '0.2', '0.45'], answer: '0.4' },
          { type: 'trueFalse', q: '0.9 is greater than 0.99', answer: false },
          { type: 'fillBlank', q: '20% as a decimal is ___', answer: '0.2', accept: ['0.2', '.2'] }
        ]
      },
      {
        id: 'y5-maths-7',
        name: 'Measurement',
        description: 'Convert metric units, area/perimeter, volume of cuboids',
        questions: [
          { type: 'fillBlank', q: '5 km = ___ m', answer: '5000', accept: ['5000', '5,000'] },
          { type: 'multiple', q: 'What is the perimeter of a rectangle with length 8 cm and width 5 cm?', options: ['26 cm', '40 cm', '13 cm', '24 cm'], answer: '26 cm' },
          { type: 'multiple', q: 'Calculate the area of a rectangle: length 7 cm, width 4 cm', options: ['28 cm²', '22 cm²', '11 cm²', '56 cm²'], answer: '28 cm²' },
          { type: 'trueFalse', q: '1 kg = 1,000 g', answer: true },
          { type: 'fillBlank', q: '3,500 ml = ___ litres', answer: '3.5', accept: ['3.5', '3½'] },
          { type: 'multiple', q: 'What is the volume of a cuboid with length 3 cm, width 4 cm, height 5 cm?', options: ['60 cm³', '50 cm³', '12 cm³', '40 cm³'], answer: '60 cm³' },
          { type: 'trueFalse', q: '2.5 metres equals 250 cm', answer: true },
          { type: 'fillBlank', q: '8 metres = ___ cm', answer: '800', accept: ['800'] },
          { type: 'multiple', q: 'A square has a perimeter of 20 cm. What is the length of each side?', options: ['5 cm', '10 cm', '4 cm', '20 cm'], answer: '5 cm' },
          { type: 'trueFalse', q: 'Area is measured in cubic units', answer: false },
          { type: 'multiple', q: 'Convert 4,200 ml to litres', options: ['4.2 L', '0.42 L', '42 L', '420 L'], answer: '4.2 L' },
          { type: 'fillBlank', q: 'A cuboid has dimensions 2 m × 3 m × 4 m. Volume = ___ m³', answer: '24', accept: ['24', '24 cubic metres'] },
          { type: 'trueFalse', q: '1 litre = 100 ml', answer: false },
          { type: 'fillBlank', q: '7.5 kg = ___ g', answer: '7500', accept: ['7500', '7,500'] },
          { type: 'multiple', q: 'What is the perimeter of a square with side 6 m?', options: ['24 m', '36 m², '12 m', '18 m'], answer: '24 m' },
          { type: 'trueFalse', q: 'A rectangle with length 10 cm and width 5 cm has an area of 15 cm²', answer: false },
          { type: 'fillBlank', q: 'Convert 2,500 g to kg: ___ kg', answer: '2.5', accept: ['2.5', '2½'] },
          { type: 'multiple', q: 'A garden is 12 m long and 8 m wide. What is its perimeter?', options: ['40 m', '96 m', '20 m', '96 m²'], answer: '40 m' },
          { type: 'trueFalse', q: '3 cm = 30 mm', answer: true },
          { type: 'fillBlank', q: '6.5 L = ___ ml', answer: '6500', accept: ['6500', '6,500'] },
          { type: 'multiple', q: 'A cuboid has length 5 m, width 2 m, height 3 m. Volume = ___', options: ['30 m³', '10 m³', '15 m³', '60 m³'], answer: '30 m³' }
        ]
      },
      {
        id: 'y5-maths-8',
        name: 'Geometry',
        description: 'Angles, polygons, reflection, translation',
        questions: [
          { type: 'multiple', q: 'What is the sum of angles on a straight line?', options: ['180°', '90°', '360°', '45°'], answer: '180°' },
          { type: 'fillBlank', q: 'A right angle measures ___°', answer: '90', accept: ['90'] },
          { type: 'multiple', q: 'How many sides does a pentagon have?', options: ['5', '6', '4', '8'], answer: '5' },
          { type: 'trueFalse', q: 'The sum of angles around a point is 360°', answer: true },
          { type: 'multiple', q: 'What are vertically opposite angles?', options: ['Equal', 'Different', 'Always 90°', 'Always 180°'], answer: 'Equal' },
          { type: 'fillBlank', q: 'An octagon has ___ sides', answer: '8', accept: ['8'] },
          { type: 'trueFalse', q: 'A regular polygon has all sides and angles equal', answer: true },
          { type: 'multiple', q: 'How many lines of symmetry does a square have?', options: ['4', '2', '1', '0'], answer: '4' },
          { type: 'fillBlank', q: 'The interior angles of a triangle sum to ___°', answer: '180', accept: ['180'] },
          { type: 'multiple', q: 'Which shape is NOT a regular polygon?', options: ['Regular pentagon', 'Square', 'Scalene triangle', 'Equilateral triangle'], answer: 'Scalene triangle' },
          { type: 'trueFalse', q: 'A circle has infinite lines of symmetry', answer: true },
          { type: 'fillBlank', q: 'A hexagon has ___ sides', answer: '6', accept: ['6'] },
          { type: 'multiple', q: 'If one angle on a straight line is 60°, the other is ___', options: ['120°', '60°', '90°', '30°'], answer: '120°' },
          { type: 'trueFalse', q: 'Translation means sliding a shape without rotating', answer: true },
          { type: 'multiple', q: 'A reflection creates a mirror image. True or False?', options: ['True', 'False', 'Sometimes', 'Only for some shapes'], answer: 'True' },
          { type: 'fillBlank', q: 'A quadrilateral has ___ sides', answer: '4', accept: ['4'] },
          { type: 'trueFalse', q: 'A rectangle has 2 lines of symmetry', answer: true },
          { type: 'multiple', q: 'What happens to an angle when a shape is reflected?', options: ['Stays the same', 'Doubles', 'Halves', 'Becomes 90°'], answer: 'Stays the same' },
          { type: 'fillBlank', q: 'A decagon has ___ sides', answer: '10', accept: ['10'] },
          { type: 'trueFalse', q: 'An isosceles triangle has two equal sides', answer: true },
          { type: 'multiple', q: 'How many lines of symmetry does an equilateral triangle have?', options: ['3', '1', '0', '2'], answer: '3' }
        ]
      },
      {
        id: 'y5-maths-9',
        name: 'Statistics',
        description: 'Tables, timetables, line graphs, solving problems',
        questions: [
          { type: 'multiple', q: 'What does the mode represent in statistics?', options: ['The most frequent value', 'The middle value', 'The average value', 'The spread'], answer: 'The most frequent value' },
          { type: 'fillBlank', q: 'The range is found by subtracting the ___ number from the ___ number', answer: 'smallest/highest', accept: ['smallest, highest', 'lowest, highest', 'minimum, maximum'] },
          { type: 'trueFalse', q: 'A bar chart uses bars to represent data', answer: true },
          { type: 'multiple', q: 'A train leaves at 14:30 and travels for 2 hours 15 minutes. When does it arrive?', options: ['16:45', '16:15', '17:00', '16:30'], answer: '16:45' },
          { type: 'multiple', q: 'The set of numbers is: 2, 3, 5, 3, 8, 3. What is the mode?', options: ['3', '2', '5', '8'], answer: '3' },
          { type: 'trueFalse', q: 'A line graph shows continuous data over time', answer: true },
          { type: 'fillBlank', q: 'The ___ is the middle value when data is ordered', answer: 'median', accept: ['median'] },
          { type: 'multiple', q: 'Data: 4, 7, 2, 9, 3. What is the median?', options: ['4', '7', '5', '2'], answer: '4' },
          { type: 'multiple', q: 'A bus timetable shows departure times at: 09:00, 09:30, 10:00, 10:30. The interval is ___', options: ['30 minutes', '1 hour', '15 minutes', '45 minutes'], answer: '30 minutes' },
          { type: 'trueFalse', q: 'The mean is calculated by adding all values and dividing by how many there are', answer: true },
          { type: 'fillBlank', q: 'Range of 2, 5, 8, 12 is ___', answer: '10', accept: ['10'] },
          { type: 'multiple', q: 'Numbers: 10, 15, 12, 18, 20. What is the mean?', options: ['15', '12', '18', '20'], answer: '15' },
          { type: 'trueFalse', q: 'A pictogram uses symbols to represent data', answer: true },
          { type: 'fillBlank', q: 'A school day starts at 08:45 and ends at 15:15. Duration = ___ hours ___ minutes', answer: '6 hours 30 minutes', accept: ['6 hours 30 minutes', '6:30', '6 1/2'] },
          { type: 'multiple', q: 'Which data is best shown in a pie chart?', options: ['Parts of a whole', 'Trends over time', 'Specific values', 'Frequencies'], answer: 'Parts of a whole' },
          { type: 'trueFalse', q: 'A scatter graph shows the relationship between two sets of data', answer: true },
          { type: 'fillBlank', q: 'If a timetable shows times at 07:00 and 07:45, the interval is ___ minutes', answer: '45', accept: ['45'] },
          { type: 'multiple', q: 'Data set: 5, 5, 6, 7, 8, 9, 10. Mode = ___', options: ['5', '7', '10', '8'], answer: '5' },
          { type: 'trueFalse', q: 'A frequency table shows how often values occur', answer: true },
          { type: 'multiple', q: 'A film starts at 19:30 and lasts 2 hours 10 minutes. End time = ___', options: ['21:40', '21:30', '21:50', '20:40'], answer: '21:40' },
          { type: 'fillBlank', q: 'Numbers: 2, 4, 6, 8, 10. Mean = ___', answer: '6', accept: ['6'] }
        ]
      },
      {
        id: 'y5-maths-10',
        name: 'Roman Numerals & Sequences',
        description: 'Roman numerals to 1000, patterns in sequences',
        questions: [
          { type: 'fillBlank', q: 'The Roman numeral for 5 is ___', answer: 'V', accept: ['V'] },
          { type: 'multiple', q: 'What does X represent in Roman numerals?', options: ['10', '100', '5', '1'], answer: '10' },
          { type: 'fillBlank', q: 'Roman numeral for 50 is ___', answer: 'L', accept: ['L'] },
          { type: 'multiple', q: 'Convert 27 to Roman numerals', options: ['XXVII', 'XVII', 'XXII', 'XXXVII'], answer: 'XXVII' },
          { type: 'trueFalse', q: 'IV represents 4', answer: true },
          { type: 'fillBlank', q: 'The Roman numeral for 100 is ___', answer: 'C', accept: ['C'] },
          { type: 'multiple', q: 'Convert VI to numbers', options: ['6', '4', '5', '7'], answer: '6' },
          { type: 'trueFalse', q: 'XL represents 40', answer: true },
          { type: 'fillBlank', q: 'M represents ___ in Roman numerals', answer: '1000', accept: ['1000', 'one thousand'] },
          { type: 'multiple', q: 'Convert 49 to Roman numerals', options: ['XLIX', 'IL', 'XLVIII', 'XLIX'], answer: 'XLIX' },
          { type: 'trueFalse', q: 'CD represents 400', answer: true },
          { type: 'fillBlank', q: 'The next number in the sequence 2, 4, 6, 8 is ___', answer: '10', accept: ['10'] },
          { type: 'multiple', q: 'What is the pattern: 3, 6, 9, 12?', options: ['Add 3', 'Add 2', 'Multiply by 2', 'Add 4'], answer: 'Add 3' },
          { type: 'fillBlank', q: 'Next in sequence: 5, 10, 15, 20, ___', answer: '25', accept: ['25'] },
          { type: 'trueFalse', q: 'The sequence 1, 4, 9, 16, 25 is the square numbers', answer: true },
          { type: 'multiple', q: 'What comes next: 100, 90, 80, 70, ___?', options: ['60', '50', '40', '30'], answer: '60' },
          { type: 'fillBlank', q: 'The next number in 2, 4, 8, 16 is ___', answer: '32', accept: ['32'] },
          { type: 'trueFalse', q: 'The sequence 1, 1, 2, 3, 5, 8 is a Fibonacci sequence', answer: true },
          { type: 'multiple', q: 'Convert XLII to numbers', options: ['42', '52', '32', '41'], answer: '42' },
          { type: 'fillBlank', q: 'In the sequence 1, 8, 27, 64, each number is a ___', answer: 'cube', accept: ['cube number', 'cube'] },
          { type: 'multiple', q: 'What is the rule for this sequence: 7, 14, 21, 28?', options: ['Add 7 each time', 'Double each time', 'Add 8 each time', 'Multiply by 2'], answer: 'Add 7 each time' }
        ]
      }
    ]
  },
  english: {
    name: 'English',
    icon: '📖',
    color: '#2196F3',
    lessons: [
      {
        id: 'y5-english-1',
        name: 'Modal Verbs',
        description: 'might, should, will, must, could, would, may, shall',
        questions: [
          { type: 'multiple', q: 'Which modal verb shows obligation or necessity?', options: ['must', 'might', 'could', 'would'], answer: 'must' },
          { type: 'fillBlank', q: 'I ___ go to school today (expressing permission)', answer: 'may', accept: ['may', 'can'] },
          { type: 'multiple', q: 'Complete: You ___ arrive on time if you leave early.', options: ['should', 'must', 'will', 'might'], answer: 'should' },
          { type: 'trueFalse', q: '"I might go to the park" shows a definite plan', answer: false },
          { type: 'fillBlank', q: 'She ___ be at home (showing possibility)', answer: 'might', accept: ['might', 'could'] },
          { type: 'multiple', q: 'Which sentence uses a modal verb correctly?', options: ['He can swim very well', 'She must to study', 'They will goes tomorrow', 'I could goes there'], answer: 'He can swim very well' },
          { type: 'trueFalse', q: '"Would you like tea?" - Would is a modal verb', answer: true },
          { type: 'fillBlank', q: 'The student ___ complete their homework (showing need)', answer: 'must', accept: ['must'] },
          { type: 'multiple', q: 'What does "should" typically express?', options: ['Advice or recommendation', 'Certainty', 'Permission', 'Past action'], answer: 'Advice or recommendation' },
          { type: 'trueFalse', q: 'All modal verbs are followed by the base form of the verb', answer: true },
          { type: 'fillBlank', q: '___ I help you? (offering help)', answer: 'Shall', accept: ['Shall', 'Can'] },
          { type: 'multiple', q: 'Choose the correct sentence:', options: ['They could go to the cinema', 'They could goes to the cinema', 'They could to go to the cinema', 'They cans go to the cinema'], answer: 'They could go to the cinema' },
          { type: 'trueFalse', q: '"I will definitely pass the test" shows certainty', answer: true },
          { type: 'fillBlank', q: 'You ___ not park here (showing prohibition)', answer: 'must', accept: ['must'] },
          { type: 'multiple', q: 'Which modal verb is used for polite requests?', options: ['Could', 'must', 'will', 'might'], answer: 'Could' },
          { type: 'trueFalse', q: '"Would" can be used to talk about habits in the past', answer: true },
          { type: 'fillBlank', q: 'The weather ___ be sunny tomorrow (showing possibility)', answer: 'might', accept: ['might', 'may', 'could'] },
          { type: 'multiple', q: 'Correct the modal verb: "She may not to come"', options: ['She may not come', 'She not may come', 'She may come not', 'She mays not come'], answer: 'She may not come' },
          { type: 'trueFalse', q: '"Must" and "have to" always mean exactly the same thing', answer: false },
          { type: 'fillBlank', q: '___ you pass me the salt, please? (polite request)', answer: 'Could', accept: ['Could', 'Would', 'Can'] }
        ]
      },
      {
        id: 'y5-english-2',
        name: 'Relative Clauses',
        description: 'who, which, where, when, whose, that',
        questions: [
          { type: 'multiple', q: 'Which relative pronoun is used for people?', options: ['who', 'which', 'where', 'whose'], answer: 'who' },
          { type: 'fillBlank', q: 'The book ___ I read was interesting (relative pronoun)', answer: 'which', accept: ['which', 'that'] },
          { type: 'multiple', q: 'Complete: The girl who ___ my friend is called Sarah.', options: ['is', 'are', 'am', 'be'], answer: 'is' },
          { type: 'trueFalse', q: '"Where" is a relative pronoun used for places', answer: true },
          { type: 'fillBlank', q: 'The building ___ they work is very tall', answer: 'where', accept: ['where'] },
          { type: 'multiple', q: 'Which sentence correctly uses a relative clause?', options: ['The teacher who taught us was kind', 'The teacher who taught us was being kind', 'The teacher which taught us was kind', 'The teacher when taught us was kind'], answer: 'The teacher who taught us was kind' },
          { type: 'trueFalse', q: '"Whose" shows possession in a relative clause', answer: true },
          { type: 'fillBlank', q: 'The student ___ pencil I borrowed passed the exam', answer: 'whose', accept: ['whose'] },
          { type: 'multiple', q: 'Choose the correct sentence:', options: ['The dog which barked was mine', 'The dog who barked was mine', 'The dog that barking was mine', 'The dog who was barked was mine'], answer: 'The dog which barked was mine' },
          { type: 'trueFalse', q: 'Relative clauses always come after the noun they describe', answer: true },
          { type: 'fillBlank', q: 'The time ___ we met was noon', answer: 'when', accept: ['when'] },
          { type: 'multiple', q: 'What does a relative clause do in a sentence?', options: ['Provides extra information about a noun', 'Shows the main action', 'Expresses emotion', 'Gives a command'], answer: 'Provides extra information about a noun' },
          { type: 'trueFalse', q: '"That" can be used as a relative pronoun', answer: true },
          { type: 'fillBlank', q: 'The place ___ we went was beautiful', answer: 'where', accept: ['where'] },
          { type: 'multiple', q: 'Correct: The person __ helped me was kind.', options: ['who', 'which', 'where', 'whose'], answer: 'who' },
          { type: 'trueFalse', q: 'You cannot remove a relative clause from a sentence', answer: false },
          { type: 'fillBlank', q: 'The book ___ is on the table belongs to me', answer: 'which', accept: ['which', 'that'] },
          { type: 'multiple', q: 'Choose the sentence with a correct relative clause:', options: ['The girl whose mother is a doctor is smart', 'The girl which mother is a doctor is smart', 'The girl who mother is a doctor is smart', 'The girl where mother is a doctor is smart'], answer: 'The girl whose mother is a doctor is smart' },
          { type: 'trueFalse', q: '"Which" is used for both people and things', answer: false },
          { type: 'fillBlank', q: 'The reason ___ she left was unknown', answer: 'why', accept: ['why'] }
        ]
      },
      {
        id: 'y5-english-3',
        name: 'Parenthesis',
        description: 'Brackets, dashes, commas to mark parenthesis',
        questions: [
          { type: 'multiple', q: 'What does parenthesis mean?', options: ['Extra information inserted into a sentence', 'A type of word', 'A grammatical tense', 'A punctuation mark'], answer: 'Extra information inserted into a sentence' },
          { type: 'fillBlank', q: 'The swimmer (___) trained hard for the Olympics.', answer: 'optional insertion', accept: ['optional', 'extra information', 'a detail'] },
          { type: 'trueFalse', q: 'Dashes can be used to mark parenthetical information', answer: true },
          { type: 'multiple', q: 'Which sentence uses parenthesis correctly?', options: ['She went to the park (which is near her house)', 'She went (to) the park', 'She (went to) the park very quickly', '(She went) to the park'], answer: 'She went to the park (which is near her house)' },
          { type: 'fillBlank', q: 'Commas, dashes, and ___ can all mark parenthesis', answer: 'brackets', accept: ['brackets', 'parentheses'] },
          { type: 'trueFalse', q: 'A parenthetical phrase must be essential to the sentence', answer: false },
          { type: 'multiple', q: 'Complete: The book – my favourite – is on the shelf.', options: ['is', 'are', 'was', 'were'], answer: 'is' },
          { type: 'trueFalse', q: 'If you remove parenthetical information, the sentence should still make sense', answer: true },
          { type: 'fillBlank', q: 'She wore (a bright red dress) to the party.', answer: 'optional detail', accept: ['a detail', 'extra', 'parenthetical information'] },
          { type: 'multiple', q: 'What is the function of brackets in this sentence: "The museum (which opened last year) is impressive"?', options: ['To add extra information', 'To show multiplication', 'To indicate emphasis', 'To show alternatives'], answer: 'To add extra information' },
          { type: 'trueFalse', q: 'Dashes – like these – are used instead of commas for emphasis', answer: true },
          { type: 'fillBlank', q: 'The footballer, who is only seventeen, ___ already professional.', answer: 'is', accept: ['is'] },
          { type: 'multiple', q: 'Which correctly uses parenthesis with commas?', options: ['The café, next to the shop, is lovely', 'The café next to the shop is lovely', 'The, café next to the shop is lovely', 'The café, next to the, shop is lovely'], answer: 'The café, next to the shop, is lovely' },
          { type: 'trueFalse', q: 'Parenthetical information is always in commas', answer: false },
          { type: 'fillBlank', q: 'My sister (who lives in Paris) ___ me last week.', answer: 'visited', accept: ['visited', 'rings'] },
          { type: 'multiple', q: 'Choose the correct use of dashes:', options: ['The car – an old model – still runs well', 'The car – an old model still runs well', 'The car an old model – still runs well', '– The car an old model – still runs well'], answer: 'The car – an old model – still runs well' },
          { type: 'trueFalse', q: 'Brackets [like these] are more formal than dashes', answer: true },
          { type: 'fillBlank', q: 'The recipe (from her grandmother) was ___', answer: 'delicious', accept: ['delicious', 'excellent', 'wonderful'] },
          { type: 'multiple', q: 'What punctuation marks this parenthetical phrase? "The film which was long was interesting"', options: ['Commas around "which was long"', 'Dashes', 'Brackets', 'No punctuation needed'], answer: 'Commas around "which was long"' },
          { type: 'trueFalse', q: 'You can use commas, dashes, OR brackets – they are interchangeable', answer: false },
          { type: 'fillBlank', q: 'The teacher – Mr Smith – gave us ___', answer: 'homework', accept: ['homework', 'a lot'] }
        ]
      },
      {
        id: 'y5-english-4',
        name: 'Cohesive Devices',
        description: 'Adverbials, pronouns, conjunctions, synonyms for cohesion',
        questions: [
          { type: 'multiple', q: 'What are cohesive devices?', options: ['Words/phrases that link ideas together', 'Types of verbs', 'Adjectives', 'Punctuation marks'], answer: 'Words/phrases that link ideas together' },
          { type: 'fillBlank', q: '_____, she decided to go outside. (adverbial cohesive device)', answer: 'Eventually', accept: ['Eventually', 'Finally', 'Later', 'Then'] },
          { type: 'multiple', q: 'Which is a cohesive device?', options: ['However', 'Beautiful', 'Quickly', 'Run'], answer: 'However' },
          { type: 'trueFalse', q: 'Pronouns like "he", "she", "it" link ideas by referring back to previous nouns', answer: true },
          { type: 'fillBlank', q: 'The boy played football. _____ was very tired afterwards.', answer: 'He', accept: ['He'] },
          { type: 'multiple', q: 'What is a synonym used for in writing?', options: ['To avoid repetition and maintain interest', 'To make sentences longer', 'To confuse the reader', 'To change the meaning'], answer: 'To avoid repetition and maintain interest' },
          { type: 'trueFalse', q: '"Moreover" is a cohesive device that adds information', answer: true },
          { type: 'fillBlank', q: 'The cat was hungry. It ___ its food immediately. (pronoun link)', answer: 'ate', accept: ['ate', 'had', 'devoured'] },
          { type: 'multiple', q: 'Which conjunction shows contrast?', options: ['However', 'Because', 'And', 'Also'], answer: 'However' },
          { type: 'trueFalse', q: 'Conjunctions like "and", "but", "because" are cohesive devices', answer: true },
          { type: 'fillBlank', q: 'She studied hard. ___, she failed the exam.', answer: 'However', accept: ['However', 'Nevertheless', 'Yet'] },
          { type: 'multiple', q: 'Instead of repeating "the shop", what cohesive device could you use?', options: ['A pronoun like "it"', 'The same noun', 'An exclamation', 'A comma'], answer: 'A pronoun like "it"' },
          { type: 'trueFalse', q: '"Finally" and "eventually" are adverbial cohesive devices', answer: true },
          { type: 'fillBlank', q: 'The dog ran away. The girl chased the dog. The girl ___ it to the park.', answer: 'followed', accept: ['followed', 'chased'] },
          { type: 'multiple', q: 'Which would best replace "car" in: "The car was fast. The __ was red."?', options: ['vehicle', 'automobile', 'machine', 'transport'], answer: 'vehicle' },
          { type: 'trueFalse', q: 'Adverbials like "meanwhile", "afterwards", "previously" connect time sequences', answer: true },
          { type: 'fillBlank', q: 'He liked pizza. _____, he enjoyed pasta. (cohesive device)', answer: 'Similarly', accept: ['Similarly', 'Also', 'Moreover'] },
          { type: 'multiple', q: 'Choose the most cohesive paragraph:', options: ['The boy played. He was happy. It was fun.', 'The boy played. Therefore, he was happy.', 'The boy played. The boy was happy. The play was fun.', 'The boy was playing. He played. Playing was happy.'], answer: 'The boy played. Therefore, he was happy.' },
          { type: 'trueFalse', q: 'Substituting "hospital" for "building" changes meaning if used cohesively', answer: false },
          { type: 'fillBlank', q: 'The team lost. ___, they congratulated their opponents. (showing contrast)', answer: 'Nevertheless', accept: ['Nevertheless', 'However', 'Yet'] }
        ]
      },
      {
        id: 'y5-english-5',
        name: 'Verb Prefixes',
        description: 'de-, dis-, mis-, over-, re-, pre-',
        questions: [
          { type: 'fillBlank', q: 'The prefix dis- means ___', answer: 'opposite', accept: ['opposite', 'not', 'away'] },
          { type: 'multiple', q: 'What does "misunderstand" mean?', options: ['To understand wrongly', 'To understand again', 'To not understand', 'To understand over'], answer: 'To understand wrongly' },
          { type: 'trueFalse', q: 'The prefix "re-" means to do something again', answer: true },
          { type: 'fillBlank', q: 'To ___ frost (remove frost) - de+ frost', answer: 'defrost', accept: ['defrost'] },
          { type: 'multiple', q: 'What does "overcook" mean?', options: ['To cook too much', 'To cook again', 'To cook wrong', 'To cook before'], answer: 'To cook too much' },
          { type: 'trueFalse', q: '"Prewrite" means to write before something else', answer: true },
          { type: 'fillBlank', q: 'To ___ a button (fasten again)', answer: 'rebutton', accept: ['rebutton', 'button'] },
          { type: 'multiple', q: 'Which word uses the prefix "dis-"?', options: ['Disappear', 'Reorganise', 'Overheat', 'Redo'], answer: 'Disappear' },
          { type: 'trueFalse', q: '"Deactivate" means to make something inactive', answer: true },
          { type: 'fillBlank', q: 'To mis___ (say something wrongly) - mis + speak', answer: 'speak', accept: ['speak'] },
          { type: 'multiple', q: 'What does "overslept" mean?', options: ['Slept too long', 'Slept before', 'Slept wrongly', 'Slept again'], answer: 'Slept too long' },
          { type: 'trueFalse', q: '"Preview" means to see before', answer: true },
          { type: 'fillBlank', q: 'To pre___ (arrange beforehand)', answer: 'arrange', accept: ['arrange', 'plan', 'order'] },
          { type: 'multiple', q: 'Which prefix means "opposite"?', options: ['dis-', 're-', 'over-', 'pre-'], answer: 'dis-' },
          { type: 'trueFalse', q: '"Miscalculate" means to calculate wrongly', answer: true },
          { type: 'fillBlank', q: 'To de___ (frost) - remove frost', answer: 'frost', accept: ['frost'] },
          { type: 'multiple', q: 'What does "reorganise" mean?', options: ['To organise again', 'To not organise', 'To organise too much', 'To organise before'], answer: 'To organise again' },
          { type: 'trueFalse', q: '"Overestimate" means to estimate too high', answer: true },
          { type: 'fillBlank', q: 'The prefix "mis-" means ___', answer: 'wrongly', accept: ['wrongly', 'incorrectly', 'badly'] },
          { type: 'multiple', q: 'Which word uses the prefix "re-"?', options: ['Rewrite', 'Dislike', 'Overheat', 'Preview'], answer: 'Rewrite' }
        ]
      },
      {
        id: 'y5-english-6',
        name: 'Converting Parts of Speech',
        description: 'Noun/adjective to verb with suffixes -ate, -ise, -ify, -en',
        questions: [
          { type: 'multiple', q: 'What suffix can convert a noun to a verb?', options: ['-ate, -ise, -ify, -en', '-able, -ment, -ous', '-ing, -ed, -ly', '-ness, -less, -ful'], answer: '-ate, -ise, -ify, -en' },
          { type: 'fillBlank', q: 'Adjective: active. Verb: ___ (add -ate)', answer: 'activate', accept: ['activate'] },
          { type: 'trueFalse', q: 'The suffix "-ify" means to make', answer: true },
          { type: 'fillBlank', q: 'Noun: dark. Verb: ___ (add -en)', answer: 'darken', accept: ['darken'] },
          { type: 'multiple', q: 'What verb is created from the adjective "private"?', options: ['Privatise', 'Priven', 'Privateate', 'Privatify'], answer: 'Privatise' },
          { type: 'trueFalse', q: '"Beautify" means to make beautiful', answer: true },
          { type: 'fillBlank', q: 'Adjective: cruel. Verb: ___ (add -ty to make noun, then -ise to make verb)', answer: 'cruelty', accept: ['cruelty', 'cruelise'] },
          { type: 'multiple', q: 'Which verb is formed correctly from an adjective?', options: ['Popular → popularise', 'Quick → quickate', 'Soft → softify', 'Slow → slowen'], answer: 'Popular → popularise' },
          { type: 'trueFalse', q: 'The suffix "-ise" is used in British English', answer: true },
          { type: 'fillBlank', q: 'Noun: legal. Verb: ___ (add -ise)', answer: 'legalise', accept: ['legalise'] },
          { type: 'multiple', q: 'What does "terrify" mean?', options: ['To make terrified', 'To become terrified', 'To show terror', 'To reduce terror'], answer: 'To make terrified' },
          { type: 'trueFalse', q: '"Strengthen" is formed by adding -en to the adjective "strong"', answer: true },
          { type: 'fillBlank', q: 'Adjective: deaf. Verb: ___ (add -en)', answer: 'deafen', accept: ['deafen'] },
          { type: 'multiple', q: 'Which word is formed by converting a noun to a verb?', options: ['Popularise', 'Beautiful', 'Hopefully', 'Kindness'], answer: 'Popularise' },
          { type: 'trueFalse', q: '"Classify" means to place into classes', answer: true },
          { type: 'fillBlank', q: 'Adjective: white. Verb: ___ (add -en)', answer: 'whiten', accept: ['whiten'] },
          { type: 'multiple', q: 'What verb is created from "equal"?', options: ['Equalise', 'Equaten', 'Equalify', 'Equalen'], answer: 'Equalise' },
          { type: 'trueFalse', q: '"Identify" means to make an identity', answer: true },
          { type: 'fillBlank', q: 'Adjective: pale. Verb: ___ (add -en)', answer: 'palen', accept: ['pale'] },
          { type: 'multiple', q: 'Which conversion is correct?', options: ['Noun "organ" → verb "organise"', 'Adjective "sharp" → verb "sharpise"', 'Noun "legal" → verb "legalify"', 'Adjective "clear" → verb "clearate"'], answer: 'Noun "organ" → verb "organise"' }
        ]
      },
      {
        id: 'y5-english-7',
        name: 'Formal & Informal Language',
        description: 'Register, audience, tone',
        questions: [
          { type: 'multiple', q: 'What is register in writing?', options: ['The level of formality in language', 'A list of names', 'The way words are arranged', 'A type of punctuation'], answer: 'The level of formality in language' },
          { type: 'fillBlank', q: 'Formal: "Good morning." Informal: "___"', answer: 'Hi', accept: ['Hi', 'Hey', 'Hello'] },
          { type: 'trueFalse', q: 'You should use formal language when writing a friendly letter', answer: false },
          { type: 'multiple', q: 'Which is formal language?', options: ['I regret to inform you', 'Sorry, but no', 'Can\'t help', 'My bad'], answer: 'I regret to inform you' },
          { type: 'fillBlank', q: 'Formal: "Thank you for your assistance." Informal: "Thanks for the ___"', answer: 'help', accept: ['help'] },
          { type: 'trueFalse', q: 'Tone means the attitude shown in writing', answer: true },
          { type: 'multiple', q: 'Which piece of writing should use formal language?', options: ['A formal letter to a company', 'A text message to a friend', 'A chat with your teacher', 'A note to your parents'], answer: 'A formal letter to a company' },
          { type: 'fillBlank', q: 'The audience for a job application is ___', answer: 'formal', accept: ['formal', 'an employer', 'a professional'] },
          { type: 'trueFalse', q: 'Contractions like "don\'t" are more informal than "do not"', answer: true },
          { type: 'multiple', q: 'Formal or informal? "We are unable to proceed"', options: ['Formal', 'Informal', 'Both', 'Neither'], answer: 'Formal' },
          { type: 'fillBlank', q: 'Informal: "It was brilliant!" Formal: "It was ___"', answer: 'excellent', accept: ['excellent', 'wonderful', 'outstanding'] },
          { type: 'trueFalse', q: 'Using slang is appropriate in formal academic writing', answer: false },
          { type: 'multiple', q: 'Which sentence is more informal?', options: ['Yo, check it out!', 'Observe this, if you would', 'I must draw your attention to', 'Could you please observe'], answer: 'Yo, check it out!' },
          { type: 'fillBlank', q: 'When writing a school report, you should use ___ language', answer: 'formal', accept: ['formal'] },
          { type: 'trueFalse', q: 'Exclamation marks are less formal than full stops', answer: true },
          { type: 'multiple', q: 'Which phrase is formal?', options: ['With regard to', 'About', 'Regarding', 'Concerning'], answer: 'With regard to' },
          { type: 'fillBlank', q: 'Informal: "loads of" Formal: "a ___ amount of"', answer: 'considerable', accept: ['considerable', 'large', 'great'] },
          { type: 'trueFalse', q: 'Audience determines the register you should use', answer: true },
          { type: 'multiple', q: 'Which is least formal?', options: ['Hi mate!', 'Greetings', 'Hello there', 'Good morning'], answer: 'Hi mate!' },
          { type: 'fillBlank', q: 'A letter to a company should start with ___ (formal) or Hi (informal)', answer: 'Dear', accept: ['Dear', 'Greetings'] }
        ]
      },
      {
        id: 'y5-english-8',
        name: 'Spelling Patterns',
        description: 'Silent letters, -ough words, homophones, common misspellings',
        questions: [
          { type: 'fillBlank', q: 'Knot, knife, know - the silent letter is ___', answer: 'k', accept: ['k', 'K'] },
          { type: 'multiple', q: 'Which word has a silent letter?', options: ['Wreck', 'Green', 'Float', 'Magic'], answer: 'Wreck' },
          { type: 'trueFalse', q: 'The word "psychology" has a silent "p"', answer: true },
          { type: 'fillBlank', q: 'The -ough combination in "through" sounds like ___', answer: 'oo', accept: ['oo', 'ew'] },
          { type: 'multiple', q: 'Which pair are homophones (sound the same)?', options: ['Right and write', 'Cut and cute', 'Best and beast', 'Plate and plant'], answer: 'Right and write' },
          { type: 'trueFalse', q: '"Their" and "there" sound the same but have different meanings', answer: true },
          { type: 'fillBlank', q: 'Spell the -ough word: the route through the mountains is very rough. Spelling: ___', answer: 'rough', accept: ['rough'] },
          { type: 'multiple', q: 'Which word is commonly misspelled?', options: ['Occassion (should be occasion)', 'Celebration', 'Dictionary', 'Beautiful'], answer: 'Occassion (should be occasion)' },
          { type: 'trueFalse', q: '"Weather" and "whether" are homophones', answer: false },
          { type: 'fillBlank', q: 'The silent letter in "debt" is ___', answer: 'b', accept: ['b', 'B'] },
          { type: 'multiple', q: 'Which -ough word rhymes with "go"?', options: ['Through', 'Rough', 'Dough', 'Cough'], answer: 'Through' },
          { type: 'trueFalse', q: '"Piece" and "peace" are homophones', answer: true },
          { type: 'fillBlank', q: 'The silent letter in "castle" is ___', answer: 't', accept: ['t', 'T'] },
          { type: 'multiple', q: 'Which word contains a silent "gh"?', options: ['Night', 'Light', 'Weight', 'All of these'], answer: 'All of these' },
          { type: 'trueFalse', q: '"Alright" and "all right" are both acceptable spellings', answer: true },
          { type: 'fillBlank', q: 'Common misspelling: "definite" is often misspelled as "definitly". Correct spelling: ___', answer: 'definite', accept: ['definite'] },
          { type: 'multiple', q: 'Which is a common misspelling?', options: ['Occurrance (should be occurrence)', 'Definitely', 'Separate', 'Beginning'], answer: 'Occurrance (should be occurrence)' },
          { type: 'trueFalse', q: 'The silent letter in "honest" is "h"', answer: true },
          { type: 'fillBlank', q: 'Homophones: "one" sounds like ___', answer: 'won', accept: ['won'] },
          { type: 'multiple', q: 'Which -ough word means "finished"?', options: ['Though', 'Through', 'Thorough', 'Thought'], answer: 'Thorough' }
        ]
      }
    ]
  },
  science: {
    name: 'Science',
    icon: '🔬',
    color: '#9C27B0',
    lessons: [
      {
        id: 'y5-science-1',
        name: 'Living Things & Life Cycles',
        description: 'Sexual and asexual reproduction, life cycles',
        questions: [
          { type: 'multiple', q: 'Which plants reproduce asexually?', options: ['Strawberries (runners)', 'Roses (seeds)', 'Tulips (bulbs)', 'All of these'], answer: 'All of these' },
          { type: 'fillBlank', q: 'The life cycle of a butterfly has ___ stages', answer: '4', accept: ['4', 'four'] },
          { type: 'trueFalse', q: 'Sexual reproduction requires two parents', answer: true },
          { type: 'multiple', q: 'What are the four stages of a butterfly life cycle?', options: ['Egg, larva, pupa, adult', 'Egg, caterpillar, chrysalis, butterfly', 'Both A and B', 'Nymph, larva, pupa, adult'], answer: 'Both A and B' },
          { type: 'fillBlank', q: 'A frog starts as an ___ before becoming a tadpole', answer: 'egg', accept: ['egg'] },
          { type: 'trueFalse', q: 'Asexual reproduction requires two parents', answer: false },
          { type: 'multiple', q: 'Which animal has a metamorphosis life cycle?', options: ['Frog', 'Insect', 'Bird', 'Both A and B'], answer: 'Both A and B' },
          { type: 'trueFalse', q: 'Seeds are produced by sexual reproduction in plants', answer: true },
          { type: 'fillBlank', q: 'Strawberry plants reproduce asexually using ___', answer: 'runners', accept: ['runners', 'stolons'] },
          { type: 'multiple', q: 'What does a tadpole become?', options: ['A frog', 'A newt', 'A fish', 'A lizard'], answer: 'A frog' },
          { type: 'trueFalse', q: 'Flowers produce seeds for reproduction', answer: true },
          { type: 'fillBlank', q: 'In the insect life cycle, the ___ is the resting stage', answer: 'pupa', accept: ['pupa', 'pupae'] },
          { type: 'multiple', q: 'Which shows complete metamorphosis?', options: ['Butterfly', 'Grasshopper', 'Dragonfly', 'All have incomplete metamorphosis'], answer: 'Butterfly' },
          { type: 'trueFalse', q: 'Potatoes reproduce asexually by growing new plants from tubers', answer: true },
          { type: 'fillBlank', q: 'The eggs of an insect hatch into ___', answer: 'larvae', accept: ['larvae', 'larva'] },
          { type: 'multiple', q: 'Which plant reproduces asexually from bulbs?', options: ['Daffodils', 'Tulips', 'Onions', 'All of these'], answer: 'All of these' },
          { type: 'trueFalse', q: 'A bird\'s life cycle includes eggs and chicks', answer: true },
          { type: 'fillBlank', q: 'Asexual reproduction creates offspring with ___ genes as the parent', answer: 'identical', accept: ['identical', 'same'] },
          { type: 'multiple', q: 'What stage follows the pupa in a butterfly?', options: ['Adult butterfly', 'Egg', 'Larva', 'Chrysalis'], answer: 'Adult butterfly' },
          { type: 'trueFalse', q: 'Ferns reproduce asexually using spores', answer: true }
        ]
      },
      {
        id: 'y5-science-2',
        name: 'Animals & Humans',
        description: 'Growth, development, changes in old age, gestation',
        questions: [
          { type: 'multiple', q: 'How long is the human gestation period?', options: ['About 9 months', 'About 6 months', 'About 12 months', 'About 3 months'], answer: 'About 9 months' },
          { type: 'fillBlank', q: 'A newborn baby is called an ___', answer: 'infant', accept: ['infant', 'baby'] },
          { type: 'trueFalse', q: 'Humans grow continuously throughout their entire life', answer: false },
          { type: 'multiple', q: 'What is the developmental stage after infancy?', options: ['Childhood', 'Adulthood', 'Adolescence', 'Toddlerhood'], answer: 'Childhood' },
          { type: 'fillBlank', q: 'During puberty, the body goes through physical ___', answer: 'changes', accept: ['changes'] },
          { type: 'trueFalse', q: 'A mammal develops inside the mother\'s womb', answer: true },
          { type: 'multiple', q: 'Which gestation period is longest?', options: ['Elephant: 22 months', 'Cow: 9 months', 'Dog: 2 months', 'Human: 9 months'], answer: 'Elephant: 22 months' },
          { type: 'trueFalse', q: 'Growth and development are the same thing', answer: false },
          { type: 'fillBlank', q: 'The ___ is where the baby develops in the mother', answer: 'womb', accept: ['womb', 'uterus', 'uterine'] },
          { type: 'multiple', q: 'What happens in old age?', options: ['Hair turns grey', 'Skin becomes wrinkled', 'Bones become weaker', 'All of these'], answer: 'All of these' },
          { type: 'trueFalse', q: 'The gestation period for humans is the same for all species', answer: false },
          { type: 'fillBlank', q: 'Children lose their milk teeth and grow ___ teeth', answer: 'permanent', accept: ['permanent', 'adult'] },
          { type: 'multiple', q: 'At what age do most humans reach full growth?', options: ['Late teens/early 20s', '12 years old', '30 years old', 'Never stop growing'], answer: 'Late teens/early 20s' },
          { type: 'trueFalse', q: 'A cat\'s gestation period is longer than a human\'s', answer: false },
          { type: 'fillBlank', q: 'The ___ umbilical cord connects the baby to the mother during pregnancy', answer: 'umbilical', accept: ['umbilical'] },
          { type: 'multiple', q: 'Which animal has the shortest gestation period?', options: ['Hamster: 16 days', 'Rabbit: 31 days', 'Mouse: 19 days', 'Hamster'], answer: 'Hamster: 16 days' },
          { type: 'trueFalse', q: 'Muscles and bones weaken with age', answer: true },
          { type: 'fillBlank', q: 'A ___ is a young animal after it is born', answer: 'offspring', accept: ['offspring', 'baby'] },
          { type: 'multiple', q: 'What supports the baby before birth?', options: ['The umbilical cord', 'The placenta', 'The womb', 'All of these'], answer: 'All of these' },
          { type: 'trueFalse', q: 'Infants can support their own head immediately after birth', answer: false }
        ]
      },
      {
        id: 'y5-science-3',
        name: 'Properties of Materials',
        description: 'Dissolving, reversible/irreversible changes, thermal conductors',
        questions: [
          { type: 'multiple', q: 'What is dissolving?', options: ['When a solid mixes completely in a liquid', 'When a liquid evaporates', 'When a solid breaks apart', 'When a liquid freezes'], answer: 'When a solid mixes completely in a liquid' },
          { type: 'fillBlank', q: 'Sugar in water is a ___ change (can be reversed)', answer: 'reversible', accept: ['reversible'] },
          { type: 'trueFalse', q: 'A reversible change can be undone', answer: true },
          { type: 'multiple', q: 'Which is an irreversible change?', options: ['Cooking an egg', 'Freezing water', 'Melting ice', 'Dissolving salt'], answer: 'Cooking an egg' },
          { type: 'fillBlank', q: 'When a liquid turns into a gas, it ___', answer: 'evaporates', accept: ['evaporates'] },
          { type: 'trueFalse', q: 'Burning paper is a reversible change', answer: false },
          { type: 'multiple', q: 'What does a thermal conductor do?', options: ['Conducts heat easily', 'Blocks heat', 'Absorbs heat', 'Reflects heat'], answer: 'Conducts heat easily' },
          { type: 'fillBlank', q: 'A thermal insulator ___', answer: 'prevents heat transfer', accept: ['prevents heat transfer', 'blocks heat', 'stops heat'] },
          { type: 'trueFalse', q: 'Metal is a good thermal conductor', answer: true },
          { type: 'multiple', q: 'Which material is a good insulator?', options: ['Wool', 'Metal', 'Water', 'Glass'], answer: 'Wool' },
          { type: 'trueFalse', q: 'All irreversible changes involve heat', answer: false },
          { type: 'fillBlank', q: 'When water freezes, it becomes ___', answer: 'ice', accept: ['ice'] },
          { type: 'multiple', q: 'What is the opposite of freezing?', options: ['Melting', 'Evaporating', 'Condensing', 'Boiling'], answer: 'Melting' },
          { type: 'trueFalse', q: 'Dissolving and melting are the same process', answer: false },
          { type: 'fillBlank', q: 'Water changes from liquid to solid at ___°C', answer: '0', accept: ['0', 'zero'] },
          { type: 'multiple', q: 'Which is an electrical conductor?', options: ['Copper', 'Rubber', 'Plastic', 'Wood'], answer: 'Copper' },
          { type: 'trueFalse', q: 'An electrical insulator prevents current from flowing', answer: true },
          { type: 'fillBlank', q: 'Mixing oil and water demonstrates a ___ mixture', answer: 'immiscible', accept: ['immiscible'] },
          { type: 'multiple', q: 'What happens when salt dissolves in water?', options: ['It disappears completely in the liquid', 'It still exists but cannot be seen', 'Crystals form', 'Both A and B'], answer: 'Both A and B' },
          { type: 'trueFalse', q: 'Cooling water until it freezes is a reversible change', answer: true }
        ]
      },
      {
        id: 'y5-science-4',
        name: 'Earth & Space',
        description: 'Solar system, planets, Sun, Earth rotation, Moon phases',
        questions: [
          { type: 'multiple', q: 'What is at the centre of our solar system?', options: ['The Sun', 'Earth', 'The Moon', 'Jupiter'], answer: 'The Sun' },
          { type: 'fillBlank', q: 'Earth rotates on its axis every ___ hours', answer: '24', accept: ['24', 'twenty-four'] },
          { type: 'trueFalse', q: 'The Sun is a star', answer: true },
          { type: 'multiple', q: 'What causes day and night?', options: ['Earth\'s rotation', 'Earth\'s orbit', 'The Moon', 'Atmosphere'], answer: 'Earth\'s rotation' },
          { type: 'fillBlank', q: 'There are ___ planets in our solar system', answer: '8', accept: ['8', 'eight'] },
          { type: 'trueFalse', q: 'Mercury is the closest planet to the Sun', answer: true },
          { type: 'multiple', q: 'What are the phases of the Moon?', options: ['Different amounts of Moon visible from Earth', 'Changes in the Moon\'s size', 'The Moon\'s orbit stages', 'Answer A (they appear different due to Earth\'s view)'], answer: 'Answer A (they appear different due to Earth\'s view)' },
          { type: 'fillBlank', q: 'A new moon occurs when the Moon is between the ___ and Earth', answer: 'Sun', accept: ['Sun'] },
          { type: 'trueFalse', q: 'The Moon orbits Earth', answer: true },
          { type: 'fillBlank', q: 'Earth orbits the Sun every ___ days', answer: '365', accept: ['365', '365.25'] },
          { type: 'multiple', q: 'Which planet is known as the "Red Planet"?', options: ['Mars', 'Venus', 'Jupiter', 'Saturn'], answer: 'Mars' },
          { type: 'trueFalse', q: 'The full moon is the brightest phase', answer: true },
          { type: 'fillBlank', q: 'The Sun is at the centre of a ___ system', answer: 'solar', accept: ['solar'] },
          { type: 'multiple', q: 'What causes seasons on Earth?', options: ['The tilt of Earth\'s axis as it orbits the Sun', 'The distance from the Sun', 'The Moon\'s position', 'The Sun\'s rotation'], answer: 'The tilt of Earth\'s axis as it orbits the Sun' },
          { type: 'trueFalse', q: 'Jupiter is the largest planet in our solar system', answer: true },
          { type: 'fillBlank', q: 'The Moon takes about ___ days to orbit Earth', answer: '28', accept: ['28', 'twenty-eight'] },
          { type: 'multiple', q: 'Which planet has rings?', options: ['Saturn', 'Jupiter', 'Uranus', 'All have rings'], answer: 'Saturn' },
          { type: 'trueFalse', q: 'Venus is the second planet from the Sun', answer: true },
          { type: 'fillBlank', q: 'Earth is the ___ planet from the Sun', answer: 'third', accept: ['third', '3rd'] },
          { type: 'multiple', q: 'What is the atmosphere?', options: ['Layer of air around Earth', 'Part of the Sun', 'The space between planets', 'The Moon\'s surface'], answer: 'Layer of air around Earth' }
        ]
      },
      {
        id: 'y5-science-5',
        name: 'Forces',
        description: 'Gravity, air/water resistance, friction, mechanisms',
        questions: [
          { type: 'multiple', q: 'What is gravity?', options: ['A force that pulls objects towards Earth', 'A force that pushes objects away', 'A type of friction', 'A type of spring'], answer: 'A force that pulls objects towards Earth' },
          { type: 'fillBlank', q: 'Air resistance opposes ___ motion', answer: 'motion', accept: ['motion', 'moving'] },
          { type: 'trueFalse', q: 'Friction opposes motion between surfaces', answer: true },
          { type: 'multiple', q: 'What reduces friction?', options: ['Lubricants like oil', 'Rough surfaces', 'Loose joints', 'Heavy objects'], answer: 'Lubricants like oil' },
          { type: 'fillBlank', q: 'Water resistance is a force that opposes ___ through water', answer: 'movement', accept: ['movement', 'motion'] },
          { type: 'trueFalse', q: 'A parachute uses air resistance to slow descent', answer: true },
          { type: 'multiple', q: 'What is a lever?', options: ['A simple machine with a rigid bar', 'A type of pulley', 'A spring mechanism', 'A type of ramp'], answer: 'A simple machine with a rigid bar' },
          { type: 'fillBlank', q: 'A ___ is a wheel with a groove that holds a rope', answer: 'pulley', accept: ['pulley'] },
          { type: 'trueFalse', q: 'A pulley can change the direction of force', answer: true },
          { type: 'multiple', q: 'What do gears do?', options: ['Transfer motion and change speed/force', 'Create friction', 'Reduce gravity', 'Create resistance'], answer: 'Transfer motion and change speed/force' },
          { type: 'trueFalse', q: 'Friction always slows things down', answer: false },
          { type: 'fillBlank', q: 'A ramp reduces the ___ needed to push something uphill', answer: 'force', accept: ['force'] },
          { type: 'multiple', q: 'What does a wheel and axle do?', options: ['Reduce the force needed to turn something', 'Increase friction', 'Stop motion', 'Create gravity'], answer: 'Reduce the force needed to turn something' },
          { type: 'trueFalse', q: 'Friction produces heat', answer: true },
          { type: 'fillBlank', q: 'A skydiver falls due to ___', answer: 'gravity', accept: ['gravity'] },
          { type: 'multiple', q: 'Which reduces air resistance when cycling?', options: ['Streamlined shapes', 'Large surface area', 'Loose clothing', 'Low speed'], answer: 'Streamlined shapes' },
          { type: 'trueFalse', q: 'A screw is a simple machine used for holding or fastening', answer: true },
          { type: 'fillBlank', q: 'Springs store and release ___', answer: 'energy', accept: ['energy'] },
          { type: 'multiple', q: 'What is the fulcrum of a lever?', options: ['The pivot point', 'The load', 'The effort', 'The resistance'], answer: 'The pivot point' },
          { type: 'trueFalse', q: 'A wedge is used to split or separate objects', answer: true }
        ]
      },
      {
        id: 'y5-science-6',
        name: 'Working Scientifically',
        description: 'Planning investigations, variables, accurate measurement, data',
        questions: [
          { type: 'multiple', q: 'What is a fair test?', options: ['An experiment where only one variable changes', 'An experiment everyone enjoys', 'An experiment with many variables', 'An experiment with no results'], answer: 'An experiment where only one variable changes' },
          { type: 'fillBlank', q: 'The variable you change is the ___ variable', answer: 'independent', accept: ['independent'] },
          { type: 'trueFalse', q: 'You should keep all other conditions the same except the independent variable', answer: true },
          { type: 'multiple', q: 'What is a control variable?', options: ['A variable that stays the same', 'The variable you measure', 'The variable you change', 'A variable you ignore'], answer: 'A variable that stays the same' },
          { type: 'fillBlank', q: 'The variable you measure is the ___ variable', answer: 'dependent', accept: ['dependent'] },
          { type: 'trueFalse', q: 'A hypothesis is an educated guess based on knowledge', answer: true },
          { type: 'fillBlank', q: 'To measure accurately, you should use ___ equipment', answer: 'appropriate', accept: ['appropriate', 'precise'] },
          { type: 'multiple', q: 'What should you do with results?', options: ['Record them immediately', 'Ignore them if unexpected', 'Change them to match the hypothesis', 'Discard unreliable data carefully'], answer: 'Record them immediately' },
          { type: 'trueFalse', q: 'Repeating an experiment improves reliability', answer: true },
          { type: 'fillBlank', q: 'Data can be presented using tables, graphs, or ___', answer: 'charts', accept: ['charts', 'diagrams'] },
          { type: 'multiple', q: 'What is the first step in a fair test?', options: ['Make a prediction', 'Plan the experiment', 'Collect equipment', 'Analyze results'], answer: 'Plan the experiment' },
          { type: 'trueFalse', q: 'Precise measurements use appropriate equipment', answer: true },
          { type: 'fillBlank', q: 'A ___ is a diagram showing the relationship between variables', answer: 'graph', accept: ['graph', 'chart'] },
          { type: 'multiple', q: 'What conclusion should you draw?', options: ['Based on evidence from your results', 'Whatever supports your hypothesis', 'Whatever is interesting', 'Before you do the experiment'], answer: 'Based on evidence from your results' },
          { type: 'trueFalse', q: 'It is important to identify anomalies (unusual results)', answer: true },
          { type: 'fillBlank', q: 'Variables that might affect results must be ___', answer: 'controlled', accept: ['controlled'] },
          { type: 'multiple', q: 'How should you record measurements?', options: ['To the nearest appropriate unit', 'To the nearest whole number', 'As roughly as possible', 'Only if they confirm your hypothesis'], answer: 'To the nearest appropriate unit' },
          { type: 'trueFalse', q: 'A line graph shows how one variable changes with another', answer: true },
          { type: 'fillBlank', q: 'Carrying out an experiment multiple times checks for ___ and errors', answer: 'anomalies', accept: ['anomalies', 'errors'] },
          { type: 'multiple', q: 'What makes evidence reliable?', options: ['Careful measurement and repeated trials', 'Having unexpected results', 'Quick data collection', 'No control variables'], answer: 'Careful measurement and repeated trials' }
        ]
      }
    ]
  },
  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#FF5722',
    lessons: [
      {
        id: 'y5-french-1',
        name: 'Hobbies & Sports',
        description: 'Je joue au football, Je fais de la natation, J\'aime lire',
        questions: [
          { type: 'fillBlank', q: '"I play football" in French is: Je joue au ___', answer: 'football', accept: ['football'] },
          { type: 'multiple', q: 'What does "Je fais de la natation" mean?', options: ['I do swimming', 'I do football', 'I like swimming', 'I want to swim'], answer: 'I do swimming' },
          { type: 'trueFalse', q: '"J\'aime lire" means "I like to read"', answer: true },
          { type: 'fillBlank', q: '"I play tennis" is: Je joue au ___', answer: 'tennis', accept: ['tennis'] },
          { type: 'multiple', q: 'How do you say "I like basketball" in French?', options: ['J\'aime le basketball', 'Je joue au basketball', 'Je fais du basketball', 'Both B and C'], answer: 'Both B and C' },
          { type: 'trueFalse', q: '"Je joue du piano" means "I play the piano"', answer: true },
          { type: 'fillBlank', q: '"I do gymnastics" is: Je fais de la ___', answer: 'gymnastique', accept: ['gymnastique', 'gym'] },
          { type: 'multiple', q: 'What sport uses "le cyclisme"?', options: ['Cycling', 'Swimming', 'Tennis', 'Football'], answer: 'Cycling' },
          { type: 'trueFalse', q: '"J\'adore jouer au rugby" means "I love playing rugby"', answer: true },
          { type: 'fillBlank', q: '"I like dancing" is: J\'aime ___', answer: 'danser', accept: ['danser'] },
          { type: 'multiple', q: 'Which hobby uses "je dessine"?', options: ['I draw', 'I listen', 'I read', 'I sing'], answer: 'I draw' },
          { type: 'trueFalse', q: '"Je joue au hockey" means "I play hockey"', answer: true },
          { type: 'fillBlank', q: '"I love swimming" is: J\'adore ___', answer: 'la natation', accept: ['nager', 'la natation'] },
          { type: 'multiple', q: 'What is "la musculation"?', options: ['Weight training/gym', 'Basketball', 'Volleyball', 'Badminton'], answer: 'Weight training/gym' },
          { type: 'trueFalse', q: '"J\'aime faire du skateboard" means "I like skateboarding"', answer: true },
          { type: 'fillBlank', q: '"I play volleyball" is: Je joue au ___', answer: 'volley', accept: ['volley', 'volleyball'] },
          { type: 'multiple', q: 'Which phrase means "I like singing"?', options: ['J\'aime chanter', 'Je chante bien', 'Je fais du chant', 'Both A and C'], answer: 'Both A and C' },
          { type: 'trueFalse', q: '"Je fais du ski" means "I do skiing"', answer: true },
          { type: 'fillBlank', q: '"I play cricket" is: Je joue au ___', answer: 'cricket', accept: ['cricket'] },
          { type: 'multiple', q: 'What does "Je joue de la guitare" mean?', options: ['I play the guitar', 'I play guitar sport', 'I like guitar', 'I listen to guitar'], answer: 'I play the guitar' }
        ]
      },
      {
        id: 'y5-french-2',
        name: 'Telling the Time',
        description: 'Quelle heure est-il?, Il est trois heures, et demie, et quart, moins le quart',
        questions: [
          { type: 'fillBlank', q: '"What time is it?" in French is: ___ heure est-il?', answer: 'Quelle', accept: ['Quelle'] },
          { type: 'multiple', q: 'How do you say 3 o\'clock in French?', options: ['Il est trois heures', 'Il est trois', 'Il est 3h', 'C\'est trois heures'], answer: 'Il est trois heures' },
          { type: 'trueFalse', q: '"Et demie" means "and half"', answer: true },
          { type: 'fillBlank', q: '"3:30" is expressed as: Il est trois heures et ___', answer: 'demie', accept: ['demie'] },
          { type: 'multiple', q: 'What does "et quart" mean?', options: ['Quarter past (add 15 minutes)', 'Half past', 'Quarter to', 'Twenty past'], answer: 'Quarter past (add 15 minutes)' },
          { type: 'trueFalse', q: '"Il est neuf heures et quart" means 9:15', answer: true },
          { type: 'fillBlank', q: '"4:45" is: Il est ___ moins le quart', answer: 'cinq', accept: ['cinq'] },
          { type: 'multiple', q: 'How do you say 12 o\'clock noon in French?', options: ['Il est midi', 'Il est minuit', 'Il est douze heures', 'Il est demi-jour'], answer: 'Il est midi' },
          { type: 'trueFalse', q: '"Moins le quart" means "quarter to"', answer: true },
          { type: 'fillBlank', q: '"6:00" in French is: Il est ___ heures', answer: 'six', accept: ['six'] },
          { type: 'multiple', q: '"Il est deux heures moins dix" means what time?', options: ['1:50', '2:10', '2:50', '2:00'], answer: '1:50' },
          { type: 'trueFalse', q: '"Minuit" means midnight', answer: true },
          { type: 'fillBlank', q: '"8:20" is: Il est huit heures et ___', answer: 'vingt', accept: ['vingt'] },
          { type: 'multiple', q: 'How do you ask "What time is it?"', options: ['Quelle heure est-il?', 'Quel heure est-ce?', 'C\'est quelle heure?', 'Both A and C'], answer: 'Both A and C' },
          { type: 'trueFalse', q: '"Il est midi et quart" means 12:15', answer: true },
          { type: 'fillBlank', q: '"10:30" is: Il est dix heures et ___', answer: 'demie', accept: ['demie'] },
          { type: 'multiple', q: '"Il est une heure" is what time?', options: ['1 o\'clock', '11 o\'clock', '1:00 PM', 'Both A and C'], answer: 'Both A and C' },
          { type: 'trueFalse', q: '"Et" means "and" when telling time', answer: true },
          { type: 'fillBlank', q: '"7:45" is: Il est ___ heures moins le quart', answer: 'huit', accept: ['huit'] },
          { type: 'multiple', q: 'How is "minus" expressed when telling time?', options: ['Moins', 'Sauf', 'Pas', 'Non'], answer: 'Moins' }
        ]
      },
      {
        id: 'y5-french-3',
        name: 'Places in Town',
        description: 'la boulangerie, la bibliothèque, le parc, le supermarché, l\'école, l\'hôpital',
        questions: [
          { type: 'fillBlank', q: '"The bakery" is: la ___', answer: 'boulangerie', accept: ['boulangerie'] },
          { type: 'multiple', q: 'Where would you borrow books?', options: ['La bibliothèque', 'La boulangerie', 'Le supermarché', 'L\'hôpital'], answer: 'La bibliothèque' },
          { type: 'trueFalse', q: '"Le parc" means "the park"', answer: true },
          { type: 'fillBlank', q: '"The supermarket" is: le ___', answer: 'supermarché', accept: ['supermarché'] },
          { type: 'multiple', q: 'Where do you go to school?', options: ['À l\'école', 'À la boulangerie', 'Au supermarché', 'À l\'hôpital'], answer: 'À l\'école' },
          { type: 'trueFalse', q: '"L\'hôpital" means "the hospital"', answer: true },
          { type: 'fillBlank', q: '"The library" is: la ___', answer: 'bibliothèque', accept: ['bibliothèque'] },
          { type: 'multiple', q: 'Where would you buy bread?', options: ['À la boulangerie', 'À la bibliothèque', 'Au supermarché', 'À l\'école'], answer: 'À la boulangerie' },
          { type: 'trueFalse', q: '"Le restaurant" is a place where you eat', answer: true },
          { type: 'fillBlank', q: '"The park" is: le ___', answer: 'parc', accept: ['parc'] },
          { type: 'multiple', q: 'What do you do at "la piscine"?', options: ['Swim', 'Shop', 'Read books', 'Go to school'], answer: 'Swim' },
          { type: 'trueFalse', q: '"La gare" means "the train station"', answer: true },
          { type: 'fillBlank', q: '"The church" is: l\'___', answer: 'église', accept: ['église'] },
          { type: 'multiple', q: 'Where would you see a doctor?', options: ['À l\'hôpital', 'À l\'école', 'À la bibliothèque', 'Au cinéma'], answer: 'À l\'hôpital' },
          { type: 'trueFalse', q: '"Le cinéma" is where you watch films', answer: true },
          { type: 'fillBlank', q: '"The school" is: l\'___', answer: 'école', accept: ['école'] },
          { type: 'multiple', q: 'Which place sells groceries?', options: ['Le supermarché', 'La boulangerie', 'La gare', 'Le cinéma'], answer: 'Le supermarché' },
          { type: 'trueFalse', q: '"Le musée" is the museum', answer: true },
          { type: 'fillBlank', q: '"The hospital" is: l\'___', answer: 'hôpital', accept: ['hôpital'] },
          { type: 'multiple', q: 'Where would you play sports?', options: ['Au stade/Au parc', 'À la bibliothèque', 'À la boulangerie', 'Au cinéma'], answer: 'Au stade/Au parc' }
        ]
      },
      {
        id: 'y5-french-4',
        name: 'Clothes',
        description: 'un pantalon, une jupe, un t-shirt, des chaussures, un manteau, une robe',
        questions: [
          { type: 'fillBlank', q: '"Trousers" in French is: un ___', answer: 'pantalon', accept: ['pantalon'] },
          { type: 'multiple', q: 'What is "une jupe"?', options: ['A skirt', 'A dress', 'Trousers', 'A coat'], answer: 'A skirt' },
          { type: 'trueFalse', q: '"Un t-shirt" is a t-shirt', answer: true },
          { type: 'fillBlank', q: '"Shoes" are: des ___', answer: 'chaussures', accept: ['chaussures'] },
          { type: 'multiple', q: 'What is "un manteau"?', options: ['A coat', 'A hat', 'Gloves', 'A sweater'], answer: 'A coat' },
          { type: 'trueFalse', q: '"Une robe" means "a dress"', answer: true },
          { type: 'fillBlank', q: '"A hat" is: un ___', answer: 'chapeau', accept: ['chapeau'] },
          { type: 'multiple', q: 'What clothing do you wear on your feet?', options: ['Des chaussures', 'Un pantalon', 'Un manteau', 'Une ceinture'], answer: 'Des chaussures' },
          { type: 'trueFalse', q: '"Des gants" means "gloves"', answer: true },
          { type: 'fillBlank', q: '"A jumper/sweater" is: un ___', answer: 'pull', accept: ['pull', 'pullover'] },
          { type: 'multiple', q: 'What is "une ceinture"?', options: ['A belt', 'A scarf', 'Socks', 'A shirt'], answer: 'A belt' },
          { type: 'trueFalse', q: '"Un chemise" is a shirt', answer: false },
          { type: 'fillBlank', q: '"Socks" are: des ___', answer: 'chaussettes', accept: ['chaussettes'] },
          { type: 'multiple', q: 'What is "une écharpe"?', options: ['A scarf', 'A skirt', 'A coat', 'Gloves'], answer: 'A scarf' },
          { type: 'trueFalse', q: '"Un veston" is a jacket', answer: true },
          { type: 'fillBlank', q: '"Trousers" (plural) in French: un ___', answer: 'pantalon', accept: ['pantalon'] },
          { type: 'multiple', q: 'What is "un short"?', options: ['Shorts', 'A shirt', 'A skirt', 'A coat'], answer: 'Shorts' },
          { type: 'trueFalse', q: '"Une blouse" is a blouse', answer: true },
          { type: 'fillBlank', q: '"A tie" is: une ___', answer: 'cravate', accept: ['cravate'] },
          { type: 'multiple', q: 'What would you wear in winter to stay warm?', options: ['Un manteau', 'Un t-shirt', 'Des chaussures', 'Une ceinture'], answer: 'Un manteau' }
        ]
      },
      {
        id: 'y5-french-5',
        name: 'Numbers 50-100 & Prices',
        description: 'combien ça coûte?, ça coûte ... euros',
        questions: [
          { type: 'fillBlank', q: '"How much does it cost?" is: ___ ça coûte?', answer: 'Combien', accept: ['Combien'] },
          { type: 'multiple', q: 'What is the French number for 50?', options: ['Cinquante', 'Soixante', 'Quarante', 'Trente'], answer: 'Cinquante' },
          { type: 'trueFalse', q: '"Soixante" is 60', answer: true },
          { type: 'fillBlank', q: '70 in French is: soixante-___', answer: 'dix', accept: ['dix'] },
          { type: 'multiple', q: 'What is 80 in French?', options: ['Quatre-vingts', 'Huitante', 'Octante', 'Octante'], answer: 'Quatre-vingts' },
          { type: 'trueFalse', q: '"Quatre-vingt-dix" is 90', answer: true },
          { type: 'fillBlank', q: '100 in French is: ___', answer: 'cent', accept: ['cent'] },
          { type: 'multiple', q: '"Ça coûte cinq euros" means what?', options: ['It costs five euros', 'It costs fifty euros', 'That is five euros', 'It is worth euros'], answer: 'It costs five euros' },
          { type: 'trueFalse', q: '"Combien ça coûte?" is a question about price', answer: true },
          { type: 'fillBlank', q: 'How do you say 55? Cinquante-___', answer: 'cinq', accept: ['cinq'] },
          { type: 'multiple', q: 'What is 65 in French?', options: ['Soixante-cinq', 'Soixante-dix', 'Septante-cinq', 'Cinquante-cinq'], answer: 'Soixante-cinq' },
          { type: 'trueFalse', q: '"Quatre-vingts" has an "s" at the end when followed by another number', answer: false },
          { type: 'fillBlank', q: '75 in French is: soixante-quinze or ___-quinze', answer: 'septante', accept: ['septante'] },
          { type: 'multiple', q: '"Ça coûte quinze euros" means', options: ['It costs fifteen euros', 'That is fifty euros', 'It will cost euros', 'It is worth euros'], answer: 'It costs fifteen euros' },
          { type: 'trueFalse', q: '95 is "quatre-vingt-quinze"', answer: true },
          { type: 'fillBlank', q: '"It costs 20 euros" is: Ça coûte vingt ___', answer: 'euros', accept: ['euros'] },
          { type: 'multiple', q: 'What is 51 in French?', options: ['Cinquante-et-un', 'Cinquante-un', 'Cinquantième', 'Cinquantunum'], answer: 'Cinquante-et-un' },
          { type: 'trueFalse', q: '"Soixante-dix" means 70', answer: true },
          { type: 'fillBlank', q: 'To ask "How much?", say: ___?', answer: 'Combien', accept: ['Combien', 'Combien ça coûte'] },
          { type: 'multiple', q: 'What is 86 in French?', options: ['Quatre-vingt-six', 'Huitante-six', 'Octante-six', 'Quatre-vinetage-six'], answer: 'Quatre-vingt-six' }
        ]
      }
    ]
  }
};
