// ==========================================
// YEAR 2 CURRICULUM DATA - Expanded Edition
// ==========================================
// Format: window.YEAR_2_DATA with subjects, each with 20-25 questions per lesson

window.YEAR_2_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        id: 'y2-maths-1',
        title: 'Place Value to 100',
        description: 'Understanding tens and ones, comparing and ordering numbers',
        questions: [
          { type: 'multiple', q: 'What is the value of the 3 in 35?', options: ['3', '30', '35', '300'], answer: 1 },
          { type: 'multiple', q: 'How many tens are in 47?', options: ['4', '7', '40', '47'], answer: 0 },
          { type: 'multiple', q: 'How many ones are in 52?', options: ['5', '2', '50', '52'], answer: 1 },
          { type: 'multiple', q: 'What is 3 tens and 6 ones?', options: ['36', '63', '306', '360'], answer: 0 },
          { type: 'multiple', q: 'Which number is bigger: 47 or 74?', options: ['47', '74', 'They are the same', 'Cannot tell'], answer: 1 },
          { type: 'trueFalse', q: '83 is greater than 38', answer: true },
          { type: 'multiple', q: 'What comes after 59?', options: ['58', '60', '69', '50'], answer: 1 },
          { type: 'multiple', q: 'What comes before 40?', options: ['41', '39', '50', '30'], answer: 1 },
          { type: 'multiple', q: 'Order these numbers from smallest to largest: 25, 52, 35', options: ['25, 35, 52', '52, 35, 25', '35, 25, 52', '25, 52, 35'], answer: 0 },
          { type: 'multiple', q: '20 + 8 = ?', options: ['28', '82', '12', '02'], answer: 0 },
          { type: 'trueFalse', q: '99 is less than 89', answer: false },
          { type: 'multiple', q: 'What number has 8 tens and 2 ones?', options: ['28', '82', '208', '82'], answer: 1 },
          { type: 'multiple', q: 'On a number line, which is between 30 and 40?', options: ['25', '35', '45', '50'], answer: 1 },
          { type: 'multiple', q: 'How many tens and ones in 64?', options: ['6 tens, 4 ones', '4 tens, 6 ones', '60 tens, 4 ones', '64 tens, 0 ones'], answer: 0 },
          { type: 'trueFalse', q: '50 + 5 = 55', answer: true },
          { type: 'multiple', q: 'Which digit is in the tens place of 71?', options: ['7', '1', '71', '17'], answer: 0 },
          { type: 'multiple', q: 'Which digit is in the ones place of 48?', options: ['4', '8', '48', '40'], answer: 1 },
          { type: 'multiple', q: 'What is the next multiple of 10 after 50?', options: ['40', '60', '51', '55'], answer: 1 },
          { type: 'multiple', q: 'Compare: 76 is ___ 67', options: ['less than', 'greater than', 'equal to', 'smaller than'], answer: 1 },
          { type: 'trueFalse', q: 'The number 90 has 9 tens and 0 ones', answer: true },
          { type: 'multiple', q: 'What number is 10 more than 35?', options: ['25', '34', '45', '36'], answer: 2 },
          { type: 'multiple', q: 'What number is 10 less than 62?', options: ['52', '72', '61', '63'], answer: 0 },
          { type: 'multiple', q: 'Order these numbers: 81, 18, 88', options: ['18, 81, 88', '88, 81, 18', '81, 18, 88', '18, 88, 81'], answer: 0 },
          { type: 'trueFalse', q: '45 is between 40 and 50', answer: true }
        ]
      },
      {
        id: 'y2-maths-2',
        title: 'Addition & Subtraction within 100',
        description: 'Number bonds, column method, mental strategies',
        questions: [
          { type: 'multiple', q: '23 + 12 = ?', options: ['11', '25', '35', '32'], answer: 2 },
          { type: 'multiple', q: '45 - 20 = ?', options: ['65', '25', '35', '46'], answer: 1 },
          { type: 'multiple', q: '30 + 15 = ?', options: ['15', '45', '35', '30'], answer: 1 },
          { type: 'multiple', q: '56 - 10 = ?', options: ['46', '66', '55', '57'], answer: 0 },
          { type: 'multiple', q: 'What number bonds to 10? 7 + ___ = 10', options: ['2', '3', '4', '5'], answer: 1 },
          { type: 'trueFalse', q: '25 + 25 = 50', answer: true },
          { type: 'multiple', q: '34 + 20 = ?', options: ['14', '30', '54', '56'], answer: 2 },
          { type: 'multiple', q: '78 - 30 = ?', options: ['108', '48', '45', '28'], answer: 1 },
          { type: 'multiple', q: '40 + 40 = ?', options: ['0', '44', '80', '44'], answer: 2 },
          { type: 'multiple', q: 'Complete: 6 + ___ = 15', options: ['8', '9', '10', '21'], answer: 1 },
          { type: 'trueFalse', q: '50 - 20 = 30', answer: true },
          { type: 'multiple', q: '12 + 8 = ?', options: ['4', '20', '18', '28'], answer: 1 },
          { type: 'multiple', q: '38 - 8 = ?', options: ['30', '40', '46', '46'], answer: 0 },
          { type: 'multiple', q: '27 + 3 = ?', options: ['24', '30', '31', '23'], answer: 1 },
          { type: 'trueFalse', q: '60 + 10 = 70', answer: true },
          { type: 'multiple', q: '55 - 5 = ?', options: ['50', '60', '49', '51'], answer: 0 },
          { type: 'multiple', q: '21 + 14 = ?', options: ['7', '35', '25', '31'], answer: 1 },
          { type: 'multiple', q: 'What must be added to 25 to make 35?', options: ['5', '10', '15', '60'], answer: 1 },
          { type: 'multiple', q: '67 - 7 = ?', options: ['60', '74', '64', '70'], answer: 0 },
          { type: 'trueFalse', q: '33 + 22 = 55', answer: true },
          { type: 'multiple', q: '44 + 10 = ?', options: ['34', '40', '54', '55'], answer: 2 },
          { type: 'multiple', q: '82 - 12 = ?', options: ['70', '94', '80', '85'], answer: 0 },
          { type: 'multiple', q: 'Complete: ___ + 15 = 25', options: ['10', '20', '40', '5'], answer: 0 },
          { type: 'trueFalse', q: '77 - 20 = 57', answer: true }
        ]
      },
      {
        id: 'y2-maths-3',
        title: 'Multiplication & Division',
        description: '2, 5 and 10 times tables, arrays, sharing',
        questions: [
          { type: 'multiple', q: '2 × 3 = ?', options: ['5', '6', '1', '23'], answer: 1 },
          { type: 'multiple', q: '5 × 2 = ?', options: ['10', '7', '3', '52'], answer: 0 },
          { type: 'multiple', q: '10 × 1 = ?', options: ['11', '1', '10', '101'], answer: 2 },
          { type: 'multiple', q: '2 × 5 = ?', options: ['7', '3', '10', '25'], answer: 2 },
          { type: 'multiple', q: '5 × 4 = ?', options: ['9', '1', '20', '54'], answer: 2 },
          { type: 'trueFalse', q: '10 × 5 = 50', answer: true },
          { type: 'multiple', q: '2 × 8 = ?', options: ['6', '10', '16', '28'], answer: 2 },
          { type: 'multiple', q: '10 ÷ 2 = ?', options: ['5', '12', '8', '20'], answer: 0 },
          { type: 'multiple', q: '20 ÷ 5 = ?', options: ['15', '4', '25', '100'], answer: 1 },
          { type: 'multiple', q: '30 ÷ 10 = ?', options: ['20', '3', '40', '300'], answer: 1 },
          { type: 'trueFalse', q: '5 × 3 = 15', answer: true },
          { type: 'multiple', q: '2 × 6 = ?', options: ['4', '8', '12', '26'], answer: 2 },
          { type: 'multiple', q: '10 × 3 = ?', options: ['30', '13', '7', '30'], answer: 0 },
          { type: 'multiple', q: '16 ÷ 2 = ?', options: ['18', '8', '14', '32'], answer: 1 },
          { type: 'trueFalse', q: '2 × 7 = 14', answer: true },
          { type: 'multiple', q: '5 × 5 = ?', options: ['10', '0', '25', '55'], answer: 2 },
          { type: 'multiple', q: '50 ÷ 5 = ?', options: ['10', '55', '45', '250'], answer: 0 },
          { type: 'multiple', q: '10 × 2 = ?', options: ['20', '12', '8', '102'], answer: 0 },
          { type: 'multiple', q: '40 ÷ 10 = ?', options: ['50', '4', '30', '400'], answer: 1 },
          { type: 'trueFalse', q: '10 × 4 = 40', answer: true },
          { type: 'multiple', q: 'How many legs on 3 cats? (4 legs each)', options: ['7', '12', '1', '34'], answer: 1 },
          { type: 'multiple', q: '15 ÷ 5 = ?', options: ['10', '20', '3', '75'], answer: 2 },
          { type: 'multiple', q: '2 × 9 = ?', options: ['11', '7', '18', '29'], answer: 2 },
          { type: 'trueFalse', q: '20 ÷ 2 = 10', answer: true }
        ]
      },
      {
        id: 'y2-maths-4',
        title: 'Fractions',
        description: 'Halves, thirds, quarters of shapes and amounts',
        questions: [
          { type: 'multiple', q: 'What is ½ of 10?', options: ['5', '10', '20', '2'], answer: 0 },
          { type: 'multiple', q: '¼ of 8 is?', options: ['2', '4', '6', '8'], answer: 0 },
          { type: 'multiple', q: '⅓ of 9 is?', options: ['3', '6', '9', '12'], answer: 0 },
          { type: 'multiple', q: '¾ of 12 is?', options: ['3', '4', '9', '16'], answer: 2 },
          { type: 'multiple', q: '½ of 20 is?', options: ['10', '20', '40', '2'], answer: 0 },
          { type: 'trueFalse', q: '½ is the same as 2/4', answer: true },
          { type: 'multiple', q: 'Which fraction is the biggest?', options: ['¼', '⅓', '½', '⅕'], answer: 2 },
          { type: 'multiple', q: 'What is ¼ of 16?', options: ['4', '8', '12', '20'], answer: 0 },
          { type: 'multiple', q: '⅓ of 15 is?', options: ['5', '10', '12', '45'], answer: 0 },
          { type: 'trueFalse', q: '¾ means 3 out of 4 equal parts', answer: true },
          { type: 'multiple', q: '½ of 6 is?', options: ['2', '3', '12', '1'], answer: 1 },
          { type: 'multiple', q: '¼ of 20 is?', options: ['5', '10', '15', '25'], answer: 0 },
          { type: 'multiple', q: 'What fraction is shaded? (1 out of 4 equal parts)', options: ['½', '¼', '⅓', '¾'], answer: 1 },
          { type: 'multiple', q: '⅓ of 12 is?', options: ['4', '8', '12', '36'], answer: 0 },
          { type: 'trueFalse', q: '½ of 50 = 25', answer: true },
          { type: 'multiple', q: 'Which is a quarter?', options: ['1 out of 2', '1 out of 3', '1 out of 4', '1 out of 5'], answer: 2 },
          { type: 'multiple', q: '¾ of 20 is?', options: ['5', '10', '15', '25'], answer: 2 },
          { type: 'multiple', q: '½ of 14 is?', options: ['7', '14', '28', '2'], answer: 0 },
          { type: 'multiple', q: 'What do you call ½ cut in half?', options: ['⅓', '¼', '⅕', '¾'], answer: 1 },
          { type: 'trueFalse', q: '⅓ of 6 = 2', answer: true },
          { type: 'multiple', q: '¼ of 24 is?', options: ['6', '12', '18', '96'], answer: 0 },
          { type: 'multiple', q: 'How many quarters in a whole?', options: ['2', '3', '4', '5'], answer: 2 },
          { type: 'multiple', q: '⅓ of 18 is?', options: ['6', '9', '12', '54'], answer: 0 },
          { type: 'trueFalse', q: '½ of 32 = 16', answer: true }
        ]
      },
      {
        id: 'y2-maths-5',
        title: 'Time',
        description: 'O\'clock, half past, quarter past/to, 5-minute intervals, days and months',
        questions: [
          { type: 'multiple', q: 'How many minutes in an hour?', options: ['30', '60', '24', '100'], answer: 1 },
          { type: 'multiple', q: 'What time is quarter past 3?', options: ['3:30', '3:15', '3:45', '2:45'], answer: 1 },
          { type: 'multiple', q: 'Half past 7 is written as...', options: ['7:30', '7:50', '7:15', '7:45'], answer: 0 },
          { type: 'multiple', q: 'Quarter to 5 is...', options: ['5:15', '4:45', '5:45', '4:15'], answer: 1 },
          { type: 'multiple', q: 'How many hours in a day?', options: ['12', '24', '48', '6'], answer: 1 },
          { type: 'trueFalse', q: 'There are 60 seconds in a minute', answer: true },
          { type: 'multiple', q: 'How many days in a week?', options: ['5', '7', '10', '6'], answer: 1 },
          { type: 'multiple', q: 'How many days in February?', options: ['28', '30', '31', '29'], answer: 0 },
          { type: 'multiple', q: 'What time is it 15 minutes after 2:00?', options: ['2:15', '2:30', '2:45', '3:00'], answer: 0 },
          { type: 'trueFalse', q: 'Half past is 30 minutes past the hour', answer: true },
          { type: 'multiple', q: 'Which month comes after March?', options: ['February', 'May', 'April', 'June'], answer: 2 },
          { type: 'multiple', q: 'How many months in a year?', options: ['10', '11', '12', '13'], answer: 2 },
          { type: 'multiple', q: 'O\'clock means...', options: ['5 minutes past', 'Exactly on the hour', 'Half past', 'Quarter past'], answer: 1 },
          { type: 'multiple', q: 'What time is 5 minutes after 10:00?', options: ['10:05', '10:15', '10:50', '11:00'], answer: 0 },
          { type: 'trueFalse', q: 'Quarter past 4 is 4:15', answer: true },
          { type: 'multiple', q: 'How many minutes to midnight from 11:55?', options: ['5', '10', '55', '65'], answer: 0 },
          { type: 'multiple', q: 'What day comes after Wednesday?', options: ['Friday', 'Tuesday', 'Thursday', 'Monday'], answer: 2 },
          { type: 'multiple', q: '20 minutes past 6 is written as...', options: ['6:20', '6:40', '5:40', '6:25'], answer: 0 },
          { type: 'trueFalse', q: 'Quarter to 3 is 2:45', answer: true },
          { type: 'multiple', q: 'How many weeks in a year?', options: ['26', '48', '52', '12'], answer: 2 },
          { type: 'multiple', q: 'What is 30 minutes after 1:30?', options: ['1:00', '2:00', '2:30', '1:60'], answer: 1 },
          { type: 'multiple', q: 'Which is NOT a day of the week?', options: ['Monday', 'Funday', 'Friday', 'Sunday'], answer: 1 },
          { type: 'multiple', q: '5 minutes to 9 is written as...', options: ['9:05', '8:55', '8:05', '9:55'], answer: 1 },
          { type: 'trueFalse', q: 'January has 31 days', answer: true }
        ]
      },
      {
        id: 'y2-maths-6',
        title: 'Measurement',
        description: 'Centimetres, metres, grams, kilograms, millilitres, litres',
        questions: [
          { type: 'multiple', q: 'How many centimetres in 1 metre?', options: ['10', '50', '100', '1000'], answer: 2 },
          { type: 'multiple', q: 'Which unit measures weight?', options: ['metres', 'grams', 'litres', 'centimetres'], answer: 1 },
          { type: 'multiple', q: 'How many grams in 1 kilogram?', options: ['10', '100', '1000', '10000'], answer: 2 },
          { type: 'multiple', q: 'Which is a measure of length?', options: ['gram', 'litre', 'metre', 'kilogram'], answer: 2 },
          { type: 'trueFalse', q: 'A litre is more than a millilitre', answer: true },
          { type: 'multiple', q: 'How many millilitres in 1 litre?', options: ['100', '500', '1000', '10000'], answer: 2 },
          { type: 'multiple', q: 'Which is heavier: 1 kg or 500 g?', options: ['1 kg', '500 g', 'They are the same', 'Cannot tell'], answer: 0 },
          { type: 'multiple', q: 'A pencil is about how long?', options: ['15 cm', '15 m', '15 mm', '1 cm'], answer: 0 },
          { type: 'trueFalse', q: 'Kilometres are used to measure very long distances', answer: true },
          { type: 'multiple', q: 'Millimetres are...', options: ['Bigger than cm', 'Smaller than cm', 'Same as cm', 'Bigger than m'], answer: 1 },
          { type: 'multiple', q: 'Which would you use to measure milk?', options: ['grams', 'metres', 'litres', 'centimetres'], answer: 2 },
          { type: 'multiple', q: '1 cm = ? millimetres', options: ['5', '10', '100', '1000'], answer: 1 },
          { type: 'multiple', q: 'Which is longest: 1 cm, 10 mm, 1 m?', options: ['1 cm', '10 mm', '1 m', 'They are equal'], answer: 2 },
          { type: 'trueFalse', q: 'A door is about 2 metres tall', answer: true },
          { type: 'multiple', q: 'How many grams in 2 kg?', options: ['200', '2000', '20', '200000'], answer: 1 },
          { type: 'multiple', q: 'Which weighs more: 500 g or 1 kg?', options: ['500 g', '1 kg', 'They are the same', 'Cannot tell'], answer: 1 },
          { type: 'multiple', q: 'How many litres in 2000 millilitres?', options: ['1', '2', '20', '200'], answer: 1 },
          { type: 'multiple', q: 'A tablespoon holds about...', options: ['15 ml', '15 cm', '15 g', '15 m'], answer: 0 },
          { type: 'trueFalse', q: 'A book is heavier than a feather', answer: true },
          { type: 'multiple', q: 'Which is the smallest?', options: ['1 cm', '1 mm', '1 m', '1 km'], answer: 1 },
          { type: 'multiple', q: 'A swimming pool holds about...', options: ['10 litres', '100 litres', '1000 litres', '1 litre'], answer: 2 },
          { type: 'multiple', q: '500 g + 500 g = ?', options: ['1 g', '100 g', '1000 g (1 kg)', '50 g'], answer: 2 },
          { type: 'multiple', q: 'How tall are you approximately?', options: ['1 cm', '10 cm', '100 cm', '1000 cm'], answer: 2 },
          { type: 'trueFalse', q: 'A litre bottle holds 1000 millilitres', answer: true }
        ]
      },
      {
        id: 'y2-maths-7',
        title: 'Shape & Position',
        description: '2D and 3D shapes, vertices, edges, faces, turns, right angles',
        questions: [
          { type: 'multiple', q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], answer: 1 },
          { type: 'multiple', q: 'How many faces does a cube have?', options: ['4', '6', '8', '12'], answer: 1 },
          { type: 'multiple', q: 'How many edges does a cube have?', options: ['6', '8', '12', '10'], answer: 2 },
          { type: 'multiple', q: 'How many vertices does a triangle have?', options: ['2', '3', '4', '5'], answer: 1 },
          { type: 'trueFalse', q: 'A circle has vertices', answer: false },
          { type: 'multiple', q: 'A quarter turn is also called a...', options: ['Right angle', 'Half turn', 'Full turn', 'Straight line'], answer: 0 },
          { type: 'multiple', q: 'A half turn is how many degrees?', options: ['90', '180', '270', '360'], answer: 1 },
          { type: 'multiple', q: 'A full turn is how many degrees?', options: ['90', '180', '270', '360'], answer: 3 },
          { type: 'trueFalse', q: 'A pentagon has 5 sides', answer: true },
          { type: 'multiple', q: 'Which shape has no straight edges?', options: ['Square', 'Triangle', 'Circle', 'Pentagon'], answer: 2 },
          { type: 'multiple', q: 'How many faces does a cuboid have?', options: ['4', '6', '8', '12'], answer: 1 },
          { type: 'multiple', q: 'How many sides does a square have?', options: ['3', '4', '5', '6'], answer: 1 },
          { type: 'trueFalse', q: 'A right angle is 90 degrees', answer: true },
          { type: 'multiple', q: 'How many vertices does a square have?', options: ['2', '3', '4', '5'], answer: 2 },
          { type: 'multiple', q: 'Which is a 3D shape?', options: ['Triangle', 'Circle', 'Sphere', 'Line'], answer: 2 },
          { type: 'multiple', q: 'How many edges does a cylinder have?', options: ['0', '1', '2', '3'], answer: 2 },
          { type: 'trueFalse', q: 'A rectangle has 4 right angles', answer: true },
          { type: 'multiple', q: 'What is a vertex?', options: ['A side', 'A corner', 'A face', 'An edge'], answer: 1 },
          { type: 'multiple', q: 'Which has curved edges?', options: ['Cube', 'Cylinder', 'Cuboid', 'Pyramid'], answer: 1 },
          { type: 'trueFalse', q: 'A triangle has 3 vertices', answer: true },
          { type: 'multiple', q: 'How many vertices does a cube have?', options: ['6', '8', '12', '4'], answer: 1 },
          { type: 'multiple', q: 'What is a face on a 3D shape?', options: ['An edge', 'A surface', 'A corner', 'A side'], answer: 1 },
          { type: 'multiple', q: 'How many sides does an octagon have?', options: ['6', '8', '10', '12'], answer: 1 },
          { type: 'trueFalse', q: 'A straight line is 180 degrees', answer: true }
        ]
      },
      {
        id: 'y2-maths-8',
        title: 'Statistics',
        description: 'Tally charts, pictograms, block diagrams and tables',
        questions: [
          { type: 'multiple', q: 'In a tally chart, a group of 5 is shown as...', options: ['||||', '|||||', 'Four lines with a line through', 'V'], answer: 2 },
          { type: 'multiple', q: 'A pictogram uses...', options: ['Words', 'Numbers', 'Pictures', 'Letters'], answer: 2 },
          { type: 'trueFalse', q: 'A tally chart organises data', answer: true },
          { type: 'multiple', q: 'If 3 children like apples and 5 like bananas, how many in total?', options: ['2', '8', '15', '5'], answer: 1 },
          { type: 'multiple', q: 'In a bar chart, the tallest bar shows the...', options: ['Smallest amount', 'Largest amount', 'Middle amount', 'Total'], answer: 1 },
          { type: 'trueFalse', q: 'A table is used to organize information', answer: true },
          { type: 'multiple', q: 'If each picture in a pictogram = 2 people, 3 pictures = ?', options: ['3 people', '5 people', '6 people', '8 people'], answer: 2 },
          { type: 'multiple', q: 'Data shows: Red 4, Blue 7, Green 3. Which is most popular?', options: ['Red', 'Blue', 'Green', 'Yellow'], answer: 1 },
          { type: 'multiple', q: 'Red 4, Blue 7, Green 3. How many more chose blue than green?', options: ['3', '4', '5', '7'], answer: 2 },
          { type: 'trueFalse', q: 'The mode is the most common number', answer: true },
          { type: 'multiple', q: 'In a block diagram, what does each block represent?', options: ['1 person', '10 people', '5 people', 'Cannot tell'], answer: 0 },
          { type: 'multiple', q: 'How many tally marks show 8?', options: ['||||', '|||| |||', '|||| ||||', '|||||||||'], answer: 1 },
          { type: 'trueFalse', q: 'A survey collects data', answer: true },
          { type: 'multiple', q: 'If chart shows 2 dogs, 5 cats, 3 rabbits. Total animals?', options: ['8', '10', 'Cannot tell', '5'], answer: 1 },
          { type: 'multiple', q: 'Which is NOT a way to show data?', options: ['Table', 'Picture', 'Block diagram', 'Music'], answer: 3 },
          { type: 'trueFalse', q: 'Pictograms are helpful for young children', answer: true },
          { type: 'multiple', q: 'What does a bar chart show?', options: ['Pictures', 'Bars of different heights', 'Numbers only', 'Words'], answer: 1 },
          { type: 'multiple', q: 'If 10 children were asked their colour, 3 said red. How many said other colours?', options: ['3', '7', '13', '30'], answer: 1 },
          { type: 'trueFalse', q: 'A title helps explain a chart', answer: true },
          { type: 'multiple', q: 'How is tally mark 5 shown differently?', options: ['Bigger', 'Bolder', 'With a line through 4', 'In red'], answer: 2 },
          { type: 'multiple', q: 'In a chart, the x-axis goes...', options: ['Up and down', 'Side to side', 'Diagonally', 'In circles'], answer: 1 },
          { type: 'multiple', q: 'Results: Dog 6, Cat 8, Bird 4. Most popular pet?', options: ['Dog', 'Cat', 'Bird', 'Fish'], answer: 1 },
          { type: 'multiple', q: 'What is a frequency table?', options: ['A timetable', 'A chart showing how often things happen', 'A list of numbers', 'A picture'], answer: 1 },
          { type: 'trueFalse', q: 'Axes on a chart have labels', answer: true }
        ]
      }
    ]
  },

  english: {
    name: 'English',
    icon: '📖',
    color: '#2196F3',
    lessons: [
      {
        id: 'y2-english-1',
        title: 'Punctuation',
        description: 'Full stops, exclamation marks, question marks, commas, capital letters',
        questions: [
          { type: 'multiple', q: 'Which sentence is punctuated correctly?', options: ['the cat sat', 'The cat sat.', 'The Cat Sat', 'the cat sat.'], answer: 1 },
          { type: 'multiple', q: 'What punctuation ends a question?', options: ['.', '!', '?', ','], answer: 2 },
          { type: 'trueFalse', q: 'Every sentence starts with a capital letter', answer: true },
          { type: 'multiple', q: 'Which sentence needs an exclamation mark?', options: ['I like cake', 'Watch out!', 'Where is he', 'The sky is blue'], answer: 1 },
          { type: 'multiple', q: 'What do commas do in a list?', options: ['End sentences', 'Separate items', 'Start sentences', 'Join words'], answer: 1 },
          { type: 'trueFalse', q: '"Hello!" uses an exclamation mark correctly', answer: true },
          { type: 'multiple', q: 'Which word ALWAYS starts with a capital letter?', options: ['cat', 'London', 'happy', 'running'], answer: 1 },
          { type: 'multiple', q: 'Add punctuation: "What a day__"', options: ['.', '?', '!', ','], answer: 2 },
          { type: 'multiple', q: 'Which sentence is correct?', options: ['She like cake', 'She likes cake.', 'She likes cake', 'she likes cake.'], answer: 1 },
          { type: 'trueFalse', q: 'Question marks end questions', answer: true },
          { type: 'multiple', q: 'Choose the correct punctuation: "Do you like tea"', options: ['.', '!', '?', ','], answer: 2 },
          { type: 'multiple', q: 'Which is a statement?', options: ['Are you ready', 'Be quiet', 'I am ready.', 'What time is it'], answer: 2 },
          { type: 'trueFalse', q: 'Full stops end sentences', answer: true },
          { type: 'multiple', q: 'List punctuation: "I like apples, oranges ___ bananas"', options: ['and', ',', '.', '!'], answer: 1 },
          { type: 'multiple', q: 'Which is punctuated correctly?', options: ['the boy ran', 'The boy ran', 'The boy ran.', 'the boy ran.'], answer: 2 },
          { type: 'trueFalse', q: 'Names start with capital letters', answer: true },
          { type: 'multiple', q: 'A command usually ends with...', options: ['?', '!', '.', ','], answer: 2 },
          { type: 'multiple', q: 'Which needs a full stop?', options: ['Come here', 'Can you come here', 'Please come here.', 'Run'], answer: 2 },
          { type: 'trueFalse', q: '"Go away!" is punctuated correctly', answer: true },
          { type: 'multiple', q: 'Commas separate items like: "red, blue ___ green"', options: ['and', ',', '.', ';'], answer: 0 },
          { type: 'multiple', q: 'Which is a command?', options: ['Are you coming', 'Come here.', 'I am coming.', 'Is he coming'], answer: 1 },
          { type: 'trueFalse', q: 'Place names start with capital letters', answer: true },
          { type: 'multiple', q: 'The sentence "Well done" should end with...', options: ['.', '!', '?', ','], answer: 1 },
          { type: 'trueFalse', q: 'An exclamation mark shows strong feeling', answer: true }
        ]
      },
      {
        id: 'y2-english-2',
        title: 'Apostrophes',
        description: 'Contractions and possession',
        questions: [
          { type: 'multiple', q: '"Can not" becomes...', options: ['can\'t', 'cann\'t', 'cannot\'', 'ca\'nt'], answer: 0 },
          { type: 'multiple', q: '"The dog\'s bone" means...', options: ['The dogs like bones', 'The bone belongs to the dog', 'The dogs are bony', 'Dogs have bones'], answer: 1 },
          { type: 'multiple', q: '"I am" becomes...', options: ['I\'m', 'Im', 'I\'am', 'Iam'], answer: 0 },
          { type: 'trueFalse', q: '"It\'s" means "it is"', answer: true },
          { type: 'multiple', q: 'Which is correct?', options: ['The girls bag', 'The girl\'s bag', 'The girls\' bag', 'The girle\'s bag'], answer: 1 },
          { type: 'multiple', q: '"We are" becomes...', options: ['Were', 'We\'re', 'Wear', 'We\'ar'], answer: 1 },
          { type: 'multiple', q: '"Did not" becomes...', options: ['did\'nt', 'didn\'t', 'didnt\'', 'didn\'ot'], answer: 1 },
          { type: 'trueFalse', q: 'Apostrophes show missing letters', answer: true },
          { type: 'multiple', q: '"You will" becomes...', options: ['You\'ll', 'Youll', 'You\'l', 'You\'ll'], answer: 0 },
          { type: 'trueFalse', q: '"Don\'t" is a contraction', answer: true },
          { type: 'multiple', q: '"They are" becomes...', options: ['They\'re', 'Their', 'There', 'Theyre'], answer: 0 },
          { type: 'multiple', q: 'The boy\'s shoes belong to...', options: ['Two boys', 'One boy', 'Several boys', 'No one'], answer: 1 },
          { type: 'trueFalse', q: '"Isn\'t" means "is not"', answer: true },
          { type: 'multiple', q: '"Will not" becomes...', options: ['will\'t', 'willn\'t', 'won\'t', 'will not'], answer: 2 },
          { type: 'multiple', q: '"She would" becomes...', options: ['She\'d', 'Shed', 'She\'ud', 'She\'ould'], answer: 0 },
          { type: 'trueFalse', q: 'The cats\' toys means toys belong to many cats', answer: true },
          { type: 'multiple', q: '"Has not" becomes...', options: ['hasn\'t', 'hasnt\'', 'has\'nt', 'hasi\'t'], answer: 0 },
          { type: 'multiple', q: '"I have" becomes...', options: ['I\'ve', 'Ive', 'I\'av', 'I\'hav'], answer: 0 },
          { type: 'trueFalse', q: '"Can\'t" means "cannot"', answer: true },
          { type: 'multiple', q: '"She is" becomes...', options: ['She\'s', 'Shes', 'She\'iz', 'She\'s'], answer: 0 },
          { type: 'multiple', q: 'Tom\'s book is Tom\'s...', options: ['Books', 'Book', 'Belongings', 'Name'], answer: 1 },
          { type: 'trueFalse', q: '"They\'re" means "they are"', answer: true },
          { type: 'multiple', q: '"Do not" becomes...', options: ['do\'t', 'don\'t', 'donot', 'do\'nt'], answer: 1 },
          { type: 'trueFalse', q: 'An apostrophe shows possession', answer: true }
        ]
      },
      {
        id: 'y2-english-3',
        title: 'Tenses',
        description: 'Past simple, present, future with will and going to',
        questions: [
          { type: 'multiple', q: 'Which is in the past tense?', options: ['I walk', 'I walked', 'I will walk', 'I walking'], answer: 1 },
          { type: 'multiple', q: 'Change to past tense: "jump"', options: ['jumping', 'jumped', 'will jump', 'jumps'], answer: 1 },
          { type: 'multiple', q: 'Which shows something happening now?', options: ['ran', 'will run', 'is running', 'run'], answer: 2 },
          { type: 'trueFalse', q: '"She will play tomorrow" is future tense', answer: true },
          { type: 'multiple', q: 'Past tense of "go" is...', options: ['goed', 'went', 'going', 'gone'], answer: 1 },
          { type: 'multiple', q: 'Past tense of "eat" is...', options: ['eated', 'eaten', 'ate', 'eating'], answer: 2 },
          { type: 'multiple', q: '"The birds are singing" — what tense?', options: ['Past', 'Present', 'Future', 'None'], answer: 1 },
          { type: 'trueFalse', q: '"Yesterday I played" is past tense', answer: true },
          { type: 'multiple', q: 'Which is the present tense?', options: ['played', 'will play', 'is playing', 'played yesterday'], answer: 2 },
          { type: 'trueFalse', q: '"I am going to run" is future', answer: true },
          { type: 'multiple', q: 'Past tense of "see" is...', options: ['seeing', 'saw', 'seen', 'sees'], answer: 1 },
          { type: 'multiple', q: '"Will" shows...', options: ['Past', 'Present', 'Future', 'Time'], answer: 2 },
          { type: 'trueFalse', q: '"I walked to school" is past tense', answer: true },
          { type: 'multiple', q: 'Past tense of "make" is...', options: ['making', 'maked', 'made', 'makes'], answer: 2 },
          { type: 'multiple', q: '"I am playing" is...', options: ['Past simple', 'Present continuous', 'Future', 'None'], answer: 1 },
          { type: 'trueFalse', q: '"Tomorrow I will run" is future tense', answer: true },
          { type: 'multiple', q: 'Past tense of "buy" is...', options: ['buyed', 'bought', 'buying', 'buys'], answer: 1 },
          { type: 'multiple', q: '"She plays football" is...', options: ['Past tense', 'Present tense', 'Future tense', 'No tense'], answer: 1 },
          { type: 'trueFalse', q: '"Going to" can show future plans', answer: true },
          { type: 'multiple', q: 'Past tense of "come" is...', options: ['coming', 'comed', 'came', 'comes'], answer: 2 },
          { type: 'multiple', q: '"He is going to swim" is...', options: ['Past', 'Present', 'Future', 'Present continuous'], answer: 2 },
          { type: 'trueFalse', q: '"I eat apples" is present tense', answer: true },
          { type: 'multiple', q: 'Past tense of "take" is...', options: ['taking', 'taked', 'took', 'takes'], answer: 2 },
          { type: 'trueFalse', q: 'Regular verbs add -ed for past tense', answer: true }
        ]
      },
      {
        id: 'y2-english-4',
        title: 'Nouns & Adjectives',
        description: 'Common and proper nouns, noun phrases, adjectives for description',
        questions: [
          { type: 'multiple', q: 'Which is a noun?', options: ['happy', 'run', 'dog', 'quickly'], answer: 2 },
          { type: 'multiple', q: 'Which is a proper noun?', options: ['cat', 'London', 'blue', 'small'], answer: 1 },
          { type: 'multiple', q: 'Which is an adjective?', options: ['happy', 'run', 'dog', 'quickly'], answer: 0 },
          { type: 'trueFalse', q: 'Adjectives describe nouns', answer: true },
          { type: 'multiple', q: '"The big red ball" — how many adjectives?', options: ['0', '1', '2', '3'], answer: 2 },
          { type: 'multiple', q: 'Which is a common noun?', options: ['Sarah', 'England', 'table', 'Japan'], answer: 2 },
          { type: 'trueFalse', q: 'Proper nouns start with capital letters', answer: true },
          { type: 'multiple', q: 'In "the small cat", what is "small"?', options: ['Noun', 'Verb', 'Adjective', 'Adverb'], answer: 2 },
          { type: 'multiple', q: 'Choose the noun: "The quick fox runs"', options: ['quick', 'fox', 'runs', 'the'], answer: 1 },
          { type: 'trueFalse', q: '"Book" is a common noun', answer: true },
          { type: 'multiple', q: '"A beautiful flower" — what is "beautiful"?', options: ['Noun', 'Adjective', 'Verb', 'Adverb'], answer: 1 },
          { type: 'multiple', q: 'Which adjective describes taste?', options: ['soft', 'sweet', 'rough', 'hard'], answer: 1 },
          { type: 'trueFalse', q: 'Nouns are naming words', answer: true },
          { type: 'multiple', q: '"She has a kind teacher" — what is "kind"?', options: ['Noun', 'Adjective', 'Verb', 'Name'], answer: 1 },
          { type: 'multiple', q: 'Which is a proper noun?', options: ['boy', 'Emma', 'girl', 'friend'], answer: 1 },
          { type: 'trueFalse', q: '"Brave" is an adjective', answer: true },
          { type: 'multiple', q: 'A noun phrase contains...', options: ['Just a noun', 'Noun + adjective', 'Just an adjective', 'Just a verb'], answer: 1 },
          { type: 'multiple', q: '"The tall building" — what is the noun?', options: ['the', 'tall', 'building', 'tall building'], answer: 2 },
          { type: 'trueFalse', q: 'Days of the week start with capital letters', answer: true },
          { type: 'multiple', q: 'Which word is a noun?', options: ['run', 'fast', 'table', 'quickly'], answer: 2 },
          { type: 'multiple', q: '"Friendly" is an...', options: ['Noun', 'Adjective', 'Verb', 'Adverb'], answer: 1 },
          { type: 'trueFalse', q: '"Ocean" is a common noun', answer: true },
          { type: 'multiple', q: '"A cold winter" — what is the adjective?', options: ['a', 'cold', 'winter', 'none'], answer: 1 },
          { type: 'trueFalse', q: '"Lovely" describes something', answer: true }
        ]
      },
      {
        id: 'y2-english-5',
        title: 'Verbs & Adverbs',
        description: 'Action verbs, past tense irregulars, adverbs ending in -ly',
        questions: [
          { type: 'multiple', q: 'Which is a verb?', options: ['happy', 'run', 'quick', 'blue'], answer: 1 },
          { type: 'multiple', q: 'Which is an adverb?', options: ['tall', 'slowly', 'happy', 'blue'], answer: 1 },
          { type: 'multiple', q: '"The dog ran quickly" — what is the adverb?', options: ['dog', 'ran', 'quickly', 'the'], answer: 2 },
          { type: 'trueFalse', q: 'Verbs are action words', answer: true },
          { type: 'multiple', q: '"She sang beautifully" — what is the verb?', options: ['she', 'sang', 'beautifully', 'the'], answer: 1 },
          { type: 'multiple', q: 'Adverbs often end in...', options: ['-ing', '-ful', '-ly', '-ness'], answer: 2 },
          { type: 'trueFalse', q: '"Happily" is an adverb', answer: true },
          { type: 'multiple', q: 'Past tense of "see" is...', options: ['seeing', 'saw', 'see', 'sees'], answer: 1 },
          { type: 'multiple', q: '"The children played happily" — adverb is?', options: ['played', 'happily', 'children', 'the'], answer: 1 },
          { type: 'trueFalse', q: '"Carefully" is an adverb', answer: true },
          { type: 'multiple', q: 'Which verb is irregular?', options: ['walked', 'jumped', 'went', 'played'], answer: 2 },
          { type: 'multiple', q: '"She walks slowly to school" — verb is?', options: ['she', 'walks', 'slowly', 'school'], answer: 1 },
          { type: 'trueFalse', q: 'Adverbs describe verbs', answer: true },
          { type: 'multiple', q: '"Fast" can be an...', options: ['Adjective and adverb', 'Only adjective', 'Only adverb', 'Neither'], answer: 0 },
          { type: 'multiple', q: 'Past tense of "buy" is...', options: ['buyed', 'bought', 'buy', 'buys'], answer: 1 },
          { type: 'trueFalse', q: '"Loudly" describes how something is done', answer: true },
          { type: 'multiple', q: '"He talked quietly" — the verb is?', options: ['quietly', 'talked', 'he', 'the'], answer: 1 },
          { type: 'multiple', q: 'Past tense of "eat" is...', options: ['eated', 'ate', 'eat', 'eats'], answer: 1 },
          { type: 'trueFalse', q: '"Softly" is an adverb', answer: true },
          { type: 'multiple', q: '"Jump" + "-ly" makes...', options: ['jumply', 'jumpily', 'jumpily', 'jumpingly'], answer: 1 },
          { type: 'multiple', q: '"She danced gracefully" — adverb is?', options: ['danced', 'gracefully', 'she', 'the'], answer: 1 },
          { type: 'trueFalse', q: '"Quickly" tells us how something happens', answer: true },
          { type: 'multiple', q: '"Run" is...', options: ['Past tense', 'Present tense', 'Noun', 'Adjective'], answer: 1 },
          { type: 'trueFalse', q: 'Past tense of "make" is "made"', answer: true }
        ]
      },
      {
        id: 'y2-english-6',
        title: 'Sentence Types',
        description: 'Statements, questions, exclamations and commands',
        questions: [
          { type: 'multiple', q: 'Which is a statement?', options: ['Are you ready?', 'I am ready.', 'Be ready!', 'Ready?'], answer: 1 },
          { type: 'multiple', q: 'Which is a question?', options: ['The cat is black', 'Watch the cat!', 'Is the cat black?', 'The cat.'], answer: 2 },
          { type: 'multiple', q: 'Which is an exclamation?', options: ['I like it', 'Do you like it', 'I love it!', 'Does it matter'], answer: 2 },
          { type: 'trueFalse', q: 'Commands tell someone to do something', answer: true },
          { type: 'multiple', q: '"What is your name?" is a...', options: ['Statement', 'Command', 'Question', 'Exclamation'], answer: 2 },
          { type: 'multiple', q: '"Sit down." is a...', options: ['Question', 'Statement', 'Command', 'Exclamation'], answer: 2 },
          { type: 'trueFalse', q: 'Statements end with a full stop', answer: true },
          { type: 'multiple', q: '"This is great!" is an...', options: ['Statement', 'Question', 'Exclamation', 'Command'], answer: 2 },
          { type: 'multiple', q: 'Which sentence is a command?', options: ['Come here.', 'Are you coming?', 'You are here.', 'Coming here!'], answer: 0 },
          { type: 'trueFalse', q: 'Questions end with a question mark', answer: true },
          { type: 'multiple', q: '"I like apples" is a...', options: ['Question', 'Statement', 'Command', 'Exclamation'], answer: 1 },
          { type: 'multiple', q: '"Help!" is an...', options: ['Question', 'Statement', 'Command', 'Exclamation'], answer: 3 },
          { type: 'trueFalse', q: 'Exclamations show strong feeling', answer: true },
          { type: 'multiple', q: '"Can you help me?" is a...', options: ['Statement', 'Command', 'Question', 'Exclamation'], answer: 2 },
          { type: 'multiple', q: 'A question asks for...', options: ['Information', 'You to do something', 'A statement', 'Nothing'], answer: 0 },
          { type: 'trueFalse', q: 'Commands end with full stops or exclamation marks', answer: true },
          { type: 'multiple', q: '"Don\'t touch that!" is an...', options: ['Statement', 'Command', 'Question', 'Greeting'], answer: 1 },
          { type: 'multiple', q: '"I have a cat" is a...', options: ['Question', 'Statement', 'Command', 'Exclamation'], answer: 1 },
          { type: 'trueFalse', q: 'Exclamation marks end exclamations', answer: true },
          { type: 'multiple', q: 'Which shows a command?', options: ['Run.', 'Are you running?', 'I run.', 'Running!'], answer: 0 },
          { type: 'multiple', q: '"Please sit down" is a...', options: ['Question', 'Statement', 'Command', 'Exclamation'], answer: 2 },
          { type: 'trueFalse', q: 'A statement tells us something', answer: true },
          { type: 'multiple', q: '"What a beautiful day!" is an...', options: ['Statement', 'Question', 'Command', 'Exclamation'], answer: 3 },
          { type: 'trueFalse', q: 'Question marks show questions', answer: true }
        ]
      }
    ]
  },

  science: {
    name: 'Science',
    icon: '🔬',
    color: '#9C27B0',
    lessons: [
      {
        id: 'y2-science-1',
        title: 'Living Things & Habitats',
        description: 'Living/dead/never alive, habitats, food chains, adaptation',
        questions: [
          { type: 'multiple', q: 'Which is a living thing?', options: ['Rock', 'Tree', 'Water', 'Plastic'], answer: 1 },
          { type: 'trueFalse', q: 'A habitat is where an animal lives', answer: true },
          { type: 'multiple', q: 'Which is NOT alive?', options: ['Cat', 'Flower', 'Rock', 'Bird'], answer: 2 },
          { type: 'multiple', q: 'What do living things need to survive?', options: ['Toys', 'Food and water', 'Books', 'Nothing'], answer: 1 },
          { type: 'trueFalse', q: 'All animals breathe oxygen', answer: true },
          { type: 'multiple', q: 'Which animal lives in a desert?', options: ['Penguin', 'Camel', 'Polar bear', 'Fish'], answer: 1 },
          { type: 'multiple', q: 'A food chain starts with...', options: ['Meat', 'Plants', 'Animals', 'Insects'], answer: 1 },
          { type: 'trueFalse', q: 'Habitats provide food and shelter', answer: true },
          { type: 'multiple', q: 'Which animal lives in a rainforest?', options: ['Penguin', 'Monkey', 'Polar bear', 'Camel'], answer: 1 },
          { type: 'multiple', q: 'What is adaptation?', options: ['A type of animal', 'How animals suit their habitat', 'A habitat', 'Food'], answer: 1 },
          { type: 'trueFalse', q: 'Fish are adapted to live in water', answer: true },
          { type: 'multiple', q: 'An animal that eats plants is a...', options: ['Carnivore', 'Omnivore', 'Herbivore', 'Scavenger'], answer: 2 },
          { type: 'multiple', q: 'Which lives in a pond?', options: ['Camel', 'Frog', 'Eagle', 'Snake'], answer: 1 },
          { type: 'trueFalse', q: 'Plants are living things', answer: true },
          { type: 'multiple', q: 'In a food chain, who eats the plants?', options: ['The sun', 'The predator', 'The herbivore', 'Nothing'], answer: 2 },
          { type: 'trueFalse', q: 'Some animals never lived and are not alive', answer: true },
          { type: 'multiple', q: 'Which habitat is very cold?', options: ['Rainforest', 'Desert', 'Arctic', 'Savanna'], answer: 2 },
          { type: 'multiple', q: 'What do herbivores eat?', options: ['Meat', 'Plants', 'Other animals', 'Fish'], answer: 1 },
          { type: 'trueFalse', q: 'Camouflage helps animals hide', answer: true },
          { type: 'multiple', q: 'Which is a carnivore?', options: ['Cow', 'Deer', 'Lion', 'Rabbit'], answer: 2 },
          { type: 'multiple', q: 'Living things can...', options: ['Never change', 'Grow and reproduce', 'Not eat', 'Live forever'], answer: 1 },
          { type: 'trueFalse', q: 'A habitat contains living and non-living things', answer: true },
          { type: 'multiple', q: 'Which habitat has lots of trees?', options: ['Desert', 'Ocean', 'Forest', 'Mountain'], answer: 2 },
          { type: 'trueFalse', q: 'Different animals need different habitats', answer: true }
        ]
      },
      {
        id: 'y2-science-2',
        title: 'Plants',
        description: 'Seeds, bulbs, germination, what plants need to grow',
        questions: [
          { type: 'multiple', q: 'What do plants need to grow?', options: ['Sunlight, water and soil', 'Just water', 'Only sunshine', 'Darkness'], answer: 0 },
          { type: 'multiple', q: 'Which part of a plant takes in water?', options: ['Leaf', 'Flower', 'Root', 'Stem'], answer: 2 },
          { type: 'multiple', q: 'What does the stem do?', options: ['Makes food', 'Carries water up', 'Attracts bees', 'Stores seeds'], answer: 1 },
          { type: 'trueFalse', q: 'Flowers help plants make seeds', answer: true },
          { type: 'multiple', q: 'What do leaves use to make food?', options: ['Water only', 'Sunlight', 'Soil', 'Wind'], answer: 1 },
          { type: 'multiple', q: 'Seeds are spread by...', options: ['Wind, animals, water', 'Only the rain', 'Only birds', 'Gravity only'], answer: 0 },
          { type: 'trueFalse', q: 'A bulb can grow into a plant', answer: true },
          { type: 'multiple', q: 'What is germination?', options: ['When a flower dies', 'When a seed starts to grow', 'When leaves fall off', 'When fruit ripens'], answer: 1 },
          { type: 'multiple', q: 'How many main parts does a plant have?', options: ['2', '3', '4', '5'], answer: 2 },
          { type: 'trueFalse', q: 'Plants make their own food', answer: true },
          { type: 'multiple', q: 'Which is the flower for?', options: ['Making stems', 'Making seeds', 'Making roots', 'Making leaves'], answer: 1 },
          { type: 'trueFalse', q: 'Roots hold plants in the ground', answer: true },
          { type: 'multiple', q: 'What colour are leaves usually?', options: ['Red', 'Green', 'Yellow', 'Brown'], answer: 1 },
          { type: 'multiple', q: 'Plants breathe through...', options: ['Roots', 'Stems', 'Leaves', 'Flowers'], answer: 2 },
          { type: 'trueFalse', q: 'Plants need light to grow', answer: true },
          { type: 'multiple', q: 'A seed contains...', options: ['Water', 'A baby plant', 'Soil', 'Air'], answer: 1 },
          { type: 'multiple', q: 'What does photosynthesis make?', options: ['Water', 'Light', 'Food for the plant', 'Seeds'], answer: 2 },
          { type: 'trueFalse', q: 'All plants have flowers', answer: false },
          { type: 'multiple', q: 'How do seeds grow into big plants?', options: ['Magic', 'Time and care', 'Overnight', 'Never'], answer: 1 },
          { type: 'trueFalse', q: 'Soil gives plants nutrients', answer: true },
          { type: 'multiple', q: 'What spreads pollen between flowers?', options: ['Wind', 'Bees', 'Water', 'All of the above'], answer: 3 },
          { type: 'trueFalse', q: 'Plants need water to live', answer: true },
          { type: 'multiple', q: 'A bulb is like a...', options: ['Flower', 'Seed', 'Root', 'Leaf'], answer: 1 },
          { type: 'trueFalse', q: 'Green plants produce oxygen', answer: true }
        ]
      },
      {
        id: 'y2-science-3',
        title: 'Animals Including Humans',
        description: 'Offspring, basic needs, exercise, diet and hygiene',
        questions: [
          { type: 'multiple', q: 'What do all animals need to survive?', options: ['Toys', 'Food, water and shelter', 'Books', 'Nothing'], answer: 1 },
          { type: 'trueFalse', q: 'Baby animals are called offspring', answer: true },
          { type: 'multiple', q: 'Which is a basic human need?', options: ['Television', 'Food', 'Games', 'Sweets'], answer: 1 },
          { type: 'multiple', q: 'What helps keep humans healthy?', options: ['Staying in bed', 'Exercise', 'Eating sweets', 'No sleep'], answer: 1 },
          { type: 'trueFalse', q: 'A healthy diet includes vegetables', answer: true },
          { type: 'multiple', q: 'Why is exercise important?', options: ['It is boring', 'It keeps us healthy', 'It makes us tired', 'It is bad'], answer: 1 },
          { type: 'trueFalse', q: 'Washing hands is important for hygiene', answer: true },
          { type: 'multiple', q: 'A baby cat is called a...', options: ['Kitten', 'Piglet', 'Calf', 'Puppy'], answer: 0 },
          { type: 'multiple', q: 'What should you eat regularly?', options: ['Sweets', 'Fruit and vegetables', 'Chips only', 'Ice cream'], answer: 1 },
          { type: 'trueFalse', q: 'Sleep is important for health', answer: true },
          { type: 'multiple', q: 'How many main food groups are there?', options: ['2', '3', '4', '5'], answer: 3 },
          { type: 'trueFalse', q: 'Water is essential for the body', answer: true },
          { type: 'multiple', q: 'A baby dog is called a...', options: ['Kitten', 'Chick', 'Puppy', 'Calf'], answer: 2 },
          { type: 'multiple', q: 'Which is NOT a healthy habit?', options: ['Brushing teeth', 'Exercise', 'Eating sweets all day', 'Sleeping well'], answer: 2 },
          { type: 'trueFalse', q: 'Exercise makes your heart stronger', answer: true },
          { type: 'multiple', q: 'How often should you wash your hands?', options: ['Never', 'Regularly', 'Once a year', 'Never'], answer: 1 },
          { type: 'multiple', q: 'What does a balanced diet include?', options: ['Only fruit', 'Different food groups', 'Only meat', 'Only vegetables'], answer: 1 },
          { type: 'trueFalse', q: 'All animals have babies', answer: true },
          { type: 'multiple', q: 'How much exercise do children need daily?', options: ['None', 'At least 1 hour', '10 minutes', '30 seconds'], answer: 1 },
          { type: 'trueFalse', q: 'Hygiene prevents illness', answer: true },
          { type: 'multiple', q: 'A baby bird is called a...', options: ['Duckling', 'Chick', 'Kitten', 'Calf'], answer: 1 },
          { type: 'trueFalse', q: 'Different animals have different baby names', answer: true },
          { type: 'multiple', q: 'What helps babies grow strong?', options: ['Playing', 'Good food', 'Exercise', 'All of above'], answer: 3 },
          { type: 'trueFalse', q: 'Keeping clean is part of good hygiene', answer: true }
        ]
      },
      {
        id: 'y2-science-4',
        title: 'Uses of Everyday Materials',
        description: 'Properties, suitability, comparing, squashing, bending, twisting, stretching',
        questions: [
          { type: 'multiple', q: 'Which material is transparent?', options: ['Wood', 'Metal', 'Glass', 'Cardboard'], answer: 2 },
          { type: 'multiple', q: 'Which is a natural material?', options: ['Plastic', 'Nylon', 'Wool', 'Rubber'], answer: 2 },
          { type: 'trueFalse', q: 'Metal is a good conductor of heat', answer: true },
          { type: 'multiple', q: 'Why are windows made of glass?', options: ['It is strong', 'You can see through it', 'It is cheap', 'It is soft'], answer: 1 },
          { type: 'multiple', q: 'Which material is waterproof?', options: ['Paper', 'Fabric', 'Rubber', 'Cardboard'], answer: 2 },
          { type: 'multiple', q: 'Which can be bent easily?', options: ['Glass', 'Stone', 'Rubber', 'Metal'], answer: 2 },
          { type: 'trueFalse', q: 'Wood comes from trees', answer: true },
          { type: 'multiple', q: 'Which is a man-made material?', options: ['Cotton', 'Silk', 'Plastic', 'Leather'], answer: 2 },
          { type: 'multiple', q: 'What does "opaque" mean?', options: ['See-through', 'Cannot see through', 'Very hard', 'Very soft'], answer: 1 },
          { type: 'trueFalse', q: 'Some materials are elastic', answer: true },
          { type: 'multiple', q: 'Which property describes texture?', options: ['Hard', 'Smooth', 'Rough', 'All of above'], answer: 3 },
          { type: 'multiple', q: 'Paper can be...', options: ['Stretched', 'Squashed', 'Bent', 'All of above'], answer: 3 },
          { type: 'trueFalse', q: 'Plastic can be stretched', answer: true },
          { type: 'multiple', q: 'Why is plastic used for bags?', options: ['It is heavy', 'It is waterproof', 'It breaks easily', 'It dissolves'], answer: 1 },
          { type: 'trueFalse', q: 'Metal is stronger than plastic', answer: true },
          { type: 'multiple', q: 'Which material is flexible?', options: ['Stone', 'Glass', 'Rubber', 'Brick'], answer: 2 },
          { type: 'multiple', q: 'What does stretching mean?', options: ['Making shorter', 'Making longer', 'Making softer', 'Making harder'], answer: 1 },
          { type: 'trueFalse', q: 'Wool is a natural material', answer: true },
          { type: 'multiple', q: 'Which material is used for clothes?', options: ['Glass', 'Metal', 'Fabric', 'Stone'], answer: 2 },
          { type: 'trueFalse', q: 'Some materials are magnetic', answer: true },
          { type: 'multiple', q: 'Why would you choose rubber for a shoe sole?', options: ['Hard', 'Waterproof and bendy', 'Cheap', 'Heavy'], answer: 1 },
          { type: 'trueFalse', q: 'Material properties help us choose what to use', answer: true },
          { type: 'multiple', q: 'Which cannot be recycled?', options: ['Paper', 'Plastic', 'Metal', 'All can be'], answer: 3 },
          { type: 'trueFalse', q: 'Comparing materials helps us choose the best one', answer: true }
        ]
      }
    ]
  },

  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#FF5722',
    lessons: [
      {
        id: 'y2-french-1',
        title: 'Greetings & Introductions',
        description: 'Bonjour, Au revoir, Comment tu t\'appelles?, Je m\'appelle...',
        questions: [
          { type: 'multiple', q: 'How do you say "Hello" in French?', options: ['Au revoir', 'Bonjour', 'Merci', 'S\'il vous plaît'], answer: 1 },
          { type: 'multiple', q: 'What does "Bonjour" mean?', options: ['Goodbye', 'Good morning/afternoon', 'Thank you', 'Please'], answer: 1 },
          { type: 'multiple', q: 'How do you say "Goodbye"?', options: ['Bonjour', 'Au revoir', 'Bienvenue', 'Merci'], answer: 1 },
          { type: 'trueFalse', q: '"Au revoir" means "goodbye"', answer: true },
          { type: 'multiple', q: '"Comment tu t\'appelles?" means...', options: ['What are you doing?', 'What is your name?', 'How are you?', 'Where are you?'], answer: 1 },
          { type: 'multiple', q: '"Je m\'appelle Marie" means...', options: ['I am happy', 'My name is Marie', 'I like Marie', 'Where is Marie'], answer: 1 },
          { type: 'trueFalse', q: '"Je m\'appelle" means "I am called"', answer: true },
          { type: 'multiple', q: 'How do you introduce yourself in French?', options: ['Bonjour, je m\'appelle...', 'Au revoir, je suis...', 'Merci, je m\'appelle...', 'S\'il vous plaît...'], answer: 0 },
          { type: 'multiple', q: 'What does "Enchanté" mean?', options: ['Angry', 'Nice to meet you', 'How are you', 'See you'], answer: 1 },
          { type: 'trueFalse', q: '"Bonsoir" means "good evening"', answer: true },
          { type: 'multiple', q: '"Salut" is...', options: ['Thank you', 'Hello (informal)', 'Goodbye', 'Please'], answer: 1 },
          { type: 'multiple', q: 'How do you ask "How are you?" formally?', options: ['Ça va?', 'Comment allez-vous?', 'Tu vas bien?', 'Ça va?'], answer: 1 },
          { type: 'trueFalse', q: '"Ça va?" means "How are you?"', answer: true },
          { type: 'multiple', q: '"Très bien, merci" means...', options: ['Not very well', 'Very well, thank you', 'Not bad', 'So-so'], answer: 1 },
          { type: 'multiple', q: 'What is a casual greeting?', options: ['Bonjour', 'Salut', 'Au revoir', 'S\'il vous plaît'], answer: 1 },
          { type: 'trueFalse', q: '"Merci beaucoup" means "thank you very much"', answer: true },
          { type: 'multiple', q: '"De rien" means...', options: ['You are welcome', 'No thanks', 'Goodbye', 'Hello'], answer: 0 },
          { type: 'multiple', q: 'How do you say "Nice to meet you" (formal)?', options: ['Enchanté', 'Salut', 'Au revoir', 'Merci'], answer: 0 },
          { type: 'trueFalse', q: '"Bienvenue" means "welcome"', answer: true },
          { type: 'multiple', q: '"Je m\'appelle Tom. Et toi?" means...', options: ['I am Tom. Are you?', 'I am called Tom. And you?', 'I like Tom. What?', 'I am Tom. Where?'], answer: 1 },
          { type: 'multiple', q: 'How do you respond to "Comment tu t\'appelles?"', options: ['Je suis...', 'Je m\'appelle...', 'Je vais...', 'Je fais...'], answer: 1 },
          { type: 'trueFalse', q: '"Bonne journée" means "have a good day"', answer: true },
          { type: 'multiple', q: 'What do you say before eating?', options: ['Merci', 'Bon appétit', 'Bonjour', 'Au revoir'], answer: 1 },
          { type: 'trueFalse', q: '"S\'il vous plaît" is a formal "please"', answer: true }
        ]
      },
      {
        id: 'y2-french-2',
        title: 'Numbers 1-20',
        description: 'un, deux, trois... vingt',
        questions: [
          { type: 'multiple', q: 'What is "one" in French?', options: ['Deux', 'Un', 'Trois', 'Cinq'], answer: 1 },
          { type: 'multiple', q: '"Deux" is...', options: ['1', '2', '3', '4'], answer: 1 },
          { type: 'multiple', q: 'What is "three" in French?', options: ['Deux', 'Trois', 'Quatre', 'Cinq'], answer: 1 },
          { type: 'multiple', q: '"Quatre" means...', options: ['3', '4', '5', '6'], answer: 1 },
          { type: 'trueFalse', q: '"Cinq" means "five"', answer: true },
          { type: 'multiple', q: 'What is "six" in French?', options: ['Cinq', 'Six', 'Sept', 'Huit'], answer: 1 },
          { type: 'multiple', q: '"Sept" is...', options: ['6', '7', '8', '9'], answer: 1 },
          { type: 'multiple', q: 'What is "eight" in French?', options: ['Sept', 'Huit', 'Neuf', 'Dix'], answer: 1 },
          { type: 'multiple', q: '"Neuf" means...', options: ['7', '8', '9', '10'], answer: 2 },
          { type: 'trueFalse', q: '"Dix" means "ten"', answer: true },
          { type: 'multiple', q: 'What is "eleven" in French?', options: ['Dix', 'Onze', 'Douze', 'Treize'], answer: 1 },
          { type: 'multiple', q: '"Douze" is...', options: ['10', '11', '12', '13'], answer: 2 },
          { type: 'multiple', q: 'What is "thirteen" in French?', options: ['Douze', 'Treize', 'Quatorze', 'Quinze'], answer: 1 },
          { type: 'trueFalse', q: '"Quatorze" means "fourteen"', answer: true },
          { type: 'multiple', q: 'What is "fifteen" in French?', options: ['Quatorze', 'Quinze', 'Seize', 'Dix-sept'], answer: 1 },
          { type: 'multiple', q: '"Seize" is...', options: ['14', '15', '16', '17'], answer: 2 },
          { type: 'multiple', q: 'What is "seventeen" in French?', options: ['Quinze', 'Seize', 'Dix-sept', 'Dix-huit'], answer: 2 },
          { type: 'trueFalse', q: '"Dix-huit" means "eighteen"', answer: true },
          { type: 'multiple', q: 'What is "nineteen" in French?', options: ['Dix-huit', 'Dix-neuf', 'Vingt', 'Vingt-un'], answer: 1 },
          { type: 'trueFalse', q: '"Vingt" means "twenty"', answer: true },
          { type: 'multiple', q: 'Count: Un, deux, trois, ___?', options: ['Cinq', 'Quatre', 'Six', 'Deux'], answer: 1 },
          { type: 'multiple', q: 'Count: Dix, onze, douze, ___?', options: ['Quatorze', 'Treize', 'Quinze', 'Seize'], answer: 1 },
          { type: 'multiple', q: 'What number comes after "dix-neuf"?', options: ['Dix-huit', 'Vingt', 'Dix-sept', 'Vingt-un'], answer: 1 },
          { type: 'trueFalse', q: '"Zéro" means "zero"', answer: true }
        ]
      },
      {
        id: 'y2-french-3',
        title: 'Colours',
        description: 'rouge, bleu, vert, jaune, orange, rose, noir, blanc, marron, violet, gris',
        questions: [
          { type: 'multiple', q: 'What is "red" in French?', options: ['Bleu', 'Rouge', 'Vert', 'Jaune'], answer: 1 },
          { type: 'multiple', q: '"Bleu" means...', options: ['Red', 'Blue', 'Green', 'Yellow'], answer: 1 },
          { type: 'multiple', q: 'What is "green" in French?', options: ['Bleu', 'Vert', 'Jaune', 'Rouge'], answer: 1 },
          { type: 'trueFalse', q: '"Jaune" means "yellow"', answer: true },
          { type: 'multiple', q: 'What is "orange" in French?', options: ['Orange', 'Jaune', 'Rouge', 'Rose'], answer: 0 },
          { type: 'multiple', q: '"Rose" is...', options: ['Red', 'Orange', 'Pink', 'Purple'], answer: 2 },
          { type: 'multiple', q: 'What is "black" in French?', options: ['Blanc', 'Noir', 'Gris', 'Marron'], answer: 1 },
          { type: 'trueFalse', q: '"Blanc" means "white"', answer: true },
          { type: 'multiple', q: 'What is "brown" in French?', options: ['Noir', 'Marron', 'Gris', 'Bleu'], answer: 1 },
          { type: 'multiple', q: '"Violet" is...', options: ['Green', 'Purple', 'Pink', 'Orange'], answer: 1 },
          { type: 'multiple', q: 'What is "grey" in French?', options: ['Gris', 'Rose', 'Marron', 'Blanc'], answer: 0 },
          { type: 'trueFalse', q: '"Orange" is the same in French and English', answer: true },
          { type: 'multiple', q: 'What colour is "bleu"?', options: ['Red', 'Green', 'Blue', 'Yellow'], answer: 2 },
          { type: 'trueFalse', q: '"Rose" means "pink"', answer: true },
          { type: 'multiple', q: 'What colour is "noir"?', options: ['White', 'Black', 'Grey', 'Brown'], answer: 1 },
          { type: 'multiple', q: '"Vert" is which colour?', options: ['Red', 'Green', 'Blue', 'Yellow'], answer: 1 },
          { type: 'trueFalse', q: '"Marron" means "brown"', answer: true },
          { type: 'multiple', q: 'What colour is "blanc"?', options: ['Black', 'White', 'Grey', 'Pink'], answer: 1 },
          { type: 'multiple', q: '"Violet" is which colour?', options: ['Orange', 'Purple', 'Green', 'Pink'], answer: 1 },
          { type: 'trueFalse', q: '"Gris" means "grey"', answer: true },
          { type: 'multiple', q: 'Which colour is "jaune"?', options: ['Red', 'Orange', 'Yellow', 'Green'], answer: 2 },
          { type: 'multiple', q: '"Rouge" is which colour?', options: ['Red', 'Orange', 'Pink', 'Purple'], answer: 0 },
          { type: 'multiple', q: 'What colour is "rose"?', options: ['Red', 'Orange', 'Pink', 'Purple'], answer: 2 },
          { type: 'trueFalse', q: '"Bleu" means "blue"', answer: true }
        ]
      }
    ]
  }
};
