window.YEAR_6_DATA = {
  maths: {
    name: 'Maths',
    icon: '🔢',
    color: '#4CAF50',
    lessons: [
      {
        id: 'y6-maths-1',
        name: 'Place Value',
        description: 'Numbers to 10 million, negative numbers, rounding',
        questions: [
          { type: 'multiple', q: 'What is the value of 7 in 7,654,321?', options: ['7 million', '700,000', '7,000', '700'], answer: '7 million' },
          { type: 'fillBlank', q: '10 million written in numerals is ___', answer: '10000000', accept: ['10,000,000', '10000000'] },
          { type: 'trueFalse', q: 'The number -25 is less than -10', answer: true },
          { type: 'multiple', q: 'Round 4,567,890 to the nearest million', options: ['5,000,000', '4,500,000', '4,600,000', '4,000,000'], answer: '5,000,000' },
          { type: 'fillBlank', q: 'In 9,876,543, the digit 8 represents ___ hundred thousands', answer: '8', accept: ['8'] },
          { type: 'trueFalse', q: '-100 is further from zero than -50', answer: true },
          { type: 'multiple', q: 'What is 3,456,789 rounded to the nearest 10,000?', options: ['3,460,000', '3,457,000', '3,456,800', '3,450,000'], answer: '3,460,000' },
          { type: 'fillBlank', q: 'Order from smallest to largest: -5, 0, -15, 10, -1: ___', answer: '-15, -5, -1, 0, 10', accept: ['-15, -5, -1, 0, 10', '-15,-5,-1,0,10'] },
          { type: 'multiple', q: 'What is 8,912,345 rounded to the nearest million?', options: ['9,000,000', '8,900,000', '8,000,000', '9,000,000'], answer: '9,000,000' },
          { type: 'trueFalse', q: 'Negative numbers are used to show temperatures below freezing', answer: true },
          { type: 'fillBlank', q: '5 million + 600 thousand + 7 = ___', answer: '5600007', accept: ['5,600,007', '5600007'] },
          { type: 'multiple', q: 'Which number is larger: -8 or -3?', options: ['-3', '-8', 'They are equal', 'Cannot compare'], answer: '-3' },
          { type: 'trueFalse', q: 'You can partition 7,654,321 as 7,000,000 + 600,000 + 50,000 + 4,000 + 300 + 20 + 1', answer: true },
          { type: 'fillBlank', q: '9,999,999 rounded to the nearest 100,000 is ___', answer: '10000000', accept: ['10,000,000', '10000000'] },
          { type: 'multiple', q: 'What is the place value of 5 in 2,534,678?', options: ['500,000', '50,000', '5,000', '500'], answer: '500,000' },
          { type: 'trueFalse', q: '-20 is colder than 0°C', answer: true },
          { type: 'fillBlank', q: 'Write 8,000,000 in words: ___ million', answer: 'eight', accept: ['eight'] },
          { type: 'multiple', q: 'Order from largest to smallest: 1,234,567 and 1,243,567 and 1,324,567', options: ['1,324,567 > 1,243,567 > 1,234,567', '1,234,567 > 1,243,567 > 1,324,567', '1,243,567 > 1,324,567 > 1,234,567', 'All equal'], answer: '1,324,567 > 1,243,567 > 1,234,567' },
          { type: 'trueFalse', q: '-7 + 5 = -2', answer: true },
          { type: 'fillBlank', q: 'In the number 4,087,256, the 0 shows there are ___ hundred thousands', answer: '0', accept: ['0', 'no', 'none'] }
        ]
      },
      {
        id: 'y6-maths-2',
        name: 'Four Operations',
        description: 'Long division, BODMAS, multi-step problems, estimation',
        questions: [
          { type: 'multiple', q: 'What does BODMAS stand for?', options: ['Brackets, Orders, Division, Multiplication, Addition, Subtraction', 'Brackets, Operations, Divide, Multiply, Add, Subtract', 'Calculate in a different order', 'Only brackets first'], answer: 'Brackets, Orders, Division, Multiplication, Addition, Subtraction' },
          { type: 'fillBlank', q: 'In BODMAS, ___ come before division and multiplication', answer: 'Brackets', accept: ['Brackets', 'Orders'] },
          { type: 'multiple', q: 'Calculate: 10 + 5 × 2', options: ['20', '30', '12', '17'], answer: '20' },
          { type: 'trueFalse', q: '(8 + 2) × 3 = 30', answer: true },
          { type: 'fillBlank', q: '24 ÷ 3 + 4 = ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'What is 456 ÷ 12 using long division?', options: ['38', '37', '39', '36'], answer: '38' },
          { type: 'trueFalse', q: '2 + 3 × 4 = 14 (not 20)', answer: true },
          { type: 'fillBlank', q: '(6 + 4) ÷ 2 = ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'Calculate: 100 - 20 + 5', options: ['85', '75', '80', '90'], answer: '85' },
          { type: 'trueFalse', q: 'In BODMAS, addition and subtraction have equal priority', answer: true },
          { type: 'fillBlank', q: '8 × 7 - 6 ÷ 2 = ___', answer: '53', accept: ['53'] },
          { type: 'multiple', q: 'What is 2³ + 5?', options: ['13', '11', '16', '8'], answer: '13' },
          { type: 'trueFalse', q: '3 × 4 ÷ 2 = 6', answer: true },
          { type: 'fillBlank', q: '(20 - 5) × 2 = ___', answer: '30', accept: ['30'] },
          { type: 'multiple', q: 'Calculate: 12 + 8 ÷ 4 × 2', options: ['16', '18', '10', '20'], answer: '16' },
          { type: 'trueFalse', q: 'Estimate: 487 + 312 ≈ 800', answer: true },
          { type: 'fillBlank', q: '5 + 3 × (10 - 2) = ___', answer: '29', accept: ['29'] },
          { type: 'multiple', q: 'What is 1,234 ÷ 8 (long division)?', options: ['154 r 2', '153 r 2', '155', '152 r 6'], answer: '154 r 2' },
          { type: 'trueFalse', q: '(2 + 3) × (4 + 1) = 25', answer: true },
          { type: 'fillBlank', q: '100 ÷ (2 + 3) = ___', answer: '20', accept: ['20'] }
        ]
      },
      {
        id: 'y6-maths-3',
        name: 'Fractions',
        description: 'Simplify, compare, four operations with fractions, mixed numbers',
        questions: [
          { type: 'multiple', q: 'Simplify 6/8', options: ['3/4', '1/2', '2/3', '6/8'], answer: '3/4' },
          { type: 'fillBlank', q: '4/5 + 1/5 = ___', answer: '1', accept: ['1', '5/5'] },
          { type: 'trueFalse', q: 'To add fractions with different denominators, you must find a common denominator', answer: true },
          { type: 'multiple', q: 'What is 1/2 + 1/4?', options: ['3/4', '2/6', '1/6', '2/4'], answer: '3/4' },
          { type: 'fillBlank', q: 'Simplify 10/15 to ___', answer: '2/3', accept: ['2/3'] },
          { type: 'trueFalse', q: '3/4 > 2/3', answer: true },
          { type: 'fillBlank', q: '2/3 + 1/6 = ___', answer: '5/6', accept: ['5/6'] },
          { type: 'multiple', q: 'What is 5/8 - 1/8?', options: ['4/8', '1/2', '4/16', 'Both A and B'], answer: 'Both A and B' },
          { type: 'trueFalse', q: 'To multiply fractions, multiply numerators and denominators separately', answer: true },
          { type: 'fillBlank', q: '2/3 × 3/4 = ___', answer: '1/2', accept: ['1/2', '6/12'] },
          { type: 'multiple', q: 'What is 3/4 ÷ 1/2?', options: ['3/2', '1/2', '3/8', '1/4'], answer: '3/2' },
          { type: 'trueFalse', q: 'To divide fractions, multiply by the reciprocal', answer: true },
          { type: 'fillBlank', q: 'Convert 9/4 to a mixed number: ___', answer: '2 1/4', accept: ['2 1/4', 'two and one quarter'] },
          { type: 'multiple', q: 'Which fraction is in simplest form?', options: ['5/7', '6/9', '8/12', '10/15'], answer: '5/7' },
          { type: 'trueFalse', q: '1/2 + 1/3 = 2/5', answer: false },
          { type: 'fillBlank', q: '1/3 + 1/4 = ___', answer: '7/12', accept: ['7/12'] },
          { type: 'multiple', q: 'Simplify 8/12', options: ['2/3', '1/2', '4/6', 'Both A and C'], answer: 'Both A and C' },
          { type: 'trueFalse', q: '2/5 < 1/2', answer: true },
          { type: 'fillBlank', q: '4/5 - 1/5 = ___', answer: '3/5', accept: ['3/5'] },
          { type: 'multiple', q: 'What is 1/2 × 1/2?', options: ['1/4', '1/2', '2/4', '1/1'], answer: '1/4' }
        ]
      },
      {
        id: 'y6-maths-4',
        name: 'Decimals',
        description: 'Multiply/divide by 10/100/1000, operations with decimals',
        questions: [
          { type: 'fillBlank', q: '3.5 × 10 = ___', answer: '35', accept: ['35'] },
          { type: 'multiple', q: 'What is 456.7 ÷ 10?', options: ['45.67', '4567', '4.567', '45.67'], answer: '45.67' },
          { type: 'trueFalse', q: '12.5 × 100 = 1250', answer: true },
          { type: 'fillBlank', q: '8,900 ÷ 100 = ___', answer: '89', accept: ['89'] },
          { type: 'multiple', q: 'Multiply: 7.23 × 10', options: ['72.3', '0.723', '723', '7230'], answer: '72.3' },
          { type: 'trueFalse', q: '0.5 × 100 = 50', answer: true },
          { type: 'fillBlank', q: '5,600 ÷ 1000 = ___', answer: '5.6', accept: ['5.6'] },
          { type: 'multiple', q: 'What is 2.4 + 3.7?', options: ['6.1', '5.11', '5.1', '6.11'], answer: '6.1' },
          { type: 'trueFalse', q: '8.5 - 2.3 = 6.2', answer: true },
          { type: 'fillBlank', q: '0.25 × 4 = ___', answer: '1', accept: ['1'] },
          { type: 'multiple', q: 'Divide: 12.5 ÷ 5', options: ['2.5', '2.25', '0.25', '25'], answer: '2.5' },
          { type: 'trueFalse', q: '3.45 × 1000 = 3450', answer: true },
          { type: 'fillBlank', q: '10.5 ÷ 10 = ___', answer: '1.05', accept: ['1.05'] },
          { type: 'multiple', q: 'What is 4.2 × 3?', options: ['12.6', '1.4', '7.2', '12.4'], answer: '12.6' },
          { type: 'trueFalse', q: 'To multiply decimals by 10, move the decimal point right one place', answer: true },
          { type: 'fillBlank', q: '7.8 + 2.5 = ___', answer: '10.3', accept: ['10.3'] },
          { type: 'multiple', q: 'What is 15.6 ÷ 100?', options: ['0.156', '1560', '156', '1.56'], answer: '0.156' },
          { type: 'trueFalse', q: '9.9 + 0.1 = 10', answer: true },
          { type: 'fillBlank', q: '6.3 - 4.1 = ___', answer: '2.2', accept: ['2.2'] },
          { type: 'multiple', q: 'Divide: 50 ÷ 1000', options: ['0.05', '0.5', '5', '50000'], answer: '0.05' }
        ]
      },
      {
        id: 'y6-maths-5',
        name: 'Percentages',
        description: 'Percentage of amount, increase/decrease, equivalence',
        questions: [
          { type: 'fillBlank', q: 'Find 10% of 50: ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'What is 50% of 100?', options: ['50', '100', '25', '75'], answer: '50' },
          { type: 'trueFalse', q: '25% of 80 = 20', answer: true },
          { type: 'fillBlank', q: 'Calculate 20% of 60: ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'What is 1% of 200?', options: ['2', '20', '200', '0.2'], answer: '2' },
          { type: 'trueFalse', q: '75% equals 3/4', answer: true },
          { type: 'fillBlank', q: 'Find 5% of 100: ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'A £50 item is increased by 10%. New price = ___', options: ['£55', '£45', '£5', '£40'], answer: '£55' },
          { type: 'trueFalse', q: '15% of 60 = 9', answer: true },
          { type: 'fillBlank', q: 'A price of £80 decreases by 25%. New price = £___', answer: '60', accept: ['60'] },
          { type: 'multiple', q: 'What percentage is 15 out of 60?', options: ['25%', '15%', '50%', '75%'], answer: '25%' },
          { type: 'trueFalse', q: '100% = 1 as a decimal', answer: true },
          { type: 'fillBlank', q: 'Find 40% of 250: ___', answer: '100', accept: ['100'] },
          { type: 'multiple', q: 'A book costs £20. It is reduced by 10%. New price?', options: ['£18', '£22', '£2', '£30'], answer: '£18' },
          { type: 'trueFalse', q: '33% is approximately 1/3', answer: true },
          { type: 'fillBlank', q: '60% of 50 = ___', answer: '30', accept: ['30'] },
          { type: 'multiple', q: 'Which equals 0.5?', options: ['50%', '5%', '5', '0.05'], answer: '50%' },
          { type: 'trueFalse', q: '200% = 2 as a fraction', answer: true },
          { type: 'fillBlank', q: 'If a £100 item is increased by 20%, it costs £___', answer: '120', accept: ['120'] },
          { type: 'multiple', q: '30% of 90 = ___', options: ['27', '30', '60', '63'], answer: '27' }
        ]
      },
      {
        id: 'y6-maths-6',
        name: 'Ratio & Proportion',
        description: 'Simplify ratios, scale factors, unequal sharing, recipes',
        questions: [
          { type: 'multiple', q: 'Simplify the ratio 6:9', options: ['2:3', '1:2', '3:2', '6:9'], answer: '2:3' },
          { type: 'fillBlank', q: 'If the ratio is 3:5 and there are 15 of the first item, there are ___ of the second', answer: '25', accept: ['25'] },
          { type: 'trueFalse', q: 'A ratio shows the relationship between two quantities', answer: true },
          { type: 'multiple', q: 'Simplify 10:15:20', options: ['2:3:4', '5:7:10', '1:1.5:2', '10:15:20'], answer: '2:3:4' },
          { type: 'fillBlank', q: 'Ratio of boys to girls is 4:5. If there are 20 boys, there are ___ girls', answer: '25', accept: ['25'] },
          { type: 'trueFalse', q: 'A scale factor of 2 doubles all dimensions', answer: true },
          { type: 'fillBlank', q: 'If a recipe uses 2:3 sugar to flour and you use 6 cups sugar, use ___ cups flour', answer: '9', accept: ['9'] },
          { type: 'multiple', q: 'Share £60 in the ratio 2:3. First share = £___', options: ['£24', '£36', '£20', '£40'], answer: '£24' },
          { type: 'trueFalse', q: '6:8:10 simplifies to 3:4:5', answer: true },
          { type: 'fillBlank', q: 'A scale factor of 1/2 halves all dimensions. Original: 10 cm. Scaled: ___ cm', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'Share 40 sweets in ratio 1:3. Smaller share = ___', options: ['10', '30', '15', '20'], answer: '10' },
          { type: 'trueFalse', q: 'If ratio is 5:2 and first quantity is 15, second is 6', answer: true },
          { type: 'fillBlank', q: 'Simplify ratio 12:8 to ___', answer: '3:2', accept: ['3:2'] },
          { type: 'multiple', q: 'A recipe needs milk:sugar = 4:1. For 8 parts milk, need ___ parts sugar', options: ['2', '4', '1', '8'], answer: '2' },
          { type: 'trueFalse', q: 'Proportion compares part to part or part to whole', answer: true },
          { type: 'fillBlank', q: 'Ratio 7:3. If second is 12, first is ___', answer: '28', accept: ['28'] },
          { type: 'multiple', q: 'Share 90 in ratio 2:4:3. Middle share = ___', options: ['40', '20', '30', '60'], answer: '40' },
          { type: 'trueFalse', q: 'If scale factor is 3, an area 4 cm² becomes 36 cm²', answer: true },
          { type: 'fillBlank', q: 'Simplify 14:21:28 to ___', answer: '2:3:4', accept: ['2:3:4'] },
          { type: 'multiple', q: 'Paint ratio red:blue = 3:5. Total paint = 40 litres. Red = ___', options: ['15', '25', '20', '8'], answer: '15' }
        ]
      },
      {
        id: 'y6-maths-7',
        name: 'Algebra',
        description: 'Simple formulae, linear sequences, find unknowns, enumerate possibilities',
        questions: [
          { type: 'fillBlank', q: 'If a = 3, then 2a + 1 = ___', answer: '7', accept: ['7'] },
          { type: 'multiple', q: 'Which is a linear sequence?', options: ['2, 4, 6, 8', '1, 2, 4, 8', '1, 4, 9, 16', '2, 3, 5, 8'], answer: '2, 4, 6, 8' },
          { type: 'trueFalse', q: 'The nth term can describe any number in a sequence', answer: true },
          { type: 'fillBlank', q: 'Sequence: 5, 10, 15, 20. The nth term is ___ × n', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'If x + 5 = 12, what is x?', options: ['7', '8', '6', '17'], answer: '7' },
          { type: 'trueFalse', q: 'In algebra, letters represent unknown or variable numbers', answer: true },
          { type: 'fillBlank', q: 'Solve: 3x = 15. x = ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'Find the nth term of: 3, 6, 9, 12', options: ['3n', 'n + 3', '3 + n', '3n - 3'], answer: '3n' },
          { type: 'trueFalse', q: 'If b = 2, then b² + 3b = 10', answer: true },
          { type: 'fillBlank', q: 'Solve: 2x + 3 = 11. x = ___', answer: '4', accept: ['4'] },
          { type: 'multiple', q: 'What is the common difference in 7, 11, 15, 19?', options: ['4', '3', '5', '8'], answer: '4' },
          { type: 'trueFalse', q: 'y = 2x + 1 is a formula', answer: true },
          { type: 'fillBlank', q: 'If c = 5, then 10 - c = ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'The formula is P = 2l + 2w. If l=5, w=3, then P = ___', options: ['16', '15', '30', '8'], answer: '16' },
          { type: 'trueFalse', q: 'If 4y = 20, then y = 5', answer: true },
          { type: 'fillBlank', q: 'Sequence: 2, 5, 8, 11. Nth term = ___ n + ___', answer: '3, -1', accept: ['3n - 1', '3n-1'] },
          { type: 'multiple', q: 'Solve: a ÷ 2 = 6. a = ___', options: ['12', '3', '8', '4'], answer: '12' },
          { type: 'trueFalse', q: 'The term "enumerate" means to list possibilities', answer: true },
          { type: 'fillBlank', q: 'If the formula is A = l × w, and l=4, w=3, then A = ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'Which sequence has nth term = 2n?', options: ['2, 4, 6, 8', '1, 2, 3, 4', '1, 3, 5, 7', '3, 6, 9, 12'], answer: '2, 4, 6, 8' }
        ]
      },
      {
        id: 'y6-maths-8',
        name: 'Measurement',
        description: 'Area of triangles/parallelograms, volume of cuboids, unit conversion',
        questions: [
          { type: 'fillBlank', q: 'Area of triangle = 1/2 × base × ___', answer: 'height', accept: ['height'] },
          { type: 'multiple', q: 'Find the area of a triangle: base 8 cm, height 6 cm', options: ['24 cm²', '48 cm²', '14 cm²', '28 cm²'], answer: '24 cm²' },
          { type: 'trueFalse', q: 'Area of a parallelogram = base × height', answer: true },
          { type: 'fillBlank', q: 'A parallelogram has base 5 cm, height 4 cm. Area = ___ cm²', answer: '20', accept: ['20'] },
          { type: 'multiple', q: 'A cuboid is 3 m long, 2 m wide, 4 m tall. Volume = ___', options: ['24 m³', '12 m³', '9 m³', '8 m³'], answer: '24 m³' },
          { type: 'trueFalse', q: '1 km = 1,000 m', answer: true },
          { type: 'fillBlank', q: 'Convert 5 km to metres: ___', answer: '5000', accept: ['5000', '5,000'] },
          { type: 'multiple', q: 'How many millilitres in 2.5 litres?', options: ['2,500 ml', '250 ml', '25 ml', '0.25 ml'], answer: '2,500 ml' },
          { type: 'trueFalse', q: '1 mile is approximately 1.6 km', answer: true },
          { type: 'fillBlank', q: 'A triangle has base 12 cm, height 7 cm. Area = ___ cm²', answer: '42', accept: ['42'] },
          { type: 'multiple', q: 'How many centimetres in 3.5 metres?', options: ['350 cm', '35 cm', '3,500 cm', '3.5 cm'], answer: '350 cm' },
          { type: 'trueFalse', q: 'Volume is measured in cubic units (cm³, m³)', answer: true },
          { type: 'fillBlank', q: 'A cuboid: 5 cm × 3 cm × 2 cm = ___ cm³', answer: '30', accept: ['30'] },
          { type: 'multiple', q: 'Convert 7,200 seconds to minutes', options: ['120 minutes', '72 minutes', '720 minutes', '7,200 minutes'], answer: '120 minutes' },
          { type: 'trueFalse', q: '10 mm = 1 cm', answer: true },
          { type: 'fillBlank', q: 'Area of parallelogram: base 9 m, height 5 m = ___ m²', answer: '45', accept: ['45'] },
          { type: 'multiple', q: 'Convert 2,500 g to kg', options: ['2.5 kg', '25 kg', '0.25 kg', '250 kg'], answer: '2.5 kg' },
          { type: 'trueFalse', q: 'A triangle with base 10 cm, height 8 cm has area 80 cm²', answer: false },
          { type: 'fillBlank', q: 'A cuboid volume is 60 m³. Dimensions: 3 m × 5 m × ___ m', answer: '4', accept: ['4'] },
          { type: 'multiple', q: 'How many hours in 300 minutes?', options: ['5 hours', '50 hours', '3 hours', '30 hours'], answer: '5 hours' }
        ]
      },
      {
        id: 'y6-maths-9',
        name: 'Geometry',
        description: 'Classify shapes, circles, angles in triangles, nets of 3D, coordinates',
        questions: [
          { type: 'multiple', q: 'What is the circumference formula?', options: ['π × diameter', 'π × radius', '2 × π × diameter', 'π ÷ radius'], answer: 'π × diameter' },
          { type: 'fillBlank', q: 'A regular polygon has all ___ equal', answer: 'sides and angles', accept: ['sides and angles', 'angles', 'sides'] },
          { type: 'trueFalse', q: 'The sum of angles in a triangle is always 180°', answer: true },
          { type: 'multiple', q: 'What is a net?', options: ['A 2D shape that can be folded to make a 3D shape', 'A fishing net', 'A type of pattern', 'A mathematical formula'], answer: 'A net' },
          { type: 'fillBlank', q: 'A ___ is a quadrilateral with all sides equal and all angles 90°', answer: 'square', accept: ['square'] },
          { type: 'trueFalse', q: 'A circle has infinite lines of symmetry', answer: true },
          { type: 'fillBlank', q: 'The point (3, 4) has x-coordinate ___ and y-coordinate 4', answer: '3', accept: ['3'] },
          { type: 'multiple', q: 'In 4 quadrants, which quadrant is (-2, 3)?', options: ['Quadrant II (top-left)', 'Quadrant I (top-right)', 'Quadrant III (bottom-left)', 'Quadrant IV (bottom-right)'], answer: 'Quadrant II (top-left)' },
          { type: 'trueFalse', q: 'A radius is half of the diameter', answer: true },
          { type: 'fillBlank', q: 'A triangle where all angles are less than 90° is ___', answer: 'acute', accept: ['acute'] },
          { type: 'multiple', q: 'What is a trapezium?', options: ['A quadrilateral with one pair of parallel sides', 'A triangle', 'A parallelogram', 'A shape with 5 sides'], answer: 'A quadrilateral with one pair of parallel sides' },
          { type: 'trueFalse', q: 'A cube net has 6 square faces', answer: true },
          { type: 'fillBlank', q: 'The distance from the centre of a circle to the edge is the ___', answer: 'radius', accept: ['radius'] },
          { type: 'multiple', q: 'If one angle in a triangle is 90°, what type of triangle is it?', options: ['Right-angled', 'Acute', 'Obtuse', 'Equilateral'], answer: 'Right-angled' },
          { type: 'trueFalse', q: 'Opposite angles in a parallelogram are equal', answer: true },
          { type: 'fillBlank', q: 'The point where the x and y axes meet is (___,___)', answer: '0,0', accept: ['0,0', '0, 0'] },
          { type: 'multiple', q: 'How many faces does a rectangular prism (cuboid) have?', options: ['6', '8', '12', '4'], answer: '6' },
          { type: 'trueFalse', q: 'A rhombus is a parallelogram with all sides equal', answer: true },
          { type: 'fillBlank', q: 'A polygon with 6 sides is a ___', answer: 'hexagon', accept: ['hexagon'] },
          { type: 'multiple', q: 'What is the area of a circle?', options: ['πr²', 'πd', '2πr', 'π × d²'], answer: 'πr²' }
        ]
      },
      {
        id: 'y6-maths-10',
        name: 'Statistics',
        description: 'Pie charts, the mean, interpret tables/graphs, construct line graphs',
        questions: [
          { type: 'multiple', q: 'What is the mean of 2, 4, 6, 8?', options: ['5', '4', '6', '8'], answer: '5' },
          { type: 'fillBlank', q: 'A ___ chart shows parts of a whole as sectors', answer: 'pie', accept: ['pie'] },
          { type: 'trueFalse', q: 'The median is the middle value when data is ordered', answer: true },
          { type: 'multiple', q: 'What is the mode of 3, 5, 5, 7, 9, 5?', options: ['5', '6', '7', '3'], answer: '5' },
          { type: 'fillBlank', q: 'Range = ___ value - ___ value', answer: 'highest, lowest', accept: ['highest, lowest', 'largest, smallest', 'maximum, minimum'] },
          { type: 'trueFalse', q: 'The median of 1, 2, 3, 4, 5 is 3', answer: true },
          { type: 'fillBlank', q: 'Mean of 10, 20, 30 = ___', answer: '20', accept: ['20'] },
          { type: 'multiple', q: 'A line graph shows data points connected by ___', options: ['Lines', 'Bars', 'Circles', 'Squares'], answer: 'Lines' },
          { type: 'trueFalse', q: 'A scatter graph shows the correlation between two variables', answer: true },
          { type: 'fillBlank', q: 'Range of 5, 12, 3, 18, 7 = ___', answer: '15', accept: ['15'] },
          { type: 'multiple', q: 'What does a histogram show?', options: ['Frequency distribution of continuous data', 'Data over time', 'Parts of a whole', 'Relationship between two variables'], answer: 'Frequency distribution of continuous data' },
          { type: 'trueFalse', q: 'In a pie chart, the total is always 360°', answer: true },
          { type: 'fillBlank', q: 'If data is 8, 10, 12, 14, 16, the mean is ___', answer: '12', accept: ['12'] },
          { type: 'multiple', q: 'Which type of chart would best show change over time?', options: ['Line graph', 'Pie chart', 'Histogram', 'Scatter graph'], answer: 'Line graph' },
          { type: 'trueFalse', q: 'A bar chart uses rectangles of equal width', answer: true },
          { type: 'fillBlank', q: 'Median of 2, 4, 5, 6, 8 = ___', answer: '5', accept: ['5'] },
          { type: 'multiple', q: 'What information might a table show?', options: ['Frequency, values, categories', 'Only numbers', 'Only text', 'Nothing specific'], answer: 'Frequency, values, categories' },
          { type: 'trueFalse', q: 'Mode is the value that appears most often', answer: true },
          { type: 'fillBlank', q: 'Mean of 5, 10, 15, 20 = ___', answer: '12.5', accept: ['12.5'] },
          { type: 'multiple', q: 'An outlier is ___', options: ['A value very different from others', 'A missing value', 'A repeated value', 'The average'], answer: 'A value very different from others' }
        ]
      }
    ]
  },
  english: {
    name: 'English',
    icon: '📖',
    color: '#2196F3',
    lessons: [
      {
        id: 'y6-english-1',
        name: 'Subjunctive Form',
        description: 'If I were..., It is essential that she be...',
        questions: [
          { type: 'multiple', q: 'What is the subjunctive mood?', options: ['A verb form expressing wishes, doubts, or hypothetical situations', 'A type of tense', 'A command', 'A past action'], answer: 'A verb form expressing wishes, doubts, or hypothetical situations' },
          { type: 'fillBlank', q: '"If I ___ you, I would go." Complete with subjunctive', answer: 'were', accept: ['were'] },
          { type: 'trueFalse', q: '"If I was you" is grammatically correct subjunctive', answer: false },
          { type: 'fillBlank', q: 'It is essential that he ___ on time.', answer: 'be', accept: ['be'] },
          { type: 'multiple', q: 'Which sentence uses subjunctive correctly?', options: ['If I were rich, I would travel', 'If I was rich, I would travel', 'If I am rich, I will travel', 'If I had been rich, I would be travel'], answer: 'If I were rich, I would travel' },
          { type: 'trueFalse', q: 'The subjunctive is used after "wish" clauses', answer: true },
          { type: 'fillBlank', q: '"I suggest that she ___ the exam." (use subjunctive)', answer: 'take', accept: ['take'] },
          { type: 'multiple', q: 'What follows "It is important that..." in subjunctive?', options: ['The base form of the verb (without -s)', 'Past tense', 'Present tense + -s', 'Infinitive'], answer: 'The base form of the verb (without -s)' },
          { type: 'trueFalse', q: '"If she be here" is modern subjunctive', answer: false },
          { type: 'fillBlank', q: '"I wish that you ___ here." (subjunctive)', answer: 'were', accept: ['were'] },
          { type: 'multiple', q: 'Complete: "It is vital that everyone ___ their homework."', options: ['do', 'does', 'did', 'is doing'], answer: 'do' },
          { type: 'trueFalse', q: 'Subjunctive "were" is used after "if" in hypothetical situations', answer: true },
          { type: 'fillBlank', q: '"God ___ you." (archaic subjunctive)', answer: 'bless', accept: ['bless'] },
          { type: 'multiple', q: 'Which expresses a hypothetical situation?', options: ['If I were invisible', 'If I am invisible', 'If I was invisible', 'If I am being invisible'], answer: 'If I were invisible' },
          { type: 'trueFalse', q: 'The subjunctive is uncommon in modern English', answer: true },
          { type: 'fillBlank', q: '"It is crucial that she ___ the deadline." (subjunctive)', answer: 'meet', accept: ['meet'] },
          { type: 'multiple', q: 'Suggest clause: "I recommend that they ___ the offer."', options: ['accept', 'accepts', 'accepted', 'are accepting'], answer: 'accept' },
          { type: 'trueFalse', q: 'Subjunctive is found in formal writing and speech', answer: true },
          { type: 'fillBlank', q: '"If this be true, it is tragic." (subjunctive)', answer: 'be', accept: ['be'] },
          { type: 'multiple', q: 'Complete: "I move that the motion ___ approved."', options: ['be', 'is', 'being', 'been'], answer: 'be' }
        ]
      },
      {
        id: 'y6-english-2',
        name: 'Active & Passive Voice',
        description: 'The cat chased the mouse / The mouse was chased by the cat',
        questions: [
          { type: 'multiple', q: 'What is active voice?', options: ['The subject performs the action', 'The subject receives the action', 'No action is performed', 'Past action only'], answer: 'The subject performs the action' },
          { type: 'fillBlank', q: '"The dog caught the ball." Voice: ___', answer: 'active', accept: ['active'] },
          { type: 'trueFalse', q: '"The book was read by Sarah" is passive voice', answer: true },
          { type: 'multiple', q: 'Convert to passive: "They built the house"', options: ['The house was built by them', 'The house they built', 'They were building the house', 'The house is being built'], answer: 'The house was built by them' },
          { type: 'fillBlank', q: '"The pizza was eaten." Voice: ___', answer: 'passive', accept: ['passive'] },
          { type: 'trueFalse', q: 'Passive voice uses "to be" + past participle', answer: true },
          { type: 'multiple', q: 'Convert to active: "The letter was posted by Emma"', options: ['Emma posted the letter', 'The letter Emma posted', 'Emma was posting the letter', 'The letter post was by Emma'], answer: 'Emma posted the letter' },
          { type: 'trueFalse', q: '"Sarah wrote the essay" is passive voice', answer: false },
          { type: 'fillBlank', q: 'Active: "The teacher marked the tests." Passive: "The tests ___ by the teacher."', answer: 'were marked', accept: ['were marked', 'was marked'] },
          { type: 'multiple', q: 'Which is passive?', options: ['The cake was baked by Mum', 'Mum baked the cake', 'Mum is baking the cake', 'The cake bakes easily'], answer: 'The cake was baked by Mum' },
          { type: 'trueFalse', q: 'Passive voice is always weaker than active voice', answer: false },
          { type: 'fillBlank', q: 'Passive: "The car was stolen." Active: "___ the car."', answer: 'They stole', accept: ['They stole', 'Someone stole'] },
          { type: 'multiple', q: 'Convert to passive: "The manager will approve the request"', options: ['The request will be approved by the manager', 'The request was approved by the manager', 'The request is approved by the manager', 'The manager approved the request'], answer: 'The request will be approved by the manager' },
          { type: 'trueFalse', q: 'You can write passive voice without mentioning who did the action', answer: true },
          { type: 'fillBlank', q: '"The homework is being done by the students." Tense: ___', answer: 'present continuous passive', accept: ['present continuous passive', 'present continuous'] },
          { type: 'multiple', q: 'Which sentence is more direct?', options: ['Sarah broke the vase', 'The vase was broken by Sarah', 'The vase had been broken', 'Breaking occurred to the vase'], answer: 'Sarah broke the vase' },
          { type: 'trueFalse', q: 'Passive voice can sometimes be useful in formal writing', answer: true },
          { type: 'fillBlank', q: 'Active: "They discovered the island." Passive: "The island ___ by them."', answer: 'was discovered', accept: ['was discovered'] },
          { type: 'multiple', q: 'Identify the voice: "The film was enjoyed by everyone"', options: ['Passive', 'Active', 'Neither', 'Both'], answer: 'Passive' },
          { type: 'trueFalse', q: 'Past participles are essential for forming passive voice', answer: true }
        ]
      },
      {
        id: 'y6-english-3',
        name: 'Synonyms & Antonyms',
        description: 'Word relationships, shades of meaning, vocabulary precision',
        questions: [
          { type: 'multiple', q: 'What is a synonym?', options: ['A word with a similar meaning', 'A word with the opposite meaning', 'A word spelled the same', 'A related word'], answer: 'A word with a similar meaning' },
          { type: 'fillBlank', q: 'A synonym for "happy" is ___', answer: 'joyful', accept: ['joyful', 'cheerful', 'delighted'] },
          { type: 'trueFalse', q: 'An antonym has the opposite meaning', answer: true },
          { type: 'multiple', q: 'What is an antonym for "big"?', options: ['Small', 'Large', 'Huge', 'Tall'], answer: 'Small' },
          { type: 'fillBlank', q: 'Antonym of "hot" is ___', answer: 'cold', accept: ['cold', 'cool'] },
          { type: 'trueFalse', q: '"Fast" and "quick" are perfect synonyms with identical meaning', answer: false },
          { type: 'multiple', q: 'Which pair are synonyms?', options: ['Terrified and afraid', 'Happy and sad', 'Old and young', 'Big and small'], answer: 'Terrified and afraid' },
          { type: 'trueFalse', q: 'Shades of meaning show subtle differences between synonyms', answer: true },
          { type: 'fillBlank', q: 'Synonym for "said" in formal writing might be ___', answer: 'declared', accept: ['declared', 'stated', 'announced'] },
          { type: 'multiple', q: 'Which words show increasing intensity?', options: ['Annoyed, irritated, furious', 'Furious, irritated, annoyed', 'Annoyed, furious, irritated', 'All the same'], answer: 'Annoyed, irritated, furious' },
          { type: 'trueFalse', q: '"Walked" and "sauntered" have the same precise meaning', answer: false },
          { type: 'fillBlank', q: 'Antonym of "difficult" is ___', answer: 'easy', accept: ['easy', 'simple'] },
          { type: 'multiple', q: 'Choose the word closest in meaning to "enormous"', options: ['Huge', 'Big', 'Large', 'Vast'], answer: 'Huge' },
          { type: 'trueFalse', q: 'Word choice affects the tone and precision of writing', answer: true },
          { type: 'fillBlank', q: 'Synonym for "beautiful" might be ___', answer: 'gorgeous', accept: ['gorgeous', 'lovely', 'stunning'] },
          { type: 'multiple', q: 'Which pairs are antonyms?', options: ['Begin and end', 'Big and tall', 'Fast and slow', 'Both A and C'], answer: 'Both A and C' },
          { type: 'trueFalse', q: '"Timid" is a stronger synonym for "shy" than "reserved"', answer: true },
          { type: 'fillBlank', q: 'Antonym of "generous" is ___', answer: 'stingy', accept: ['stingy', 'mean', 'selfish'] },
          { type: 'multiple', q: 'Which set shows increasing shades of warmth?', options: ['Chilly, cool, pleasant, warm, hot', 'Hot, warm, pleasant, cool, chilly', 'Cool, pleasant, warm, chilly, hot', 'All the same'], answer: 'Chilly, cool, pleasant, warm, hot' },
          { type: 'trueFalse', q: 'Understanding synonyms helps improve vocabulary precision', answer: true }
        ]
      },
      {
        id: 'y6-english-4',
        name: 'Colons, Semi-colons & Dashes',
        description: 'Listing, explanation, independent clauses',
        questions: [
          { type: 'multiple', q: 'What is a colon used for?', options: ['To introduce a list or explanation', 'To join two sentences', 'To show hesitation', 'To mark the end of a sentence'], answer: 'To introduce a list or explanation' },
          { type: 'trueFalse', q: 'A semi-colon joins two related independent clauses', answer: true },
          { type: 'fillBlank', q: 'Example: "I need: apples, oranges, and bananas." Mark: ___', answer: 'colon', accept: ['colon', ':'] },
          { type: 'multiple', q: 'When should you use a semi-colon?', options: ['To connect two independent clauses', 'Instead of a full stop', 'To mark a pause', 'Before a long list'], answer: 'To connect two independent clauses' },
          { type: 'trueFalse', q: '"She was tired; she still went to school." Semi-colon use is correct', answer: true },
          { type: 'fillBlank', q: 'Dashes can show a sudden ___ or break in thought', answer: 'change', accept: ['change', 'pause', 'interruption'] },
          { type: 'multiple', q: 'Which shows correct colon use?', options: ['I have three goals: pass exams, make friends, stay healthy', 'I have three goals, pass exams, make friends, stay healthy', 'I have three goals; pass exams, make friends, stay healthy', 'I have three goals. Pass exams, make friends, stay healthy'], answer: 'I have three goals: pass exams, make friends, stay healthy' },
          { type: 'trueFalse', q: 'A dash is more formal than a semi-colon', answer: false },
          { type: 'fillBlank', q: '"There are two choices: stay or go." Punctuation: ___', answer: 'colon', accept: ['colon', ':'] },
          { type: 'multiple', q: 'Which is correct semi-colon usage?', options: ['The show was entertaining; I enjoyed every minute', 'The show was entertaining; enjoyed every minute', 'The show was entertaining; it was good', 'The show was entertaining, I enjoyed it'], answer: 'The show was entertaining; I enjoyed every minute' },
          { type: 'trueFalse', q: 'A dash can replace parentheses for emphasis', answer: true },
          { type: 'fillBlank', q: '"She wanted to leave – but she stayed." Mark: ___', answer: 'dash', accept: ['dash', '–'] },
          { type: 'multiple', q: 'When introducing a quote, use a ___', options: ['Colon', 'Semi-colon', 'Dash', 'Comma'], answer: 'Colon' },
          { type: 'trueFalse', q: '"Fish are amazing; they can breathe underwater." Semi-colon is correct', answer: true },
          { type: 'fillBlank', q: 'Use a colon to introduce: examples, lists, or ___', answer: 'explanations', accept: ['explanations'] },
          { type: 'multiple', q: 'Which punctuation joins two related independent clauses?', options: ['Semi-colon', 'Colon', 'Comma', 'Dash'], answer: 'Semi-colon' },
          { type: 'trueFalse', q: '"The materials are: paper, paint, and brushes" is correct', answer: true },
          { type: 'fillBlank', q: '"He was nervous – very nervous – about the test." Punctuation: ___', answer: 'dashes', accept: ['dashes', '–'] },
          { type: 'multiple', q: 'A colon should be followed by ___', options: ['A lower-case word or capital letter (depending on what follows)', 'Always a capital letter', 'Always a lower-case word', 'A number'], answer: 'A lower-case word or capital letter (depending on what follows)' },
          { type: 'trueFalse', q: 'Semi-colons are rarely used in modern writing', answer: false }
        ]
      },
      {
        id: 'y6-english-5',
        name: 'Hyphens',
        description: 'Co-ordinate, re-enter, compound adjectives: well-known',
        questions: [
          { type: 'multiple', q: 'What does a hyphen do?', options: ['Joins two words to form one', 'Separates clauses', 'Marks a pause', 'Ends a sentence'], answer: 'Joins two words to form one' },
          { type: 'fillBlank', q: 'The prefix "re-" followed by a vowel often needs a hyphen: re-___', answer: 'enter', accept: ['enter', 'arrange', 'apply'] },
          { type: 'trueFalse', q: '"Well-known" uses a hyphen as a compound adjective', answer: true },
          { type: 'multiple', q: 'When is a hyphen used with a prefix?', options: ['Before a capital letter or vowel', 'Always', 'Never', 'Only with re-'], answer: 'Before a capital letter or vowel' },
          { type: 'fillBlank', q: 'Compound adjective: "a ___-looking dog"', answer: 'well', accept: ['well'] },
          { type: 'trueFalse', q: '"Twenty-five" is hyphenated', answer: true },
          { type: 'multiple', q: 'Which compound adjective is correct?', options: ['A well-behaved child', 'A well behaved child', 'A well-child behaved', 'A well-behaves-child'], answer: 'A well-behaved child' },
          { type: 'trueFalse', q: '"Co-operate" uses a hyphen to clarify pronunciation', answer: true },
          { type: 'fillBlank', q: 'Compound word: "mother-___"', answer: 'in-law', accept: ['in-law'] },
          { type: 'multiple', q: 'Which number is correctly hyphenated?', options: ['Fifty-three', 'Fifty three', 'Fifty-3', 'Five-ty-three'], answer: 'Fifty-three' },
          { type: 'trueFalse', q: 'A hyphen prevents ambiguity in compounds like "man-eating shark"', answer: true },
          { type: 'fillBlank', q: '"A ___-year-old child" needs hyphens', answer: 'five', accept: ['five', '5'] },
          { type: 'multiple', q: 'When is "re-" hyphenated?', options: ['Before a vowel or capital (e.g., re-enter, re-enter)', 'Always', 'Never', 'Only if confusing'], answer: 'Before a vowel or capital (e.g., re-enter, re-enter)' },
          { type: 'trueFalse', q: '"Mother in law" (no hyphens) is correct', answer: false },
          { type: 'fillBlank', q: 'Compound: "a ___-time job"', answer: 'part', accept: ['part'] },
          { type: 'multiple', q: 'Which is hyphenated correctly?', options: ['A light-blue car', 'A light blue car', 'A light-blue-car', 'A light-blue car-colour'], answer: 'A light-blue car' },
          { type: 'trueFalse', q: 'Hyphens in compound adjectives prevent confusion of meaning', answer: true },
          { type: 'fillBlank', q: '"Un-happy" should be written without hyphen as ___', answer: 'unhappy', accept: ['unhappy'] },
          { type: 'multiple', q: 'When is hyphenation necessary in compounds?', options: ['To clarify meaning and prevent ambiguity', 'Always', 'Never in modern English', 'Only for long words'], answer: 'To clarify meaning and prevent ambiguity' },
          { type: 'trueFalse', q: '"A small-scale project" is correctly hyphenated', answer: true }
        ]
      },
      {
        id: 'y6-english-6',
        name: 'Formal Language & Register',
        description: 'Subjunctive, passive voice, formal conjunctions',
        questions: [
          { type: 'multiple', q: 'What is formal register?', options: ['Language used in official or academic contexts', 'Casual everyday speech', 'Language with errors', 'Slang'], answer: 'Language used in official or academic contexts' },
          { type: 'fillBlank', q: 'Formal: "Consequently." Informal: "___"', answer: 'So', accept: ['So', 'Then'] },
          { type: 'trueFalse', q: 'Passive voice is often used in formal writing', answer: true },
          { type: 'multiple', q: 'Which is formal?', options: ['With regard to the matter', 'About the thing', 'Concerning the stuff', 'Regarding the thing'], answer: 'With regard to the matter' },
          { type: 'fillBlank', q: 'Formal conjunction: "___" (showing result)', answer: 'Therefore', accept: ['Therefore', 'Thus', 'Consequently'] },
          { type: 'trueFalse', q: 'Contractions are acceptable in formal writing', answer: false },
          { type: 'multiple', q: 'Complete formally: "It is essential that the deadline ___"', options: ['be met', 'is met', 'gets met', 'being met'], answer: 'be met' },
          { type: 'trueFalse', q: 'Subjunctive mood is more formal than indicative', answer: true },
          { type: 'fillBlank', q: 'Informal: "You should definitely come." Formal: "Your ___ would be greatly appreciated."', answer: 'attendance', accept: ['attendance', 'presence'] },
          { type: 'multiple', q: 'Which formal conjunction shows addition?', options: ['Furthermore', 'Therefore', 'However', 'Nevertheless'], answer: 'Furthermore' },
          { type: 'trueFalse', q: 'Academic writing uses colloquial expressions freely', answer: false },
          { type: 'fillBlank', q: 'Formal: "I would appreciate if you could ___"', answer: 'provide', accept: ['provide'] },
          { type: 'multiple', q: 'Which shows formal language?', options: ['The results were analysed thoroughly', 'We looked at the results really well', 'The results got looked at', 'Looking at the results well'], answer: 'The results were analysed thoroughly' },
          { type: 'trueFalse', q: 'Formal writing often uses "one" instead of "you"', answer: true },
          { type: 'fillBlank', q: 'Formal: "Notwithstanding this ___"', answer: 'consideration', accept: ['consideration', 'fact', 'point'] },
          { type: 'multiple', q: 'In formal writing, avoid ___', options: ['Contractions, slang, informal phrases', 'All verbs', 'Adjectives', 'Complex ideas'], answer: 'Contractions, slang, informal phrases' },
          { type: 'trueFalse', q: 'Formal language maintains professional distance', answer: true },
          { type: 'fillBlank', q: 'Informal: "The bad stuff happened." Formal: "Unfortunate ___ occurred."', answer: 'circumstances', accept: ['circumstances', 'events'] },
          { type: 'multiple', q: 'Which formal conjunction shows contrast?', options: ['However', 'Moreover', 'Furthermore', 'Likewise'], answer: 'However' },
          { type: 'trueFalse', q: 'Register should match your audience and purpose', answer: true }
        ]
      },
      {
        id: 'y6-english-7',
        name: 'Word Classes & Sentence Structure',
        description: 'Subject, object, verb forms, multi-clause sentences',
        questions: [
          { type: 'multiple', q: 'What is the subject of a sentence?', options: ['The person or thing performing the action', 'The action being performed', 'The object affected', 'The location'], answer: 'The person or thing performing the action' },
          { type: 'fillBlank', q: '"The cat sat on the mat." Subject: ___', answer: 'cat', accept: ['cat', 'the cat'] },
          { type: 'trueFalse', q: 'The object receives the action from the subject', answer: true },
          { type: 'multiple', q: 'In "Sarah wrote a letter," what is the object?', options: ['Letter', 'Sarah', 'Wrote', 'A'], answer: 'Letter' },
          { type: 'fillBlank', q: '"The verb shows ___" (the action/state)', answer: 'action', accept: ['action', 'what is happening'] },
          { type: 'trueFalse', q: 'A multi-clause sentence has more than one clause', answer: true },
          { type: 'multiple', q: 'What is a clause?', options: ['A group of words with a subject and verb', 'A punctuation mark', 'A type of word', 'A list'], answer: 'A group of words with a subject and verb' },
          { type: 'trueFalse', q: '"She smiled because she was happy" contains two clauses', answer: true },
          { type: 'fillBlank', q: 'In a sentence, the ___ usually comes before the object', answer: 'verb', accept: ['verb'] },
          { type: 'multiple', q: 'Which sentence has a simple structure?', options: ['The cat sat on the mat', 'The cat, which was black, sat on the mat', 'Although the cat was tired, it sat on the mat', 'The cat sat on the mat because it was warm'], answer: 'The cat sat on the mat' },
          { type: 'trueFalse', q: 'An adverb modifies a verb, adjective, or another adverb', answer: true },
          { type: 'fillBlank', q: '"They played happily." Word class of "happily": ___', answer: 'adverb', accept: ['adverb'] },
          { type: 'multiple', q: 'In "The girl ran quickly away," identify the verb', options: ['Ran', 'Girl', 'Quickly', 'Away'], answer: 'Ran' },
          { type: 'trueFalse', q: 'A dependent clause can stand alone as a sentence', answer: false },
          { type: 'fillBlank', q: '"The beautiful girl danced." "Beautiful" is a/an ___', answer: 'adjective', accept: ['adjective'] },
          { type: 'multiple', q: 'Which shows correct subject-verb agreement?', options: ['The team is playing well', 'The team are playing well', 'The team was playing good', 'The team play good'], answer: 'The team is playing well' },
          { type: 'trueFalse', q: 'A compound sentence joins two independent clauses', answer: true },
          { type: 'fillBlank', q: '"He runs, jumps, and laughs." Verbs: ___, ___, ___', answer: 'runs, jumps, laughs', accept: ['runs, jumps, laughs'] },
          { type: 'multiple', q: 'In "They gave him a book," what is the indirect object?', options: ['Him', 'They', 'Book', 'Gave'], answer: 'Him' },
          { type: 'trueFalse', q: 'Complex sentences contain a main clause and subordinate clauses', answer: true }
        ]
      },
      {
        id: 'y6-english-8',
        name: 'Spelling Challenges',
        description: '-ible/-able, -ance/-ence, -cious/-tious, Year 5/6 list',
        questions: [
          { type: 'multiple', q: 'When do you use "-ible" vs "-able"?', options: ['"-ible" after root words not ending in e; "-able" after most other roots', '"-able" always for adjectives', '-ible" is old-fashioned', 'Both are identical'], answer: '"-ible" after root words not ending in e; "-able" after most other roots' },
          { type: 'fillBlank', q: '"Possible" ends in ___ (not -able)', answer: '-ible', accept: ['-ible', 'ible'] },
          { type: 'trueFalse', q: '"Comfortable" uses the "-able" suffix', answer: true },
          { type: 'fillBlank', q: '"Reasonable" is spelled with ___', answer: '-able', accept: ['-able', 'able'] },
          { type: 'multiple', q: 'Which word uses "-ible"?', options: ['Terrible', 'Comfortable', 'Reliable', 'Enjoyable'], answer: 'Terrible' },
          { type: 'trueFalse', q: '"Accessible" uses "-ible"', answer: true },
          { type: 'fillBlank', q: 'Noun: "importance." Suffix: ___', answer: '-ance', accept: ['-ance', 'ance'] },
          { type: 'multiple', q: 'When to use "-ance" vs "-ence"?', options: ['"-ance" after hard c/g sounds; "-ence" after soft sounds', 'Both are the same', '"-ence" is always correct', '-ance" is modern spelling'], answer: '"-ance" after hard c/g sounds; "-ence" after soft sounds' },
          { type: 'trueFalse', q: '"Patience" uses "-ence"', answer: true },
          { type: 'fillBlank', q: '"Appearance" ends with ___', answer: '-ance', accept: ['-ance', 'ance'] },
          { type: 'multiple', q: 'Which word uses "-ence"?', options: ['Difference', 'Significance', 'Appearance', 'Guidance'], answer: 'Difference' },
          { type: 'trueFalse', q: '"Confidence" uses "-ence" suffix', answer: true },
          { type: 'fillBlank', q: '"Conscious" ends with ___', answer: '-cious', accept: ['-cious', 'cious'] },
          { type: 'multiple', q: 'Which word ends in "-tious"?', options: ['Ambitious', 'Conscious', 'Precious', 'Delicious'], answer: 'Ambitious' },
          { type: 'trueFalse', q: '"Malicious" uses "-cious"', answer: true },
          { type: 'fillBlank', q: '"Superstitious" ends with ___', answer: '-tious', accept: ['-tious', 'tious'] },
          { type: 'multiple', q: 'Year 5/6 spelling: "Necessary" is often misspelled as ___', options: ['Necessery', 'Necessary', 'Neccessary', 'Nessecary'], answer: 'Necessary' },
          { type: 'trueFalse', q: '"Believe" is spelled b-e-l-i-e-v-e', answer: true },
          { type: 'fillBlank', q: 'Common misspelling: "Definite" not "___"', answer: 'definitly', accept: ['definitly', 'definate'] },
          { type: 'multiple', q: 'Which is spelled correctly?', options: ['Recommend', 'Recomend', 'Reccommend', 'Recommand'], answer: 'Recommend' }
        ]
      }
    ]
  },
  science: {
    name: 'Science',
    icon: '🔬',
    color: '#9C27B0',
    lessons: [
      {
        id: 'y6-science-1',
        name: 'Classification of Living Things',
        description: 'Linnaeus classification, micro-organisms, fungi, bacteria, viruses',
        questions: [
          { type: 'multiple', q: 'What did Carl Linnaeus develop?', options: ['A system for classifying living organisms', 'The theory of evolution', 'The microscope', 'Cell theory'], answer: 'A system for classifying living organisms' },
          { type: 'fillBlank', q: 'The five kingdoms are: animals, plants, fungi, and ___', answer: 'bacteria', accept: ['bacteria', 'protists'] },
          { type: 'trueFalse', q: 'Bacteria are single-celled micro-organisms', answer: true },
          { type: 'multiple', q: 'What is a virus?', options: ['A non-living infectious agent', 'A type of bacteria', 'A fungus', 'A microscopic plant'], answer: 'A non-living infectious agent' },
          { type: 'fillBlank', q: 'Fungi reproduce using ___', answer: 'spores', accept: ['spores'] },
          { type: 'trueFalse', q: 'Viruses can live and reproduce on their own', answer: false },
          { type: 'multiple', q: 'Which are examples of fungi?', options: ['Mushrooms, toadstools, moulds, yeasts', 'Bacteria', 'Viruses', 'Algae'], answer: 'Mushrooms, toadstools, moulds, yeasts' },
          { type: 'trueFalse', q: 'Bacteria are always harmful to humans', answer: false },
          { type: 'fillBlank', q: 'Micro-organisms are organisms visible only under a ___', answer: 'microscope', accept: ['microscope'] },
          { type: 'multiple', q: 'What do bacteria lack?', options: ['A nucleus and membrane-bound organelles', 'A cell wall', 'Ribosomes', 'DNA'], answer: 'A nucleus and membrane-bound organelles' },
          { type: 'trueFalse', q: 'Some viruses can cause diseases in plants', answer: true },
          { type: 'fillBlank', q: 'Fungi are neither plants nor animals; they form a separate ___', answer: 'kingdom', accept: ['kingdom'] },
          { type: 'multiple', q: 'What is the order of classification from broadest to narrowest?', options: ['Kingdom, Phylum, Class, Order, Family, Genus, Species', 'Species, Genus, Family, Order, Class, Phylum, Kingdom', 'Both are equivalent', 'Classification varies'], answer: 'Kingdom, Phylum, Class, Order, Family, Genus, Species' },
          { type: 'trueFalse', q: 'Bacteria reproduce mainly by binary fission', answer: true },
          { type: 'fillBlank', q: 'A virus consists of genetic material (DNA/RNA) surrounded by a protein ___', answer: 'coat', accept: ['coat', 'shell'] },
          { type: 'multiple', q: 'Which statement about fungi is true?', options: ['They absorb nutrients from dead organic matter', 'They make their own food by photosynthesis', 'They are always harmful', 'They have no cell walls'], answer: 'They absorb nutrients from dead organic matter' },
          { type: 'trueFalse', q: 'Protists include microscopic organisms like amoebas', answer: true },
          { type: 'fillBlank', q: 'Bacteria are prokaryotes, meaning they lack a ___', answer: 'nucleus', accept: ['nucleus'] },
          { type: 'multiple', q: 'What enters a host cell when a virus infects it?', options: ['Its genetic material', 'Its cell membrane', 'Its cytoplasm', 'All its contents'], answer: 'Its genetic material' },
          { type: 'trueFalse', q: 'The scientific name of an organism uses Genus and Species (binomial nomenclature)', answer: true }
        ]
      },
      {
        id: 'y6-science-2',
        name: 'Animals & Humans',
        description: 'Circulatory system, heart, blood, diet, exercise, drugs',
        questions: [
          { type: 'multiple', q: 'What does the circulatory system do?', options: ['Transports blood around the body', 'Digests food', 'Filters waste', 'Provides movement'], answer: 'Transports blood around the body' },
          { type: 'fillBlank', q: 'The ___ pumps blood around the body', answer: 'heart', accept: ['heart'] },
          { type: 'trueFalse', q: 'Red blood cells carry oxygen', answer: true },
          { type: 'multiple', q: 'What do white blood cells do?', options: ['Fight infection and disease', 'Carry oxygen', 'Carry nutrients', 'Carry hormones'], answer: 'Fight infection and disease' },
          { type: 'fillBlank', q: 'Blood vessels that carry blood away from the heart are ___', answer: 'arteries', accept: ['arteries'] },
          { type: 'trueFalse', q: 'Veins carry blood towards the heart', answer: true },
          { type: 'fillBlank', q: 'A balanced diet includes: carbohydrates, proteins, fats, vitamins, minerals, water, and ___', answer: 'fibre', accept: ['fibre', 'fiber'] },
          { type: 'multiple', q: 'Why is exercise important?', options: ['Strengthens heart and muscles, improves circulation', 'Only for weight loss', 'Reduces muscle', 'Increases stress'], answer: 'Strengthens heart and muscles, improves circulation' },
          { type: 'trueFalse', q: 'The heart is a muscle that pumps blood', answer: true },
          { type: 'fillBlank', q: 'Capillaries are tiny blood vessels where ___ and waste exchange occurs', answer: 'oxygen', accept: ['oxygen'] },
          { type: 'multiple', q: 'What effect do stimulant drugs have?', options: ['Speed up body functions', 'Slow down body functions', 'No effect', 'Improve health'], answer: 'Speed up body functions' },
          { type: 'trueFalse', q: 'Depressant drugs slow down the nervous system', answer: true },
          { type: 'fillBlank', q: 'A healthy diet should include plenty of ___ and vegetables', answer: 'fruit', accept: ['fruit'] },
          { type: 'multiple', q: 'What is cholesterol\'s role in the blood?', options: ['Transport of fats; can damage arteries if too high', 'Carrying oxygen', 'Fighting infection', 'Providing energy only'], answer: 'Transport of fats; can damage arteries if too high' },
          { type: 'trueFalse', q: 'Regular exercise can reduce the risk of heart disease', answer: true },
          { type: 'fillBlank', q: 'The ___ is a double pump organ that propels blood through two separate circuits', answer: 'heart', accept: ['heart'] },
          { type: 'multiple', q: 'Which nutrient provides energy?', options: ['Carbohydrates and fats', 'Vitamins only', 'Minerals only', 'Water'], answer: 'Carbohydrates and fats' },
          { type: 'trueFalse', q: 'Alcohol is an example of a depressant drug', answer: true },
          { type: 'fillBlank', q: 'Blood pressure can increase with salt intake and lack of ___', answer: 'exercise', accept: ['exercise'] },
          { type: 'multiple', q: 'Why are platelets important?', options: ['They help blood clot and stop bleeding', 'They carry oxygen', 'They fight infection', 'They provide structure'], answer: 'They help blood clot and stop bleeding' }
        ]
      },
      {
        id: 'y6-science-3',
        name: 'Evolution & Inheritance',
        description: 'Fossils as evidence, adaptation, variation, natural selection',
        questions: [
          { type: 'multiple', q: 'What are fossils?', options: ['Preserved remains of dead organisms', 'Types of rocks', 'Living organisms', 'Tools used by early humans'], answer: 'Preserved remains of dead organisms' },
          { type: 'fillBlank', q: 'Fossils provide evidence for ___', answer: 'evolution', accept: ['evolution'] },
          { type: 'trueFalse', q: 'Evolution is the process of change in living organisms over time', answer: true },
          { type: 'multiple', q: 'What is adaptation?', options: ['Features that help an organism survive', 'Change in behaviour', 'Movement to a new place', 'Change in size'], answer: 'Features that help an organism survive' },
          { type: 'fillBlank', q: 'A polar bear\'s white fur is an ___ to its environment', answer: 'adaptation', accept: ['adaptation'] },
          { type: 'trueFalse', q: 'Natural selection favours organisms with beneficial adaptations', answer: true },
          { type: 'multiple', q: 'What is variation?', options: ['Differences between individuals of the same species', 'Change over time', 'Evolution', 'Mutation'], answer: 'Differences between individuals of the same species' },
          { type: 'trueFalse', q: 'All individuals in a species are identical', answer: false },
          { type: 'fillBlank', q: 'Charles Darwin proposed the theory of ___', answer: 'natural selection', accept: ['natural selection', 'evolution'] },
          { type: 'multiple', q: 'How are fossils formed?', options: ['When organisms are buried and preserved over millions of years', 'Immediately when they die', 'Only for large animals', 'Through intentional burial'], answer: 'When organisms are buried and preserved over millions of years' },
          { type: 'trueFalse', q: 'Organisms inherit genes from their parents', answer: true },
          { type: 'fillBlank', q: 'A giraffe\'s long neck is an ___ for reaching leaves high in trees', answer: 'adaptation', accept: ['adaptation'] },
          { type: 'multiple', q: 'What does "survival of the fittest" mean?', options: ['Organisms best adapted to their environment are more likely to survive', 'Only the strongest survive', 'Fitness determines survival', 'Largest organisms always survive'], answer: 'Organisms best adapted to their environment are more likely to survive' },
          { type: 'trueFalse', q: 'Extinction occurs when all members of a species die out', answer: true },
          { type: 'fillBlank', q: 'Inherited traits are passed from ___ to offspring through genes', answer: 'parents', accept: ['parents'] },
          { type: 'multiple', q: 'Which is an example of variation?', options: ['Different eye colours in humans', 'All tigers look identical', 'All plants in a species are the same height', 'Evolution happens quickly'], answer: 'Different eye colours in humans' },
          { type: 'trueFalse', q: 'Acquired characteristics (traits learned in life) are inherited', answer: false },
          { type: 'fillBlank', q: 'Fossils found in rocks show organisms that lived ___', answer: 'in the past', accept: ['in the past', 'millions of years ago'] },
          { type: 'multiple', q: 'How long does evolution typically take?', options: ['Millions of years', 'Days', 'Months', 'A few years'], answer: 'Millions of years' },
          { type: 'trueFalse', q: 'Similar structures in different species suggest common ancestry', answer: true }
        ]
      },
      {
        id: 'y6-science-4',
        name: 'Light',
        description: 'How we see light, straight lines, shadows, reflection, refraction',
        questions: [
          { type: 'multiple', q: 'How do we see objects?', options: ['Light reflects from objects into our eyes', 'Objects emit light', 'Eyes produce light', 'Sound helps us see'], answer: 'Light reflects from objects into our eyes' },
          { type: 'fillBlank', q: 'Light travels in straight ___', answer: 'lines', accept: ['lines'] },
          { type: 'trueFalse', q: 'Light is faster than sound', answer: true },
          { type: 'multiple', q: 'What is a shadow?', options: ['An area where light is blocked', 'Darkness', 'A reflection', 'Cold air'], answer: 'An area where light is blocked' },
          { type: 'fillBlank', q: 'Reflection is when light bounces off a ___', answer: 'surface', accept: ['surface'] },
          { type: 'trueFalse', q: 'A mirror reflects light in a regular pattern', answer: true },
          { type: 'multiple', q: 'What is refraction?', options: ['Bending of light as it passes through different materials', 'Bouncing of light', 'Blocking of light', 'Spreading of light'], answer: 'Bending of light as it passes through different materials' },
          { type: 'fillBlank', q: 'A lens can focus light to form an ___', answer: 'image', accept: ['image'] },
          { type: 'trueFalse', q: 'Light travels slower in water than in air', answer: true },
          { type: 'multiple', q: 'What makes a shadow longer or shorter?', options: ['The position of the light source', 'The time of day', 'The object\'s colour', 'The observer\'s position'], answer: 'The position of the light source' },
          { type: 'trueFalse', q: 'A transparent material lets all light pass through', answer: true },
          { type: 'fillBlank', q: 'An opaque material ___ light from passing through', answer: 'blocks', accept: ['blocks'] },
          { type: 'multiple', q: 'Why is the sky blue?', options: ['Blue light is scattered in the atmosphere', 'The sun is blue', 'Water reflects blue light', 'It absorbs other colours'], answer: 'Blue light is scattered in the atmosphere' },
          { type: 'trueFalse', q: 'White light is made up of different colours', answer: true },
          { type: 'fillBlank', q: 'A prism separates white light into a ___', answer: 'rainbow', accept: ['rainbow'] },
          { type: 'multiple', q: 'What is a translucent material?', options: ['Lets some light through but not all', 'Lets all light through', 'Blocks all light', 'Reflects all light'], answer: 'Lets some light through but not all' },
          { type: 'trueFalse', q: 'Shadows can tell us about the direction of light', answer: true },
          { type: 'fillBlank', q: 'When light bends passing from air to water, it ___', answer: 'slows down', accept: ['slows down', 'bends'] },
          { type: 'multiple', q: 'What colour of light has the longest wavelength?', options: ['Red', 'Blue', 'Violet', 'Green'], answer: 'Red' },
          { type: 'trueFalse', q: 'The eye is a lens that focuses light on the retina', answer: true }
        ]
      },
      {
        id: 'y6-science-5',
        name: 'Electricity',
        description: 'Voltage, circuit diagrams, standard symbols, brightness/volume vary with voltage',
        questions: [
          { type: 'multiple', q: 'What is electrical current?', options: ['The flow of electrons through a circuit', 'Stored energy', 'Resistance', 'Voltage'], answer: 'The flow of electrons through a circuit' },
          { type: 'fillBlank', q: 'Voltage is measured in ___', answer: 'volts', accept: ['volts', 'V'] },
          { type: 'trueFalse', q: 'A circuit diagram uses symbols to show electrical components', answer: true },
          { type: 'multiple', q: 'What does a battery symbol look like?', options: ['Two short and long parallel lines', 'A circle', 'A coil', 'A straight line'], answer: 'Two short and long parallel lines' },
          { type: 'fillBlank', q: 'A ___ controls the flow of electricity in a circuit', answer: 'switch', accept: ['switch'] },
          { type: 'trueFalse', q: 'In a series circuit, all components are in a single path', answer: true },
          { type: 'fillBlank', q: 'The symbol for a resistor is a ___', answer: 'zigzag', accept: ['zigzag', 'zigzag line'] },
          { type: 'multiple', q: 'What is resistance?', options: ['Opposition to the flow of current', 'The amount of current', 'The amount of voltage', 'The pathway for current'], answer: 'Opposition to the flow of current' },
          { type: 'trueFalse', q: 'Higher voltage increases the brightness of a bulb', answer: true },
          { type: 'fillBlank', q: 'In a parallel circuit, components are in ___ paths', answer: 'multiple', accept: ['multiple', 'separate'] },
          { type: 'multiple', q: 'Why does a light bulb have a filament?', options: ['It resists current and produces heat and light', 'To direct current', 'To reduce voltage', 'To store energy'], answer: 'It resists current and produces heat and light' },
          { type: 'trueFalse', q: 'A circuit must be complete (closed) for current to flow', answer: true },
          { type: 'fillBlank', q: 'A ___ is a device that uses electricity to produce light', answer: 'bulb', accept: ['bulb', 'lamp'] },
          { type: 'multiple', q: 'What happens if you increase voltage in a circuit with a loudspeaker?', options: ['Volume increases', 'Volume decreases', 'Sound disappears', 'No change'], answer: 'Volume increases' },
          { type: 'trueFalse', q: 'Electrical current is measured in amperes (amps)', answer: true },
          { type: 'fillBlank', q: 'The standard symbol for a lamp is a ___', answer: 'circle with a cross', accept: ['circle with a cross', 'circle with X'] },
          { type: 'multiple', q: 'In a series circuit, if one bulb breaks, what happens?', options: ['The circuit is broken and all bulbs go out', 'Other bulbs stay on', 'Voltage increases', 'Current increases'], answer: 'The circuit is broken and all bulbs go out' },
          { type: 'trueFalse', q: 'Conductors allow electricity to flow easily', answer: true },
          { type: 'fillBlank', q: 'Insulators like rubber ___ the flow of electricity', answer: 'prevent', accept: ['prevent', 'stop', 'block'] },
          { type: 'multiple', q: 'What is the role of a switch in a circuit?', options: ['Opens or closes the circuit', 'Reduces resistance', 'Increases voltage', 'Stores energy'], answer: 'Opens or closes the circuit' }
        ]
      },
      {
        id: 'y6-science-6',
        name: 'Working Scientifically',
        description: 'Planning, fair tests, variables, evidence-based conclusions, accuracy',
        questions: [
          { type: 'multiple', q: 'What is the scientific method?', options: ['Systematic process for investigating phenomena', 'A type of experiment', 'Recording data only', 'Guessing the answer'], answer: 'Systematic process for investigating phenomena' },
          { type: 'fillBlank', q: 'A ___ is a suggested explanation based on limited evidence', answer: 'hypothesis', accept: ['hypothesis'] },
          { type: 'trueFalse', q: 'A fair test has only one variable that changes', answer: true },
          { type: 'multiple', q: 'What should you keep constant in a fair test?', options: ['All variables except the independent variable', 'Only temperature', 'Everything including the independent variable', 'Nothing'], answer: 'All variables except the independent variable' },
          { type: 'fillBlank', q: 'The ___ variable is what you deliberately change', answer: 'independent', accept: ['independent'] },
          { type: 'trueFalse', q: 'The dependent variable is what you measure', answer: true },
          { type: 'fillBlank', q: 'To make measurements more accurate, use ___ and repeat experiments', answer: 'appropriate equipment', accept: ['appropriate equipment', 'precise equipment'] },
          { type: 'multiple', q: 'Why is precision important in science?', options: ['It reduces error and provides reliable data', 'It makes experiments faster', 'It makes results more exciting', 'It is not important'], answer: 'It reduces error and provides reliable data' },
          { type: 'trueFalse', q: 'Anomalies (unusual results) should be ignored', answer: false },
          { type: 'fillBlank', q: 'Evidence should be ___ before drawing conclusions', answer: 'analysed', accept: ['analysed', 'analyzed', 'examined'] },
          { type: 'multiple', q: 'What is a control?', options: ['A standard for comparison', 'A variable', 'An equipment type', 'A measurement'], answer: 'A standard for comparison' },
          { type: 'trueFalse', q: 'Results should be recorded as they occur', answer: true },
          { type: 'fillBlank', q: 'Conclusions should be based on ___ not wishes', answer: 'evidence', accept: ['evidence'] },
          { type: 'multiple', q: 'Why repeat an experiment?', options: ['To check reliability and identify anomalies', 'To waste time', 'To confirm the hypothesis always', 'To get different results'], answer: 'To check reliability and identify anomalies' },
          { type: 'trueFalse', q: 'Accuracy is getting the correct answer; precision is getting consistent results', answer: true },
          { type: 'fillBlank', q: 'A ___ table organises and displays collected data', answer: 'data', accept: ['data', 'results'] },
          { type: 'multiple', q: 'Which statement about conclusions is true?', options: ['Should only be made from evidence gathered', 'Can include unrelated information', 'Should always match the hypothesis', 'Are not needed'], answer: 'Should only be made from evidence gathered' },
          { type: 'trueFalse', q: 'Graphs help visualise patterns in data', answer: true },
          { type: 'fillBlank', q: 'A line graph is best for showing change over ___', answer: 'time', accept: ['time'] },
          { type: 'multiple', q: 'What makes a good scientific investigation?', options: ['Clear hypothesis, fair test, accurate measurement, evidence-based conclusion', 'Any guess followed by testing', 'Only measuring once', 'Following instructions without thinking'], answer: 'Clear hypothesis, fair test, accurate measurement, evidence-based conclusion' }
        ]
      }
    ]
  },
  french: {
    name: 'French',
    icon: '🇫🇷',
    color: '#FF5722',
    lessons: [
      {
        id: 'y6-french-1',
        name: 'Describing People',
        description: 'Il/Elle est grand(e), cheveux blonds, yeux bleus',
        questions: [
          { type: 'fillBlank', q: '"He is tall" is: Il est ___', answer: 'grand', accept: ['grand'] },
          { type: 'multiple', q: 'How do you say "She is small" in French?', options: ['Elle est petite', 'Elle est petit', 'She est petite', 'Elle is small'], answer: 'Elle est petite' },
          { type: 'trueFalse', q: '"Elle a les cheveux noirs" means "She has black hair"', answer: true },
          { type: 'fillBlank', q: '"He has blue eyes" is: Il a les yeux ___', answer: 'bleus', accept: ['bleus'] },
          { type: 'multiple', q: 'What does "Elle a les cheveux blonds" mean?', options: ['She has blonde hair', 'She has black hair', 'She has curly hair', 'She has short hair'], answer: 'She has blonde hair' },
          { type: 'trueFalse', q: '"Il est grand et fort" means "He is tall and strong"', answer: true },
          { type: 'fillBlank', q: '"She has brown eyes" is: Elle a les yeux ___', answer: 'marron', accept: ['marron'] },
          { type: 'multiple', q: 'How do you describe someone as "young"?', options: ['Jeune', 'Vieux', 'Âgé', 'Petit'], answer: 'Jeune' },
          { type: 'trueFalse', q: '"Il est vieux" means "He is old"', answer: true },
          { type: 'fillBlank', q: '"He has red hair" is: Il a les cheveux ___', answer: 'roux', accept: ['roux'] },
          { type: 'multiple', q: 'What does "Elle est élancée" mean?', options: ['She is slim/slender', 'She is heavy', 'She is short', 'She is strong'], answer: 'She is slim/slender' },
          { type: 'trueFalse', q: '"Il est beau" means "He is handsome"', answer: true },
          { type: 'fillBlank', q: '"She is beautiful" is: Elle est ___', answer: 'belle', accept: ['belle'] },
          { type: 'multiple', q: 'How do you say "She has curly hair"?', options: ['Elle a les cheveux bouclés', 'Elle a les cheveux droits', 'Elle a les cheveux courts', 'Elle a les cheveux longs'], answer: 'Elle a les cheveux bouclés' },
          { type: 'trueFalse', q: '"Il a les cheveux gris" means "He has grey hair"', answer: true },
          { type: 'fillBlank', q: '"She has long hair" is: Elle a les cheveux ___', answer: 'longs', accept: ['longs'] },
          { type: 'multiple', q: 'What does "Elle a les yeux verts" mean?', options: ['She has green eyes', 'She has blue eyes', 'She has brown eyes', 'She has black eyes'], answer: 'She has green eyes' },
          { type: 'trueFalse', q: '"Il est mince" means "He is thin"', answer: true },
          { type: 'fillBlank', q: '"He has short hair" is: Il a les cheveux ___', answer: 'courts', accept: ['courts'] },
          { type: 'multiple', q: 'How do you describe someone as "fat"?', options: ['Gros/Grosse', 'Mince', 'Maigre', 'Fort'], answer: 'Gros/Grosse' }
        ]
      },
      {
        id: 'y6-french-2',
        name: 'Daily Routine',
        description: 'Je me lève, je me couche, je prends le petit-déjeuner',
        questions: [
          { type: 'fillBlank', q: '"I wake up" is: Je me ___', answer: 'lève', accept: ['lève'] },
          { type: 'multiple', q: 'What does "Je prends le petit-déjeuner" mean?', options: ['I have breakfast', 'I have lunch', 'I have dinner', 'I drink water'], answer: 'I have breakfast' },
          { type: 'trueFalse', q: '"Je me couche" means "I go to bed"', answer: true },
          { type: 'fillBlank', q: '"I get dressed" is: Je ___', answer: 'me habille', accept: ['me habille', 'm\'habille'] },
          { type: 'multiple', q: 'How do you say "I wash myself"?', options: ['Je me lave', 'Je lave', 'Je suis lavé', 'Je lavarai'], answer: 'Je me lave' },
          { type: 'trueFalse', q: '"Je prends une douche" means "I have a shower"', answer: true },
          { type: 'fillBlank', q: '"I brush my teeth" is: Je me ___ les dents', answer: 'brosse', accept: ['brosse'] },
          { type: 'multiple', q: 'What does "Je déjeune" mean?', options: ['I have lunch', 'I have breakfast', 'I have dinner', 'I snack'], answer: 'I have lunch' },
          { type: 'trueFalse', q: '"Je dîne" means "I have dinner"', answer: true },
          { type: 'fillBlank', q: '"I go to school" is: Je vais à \'___', answer: 'école', accept: ['école'] },
          { type: 'multiple', q: 'How do you say "I do my homework"?', options: ['Je fais mes devoirs', 'Je fais les devoirs', 'Je fais du devoir', 'Je devoirs'], answer: 'Je fais mes devoirs' },
          { type: 'trueFalse', q: '"Je me maquille" means "I put on makeup"', answer: true },
          { type: 'fillBlank', q: '"I play" in the context of daily routine: Je ___', answer: 'joue', accept: ['joue'] },
          { type: 'multiple', q: 'What does "Je regarde la télévision" mean?', options: ['I watch television', 'I listen to television', 'I read television', 'I have television'], answer: 'I watch television' },
          { type: 'trueFalse', q: '"Je me repose" means "I rest"', answer: true },
          { type: 'fillBlank', q: '"I read a book" is: Je ___ un livre', answer: 'lis', accept: ['lis'] },
          { type: 'multiple', q: 'How do you say "I eat breakfast"?', options: ['Je prends le petit-déjeuner', 'Je prends le déjeuner', 'Je prends le dîner', 'Je prends un repas'], answer: 'Je prends le petit-déjeuner' },
          { type: 'trueFalse', q: '"Je m\'endors" means "I fall asleep"', answer: true },
          { type: 'fillBlank', q: '"I pack my bag" is: Je ___ mon sac', answer: 'fais', accept: ['fais'] },
          { type: 'multiple', q: 'What is a typical French daily routine order?', options: ['Se lever, se laver, s\'habiller, petit-déjeuner, école, déjeuner, devoirs, dîner, se coucher', 'Petit-déjeuner, école, se laver, dîner, se coucher', 'Se coucher, se lever, dîner, école', 'Various based on preference'], answer: 'Se lever, se laver, s\'habiller, petit-déjeuner, école, déjeuner, devoirs, dîner, se coucher' }
        ]
      },
      {
        id: 'y6-french-3',
        name: 'Directions',
        description: 'Tournez à gauche/droite, allez tout droit, traversez, c\'est à côté de',
        questions: [
          { type: 'fillBlank', q: '"Turn left" is: Tournez à ___', answer: 'gauche', accept: ['gauche'] },
          { type: 'multiple', q: 'What does "Tournez à droite" mean?', options: ['Turn right', 'Turn left', 'Go straight', 'Cross here'], answer: 'Turn right' },
          { type: 'trueFalse', q: '"Allez tout droit" means "Go straight ahead"', answer: true },
          { type: 'fillBlank', q: '"Traverse the road" is: ___ la route', answer: 'Traversez', accept: ['Traversez'] },
          { type: 'multiple', q: 'How do you ask for directions?', options: ['Où est...?', 'Quel est...?', 'Pourquoi est...?', 'Quand est...?'], answer: 'Où est...?' },
          { type: 'trueFalse', q: '"C\'est à côté de la gare" means "It\'s next to the station"', answer: true },
          { type: 'fillBlank', q: '"It\'s opposite the church" is: C\'est ___ de l\'église', answer: 'en face', accept: ['en face'] },
          { type: 'multiple', q: 'What does "C\'est entre le parc et l\'école" mean?', options: ['It\'s between the park and the school', 'It\'s next to the park and school', 'It\'s opposite the park', 'It\'s near the school'], answer: 'It\'s between the park and the school' },
          { type: 'trueFalse', q: '"Prenez la première rue à gauche" means "Take the first street on the left"', answer: true },
          { type: 'fillBlank', q: '"Go straight ahead" is: Allez tout ___', answer: 'droit', accept: ['droit'] },
          { type: 'multiple', q: 'How do you say "It\'s at the end of the street"?', options: ['C\'est au bout de la rue', 'C\'est au début de la rue', 'C\'est au milieu de la rue', 'C\'est loin de la rue'], answer: 'C\'est au bout de la rue' },
          { type: 'trueFalse', q: '"Derrière" means "behind"', answer: true },
          { type: 'fillBlank', q: '"It\'s in front of the supermarket" is: C\'est ___ du supermarché', answer: 'devant', accept: ['devant'] },
          { type: 'multiple', q: 'What does "Continue tout droit" mean?', options: ['Continue straight ahead', 'Turn around', 'Go back', 'Stop here'], answer: 'Continue straight ahead' },
          { type: 'trueFalse', q: '"À gauche" means "on the right"', answer: false },
          { type: 'fillBlank', q: '"It\'s near the library" is: C\'est ___ la bibliothèque', answer: 'près de', accept: ['près de'] },
          { type: 'multiple', q: 'How do you say "Turn around"?', options: ['Faites demi-tour', 'Continuez', 'Allez tout droit', 'Tournez'], answer: 'Faites demi-tour' },
          { type: 'trueFalse', q: '"C\'est loin d\'ici" means "It\'s far from here"', answer: true },
          { type: 'fillBlank', q: '"It\'s close to here" is: C\'est ___ d\'ici', answer: 'près', accept: ['près'] },
          { type: 'multiple', q: 'What does "Continuez jusqu\'au feu rouge" mean?', options: ['Continue until the traffic light', 'Stop at the traffic light', 'Turn at the light', 'The light is red'], answer: 'Continue until the traffic light' }
        ]
      },
      {
        id: 'y6-french-4',
        name: 'Past Tense Basics',
        description: 'J\'ai mangé, j\'ai joué, je suis allé(e), hier',
        questions: [
          { type: 'fillBlank', q: '"I ate" is: J\'ai ___', answer: 'mangé', accept: ['mangé'] },
          { type: 'multiple', q: 'What does "J\'ai joué au football" mean?', options: ['I played football', 'I am playing football', 'I will play football', 'I play football'], answer: 'I played football' },
          { type: 'trueFalse', q: '"Je suis allé" means "I went" (masculine form)'", answer: true },
          { type: 'fillBlank', q: '"I went" (feminine) is: Je suis ___', answer: 'allée', accept: ['allée'] },
          { type: 'multiple', q: 'How do you say "Yesterday I watched TV"?', options: ['Hier, j\'ai regardé la télévision', 'Hier, je regarde la télévision', 'Hier, je regarderai la télévision', 'Hier, je regardais la télévision'], answer: 'Hier, j\'ai regardé la télévision' },
          { type: 'trueFalse', q: '"J\'ai lu un livre" means "I read a book"', answer: true },
          { type: 'fillBlank', q: '"I drank" is: J\'ai ___', answer: 'bu', accept: ['bu'] },
          { type: 'multiple', q: 'What does "Je suis arrivé" mean?', options: ['I arrived', 'I am arriving', 'I will arrive', 'I arrive'], answer: 'I arrived' },
          { type: 'trueFalse', q: '"J\'ai écrit une lettre" means "I wrote a letter"', answer: true },
          { type: 'fillBlank', q: '"I did/made" (past) is: J\'ai ___', answer: 'fait', accept: ['fait'] },
          { type: 'multiple', q: 'How do you form the passé composé?', options: ['Avoir or être + past participle', 'Je + past tense', 'Verb ending in -ai', 'Verb ending in -ais'], answer: 'Avoir or être + past participle' },
          { type: 'trueFalse', q: '"Je suis parti" means "I left" (masculine)'", answer: true },
          { type: 'fillBlank', q: '"I saw" is: J\'ai ___', answer: 'vu', accept: ['vu'] },
          { type: 'multiple', q: 'What does "Hier, j\'ai mangé une pomme" mean?', options: ['Yesterday, I ate an apple', 'Yesterday, I am eating an apple', 'Yesterday, I will eat an apple', 'Yesterday, I was eating an apple'], answer: 'Yesterday, I ate an apple' },
          { type: 'trueFalse', q: '"Je suis entré dans la maison" means "I entered the house"', answer: true },
          { type: 'fillBlank', q: '"I took" (past) is: J\'ai ___', answer: 'pris', accept: ['pris'] },
          { type: 'multiple', q: 'Which verbs use "être" in passé composé?', options: ['Aller, venir, arriver, partir, entrer, sortir', 'Avoir, faire, manger, boire', 'Être, avoir, être', 'All verbs'], answer: 'Aller, venir, arriver, partir, entrer, sortir' },
          { type: 'trueFalse', q: '"J\'ai entendu un bruit" means "I heard a noise"', answer: true },
          { type: 'fillBlank', q: '"I understood" is: J\'ai ___', answer: 'compris', accept: ['compris'] },
          { type: 'multiple', q: 'How do you say "I went to the cinema yesterday"?', options: ['Hier, je suis allé au cinéma', 'Hier, j\'ai allé au cinéma', 'Hier, j\'ai vais au cinéma', 'Hier, je vais au cinéma'], answer: 'Hier, je suis allé au cinéma' }
        ]
      },
      {
        id: 'y6-french-5',
        name: 'Opinions & Preferences',
        description: 'j\'adore, j\'aime bien, je déteste, je préfère, parce que',
        questions: [
          { type: 'fillBlank', q: '"I love football" is: J\'___ le football', answer: 'adore', accept: ['adore'] },
          { type: 'multiple', q: 'What does "J\'aime bien le chocolat" mean?', options: ['I quite like chocolate', 'I love chocolate', 'I hate chocolate', 'I want chocolate'], answer: 'I quite like chocolate' },
          { type: 'trueFalse', q: '"Je déteste les épinards" means "I hate spinach"', answer: true },
          { type: 'fillBlank', q: '"I prefer pizza" is: Je ___ la pizza', answer: 'préfère', accept: ['préfère'] },
          { type: 'multiple', q: 'How do you express a reason?', options: ['Parce que...', 'Pourquoi...?', 'Parce que c\'est...', 'Parce que il...'], answer: 'Parce que...' },
          { type: 'trueFalse', q: '"J\'adore le sport parce que c\'est amusant" means "I love sport because it\'s fun"', answer: true },
          { type: 'fillBlank', q: '"I like reading" is: J\'aime ___', answer: 'lire', accept: ['lire'] },
          { type: 'multiple', q: 'What does "Je n\'aime pas les devoirs" mean?', options: ['I don\'t like homework', 'I like homework', 'I love homework', 'I hate homework'], answer: 'I don\'t like homework' },
          { type: 'trueFalse', q: '"Je pense que c\'est très bien" means "I think it\'s very good"', answer: true },
          { type: 'fillBlank', q: '"I find English interesting" is: Je trouve l\'anglais ___', answer: 'intéressant', accept: ['intéressant'] },
          { type: 'multiple', q: 'How do you say "I prefer pizza to salad"?', options: ['Je préfère la pizza à la salade', 'Je préfère la pizza et la salade', 'Je préfère la pizza de la salade', 'Je préfère plus pizza'], answer: 'Je préfère la pizza à la salade' },
          { type: 'trueFalse', q: '"C\'est nul" means "It\'s rubbish"', answer: true },
          { type: 'fillBlank', q: '"I find it boring" is: Je le trouve ___', answer: 'ennuyeux', accept: ['ennuyeux', 'ennuyant'] },
          { type: 'multiple', q: 'What does "C\'est fantastique!" mean?', options: ['It\'s fantastic!', 'It\'s terrible!', 'It\'s OK', 'It\'s boring'], answer: 'It\'s fantastic!' },
          { type: 'trueFalse', q: '"Je n\'aime pas du tout les insectes" means "I don\'t like insects at all"', answer: true },
          { type: 'fillBlank', q: '"I love because it\'s exciting" is: J\'adore ___ parce que c\'est passionnant', answer: 'ça', accept: ['ça'] },
          { type: 'multiple', q: 'How do you agree with someone\'s opinion?', options: ['Moi aussi', 'Moi non', 'Je pense que oui', 'D\'accord'], answer: 'Moi aussi' },
          { type: 'trueFalse', q: '"Je pense que tu as raison" means "I think you\'re right"', answer: true },
          { type: 'fillBlank', q: '"That\'s what I think too" is: C\'est ce que je ___ aussi', answer: 'pense', accept: ['pense'] },
          { type: 'multiple', q: 'How do you express a strong dislike?', options: ['Je déteste...', 'Je n\'aime pas...', 'Je préfère pas...', 'Je ne pense pas...'], answer: 'Je déteste...' }
        ]
      }
    ]
  }
};
